{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/1.9.2/DLDateUtil-1.9.2.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "1.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil.klib",
          "url": "DLDateUtil-iosarm64-1.9.2.klib",
          "size": 60776,
          "sha512": "8dedc6bac270d442e20a6514b03ecd9745cd9a1e1552d4a141713281a3c42a170001cd6fc1010216aa3e1c5b2ed5ec69cf8cac6f1aac7b40cc4d326906e735a3",
          "sha256": "400d20114a5c4ef69f2b81d75ee86f4d082800f0fe66abcaef3c07816db4e192",
          "sha1": "d7b5f8dac2d9c768d50482e02fd7d09d67f26ae0",
          "md5": "9f40b428c7b3b5ab8d9b211a926a34ac"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLDateUtil-iosarm64-1.9.2-sources.jar",
          "url": "DLDateUtil-iosarm64-1.9.2-sources.jar",
          "size": 11910,
          "sha512": "108bb3c148c15c16b4e240f2b11b8e20b6d7c94d6680034575999a56e166543c25e36f492bda7573695677f253071aae06e64b1ac6632f64e85fd8eaae28f0bf",
          "sha256": "5ebddfab1c84e1378c93f70a6b8be3d13a70603499e1be8db161532792516fa9",
          "sha1": "0b214b743f647748b262ec9ec3f56214c225ee52",
          "md5": "06ed913039b6a285aa1a38df9d1371ee"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-iosarm64-1.9.2-metadata.jar",
          "url": "DLDateUtil-iosarm64-1.9.2-metadata.jar",
          "size": 261,
          "sha512": "83a844ae060efc74d7ae5612bbf77646471fc749fee11a275a3699e85234bf6944bcf8ed6abaaa2f2ac464aecb06232e2efc1c405a5871778643e0afde221a10",
          "sha256": "29b047ede16cc00592fb194b4dd5218fbd188a3fc2b7f174bd47c4119452c012",
          "sha1": "a73c444920a31e99734f9eb798615bf207ebb1a0",
          "md5": "0c96ba6a5ef912a97b2438cdc8508429"
        }
      ]
    }
  ]
}
