{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLLatLngUtil/1.5.9/DLLatLngUtil-1.5.9.module",
    "group": "com.github.D10NGYANG",
    "module": "DLLatLngUtil",
    "version": "1.5.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil.klib",
          "url": "DLLatLngUtil-iosarm64-1.5.9.klib",
          "size": 52259,
          "sha512": "688f48245829bfbdd8435b96561ab8dcb2939cf56b17e65bea5d02d1ff1a555bcfc54cea983a9ff5848039813b3b0c8ec8c6abc650f9895d6e397ce0fbbb45b0",
          "sha256": "899e3e3d18424b17d341d2dac5869f74bff40444ba79b47fd590c27d8241fae7",
          "sha1": "056a5d7bef88d81a0330d94fa8cec42bced3f739",
          "md5": "1bcd1f6a207546bc298fdb1d14f13515"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil-iosarm64-1.5.9-metadata.jar",
          "url": "DLLatLngUtil-iosarm64-1.5.9-metadata.jar",
          "size": 261,
          "sha512": "9fe425ef4ceedf54456b9832a16a694658146257bbf19a118d9c2351e5ed563870425666425b0d46345262afcaa0597c8640c611f1b02bca86ff07985c47c146",
          "sha256": "d623d59c199954f666b9c07a66bfa5ae42ba3f48f5056c934d0163993a4046d9",
          "sha1": "8313c2cdfb0a8e966e9f6f7215f973611008d941",
          "md5": "e25c0abcbfaf58727859d662335e0239"
        }
      ]
    }
  ]
}
