{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLTianDiTuApi/1.1.0/DLTianDiTuApi-1.1.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLTianDiTuApi",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLTianDiTuApi-macosX64Main-1.1.0.klib",
          "url": "DLTianDiTuApi-macosx64-1.1.0.klib",
          "size": 112483,
          "sha512": "599574b51a6437ec0619ad484e1cd2b1e882b4c1cb5befd7947a257713e48b7fe7aae8fbb8e0c65b18ea5fec3d2da5af51da20eb4e300c4911067e01a914c070",
          "sha256": "62db03305b6544625e76aa7165e8aba540aec4fa49a1bb74c71b594b4ad4b115",
          "sha1": "e265e0f3f1fd775f49609ce57c41ad26f88eb85e",
          "md5": "761dd2aa58e2ed844f3f7905c9a0e16e"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLTianDiTuApi-macosx64-1.1.0-sources.jar",
          "url": "DLTianDiTuApi-macosx64-1.1.0-sources.jar",
          "size": 6741,
          "sha512": "e995fd07814e5a74a95204d799c654f7da718945c0da9e007b32c722f6f66af2530e821b6ae755d000b3f768b7ed5f5ba48599211dc0e8bed8834ec08ff7e6b0",
          "sha256": "0414baa275caeb80f95cda9aeef4ed8055384c749dae672dafeea476dc9d8b9c",
          "sha1": "0828114131dafc5114da91d86d312e29b9883d3e",
          "md5": "13050d4174ed636150e82130e94bd601"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLTianDiTuApi-macosx64-1.1.0-metadata.jar",
          "url": "DLTianDiTuApi-macosx64-1.1.0-metadata.jar",
          "size": 261,
          "sha512": "2f98010fffce8619578d688c2d9b6ee469e3eb013ae50b5b1e3b2c82bbaf08c9222b86a054cddee52f2f4a15e7246126473d867ae288bca6095ed13e960c902e",
          "sha256": "3ee796449925c33cb6729d48927b488a12b582cc4c971842fbb27ca98eac9b5d",
          "sha1": "80eb4ea6b78518cc87e6945c8593dd04d70cb722",
          "md5": "dae7a83654eacff4350f8b6a7bb50a9f"
        }
      ]
    }
  ]
}
