{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLTianDiTuApi/1.2.0/DLTianDiTuApi-1.2.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLTianDiTuApi",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "DLTianDiTuApi-iosArm64Main-1.2.0.klib",
          "url": "DLTianDiTuApi-iosarm64-1.2.0.klib",
          "size": 112381,
          "sha512": "fca8b6f98c2d3109dbbfff64b490da0917b5eb9fad37324e2a89bc8f3a905a60c749e2eaf5ff794456d74bddb6bc22b2b736dde80546fc1e7cc70d59ad7ac66c",
          "sha256": "b532915c2728673b5a2e6c6db2c8d9828a131d30dfaa6f182a560726da296f22",
          "sha1": "c96b9e9fb3f224ff9ac93a18edd35989dd324f01",
          "md5": "69f7cfa149c5d9af6a3d64dbabca7c4e"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLTianDiTuApi-iosarm64-1.2.0-sources.jar",
          "url": "DLTianDiTuApi-iosarm64-1.2.0-sources.jar",
          "size": 6741,
          "sha512": "e995fd07814e5a74a95204d799c654f7da718945c0da9e007b32c722f6f66af2530e821b6ae755d000b3f768b7ed5f5ba48599211dc0e8bed8834ec08ff7e6b0",
          "sha256": "0414baa275caeb80f95cda9aeef4ed8055384c749dae672dafeea476dc9d8b9c",
          "sha1": "0828114131dafc5114da91d86d312e29b9883d3e",
          "md5": "13050d4174ed636150e82130e94bd601"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "DLTianDiTuApi-iosarm64-1.2.0-metadata.jar",
          "url": "DLTianDiTuApi-iosarm64-1.2.0-metadata.jar",
          "size": 261,
          "sha512": "0c5ff57b01ef45cccf44cd89883b35434571579c5a6a485c0105c64d7f052a98c6e2c319dc499815e13bf8d9d5cca24b0fee1235dd91d96a273376ee428161d3",
          "sha256": "fb7bb541caeaadd35efa62698b6ca09f0bd2294bb0f27e1869ce74e359be3d91",
          "sha1": "c8d755bb3f7623a5746ff6ae3f858b7983c8bd1e",
          "md5": "10b11c3d0a9fb8efe873b9445b94bf22"
        }
      ]
    }
  ]
}
