{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLPcmResampleUtil/0.2.0/DLPcmResampleUtil-0.2.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLPcmResampleUtil",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLPcmResampleUtil.klib",
          "url": "DLPcmResampleUtil-macosarm64-0.2.0.klib",
          "size": 222849,
          "sha512": "e4e2d862e247c76eb3d3d5d28c7e83bd50a495a24f8e7ecd09d833b6a2be0ffc3ad2a7927172fe2de27d5f647d48ec52cb49d00b937dc200e17a2506ff388002",
          "sha256": "11624f2f9e20870c9c223a93ef00cebbfaf0d7fde12ee40e6a57bede12ca851f",
          "sha1": "12d9f4b2b89c6b4651f18c62c42355e455bf67fc",
          "md5": "5a78d79b048649010d6669897ed1003f"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLPcmResampleUtil-macosarm64-0.2.0-sources.jar",
          "url": "DLPcmResampleUtil-macosarm64-0.2.0-sources.jar",
          "size": 29498,
          "sha512": "4f096ce098d2c99292b316414eb3dd74a967d7436f9ab3cc27668c15b81514c25b71a0967616101694f7b024753e6a426b61d9af5e6c6dbf6d905f427c173b6b",
          "sha256": "1fc4ed72daa9d1a5d7dc8b8182b3aaeeceff08defb1317c0daf5735f82058ec4",
          "sha1": "93bc0627a4523f6fa6bab1c6acd5561a5cf5bc7a",
          "md5": "f573a7abe1cfa719011b671905188cef"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLPcmResampleUtil-macosarm64-0.2.0-metadata.jar",
          "url": "DLPcmResampleUtil-macosarm64-0.2.0-metadata.jar",
          "size": 261,
          "sha512": "28d158d9649e3fcd2f4b65d09122ed1b7220a75c82c285e7c782394a176177adcc43d196f332ee78281de59fbae220bcfaa18fb4a22c5cfeeb7e3f825c21e982",
          "sha256": "a9cda45fd242249b3af3c4c30b7f87fb53d65972659a32268cccf59cad234d71",
          "sha1": "ca5344d2d941064af96c8a20225cd41dd5784f8f",
          "md5": "934cdefd476de89283953e90dbd28525"
        }
      ]
    }
  ]
}
