{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLBluetoothUtil/1.0.0/DLBluetoothUtil-1.0.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLBluetoothUtil",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "DLBluetoothUtil-release.aar",
          "url": "DLBluetoothUtil-android-1.0.0.aar",
          "size": 211413,
          "sha512": "adb9c364ae56011304273c22417b569a7d6200df214a2a0c4bb82c6c370c86469d381f707c399d33738da36a8ec093cb21adf7187cc0d20f250bd8b7cea6ceef",
          "sha256": "b77d8fba84fa5b26a22b7b540679fd7d2a9a616844bfa08bfaefe1c6316cab5f",
          "sha1": "40f64124e8488d0eb6d865e37adb3887a6e1048a",
          "md5": "0c1a22ff191b2f3429d79c0ab8fe455f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLLogUtil",
          "version": {
            "requires": "0.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "DLBluetoothUtil-release.aar",
          "url": "DLBluetoothUtil-android-1.0.0.aar",
          "size": 211413,
          "sha512": "adb9c364ae56011304273c22417b569a7d6200df214a2a0c4bb82c6c370c86469d381f707c399d33738da36a8ec093cb21adf7187cc0d20f250bd8b7cea6ceef",
          "sha256": "b77d8fba84fa5b26a22b7b540679fd7d2a9a616844bfa08bfaefe1c6316cab5f",
          "sha1": "40f64124e8488d0eb6d865e37adb3887a6e1048a",
          "md5": "0c1a22ff191b2f3429d79c0ab8fe455f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "DLBluetoothUtil-android-1.0.0-sources.jar",
          "url": "DLBluetoothUtil-android-1.0.0-sources.jar",
          "size": 33288,
          "sha512": "20f970b92f0b2e62a6306f8a48687b5196b7c174463dc309100fe4e2ed723a547f1c2044ebe877f21093a6465a0900200f0469b3d1e5a0d88c9932d0ef26b931",
          "sha256": "7848058bce142cc575eee327ac0cee9e0d7529ee201fc412a7902916637b9c7c",
          "sha1": "f0b26944e3df135aa96ff668ac2084d4ec7ac6c1",
          "md5": "95d0b12c745765cc88c9ade2b129904b"
        }
      ]
    }
  ]
}
