{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/1.9.3/DLDateUtil-1.9.3.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "1.9.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil.klib",
          "url": "DLDateUtil-iosarm64-1.9.3.klib",
          "size": 59476,
          "sha512": "4512de95e298d505a4a80183178a7aa74665bfe64943e2bce89f3798ec9da275baa8b3687253293d60e64ceb9148fc2790d572296f9d95066f9ded819514c7d3",
          "sha256": "27c27addf0edd96edea782cb20cb9d829bf45c2ae03626ff7b20169596b7348e",
          "sha1": "f839d212abfa68543a920188ba78b382648467c4",
          "md5": "e3b268904624bcdc6541c1434d338a24"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLDateUtil-iosarm64-1.9.3-sources.jar",
          "url": "DLDateUtil-iosarm64-1.9.3-sources.jar",
          "size": 11513,
          "sha512": "05b9e52cde543fd709f0e377539f9c8354d350ca080126a9bcee3b0ae44f8c8b885faa8e7392368ee3aa817a3000efef2e8f24a14702219c2a58560fed61b039",
          "sha256": "63d1ebee5e102fce424e3f8930488261884d7d7a081f73dc855e79eb34e91619",
          "sha1": "eaee10b3558388c0932aaf5eda714f9a44e8c878",
          "md5": "6d18454747da2ed7decc0a6612d565b4"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-iosarm64-1.9.3-metadata.jar",
          "url": "DLDateUtil-iosarm64-1.9.3-metadata.jar",
          "size": 261,
          "sha512": "0c7d24ea8da3afe2af47b894c24b109550d1832a142013c6bf98bb74a2e596a784aba79a0407cdf46d1bd3789900d2ed7a25a271dbe759ce0df60c4a2f8de605",
          "sha256": "bc5eab5ffffde661f5134ce149c2ded75401cd9d8d4d854bbf10be5148f68bcc",
          "sha1": "1bcae808f292074341297e45cc47f815c4d89adc",
          "md5": "f01b7e57262ee2899e2922f3bf72a56c"
        }
      ]
    }
  ]
}
