{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLCryptoUtil",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLCryptoUtil-metadata-0.0.1.jar",
          "url": "DLCryptoUtil-0.0.1.jar",
          "size": 4333,
          "sha512": "498c99b4d5c1b7f4c6b5e2e726b8aecf2d39304ea66da0bfa04684f9a5a9ec65460fac074cf790a2b61611a2eeab21b05e060511d97d9aadb6088a0821c9ab58",
          "sha256": "f1450027862f0aa3def1ed56711e3bc8e6320ee33ac8fc4567a553cb6737e327",
          "sha1": "a44e104cbc4b0b59ccb657e2635bc638f110c467",
          "md5": "1a07761f2528b11aa4ad753a4eadda9d"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "DLCryptoUtil-kotlin-0.0.1-sources.jar",
          "url": "DLCryptoUtil-0.0.1-sources.jar",
          "size": 3146,
          "sha512": "e14905597aa75d053f0bec823cc8873f1394c9ab76718de045da3d519a5487e02b029c22ea408e5c308da4fb619470633f64c880cf1bfdc21346370481d830cf",
          "sha256": "f908386902be35152a7ca963b5776d9d1e60ccfa52d76bface73945732b08400",
          "sha1": "b9982ad26a98282dbddaa00507f88e4e31887fe0",
          "md5": "b992bfe62399939b4544ac8092f9a8e0"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLCryptoUtil-js/0.0.1/DLCryptoUtil-js-0.0.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCryptoUtil-js",
        "version": "0.0.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLCryptoUtil-js/0.0.1/DLCryptoUtil-js-0.0.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCryptoUtil-js",
        "version": "0.0.1"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLCryptoUtil-js/0.0.1/DLCryptoUtil-js-0.0.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCryptoUtil-js",
        "version": "0.0.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLCryptoUtil-jvm/0.0.1/DLCryptoUtil-jvm-0.0.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCryptoUtil-jvm",
        "version": "0.0.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLCryptoUtil-jvm/0.0.1/DLCryptoUtil-jvm-0.0.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCryptoUtil-jvm",
        "version": "0.0.1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLCryptoUtil-jvm/0.0.1/DLCryptoUtil-jvm-0.0.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCryptoUtil-jvm",
        "version": "0.0.1"
      }
    }
  ]
}
