{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/2.1.3/DLDateUtil-2.1.3.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "2.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-release.aar",
          "url": "DLDateUtil-android-2.1.3.aar",
          "size": 39443,
          "sha512": "8c65995a76d5224299c76b70688fc15fa1af892135ad680bdd0204ee2662c5774d63f5c2097c97a57834f6235de8d4df723ff6548f566ff867d195fdf83fec1f",
          "sha256": "eb4f78a489d0268af4343832dc659775a560cc73c275f1d5c8535f61641e81f9",
          "sha1": "5631788e017144990939bdeaf53f507c46985ed2",
          "md5": "7c2c270d4b6cb4b9fc49e0c839c3d9f6"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-release.aar",
          "url": "DLDateUtil-android-2.1.3.aar",
          "size": 39443,
          "sha512": "8c65995a76d5224299c76b70688fc15fa1af892135ad680bdd0204ee2662c5774d63f5c2097c97a57834f6235de8d4df723ff6548f566ff867d195fdf83fec1f",
          "sha256": "eb4f78a489d0268af4343832dc659775a560cc73c275f1d5c8535f61641e81f9",
          "sha1": "5631788e017144990939bdeaf53f507c46985ed2",
          "md5": "7c2c270d4b6cb4b9fc49e0c839c3d9f6"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "DLDateUtil-android-2.1.3-sources.jar",
          "url": "DLDateUtil-android-2.1.3-sources.jar",
          "size": 17463,
          "sha512": "bb3a3993bfaa48011c2d827153ee6aae326cf05d78463575db2b23bb4a1a7ebc39398d491c3419e5ab885bc296b5143445d65e6b401b06f887bfb7bb07946d4a",
          "sha256": "352121accf74b1ebeb34dc8f64c47432bd58599aec2da3583910e2d2d610ef88",
          "sha1": "afe3c7b840c6185cf4647bc72c46a6a6974bcf89",
          "md5": "b005d5f34aec98f5aac50d1c0877c39c"
        }
      ]
    }
  ]
}
