{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLCryptoUtil",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLCryptoUtil-metadata-0.2.1.jar",
          "url": "DLCryptoUtil-0.2.1.jar",
          "size": 3969,
          "sha512": "52d2040a803d411c83696c68d05c12bb2aeac2fe5614ce9d847f344fa97c222bbdd65e26c5f637fb3d0d11c025697e0f4d8b9c9139036f1f85efd8ffa65450e3",
          "sha256": "233f8a606ca67522f89e20e9303b8950bd64a8c7cd9d322945a1dae633f46811",
          "sha1": "087870c2e65c5bda9241bddabcc6785fd44c7e04",
          "md5": "2bdf8b0e769039a835cfa0ed0ef09195"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "DLCryptoUtil-kotlin-0.2.1-sources.jar",
          "url": "DLCryptoUtil-0.2.1-sources.jar",
          "size": 9717,
          "sha512": "776fe4209466a9102294f41a773c6e182a6fb5d591d32cb0e85462ef4e328db1e8a84a0dc0fc80f175b7379c31ca942a1b7d631ff2371bdb59dfb083f02e513b",
          "sha256": "a933cf15dc36f05bcd7e7d630a551a1c5f1a4348af7852945792ca58e09848af",
          "sha1": "2a3e6d88e2c32ca0fb018a9c578f936abbadebe0",
          "md5": "0be2b8b3a5b54ddd06331807f3c6fe82"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCryptoUtil-iosarm64/0.2.1/DLCryptoUtil-iosarm64-0.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCryptoUtil-iosarm64",
        "version": "0.2.1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCryptoUtil-iosarm64/0.2.1/DLCryptoUtil-iosarm64-0.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCryptoUtil-iosarm64",
        "version": "0.2.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCryptoUtil-iosarm64/0.2.1/DLCryptoUtil-iosarm64-0.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCryptoUtil-iosarm64",
        "version": "0.2.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCryptoUtil-iossimulatorarm64/0.2.1/DLCryptoUtil-iossimulatorarm64-0.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCryptoUtil-iossimulatorarm64",
        "version": "0.2.1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCryptoUtil-iossimulatorarm64/0.2.1/DLCryptoUtil-iossimulatorarm64-0.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCryptoUtil-iossimulatorarm64",
        "version": "0.2.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCryptoUtil-iossimulatorarm64/0.2.1/DLCryptoUtil-iossimulatorarm64-0.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCryptoUtil-iossimulatorarm64",
        "version": "0.2.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCryptoUtil-iosx64/0.2.1/DLCryptoUtil-iosx64-0.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCryptoUtil-iosx64",
        "version": "0.2.1"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCryptoUtil-iosx64/0.2.1/DLCryptoUtil-iosx64-0.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCryptoUtil-iosx64",
        "version": "0.2.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCryptoUtil-iosx64/0.2.1/DLCryptoUtil-iosx64-0.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCryptoUtil-iosx64",
        "version": "0.2.1"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLCryptoUtil-js/0.2.1/DLCryptoUtil-js-0.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCryptoUtil-js",
        "version": "0.2.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLCryptoUtil-js/0.2.1/DLCryptoUtil-js-0.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCryptoUtil-js",
        "version": "0.2.1"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLCryptoUtil-js/0.2.1/DLCryptoUtil-js-0.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCryptoUtil-js",
        "version": "0.2.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLCryptoUtil-jvm/0.2.1/DLCryptoUtil-jvm-0.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCryptoUtil-jvm",
        "version": "0.2.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLCryptoUtil-jvm/0.2.1/DLCryptoUtil-jvm-0.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCryptoUtil-jvm",
        "version": "0.2.1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLCryptoUtil-jvm/0.2.1/DLCryptoUtil-jvm-0.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCryptoUtil-jvm",
        "version": "0.2.1"
      }
    }
  ]
}
