{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ImageCompress/1.0.0-beta01/ImageCompress-1.0.0-beta01.module",
    "group": "com.hailiao.util",
    "module": "ImageCompress",
    "version": "1.0.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ImageCompress.klib",
          "url": "ImageCompress-iosarm64-1.0.0-beta01.klib",
          "size": 14048,
          "sha512": "855fed5c0d5f35395fe46f802aea98db16b2b9bda350de6c439260fdbe3d188f78971e85792492278a3c383567b05d00fd31b8668499216bd748b4d9a17c6e15",
          "sha256": "1a1f4bb52f3b6a6760d41d89b1bfc40255fc8665b2a63e922dab44c0239381b9",
          "sha1": "1c074e032769ab2624b338efe15a60c854213116",
          "md5": "a2142c5128b142b3a3383a08b0c6aecf"
        },
        {
          "name": "ImageCompress-cinterop-ImageCompress.klib",
          "url": "ImageCompress-iosarm64-1.0.0-beta01-cinterop-ImageCompress.klib",
          "size": 6921,
          "sha512": "45855192f417d04fcd5a6d7f4468384e9429564703870b694d34e6a602faa7e6b6ad9d4e7b2962c883583225603c24c98b51499ae32faabbf28e96e3c76f1614",
          "sha256": "a5234c5dccbaa126c305ebc74d71dc94a998d6e31a6e50fc11f11296f14f18b4",
          "sha1": "364fd5c295de53a9330a180443b6dde509392792",
          "md5": "ff7b380b782a4f2161250c9d4f569cd8"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ImageCompress-iosarm64-1.0.0-beta01-sources.jar",
          "url": "ImageCompress-iosarm64-1.0.0-beta01-sources.jar",
          "size": 4361,
          "sha512": "f55a09bee36ba15329b490a51b8725340cee3fa5602c36430c68197d692be70cf4d164f20082088f879f39c55ebfaea71e4c7c1174d4f1d648669632212d5056",
          "sha256": "3cd1a3f4cc4ae2fec78ed42bd342f5f3e1bb3c6504ffdeb61426021bfd055de6",
          "sha1": "b2b34b51a15fcce139f251f9f7d95d5de12a21c8",
          "md5": "19a99e07356e1fcc0c5bd03bcc410a73"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ImageCompress-iosarm64-1.0.0-beta01-metadata.jar",
          "url": "ImageCompress-iosarm64-1.0.0-beta01-metadata.jar",
          "size": 14712,
          "sha512": "bd673ff4f62a9151798910d3c996458f1a62941e626936be9fe64b03398eab2540a7fbc1b0a96baa54b0a5055fdc1e24dd0950343085932e2f0d3c0d68113232",
          "sha256": "2be9969ff52b6682f8ea87ff809adb5ff5b3b8ba45cd300621f0d99d3bed02aa",
          "sha1": "6b1143f0c56bbbec38dd64b789741400491005b9",
          "md5": "b0f5ab8421a49fc75e1a63d643b603e7"
        }
      ]
    }
  ]
}
