{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/2.1.0/DLDateUtil-2.1.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-jvm-2.1.0.jar",
          "url": "DLDateUtil-jvm-2.1.0.jar",
          "size": 39751,
          "sha512": "da899858b2b4e3f03c383e4b51815cf11d038f9f3183ee165413387afa87faf1585387af9047078e50681a937aa04ca298208b2ff840e223bcc74843b0eca686",
          "sha256": "2d3efec39700477270840057682f8f3f22c30e044200e4590a4c37c68d9a4044",
          "sha1": "10ec048b9506e96ee7d58b0c05b2fc8ef3792758",
          "md5": "a85b30379a19a6a6622c8edaa577518d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-jvm-2.1.0.jar",
          "url": "DLDateUtil-jvm-2.1.0.jar",
          "size": 39751,
          "sha512": "da899858b2b4e3f03c383e4b51815cf11d038f9f3183ee165413387afa87faf1585387af9047078e50681a937aa04ca298208b2ff840e223bcc74843b0eca686",
          "sha256": "2d3efec39700477270840057682f8f3f22c30e044200e4590a4c37c68d9a4044",
          "sha1": "10ec048b9506e96ee7d58b0c05b2fc8ef3792758",
          "md5": "a85b30379a19a6a6622c8edaa577518d"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "DLDateUtil-jvm-2.1.0-sources.jar",
          "url": "DLDateUtil-jvm-2.1.0-sources.jar",
          "size": 17232,
          "sha512": "b8d79c6283ff88e837ddc3a09ba5bdf8699a2a4fe77e5fc8901d5cce63e8c9d4febfd42667699643513e15abe3162d38b6caa93b7e57235ef6af4b0b02099887",
          "sha256": "f7b7660b171231b2f4c2aff1359711b1694e753a21041add4b009f1d859055b8",
          "sha1": "29731f21fc212fa56c686b33b47c58e97a676243",
          "md5": "cfe31385e210ad62a83d8b501483b495"
        }
      ]
    }
  ]
}
