{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/2.1.2/DLDateUtil-2.1.2.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "2.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-macosX64Main-2.1.2.klib",
          "url": "DLDateUtil-macosx64-2.1.2.klib",
          "size": 77510,
          "sha512": "3d80febf73783c64108bbb459476e82bcb4faeed42909b3311e4fbfcee2e3f2b08ef3099bed03200425ae3e0e84d64d7c129539d2047f2a3ea339d7f869a9c8e",
          "sha256": "6f9e2ecc84e9186a6b68b0cc79617b324763138b613cf45179824003e7f45901",
          "sha1": "92d4f13988dc74098b18648aa85ea492b81f8cfc",
          "md5": "410947f30991b95c3eac11433d0afff7"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLDateUtil-macosx64-2.1.2-sources.jar",
          "url": "DLDateUtil-macosx64-2.1.2-sources.jar",
          "size": 17269,
          "sha512": "1e62691bb797940348e3045d1c2a871eca8f87e7207565142e080256c4af34985862a82d2431b31730dd98370d84007e4ea007e3e47c4e722b629aa04b3dd877",
          "sha256": "2e0a12edb7838df703693d68368eaeec1db413d3153d4942abdacc8113df0c72",
          "sha1": "f3e60235b4f7f1aa2210c13d4b66d0be157c7ea3",
          "md5": "fad80f3f43425c01564714eec44f2345"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-macosx64-2.1.2-metadata.jar",
          "url": "DLDateUtil-macosx64-2.1.2-metadata.jar",
          "size": 261,
          "sha512": "e66da5584ffa6480baa1a50a6a0e3be5b91efe5400be0906e9cc7f5d01e07859f811a1cc610675f94c997d93fdc0d0269a62c1f48b622ef9c78107fec565671d",
          "sha256": "2792f8d6b743ae7c206b57aaa0f08a3c8280ef0d3bb2dca362e7e114987af9ff",
          "sha1": "fa6def9733c48994a18d10566e8697ea9f6085cc",
          "md5": "78e16a8e599d0e0143798e7b598c55f3"
        }
      ]
    }
  ]
}
