{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLCommonUtil/0.0.7/DLCommonUtil-0.0.7.module",
    "group": "com.github.D10NGYANG",
    "module": "DLCommonUtil",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "com.ditchoom",
          "module": "buffer",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-js-0.0.7.klib",
          "url": "DLCommonUtil-js-0.0.7.klib",
          "size": 108049,
          "sha512": "ba49f7328277ee60adedce8ccf7860b981e86c40ef00135fd0a8649a68997714e5531680e9f4cd724dd7335804c23bb9b0e3973a95b029cdeb105b842570701a",
          "sha256": "764f4c8f55b00b17d095af5a1697d3550dfa2b64dec31308108ac5b5f94b033a",
          "sha1": "42998981b22cbd9f3172325f77e31f362700854e",
          "md5": "ebb79d0bd5021129df9ead2ba7ef2b1e"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "com.ditchoom",
          "module": "buffer",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-js-0.0.7.klib",
          "url": "DLCommonUtil-js-0.0.7.klib",
          "size": 108049,
          "sha512": "ba49f7328277ee60adedce8ccf7860b981e86c40ef00135fd0a8649a68997714e5531680e9f4cd724dd7335804c23bb9b0e3973a95b029cdeb105b842570701a",
          "sha256": "764f4c8f55b00b17d095af5a1697d3550dfa2b64dec31308108ac5b5f94b033a",
          "sha1": "42998981b22cbd9f3172325f77e31f362700854e",
          "md5": "ebb79d0bd5021129df9ead2ba7ef2b1e"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "DLCommonUtil-js-0.0.7-sources.jar",
          "url": "DLCommonUtil-js-0.0.7-sources.jar",
          "size": 28847,
          "sha512": "000a45d3b7bca191fe4fae2501007c9feab5065dbdb189c1792b1f561d3fa5a4930dd56fc63d9312f816e9445c320c29da8b1b500650c124ebd3973c24c38c46",
          "sha256": "d5cf1450adbaeb1a37086b7c7c4ec49db9fb08d6fb952c80de1479a0a65b52a0",
          "sha1": "400ed131d09617d8ffdcc46080dfe79f75a98c33",
          "md5": "d147d60fa23d32d5cfa02c21cc04447a"
        }
      ]
    }
  ]
}
