{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLQRCodeUtil",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLQRCodeUtil-0.1.2.aar",
          "url": "DLQRCodeUtil-0.1.2.aar",
          "size": 113413,
          "sha512": "9db21c1c02205d1ae4ae1d0922c8dd9e84258ad96e910bd9f5a94a3a5ddf4610418d16232828295c416239e8de281bcaab44904700444d8cdb72c2e31a74aacf",
          "sha256": "8b7dd82efa85229a0818f7029c2f4600ec3039ec1da9795f27824f973178b297",
          "sha1": "1cba76f9591061da9376bc3fa0de15828a759533",
          "md5": "0b138c68aba4ffee4a95d1fdfad0fbb9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLJetpackComposeUtil",
          "version": {
            "requires": "2.0.25"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLAppUtil",
          "version": {
            "requires": "2.5.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLQRCodeUtil-0.1.2.aar",
          "url": "DLQRCodeUtil-0.1.2.aar",
          "size": 113413,
          "sha512": "9db21c1c02205d1ae4ae1d0922c8dd9e84258ad96e910bd9f5a94a3a5ddf4610418d16232828295c416239e8de281bcaab44904700444d8cdb72c2e31a74aacf",
          "sha256": "8b7dd82efa85229a0818f7029c2f4600ec3039ec1da9795f27824f973178b297",
          "sha1": "1cba76f9591061da9376bc3fa0de15828a759533",
          "md5": "0b138c68aba4ffee4a95d1fdfad0fbb9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLQRCodeUtil-0.1.2-sources.jar",
          "url": "DLQRCodeUtil-0.1.2-sources.jar",
          "size": 5053,
          "sha512": "7cc900933d42943d3448f296e140fbc136ee270ef45d1672ef9177f326115de771a42ba79a92d6d28af3bc96008f01145596ad46778bf657d1235bc886143653",
          "sha256": "4fec03e17c9b7c2710b1c7c537a9beabeafb174128a7e371ac1c0e52303d20d4",
          "sha1": "1f5fa3a17ead347c9cf8d607a5b80b3bba76ccc8",
          "md5": "cbf77ac1f7348a54c8107569c8968466"
        }
      ]
    }
  ]
}
