{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "2.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-metadata-2.3.1.jar",
          "url": "DLDateUtil-2.3.1.jar",
          "size": 14503,
          "sha512": "f4d360f822efb446f10848595b23358570cdc65a9b3d199f7e6322fd3cbcbea29abd82285de575a208ca569734c7dc33cf7f150ba51921afd4999b9daa9c3861",
          "sha256": "846dac1f2254d9c747e8749332a23fd243c960784d2fdb8be619f283e705a958",
          "sha1": "5568f2f3321b0a28b4590f9396dc505ab849aca3",
          "md5": "4f9ac4185f94a87f805514fc9f2f382c"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "DLDateUtil-kotlin-2.3.1-sources.jar",
          "url": "DLDateUtil-2.3.1-sources.jar",
          "size": 21080,
          "sha512": "953123f22ca1bab8337e14eb7ae72468bb4bc8cfda101870babf688f28ef9a052d4710666c1e41cfca592ea2b72f1985206df35253bb2725749b2b0ee21bbbef",
          "sha256": "917128fe4961ed7e500c08691e152d79f1719117212fcf759ecf06b91d727aed",
          "sha1": "bcd5c894ffb1e6e97692f5938153db16c80311f8",
          "md5": "acd570a277f326e858bf775b1155a5e4"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLDateUtil-android/2.3.1/DLDateUtil-android-2.3.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-android",
        "version": "2.3.1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLDateUtil-android/2.3.1/DLDateUtil-android-2.3.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-android",
        "version": "2.3.1"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLDateUtil-android/2.3.1/DLDateUtil-android-2.3.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-android",
        "version": "2.3.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iosarm64/2.3.1/DLDateUtil-iosarm64-2.3.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iosarm64",
        "version": "2.3.1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iosarm64/2.3.1/DLDateUtil-iosarm64-2.3.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iosarm64",
        "version": "2.3.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iosarm64/2.3.1/DLDateUtil-iosarm64-2.3.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iosarm64",
        "version": "2.3.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iossimulatorarm64/2.3.1/DLDateUtil-iossimulatorarm64-2.3.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iossimulatorarm64",
        "version": "2.3.1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iossimulatorarm64/2.3.1/DLDateUtil-iossimulatorarm64-2.3.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iossimulatorarm64",
        "version": "2.3.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iossimulatorarm64/2.3.1/DLDateUtil-iossimulatorarm64-2.3.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iossimulatorarm64",
        "version": "2.3.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iosx64/2.3.1/DLDateUtil-iosx64-2.3.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iosx64",
        "version": "2.3.1"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iosx64/2.3.1/DLDateUtil-iosx64-2.3.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iosx64",
        "version": "2.3.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iosx64/2.3.1/DLDateUtil-iosx64-2.3.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iosx64",
        "version": "2.3.1"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLDateUtil-js/2.3.1/DLDateUtil-js-2.3.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-js",
        "version": "2.3.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLDateUtil-js/2.3.1/DLDateUtil-js-2.3.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-js",
        "version": "2.3.1"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLDateUtil-js/2.3.1/DLDateUtil-js-2.3.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-js",
        "version": "2.3.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLDateUtil-jvm/2.3.1/DLDateUtil-jvm-2.3.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-jvm",
        "version": "2.3.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLDateUtil-jvm/2.3.1/DLDateUtil-jvm-2.3.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-jvm",
        "version": "2.3.1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLDateUtil-jvm/2.3.1/DLDateUtil-jvm-2.3.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-jvm",
        "version": "2.3.1"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-linuxarm64/2.3.1/DLDateUtil-linuxarm64-2.3.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-linuxarm64",
        "version": "2.3.1"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-linuxarm64/2.3.1/DLDateUtil-linuxarm64-2.3.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-linuxarm64",
        "version": "2.3.1"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-linuxx64/2.3.1/DLDateUtil-linuxx64-2.3.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-linuxx64",
        "version": "2.3.1"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-linuxx64/2.3.1/DLDateUtil-linuxx64-2.3.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-linuxx64",
        "version": "2.3.1"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-macosarm64/2.3.1/DLDateUtil-macosarm64-2.3.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-macosarm64",
        "version": "2.3.1"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-macosarm64/2.3.1/DLDateUtil-macosarm64-2.3.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-macosarm64",
        "version": "2.3.1"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-macosarm64/2.3.1/DLDateUtil-macosarm64-2.3.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-macosarm64",
        "version": "2.3.1"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-macosx64/2.3.1/DLDateUtil-macosx64-2.3.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-macosx64",
        "version": "2.3.1"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-macosx64/2.3.1/DLDateUtil-macosx64-2.3.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-macosx64",
        "version": "2.3.1"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-macosx64/2.3.1/DLDateUtil-macosx64-2.3.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-macosx64",
        "version": "2.3.1"
      }
    }
  ]
}
