{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLHttpUtil/1.1.0/DLHttpUtil-1.1.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLHttpUtil",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.12"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLHttpUtil.klib",
          "url": "DLHttpUtil-linuxx64-1.1.0.klib",
          "size": 13011,
          "sha512": "7227cebfd98080dcebe044126044d3a39c8c9e269b1afaef0d1863840cd7dbf4e6b19c8eb33f0ff4eb0ad1fd7685f7315918d7afd0c68200e9ac2fc9a270c5d8",
          "sha256": "24cfc7bcb28021451f5157ffd7fb6beef9808b3d14fdddffc3cc4ac94be8b206",
          "sha1": "c5e4ed3931c273a72cab0529e694a6b4fd4f7597",
          "md5": "23b0682595e5452f97714fb60161d662"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLHttpUtil-linuxx64-1.1.0-sources.jar",
          "url": "DLHttpUtil-linuxx64-1.1.0-sources.jar",
          "size": 2913,
          "sha512": "37be5199735fdcfcea2c7a63f5a4bb484bf40bb019ef8aa88d4021585b79bfacea1e22f2ff9d8209b7a1815831a67d4e2c7c521e6ab44fec866c1388a5def84a",
          "sha256": "e5a750526882cf9f6e02b8eab86ba1cb21d24b0677ae2af0bfc525935459af7a",
          "sha1": "ebc7642e7dc1c4d10a1d3b16fa514d78d68a8f31",
          "md5": "2ce7c4f734a184b63b90aa8d988649d3"
        }
      ]
    }
  ]
}
