{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLHttpUtil/1.1.0/DLHttpUtil-1.1.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLHttpUtil",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.12"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLHttpUtil.klib",
          "url": "DLHttpUtil-iossimulatorarm64-1.1.0.klib",
          "size": 13097,
          "sha512": "e05b5221769914b6f3ceb3f831d46fc429f0f62b194d40896bfa8f52bd9015ddc92efaf59f48666e2a19334ec9bb34b590d9341acbc75e10ea0a103b0552bac6",
          "sha256": "2f64f618645fa5e1b21a8c2eb51b31d629ee6e5943fb10e73dcd2eac0660f1bd",
          "sha1": "e157487cb26c984efcf6d6d411c50bb78934626c",
          "md5": "b04bffda60e8a1680dc79bab63f11ba5"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLHttpUtil-iossimulatorarm64-1.1.0-sources.jar",
          "url": "DLHttpUtil-iossimulatorarm64-1.1.0-sources.jar",
          "size": 2913,
          "sha512": "37be5199735fdcfcea2c7a63f5a4bb484bf40bb019ef8aa88d4021585b79bfacea1e22f2ff9d8209b7a1815831a67d4e2c7c521e6ab44fec866c1388a5def84a",
          "sha256": "e5a750526882cf9f6e02b8eab86ba1cb21d24b0677ae2af0bfc525935459af7a",
          "sha1": "ebc7642e7dc1c4d10a1d3b16fa514d78d68a8f31",
          "md5": "2ce7c4f734a184b63b90aa8d988649d3"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.12"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLHttpUtil-iossimulatorarm64-1.1.0-metadata.jar",
          "url": "DLHttpUtil-iossimulatorarm64-1.1.0-metadata.jar",
          "size": 261,
          "sha512": "edb41a99e855dd8fddd35241ba23ddab841ede81e089bbbe9ab223430547f1ee44789aef75a28a5ca2a144fce461e1d9c31174b0677570d2a845e534d56660da",
          "sha256": "08900570c37cd447277066bd6764bf2a11c705b87a8d3e5950fdecc29748826d",
          "sha1": "7582eed0e1058fb038b078235d170ab81d859d6b",
          "md5": "db4cdfe40dfaab276834e44f03337af4"
        }
      ]
    }
  ]
}
