{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ImageCompress/1.1.1/ImageCompress-1.1.1.module",
    "group": "com.hailiao.util",
    "module": "ImageCompress",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "ImageCompress-jvm-1.1.1.jar",
          "url": "ImageCompress-jvm-1.1.1.jar",
          "size": 764003,
          "sha512": "0d95307f97379d029ab1bfe28d9a6dd8faddba2394f3bd15150a4c5e7205c20a4603e920982daa604e1e5493661461b054129bf5f12bd1213937d7d14ee3d08b",
          "sha256": "e76d99399663c6b8af0c8907214964eec0a4874ea40c0109c8dd2f85216325ce",
          "sha1": "97399e0b2063cad60775778402caca103109a71e",
          "md5": "3b97942b016072caa5a7513c4f0a31c2"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "ImageCompress-jvm-1.1.1.jar",
          "url": "ImageCompress-jvm-1.1.1.jar",
          "size": 764003,
          "sha512": "0d95307f97379d029ab1bfe28d9a6dd8faddba2394f3bd15150a4c5e7205c20a4603e920982daa604e1e5493661461b054129bf5f12bd1213937d7d14ee3d08b",
          "sha256": "e76d99399663c6b8af0c8907214964eec0a4874ea40c0109c8dd2f85216325ce",
          "sha1": "97399e0b2063cad60775778402caca103109a71e",
          "md5": "3b97942b016072caa5a7513c4f0a31c2"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ImageCompress-jvm-1.1.1-sources.jar",
          "url": "ImageCompress-jvm-1.1.1-sources.jar",
          "size": 10563,
          "sha512": "5e7676d05b4425e2270ff31e11e1a3bbe493ea97b532737d1bb7cc2be934b735cb8cfcdd35f7afcc3c711bb43683028a501e8e3d9872ebb4a26416f01a739399",
          "sha256": "bc11f331bc99362e186379a90403dd365209b836aff973c3a1f4615ada48d1ea",
          "sha1": "a5085417759afdc82defbdc34341c34cee87c66a",
          "md5": "abaf66eb5f7c18aeee58d04c95a66ee1"
        }
      ]
    }
  ]
}
