{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLCommonUtil/1.0.1/DLCommonUtil-1.0.1.module",
    "group": "com.github.D10NGYANG",
    "module": "DLCommonUtil",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-iosSimulatorArm64Main-1.0.1.klib",
          "url": "DLCommonUtil-iossimulatorarm64-1.0.1.klib",
          "size": 281876,
          "sha512": "359d279498901a7e45822915502e8365a1d30c04c5f6842f6f6de25687a3bd401590cbfe90a13fc6a8a85711564f240cad072d5dc6be667c78b4d185e3fc7d03",
          "sha256": "b740d16fefaa298a11f0bd49156940b6d74febbc203d103a381dc0e824bda4d9",
          "sha1": "4608364b2be981f25e7da82d778a05e9b61fc6f8",
          "md5": "0b95b75159ed505358ff199605aa97ff"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLCommonUtil-iossimulatorarm64-1.0.1-sources.jar",
          "url": "DLCommonUtil-iossimulatorarm64-1.0.1-sources.jar",
          "size": 96618,
          "sha512": "53402f02364392a0c000cb7768509123817e89735dfa30d3d4651d6f36d2acb0f6877e135052e90f0e95fc6eb6c48695d8ec411ce49c1dc0065eafdc7adf9eca",
          "sha256": "a134c81a4b91f09e505a44b1567bf4da46e1e96f0e54fefa675349d7fadf82e2",
          "sha1": "705035d90807ef397684c7d0f03f078700ea3224",
          "md5": "768b498ac1d11b7df262a90140695ddd"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-iossimulatorarm64-1.0.1-metadata.jar",
          "url": "DLCommonUtil-iossimulatorarm64-1.0.1-metadata.jar",
          "size": 4062,
          "sha512": "0a7494ccf7c86f4b63c64bb55c63b0013db895d806a7d0309cbaa7610916b50cb734ccb4b79d9baa7374c7d758d2df63a2ba6b819701c6e0bc0a504d31bd96d7",
          "sha256": "ff9da034f8a51fb3a2ea8511128a2a71d31fd57e07b1dddd967b20e0502ba2f4",
          "sha1": "a5c59f76718cb2f34abcdeb797015ca19f3165a9",
          "md5": "3e4d7382160e84d8f5785e71b134582a"
        }
      ]
    }
  ]
}
