{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLQRCodeUtil",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.0-rc01"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLQRCodeUtil-0.0.9.aar",
          "url": "DLQRCodeUtil-0.0.9.aar",
          "size": 120457,
          "sha512": "db28222fb9ee8cb75f008b4c1d3d0a6d8d64a1d512022693cb7427ba333ddfe3c54e4490913600dad58f18e5d6ce05691c518d3d0cb2d0169a4df83931df24dc",
          "sha256": "107630d0e0caf6dc3ef2aebe7fd4485d0d37bf5b325e073b7ef5208ab2ba7847",
          "sha1": "9b99b59a8ee48593e3d9703c5772000775e1375f",
          "md5": "fb57213d948cdec8164ce0b3fb49f18c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLJetpackComposeUtil",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.32.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.0-rc01"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLQRCodeUtil-0.0.9.aar",
          "url": "DLQRCodeUtil-0.0.9.aar",
          "size": 120457,
          "sha512": "db28222fb9ee8cb75f008b4c1d3d0a6d8d64a1d512022693cb7427ba333ddfe3c54e4490913600dad58f18e5d6ce05691c518d3d0cb2d0169a4df83931df24dc",
          "sha256": "107630d0e0caf6dc3ef2aebe7fd4485d0d37bf5b325e073b7ef5208ab2ba7847",
          "sha1": "9b99b59a8ee48593e3d9703c5772000775e1375f",
          "md5": "fb57213d948cdec8164ce0b3fb49f18c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLQRCodeUtil-0.0.9-sources.jar",
          "url": "DLQRCodeUtil-0.0.9-sources.jar",
          "size": 5261,
          "sha512": "3b7846dfc4b3c80ccf25edb70e17a86cf7676d03eab50f02eaf98b55211150ab443141622b1e898fa2719e6f22801516639772343934ab11cb1269b21f25a124",
          "sha256": "bd3d5a1e8177dabcf2961e054127fe77af55b4b35751195fb318c00390d4d5fa",
          "sha1": "e7b46e70670e9a26d8266578b4e7d3feb892b3ed",
          "md5": "7b44ee96c9c895b051ccbbffd6c689fb"
        }
      ]
    }
  ]
}
