{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLMapboxUtil",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mapbox.maps",
          "module": "android",
          "version": {
            "requires": "10.16.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLMapboxUtil-1.1.1.aar",
          "url": "DLMapboxUtil-1.1.1.aar",
          "size": 973365,
          "sha512": "191f0df705e99797065efa8e4027ed477b821a59505fafadee81ee6c0aa1516fc2b707afe350cb110c4ee2cf949357f60234528938825a8cf2c703077cb49039",
          "sha256": "6ce789fdb314196084c929c851ed1f1f9b9db2545ac7d97e1e8b0ae2a672e27f",
          "sha1": "32b160aaca4cc8e6a4fbf587bd7abd6fe05222d1",
          "md5": "1a81ab6fb9516e6701289f57ceffb30c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.github.raamcosta.compose-destinations",
          "module": "animations-core",
          "version": {
            "requires": "1.9.54"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLJetpackComposeUtil",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLAppUtil",
          "version": {
            "requires": "2.4.8"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLTianDiTuApi",
          "version": {
            "requires": "0.5.5"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLHttpUtil",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLDatastoreUtil",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.mapbox.maps",
          "module": "android",
          "version": {
            "requires": "10.16.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLMapboxUtil-1.1.1.aar",
          "url": "DLMapboxUtil-1.1.1.aar",
          "size": 973365,
          "sha512": "191f0df705e99797065efa8e4027ed477b821a59505fafadee81ee6c0aa1516fc2b707afe350cb110c4ee2cf949357f60234528938825a8cf2c703077cb49039",
          "sha256": "6ce789fdb314196084c929c851ed1f1f9b9db2545ac7d97e1e8b0ae2a672e27f",
          "sha1": "32b160aaca4cc8e6a4fbf587bd7abd6fe05222d1",
          "md5": "1a81ab6fb9516e6701289f57ceffb30c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLMapboxUtil-1.1.1-sources.jar",
          "url": "DLMapboxUtil-1.1.1-sources.jar",
          "size": 58168,
          "sha512": "5c62aeffb4ffd075152bbaf13c21d16b7de59aa2dcea354c26a87291370ed7a8ba2baadb3092db917c6b92e6456dd3df551dbf231fdb65d288bb490657769af8",
          "sha256": "5d8219e49dd1e1b5ffd4631bec8d201dfb54a5b666bdad50cb3e79a9fd5d6aeb",
          "sha1": "7838d3c692cc0bd5dcd010583d814e4f3ff1a231",
          "md5": "05c59d14ddbb8f3c9fe83269b1ea1816"
        }
      ]
    }
  ]
}
