{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLAppUtil",
    "version": "2.4.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLAppUtil-2.4.13.aar",
          "url": "DLAppUtil-2.4.13.aar",
          "size": 145719,
          "sha512": "dae824af99e1e1c1f439c795b8f7afea12f2ce93c6aa5567cb1454b991c07af6543861746618baa1746c142f5c7b4c7c240dcc2050f61578d545e11a75a1ae58",
          "sha256": "3b85293df2bff296da871a45091407757bee8ed9ce21fb348aa6548c3724690a",
          "sha1": "eb95d6aeb8edbc430577dd49d49daae3c8a5279d",
          "md5": "45af9538b9a2f10eb2aaf90bf197a17c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLAppUtil-2.4.13.aar",
          "url": "DLAppUtil-2.4.13.aar",
          "size": 145719,
          "sha512": "dae824af99e1e1c1f439c795b8f7afea12f2ce93c6aa5567cb1454b991c07af6543861746618baa1746c142f5c7b4c7c240dcc2050f61578d545e11a75a1ae58",
          "sha256": "3b85293df2bff296da871a45091407757bee8ed9ce21fb348aa6548c3724690a",
          "sha1": "eb95d6aeb8edbc430577dd49d49daae3c8a5279d",
          "md5": "45af9538b9a2f10eb2aaf90bf197a17c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLAppUtil-2.4.13-sources.jar",
          "url": "DLAppUtil-2.4.13-sources.jar",
          "size": 38484,
          "sha512": "ead8db9c8f0737e9b70d951dd6d8e2ce9db8f3f8470b50a89326ea176572fea73ffebe9c95e2efbb203188ca684969b42b8233aac41418c581131652fe42e986",
          "sha256": "aaba6eeaa5bde198298be3de1c1b40f9b745ace55352fee764bcf15b4c2fd3aa",
          "sha1": "2e21dbded2694c47b550a4f7d542d0060e4b57f9",
          "md5": "6897db7c82f8aa6bd2deea7f5c1f6acc"
        }
      ]
    }
  ]
}
