{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLBluetoothUtil/0.1.11/DLBluetoothUtil-0.1.11.module",
    "group": "com.github.D10NGYANG",
    "module": "DLBluetoothUtil",
    "version": "0.1.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0-RC.2"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "DLBluetoothUtil.klib",
          "url": "DLBluetoothUtil-iosarm64-0.1.11.klib",
          "size": 61485,
          "sha512": "a957599a6c265fd05ccbe285d4649a2ccf2270f36afaa5ad790e4a9a33cdd7c76e0775d7765d491d850d23c4a36009da43f6bd06ee5510ce26ee2e4a5d3486b5",
          "sha256": "fc13f8c4e3bc77017b30de75acd32ca28951a9a2984a6106ba4e35dd8c73eb2b",
          "sha1": "828d97dddaf4e6f792248a51a3c2cbea10140506",
          "md5": "1588ae934cbdb01cbbfd564a7f7d6dbf"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLBluetoothUtil-iosarm64-0.1.11-sources.jar",
          "url": "DLBluetoothUtil-iosarm64-0.1.11-sources.jar",
          "size": 9751,
          "sha512": "8d53d4e50b042169c725dafd44de067f7762adbbf199ae54f54648ebecbaf870eaa7b4375903da34018f04809fbf642af793208ebaf54f0778c8d53c7e00a347",
          "sha256": "fa587e290937b5640f7a1bbe9ad1c06a76e5ea69d6e9e7aa47a6979944212f03",
          "sha1": "387ab9550d1e490e5f28a341685bb703270b81f0",
          "md5": "1a1355b23c82d18e326ae8266fc99502"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0-RC.2"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "DLBluetoothUtil-iosarm64-0.1.11-metadata.jar",
          "url": "DLBluetoothUtil-iosarm64-0.1.11-metadata.jar",
          "size": 261,
          "sha512": "325623da8ef1f2b7d20e5e819a39cee2ed52ee7fc24322c35b93970672554920616991d04670339926a21b2f6df6ec18be6a22db81bebd062c2c62fe4416baf8",
          "sha256": "7ca9fd79a2fdd7cdb8645240ee07181a8e11e37793afa678f8af6e38309cf401",
          "sha1": "ff845fc2ef9ac374e4e3f759ba186f806c298a55",
          "md5": "694cfc751b6dfb4f51d06168cee37790"
        }
      ]
    }
  ]
}
