{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLCommonUtil/0.5.3/DLCommonUtil-0.5.3.module",
    "group": "com.github.D10NGYANG",
    "module": "DLCommonUtil",
    "version": "0.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-release.aar",
          "url": "DLCommonUtil-android-0.5.3.aar",
          "size": 188026,
          "sha512": "e30b076b7fab61c98af2e0dd9461210b93d468f9e50d83ff86709a692fcdd4ac8f5f8fb480ccbe1ddc9f0f0e14249c772012e4c8ec1236139e8b9b66c04a05a2",
          "sha256": "9345e1fa1f17bd576b18168523f5ec0e312f3d44aba68868aafe7178eb863677",
          "sha1": "633b16a6d86182109f887215bd6a9b6d2de299af",
          "md5": "20150d8dcc87fbdf3c4d57ee87f3f4b4"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0-RC.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-release.aar",
          "url": "DLCommonUtil-android-0.5.3.aar",
          "size": 188026,
          "sha512": "e30b076b7fab61c98af2e0dd9461210b93d468f9e50d83ff86709a692fcdd4ac8f5f8fb480ccbe1ddc9f0f0e14249c772012e4c8ec1236139e8b9b66c04a05a2",
          "sha256": "9345e1fa1f17bd576b18168523f5ec0e312f3d44aba68868aafe7178eb863677",
          "sha1": "633b16a6d86182109f887215bd6a9b6d2de299af",
          "md5": "20150d8dcc87fbdf3c4d57ee87f3f4b4"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "DLCommonUtil-android-0.5.3-sources.jar",
          "url": "DLCommonUtil-android-0.5.3-sources.jar",
          "size": 195513,
          "sha512": "3bc229c99a5baad7931a237a1348006d000a7f1be6a47d1a08f111bf4aee408a681d35a263694c6c8de301294b96b413ae5ab512b5299cf89d758ea2e58ad30b",
          "sha256": "f93999f9d01d8df53c6d83867add1f89989cf0e36389aef228661a5e57db83bf",
          "sha1": "00423bc4a3aceb69b9908748b87317e9686f195a",
          "md5": "2d454eb63feff057e2d91fccbb230083"
        }
      ]
    }
  ]
}
