{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLLatLngUtil/1.6.6/DLLatLngUtil-1.6.6.module",
    "group": "com.github.D10NGYANG",
    "module": "DLLatLngUtil",
    "version": "1.6.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil.klib",
          "url": "DLLatLngUtil-iosarm64-1.6.6.klib",
          "size": 60764,
          "sha512": "63ae57ab1f05ba076851b31986b53dc4600d9e26a5b9d86b059b4b1ab9fd98c1d7cfde15a3cad12052936bd19057420bb8700ccae55bae97b4458c3b098dc2b5",
          "sha256": "e9c81c4f90a01a328cbfd035184146a3b7e75987a064fde4e2cfb6510c014a57",
          "sha1": "5eaf92a68fe0ac5b96cf24cc8c32e8ec861823b9",
          "md5": "322d78c5f43b063e52a6597a16029e6e"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil-iosarm64-1.6.6-metadata.jar",
          "url": "DLLatLngUtil-iosarm64-1.6.6-metadata.jar",
          "size": 261,
          "sha512": "268022e9195c4f245cae2e6cf1c6ed50951067343ee1d59b835f6bbe79925286de7173f981657a9c7ce3044748b43af0f718502038b872ee96e4f718487357f0",
          "sha256": "cd9d2d8678e51f2bdf1dc31fc555f7a803ad63301e648663cb0746ca2823d9f0",
          "sha1": "024b02cd232951c31979f096f91d4dbd924dfc78",
          "md5": "4ce2a073e82cdd3cc7fb5d4ac1836071"
        }
      ]
    }
  ]
}
