{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLAppUtil",
    "version": "2.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "DLAppUtil-2.3.2.aar",
          "url": "DLAppUtil-2.3.2.aar",
          "size": 169573,
          "sha512": "558d8afea524ad1eaa5ad95940a41697923a45a94a37f0bef82f7648bf0396cd8df361587192e4b609cd64b052a1f89ae7986e00e7dedc83f596b45705557192",
          "sha256": "9144671e57de504b607700e8166aa5e5e8f10226cf7980192e1143a1ec13f2d2",
          "sha1": "77883efd3c2cbb500901b4c2bd2cd57ba578c753",
          "md5": "a520526f3d677ea30a58ef57af3316e0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "DLAppUtil-2.3.2.aar",
          "url": "DLAppUtil-2.3.2.aar",
          "size": 169573,
          "sha512": "558d8afea524ad1eaa5ad95940a41697923a45a94a37f0bef82f7648bf0396cd8df361587192e4b609cd64b052a1f89ae7986e00e7dedc83f596b45705557192",
          "sha256": "9144671e57de504b607700e8166aa5e5e8f10226cf7980192e1143a1ec13f2d2",
          "sha1": "77883efd3c2cbb500901b4c2bd2cd57ba578c753",
          "md5": "a520526f3d677ea30a58ef57af3316e0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLAppUtil-2.3.2-sources.jar",
          "url": "DLAppUtil-2.3.2-sources.jar",
          "size": 32687,
          "sha512": "d334e131d4bdb65e5aac1887164c88b2a9d6f9eec1bae2c8c6b1f85d7603fcba95d184af5c53c8b9aa3e089a7e5d589470078b1a7e35c168d60507ed8a839fe2",
          "sha256": "3bccedf9bfd760f9d1b5df0dc54566453de69ff91cc0558d10966f8641a5a099",
          "sha1": "4bcd2db049ecbc8ef759ddf7045b429dd5c6f673",
          "md5": "151dd3f94d8252e2acc601819dc6f5e7"
        }
      ]
    }
  ]
}
