{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ImageCompress/1.0.0-beta16/ImageCompress-1.0.0-beta16.module",
    "group": "com.hailiao.util",
    "module": "ImageCompress",
    "version": "1.0.0-beta16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ImageCompress-jvm-1.0.0-beta16.jar",
          "url": "ImageCompress-jvm-1.0.0-beta16.jar",
          "size": 763897,
          "sha512": "9a5549a0aed9161e3bbfa23711826f379084055bc855c0854893650d021fc752ddf65bf36b57e1f70382a28d04c0de9147718fbcbb4421185d50d40c1c45ae61",
          "sha256": "7762fb39ce173158d4c5925baaaa3ab7ab5f3626be1e5494dc0f07e43160c42e",
          "sha1": "e6b1d79e5f3a226e217d96688a5e1b9c74d77c29",
          "md5": "8dbbfab788d1667e97b37dcb77b68b18"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ImageCompress-jvm-1.0.0-beta16.jar",
          "url": "ImageCompress-jvm-1.0.0-beta16.jar",
          "size": 763897,
          "sha512": "9a5549a0aed9161e3bbfa23711826f379084055bc855c0854893650d021fc752ddf65bf36b57e1f70382a28d04c0de9147718fbcbb4421185d50d40c1c45ae61",
          "sha256": "7762fb39ce173158d4c5925baaaa3ab7ab5f3626be1e5494dc0f07e43160c42e",
          "sha1": "e6b1d79e5f3a226e217d96688a5e1b9c74d77c29",
          "md5": "8dbbfab788d1667e97b37dcb77b68b18"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ImageCompress-jvm-1.0.0-beta16-sources.jar",
          "url": "ImageCompress-jvm-1.0.0-beta16-sources.jar",
          "size": 10552,
          "sha512": "aecece37f803bd4cef4ea8a92b7a4ce2050316c8e613717d6858e7f922fcd7a9f78b9a681d620df0407bb677d0287957544b86d2f02f8932e11662f79eea578d",
          "sha256": "027d3000a9dd8ccc456be323516bd08ba739c8ec251d9f330e37cb08d7fadd84",
          "sha1": "a5808f770134e88194993bb1dffdbeeb854ea19f",
          "md5": "e41c84b5ad41d7678ffc0307140159c8"
        }
      ]
    }
  ]
}
