{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLLatLngUtil/1.6.1/DLLatLngUtil-1.6.1.module",
    "group": "com.github.D10NGYANG",
    "module": "DLLatLngUtil",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil-js-1.6.1.klib",
          "url": "DLLatLngUtil-js-1.6.1.klib",
          "size": 51794,
          "sha512": "421d88a4059889b44cfa3b391fb2461b93996064a3c597c3444409034c64a2fc0b038971cf7a665f87755e0aec83bde753bbb14c350eb1d8d1a19e53586179de",
          "sha256": "0839fd19a8d33699c46e6208b28dace53a7209dd3ed2e3cd051082acbc508667",
          "sha1": "fceea726290d0a7e558f3b3b2736abc12d5e8f52",
          "md5": "3e67b42489bd51f311ede266b8d73e46"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil-js-1.6.1.klib",
          "url": "DLLatLngUtil-js-1.6.1.klib",
          "size": 51794,
          "sha512": "421d88a4059889b44cfa3b391fb2461b93996064a3c597c3444409034c64a2fc0b038971cf7a665f87755e0aec83bde753bbb14c350eb1d8d1a19e53586179de",
          "sha256": "0839fd19a8d33699c46e6208b28dace53a7209dd3ed2e3cd051082acbc508667",
          "sha1": "fceea726290d0a7e558f3b3b2736abc12d5e8f52",
          "md5": "3e67b42489bd51f311ede266b8d73e46"
        }
      ]
    }
  ]
}
