{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLCommonUtil/0.1.2/DLCommonUtil-0.1.2.module",
    "group": "com.github.D10NGYANG",
    "module": "DLCommonUtil",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.biezhi",
          "module": "TinyPinyin",
          "version": {
            "requires": "2.0.3.RELEASE"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-jvm-0.1.2.jar",
          "url": "DLCommonUtil-jvm-0.1.2.jar",
          "size": 67102,
          "sha512": "b11d18739dd51d3c412ec71fe13b1344739cde9967d02e74d079ed49d4efe59f10422170373b2806611cf3d68567d24640f7059ef4ec363a70330b950dae49b0",
          "sha256": "e673c5258f1acf4edf12e1426dd42d8add59f5e28baf1b46bdc0ba593527ea78",
          "sha1": "38a540ce8fa8c405eb887206938a37459ade0785",
          "md5": "04fce56800d210bc6e88142970c318ba"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.biezhi",
          "module": "TinyPinyin",
          "version": {
            "requires": "2.0.3.RELEASE"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-jvm-0.1.2.jar",
          "url": "DLCommonUtil-jvm-0.1.2.jar",
          "size": 67102,
          "sha512": "b11d18739dd51d3c412ec71fe13b1344739cde9967d02e74d079ed49d4efe59f10422170373b2806611cf3d68567d24640f7059ef4ec363a70330b950dae49b0",
          "sha256": "e673c5258f1acf4edf12e1426dd42d8add59f5e28baf1b46bdc0ba593527ea78",
          "sha1": "38a540ce8fa8c405eb887206938a37459ade0785",
          "md5": "04fce56800d210bc6e88142970c318ba"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "DLCommonUtil-jvm-0.1.2-sources.jar",
          "url": "DLCommonUtil-jvm-0.1.2-sources.jar",
          "size": 30375,
          "sha512": "3308e930f26475eb8fd658fc5b406920a5e32efde6c85cd71f2d60ea94837573f388737b882a2afdd8ac1f2812eef69e0e6cbf6bbd809a4cc82bc155ab468d4b",
          "sha256": "a7409a0f2836268a384de5b99721ad3b57bad4cd35ed34375b8815596cabd573",
          "sha1": "9f44c93c745e0710fffc68e012743a101083acfe",
          "md5": "2027bae6d7a389fbb41c4b4fd656bd7b"
        }
      ]
    }
  ]
}
