{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLGpsUtil",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLGpsUtil-2.3.0.aar",
          "url": "DLGpsUtil-2.3.0.aar",
          "size": 21621,
          "sha512": "f25440c99d7b78ac89c4b67df721add906843f79fe80192761a1c85d257396be23a52eff36aaa6c5d0067d2bb7211c2fac688c0c843783c18852d5daa565eafc",
          "sha256": "08b7a763ffd5378d04f3382eb72756adc812d8f2251e548584cd27a6bc373bd1",
          "sha1": "d01d5e738961ed17cd842beab540e32d590b98c0",
          "md5": "5671e30870c6dc9a199d7c660c5b26ee"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLLatLngUtil-jvm",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "com.amap.api",
          "module": "location",
          "version": {
            "requires": "latest.integration"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLGpsUtil-2.3.0.aar",
          "url": "DLGpsUtil-2.3.0.aar",
          "size": 21621,
          "sha512": "f25440c99d7b78ac89c4b67df721add906843f79fe80192761a1c85d257396be23a52eff36aaa6c5d0067d2bb7211c2fac688c0c843783c18852d5daa565eafc",
          "sha256": "08b7a763ffd5378d04f3382eb72756adc812d8f2251e548584cd27a6bc373bd1",
          "sha1": "d01d5e738961ed17cd842beab540e32d590b98c0",
          "md5": "5671e30870c6dc9a199d7c660c5b26ee"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLGpsUtil-2.3.0-sources.jar",
          "url": "DLGpsUtil-2.3.0-sources.jar",
          "size": 8020,
          "sha512": "b435b51d3d2d6263c9bd41f60dffeed5a8b673326192994106c9653a6af44bdef6cc74071ec3d67d830f15e9279d93b04cce5464add2afb67ef07dd0fde88b18",
          "sha256": "b30ff1f484dbc2af9fad17bc9f881c4bf5a7ced0adee8da14f565ce48fc78704",
          "sha1": "5f9866c66ee6deb4ebcfc1539c3d887b8bbaf1a7",
          "md5": "bda3a0108f6b97bd1ffc61396c33b19b"
        }
      ]
    }
  ]
}
