{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLCommonUtil",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-metadata-0.0.2.jar",
          "url": "DLCommonUtil-0.0.2.jar",
          "size": 4783,
          "sha512": "3b65630f23536647baa41342a35f1b30c6a523133d4e201ffc8eefc989c275a4be1ffcd90b95f87814aa7e4b382e0ff2a4a59cd050117f3eab5feefa168d9f8a",
          "sha256": "6dad5d6911ca9003fb90c7c9109ecb6de0cb720883f8264e178220baea4427c2",
          "sha1": "08b43d3d9151d9cc61123250ec6b3046f313d538",
          "md5": "aa4375eda0c2d3cb1046f4df9886659a"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "DLCommonUtil-kotlin-0.0.2-sources.jar",
          "url": "DLCommonUtil-0.0.2-sources.jar",
          "size": 11130,
          "sha512": "75166e7c0cca7ab3ba296f068e2479a11ee265aa02743661ba3d0cb1c790f0c3655aaa60a6a5a0b9a18e4ad1f06cf0a57c1f2802f6cf111c74a9faa029614be7",
          "sha256": "34417bc41403ad5e79eb38368f1b9b537fc727aef5ecdc4cc51b434259f8ea26",
          "sha1": "4fe626086eaa1db591f76217d7dc867c38b996bd",
          "md5": "6b0cc9fd6c34fc0e7d60846e6ea3477c"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCommonUtil-iosarm64/0.0.2/DLCommonUtil-iosarm64-0.0.2.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-iosarm64",
        "version": "0.0.2"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCommonUtil-iosarm64/0.0.2/DLCommonUtil-iosarm64-0.0.2.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-iosarm64",
        "version": "0.0.2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCommonUtil-iosarm64/0.0.2/DLCommonUtil-iosarm64-0.0.2.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-iosarm64",
        "version": "0.0.2"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCommonUtil-iosx64/0.0.2/DLCommonUtil-iosx64-0.0.2.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-iosx64",
        "version": "0.0.2"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCommonUtil-iosx64/0.0.2/DLCommonUtil-iosx64-0.0.2.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-iosx64",
        "version": "0.0.2"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCommonUtil-iosx64/0.0.2/DLCommonUtil-iosx64-0.0.2.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-iosx64",
        "version": "0.0.2"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLCommonUtil-js/0.0.2/DLCommonUtil-js-0.0.2.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-js",
        "version": "0.0.2"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLCommonUtil-js/0.0.2/DLCommonUtil-js-0.0.2.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-js",
        "version": "0.0.2"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLCommonUtil-js/0.0.2/DLCommonUtil-js-0.0.2.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-js",
        "version": "0.0.2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLCommonUtil-jvm/0.0.2/DLCommonUtil-jvm-0.0.2.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-jvm",
        "version": "0.0.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLCommonUtil-jvm/0.0.2/DLCommonUtil-jvm-0.0.2.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-jvm",
        "version": "0.0.2"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLCommonUtil-jvm/0.0.2/DLCommonUtil-jvm-0.0.2.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-jvm",
        "version": "0.0.2"
      }
    }
  ]
}
