{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ImageCompress/1.0.0-beta07/ImageCompress-1.0.0-beta07.module",
    "group": "com.hailiao.util",
    "module": "ImageCompress",
    "version": "1.0.0-beta07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ImageCompress.klib",
          "url": "ImageCompress-iosarm64-1.0.0-beta07.klib",
          "size": 37645,
          "sha512": "9c66f0fbd0351389fd3d40dd14865ea751201cde8a8c78ebc4f87dbfd28bf11454155e2fcfc869e3926252a8015abddd8de9c788e161d09dfdfa57789f2feca9",
          "sha256": "bd5c76b730d5b8f2e8283f18b6426d255b375493590817c963672c3e2fe3aa81",
          "sha1": "909290691ed4a5e4bc44902a993bc3ea22da52af",
          "md5": "b104ee41c42074a1d73a6fe7ef91ea35"
        },
        {
          "name": "ImageCompress-cinterop-ImageCompress.klib",
          "url": "ImageCompress-iosarm64-1.0.0-beta07-cinterop-ImageCompress.klib",
          "size": 267434,
          "sha512": "45e0313e50896b1d6cc65b67251159ace9b80249dbe27eb67d46d58a4cd228469d5f1bb4a3dce82f25250016cd51f24d74121ccc560f88f0067386344e046c89",
          "sha256": "fda78a1fb1f256fec0b8669605406c0a0fa7c1b9bcd9eaf55b32d8c144299d31",
          "sha1": "7c2d9a57ef891ec4dc993b76eba96e65623610b0",
          "md5": "2d23ddcc1d7b81bcab3d70f2bcddde7a"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ImageCompress-iosarm64-1.0.0-beta07-sources.jar",
          "url": "ImageCompress-iosarm64-1.0.0-beta07-sources.jar",
          "size": 11286,
          "sha512": "fa682e55d1f89ebfe7c31963d359fc7958acd6b4b099cc41975806e85187a5a87d46a20cd221d5150131220383434a3b3c52bcb912ce6d9fc0b6076de9e31893",
          "sha256": "55be3e295c238161925cb1b0887887fa017ef3e8642b938475aedab6770851af",
          "sha1": "720b67c0bdd034871bd9d93419b67e5f0820b181",
          "md5": "0823242a2331a9097f06cb256a254329"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ImageCompress-iosarm64-1.0.0-beta07-metadata.jar",
          "url": "ImageCompress-iosarm64-1.0.0-beta07-metadata.jar",
          "size": 261,
          "sha512": "102c3fe1cccc92e015dcc08e6e4a2486570338d98f1a58da17a4fb157548c6639d827a3c5c923422a6c4af4ceb86bfd0fbd2f472b5d9f6d2d3ea48b30235a2c6",
          "sha256": "2b8adaa81be6761e574f71b877a8fad07320af2587f979bdef19c5413d80561a",
          "sha1": "b43ba8e67bcaa041e0a7b46671a596178d6657bc",
          "md5": "7bab16f34f315470b05eb6b06603e621"
        }
      ]
    }
  ]
}
