{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLHttpUtil/0.7/DLHttpUtil-0.7.module",
    "group": "com.github.D10NGYANG",
    "module": "DLHttpUtil",
    "version": "0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLHttpUtil-jvm-0.7.jar",
          "url": "DLHttpUtil-jvm-0.7.jar",
          "size": 34297,
          "sha512": "b31ebca070cb83ae9cf7e5a082a7c4b7b6fd46870fa81af47d3ee8b95ba12fb25f2b1f8235fc9d02b3b3c680796fb03ff5ed2a80285111968775263429bf21af",
          "sha256": "65e8780d4f22433d83006a89777e20ca6fe99b2fb18754a501edfad6ea3eba90",
          "sha1": "df8e332ffc52a4c98a2cd327663464192b174dd4",
          "md5": "48985e3767476087978161802593c927"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLHttpUtil-jvm-0.7.jar",
          "url": "DLHttpUtil-jvm-0.7.jar",
          "size": 34297,
          "sha512": "b31ebca070cb83ae9cf7e5a082a7c4b7b6fd46870fa81af47d3ee8b95ba12fb25f2b1f8235fc9d02b3b3c680796fb03ff5ed2a80285111968775263429bf21af",
          "sha256": "65e8780d4f22433d83006a89777e20ca6fe99b2fb18754a501edfad6ea3eba90",
          "sha1": "df8e332ffc52a4c98a2cd327663464192b174dd4",
          "md5": "48985e3767476087978161802593c927"
        }
      ]
    }
  ]
}
