{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLLatLngUtil/1.6.8/DLLatLngUtil-1.6.8.module",
    "group": "com.github.D10NGYANG",
    "module": "DLLatLngUtil",
    "version": "1.6.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil.klib",
          "url": "DLLatLngUtil-iosarm64-1.6.8.klib",
          "size": 61918,
          "sha512": "8dbab6433424fefe111d213af47e7214d640db65f8106f5251d100720e6605943817c080529ca22b3b5b20eda27fd6082277e11a19587043767f52edf81c04c4",
          "sha256": "4ee17abd4a038182db7d27b5293e2668486bd76fbed3cdcee664af3caf7a7d9f",
          "sha1": "77375f7015291a57848906c5ae511d9b80a528aa",
          "md5": "c7c814efc93502a4d11aca724b45abfc"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil-iosarm64-1.6.8-metadata.jar",
          "url": "DLLatLngUtil-iosarm64-1.6.8-metadata.jar",
          "size": 261,
          "sha512": "9e58da4f03dbd81bd293cfdff8ee707c56db4b12260a5df03f46904b8059666f8eb2805ce6410ccb3aecca72cdc2fa1b585bc9a59d7b933c60073032368c27e8",
          "sha256": "ff81b7c0596718bf76b5733ac2fd606f2ac40b63719653a487abb86b6dcfd411",
          "sha1": "93a86a92326cdb8747d541c899328b3f46c8c5a7",
          "md5": "8e1854bbb6142d274919ec1ee1c23ff3"
        }
      ]
    }
  ]
}
