{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLSerialPortUtil/0.6.0/DLSerialPortUtil-0.6.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLSerialPortUtil",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "2.11.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLSerialPortUtil-jvm-0.6.0.jar",
          "url": "DLSerialPortUtil-jvm-0.6.0.jar",
          "size": 36116,
          "sha512": "d8bd65a83794934976635a9af06225cf4eae1b9caac3b21eafccde712c71f582624380e68d717427bbe18cafeb200342617a4609d17d5d89b1de4497297588ec",
          "sha256": "e5de7a68b9ddf262ce811afc226063798aefbf5cf0873e4c205a9e0ac727f902",
          "sha1": "043048cb7f94e1723cfb9ea0be2b48386d752663",
          "md5": "d01e2b9fc0768211825b5a151b3808bc"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "2.11.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLLogUtil",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLSerialPortUtil-jvm-0.6.0.jar",
          "url": "DLSerialPortUtil-jvm-0.6.0.jar",
          "size": 36116,
          "sha512": "d8bd65a83794934976635a9af06225cf4eae1b9caac3b21eafccde712c71f582624380e68d717427bbe18cafeb200342617a4609d17d5d89b1de4497297588ec",
          "sha256": "e5de7a68b9ddf262ce811afc226063798aefbf5cf0873e4c205a9e0ac727f902",
          "sha1": "043048cb7f94e1723cfb9ea0be2b48386d752663",
          "md5": "d01e2b9fc0768211825b5a151b3808bc"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "DLSerialPortUtil-jvm-0.6.0-sources.jar",
          "url": "DLSerialPortUtil-jvm-0.6.0-sources.jar",
          "size": 7955,
          "sha512": "96be97df655398af26dc832eef3a931892d588e585e2900524ece9631191523878884d0b9b4f8d20392068e5869ddec1c486dcac4f4389e0e1f0e474a55b38ed",
          "sha256": "03479b6616cfb849c5b36d2ae013d6a4150a7400a5d643288da73b9f720668a4",
          "sha1": "af5d6956e5f9c850a4960c244de063438b171d50",
          "md5": "ff13703b6946fb23ba1be6452a205e62"
        }
      ]
    }
  ]
}
