{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/1.8.6/DLDateUtil-1.8.6.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "1.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-jvm-1.8.6.jar",
          "url": "DLDateUtil-jvm-1.8.6.jar",
          "size": 28910,
          "sha512": "7c32a4f75713edfa7af7939dc417d9c76ef5c161190dd6d9a47820dda9a0fd3ca6ee096e3b2c9462c044823b6a0fe41256b5fc84085e2a365d36316b0e549345",
          "sha256": "7cf78be340ee8bdd8281193976cad5c2c6a0c1fb573dc909e85f477ac5ad7b96",
          "sha1": "42433f8ea76c6dc35a78b75a93956346e6d38c4d",
          "md5": "f9176def78d50e6c21a7e6f584434616"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-jvm-1.8.6.jar",
          "url": "DLDateUtil-jvm-1.8.6.jar",
          "size": 28910,
          "sha512": "7c32a4f75713edfa7af7939dc417d9c76ef5c161190dd6d9a47820dda9a0fd3ca6ee096e3b2c9462c044823b6a0fe41256b5fc84085e2a365d36316b0e549345",
          "sha256": "7cf78be340ee8bdd8281193976cad5c2c6a0c1fb573dc909e85f477ac5ad7b96",
          "sha1": "42433f8ea76c6dc35a78b75a93956346e6d38c4d",
          "md5": "f9176def78d50e6c21a7e6f584434616"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "DLDateUtil-jvm-1.8.6-sources.jar",
          "url": "DLDateUtil-jvm-1.8.6-sources.jar",
          "size": 11910,
          "sha512": "108bb3c148c15c16b4e240f2b11b8e20b6d7c94d6680034575999a56e166543c25e36f492bda7573695677f253071aae06e64b1ac6632f64e85fd8eaae28f0bf",
          "sha256": "5ebddfab1c84e1378c93f70a6b8be3d13a70603499e1be8db161532792516fa9",
          "sha1": "0b214b743f647748b262ec9ec3f56214c225ee52",
          "md5": "06ed913039b6a285aa1a38df9d1371ee"
        }
      ]
    }
  ]
}
