{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLSideBar_Compose",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLSideBar_Compose-1.1.1.aar",
          "url": "DLSideBar_Compose-1.1.1.aar",
          "size": 22494,
          "sha512": "ff9943f7339b0d93580dd2b2547ae9fe91169b588dd0f38377325c44177155877338aedebc2ea99e8f88bb73b01405eb69cb0c1e4a578afaba38e69077d4ce58",
          "sha256": "7e3d2b5f8240c11d750011c3f811f2743d5252a543fa65322a82004b9543e002",
          "sha1": "568fdad8a29745630a3b3504a3d1e6416a341de4",
          "md5": "5ce58bdda62c031ec2a7783e733551e0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2023.01.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLSideBar_Compose-1.1.1.aar",
          "url": "DLSideBar_Compose-1.1.1.aar",
          "size": 22494,
          "sha512": "ff9943f7339b0d93580dd2b2547ae9fe91169b588dd0f38377325c44177155877338aedebc2ea99e8f88bb73b01405eb69cb0c1e4a578afaba38e69077d4ce58",
          "sha256": "7e3d2b5f8240c11d750011c3f811f2743d5252a543fa65322a82004b9543e002",
          "sha1": "568fdad8a29745630a3b3504a3d1e6416a341de4",
          "md5": "5ce58bdda62c031ec2a7783e733551e0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLSideBar_Compose-1.1.1-sources.jar",
          "url": "DLSideBar_Compose-1.1.1-sources.jar",
          "size": 2294,
          "sha512": "87d8c12a43d8bb6fad11e1fd7efcf5d4e3fc6e32ad3ccf234b20e37e9d493998c67472049ade1b8a0fc27d0824d2f49ae8c480e750f7bdc96050d85efb9cd67d",
          "sha256": "371fc60d3619f3306c60acfecef248b4b84c3343fe774d5c11745b2a18f52c60",
          "sha1": "74b079c899bb9e328d142340d704662a54ec0464",
          "md5": "d9087ca4ca0a1cbb2625e829882fdb6f"
        }
      ]
    }
  ]
}
