{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/2.1.3/DLDateUtil-2.1.3.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "2.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-macosX64Main-2.1.3.klib",
          "url": "DLDateUtil-macosx64-2.1.3.klib",
          "size": 78195,
          "sha512": "bb2f309c70a6acbd6162495edf9b55017192774e8330faf9478af3d2dae360937f28f690d0c79c143f78c9f7523ffccc7fc2a8e5f98138da5acfbdcd1e5b1943",
          "sha256": "3ae3937e5bd37a99e18a496dc513546853e08daadcb02cc5654a31f630293016",
          "sha1": "a7f320e7ec12f861f0e8b84dacb9ae8164e0a09d",
          "md5": "544346b4386727cc9d3abdcdaa4e4ffe"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLDateUtil-macosx64-2.1.3-sources.jar",
          "url": "DLDateUtil-macosx64-2.1.3-sources.jar",
          "size": 17463,
          "sha512": "bb3a3993bfaa48011c2d827153ee6aae326cf05d78463575db2b23bb4a1a7ebc39398d491c3419e5ab885bc296b5143445d65e6b401b06f887bfb7bb07946d4a",
          "sha256": "352121accf74b1ebeb34dc8f64c47432bd58599aec2da3583910e2d2d610ef88",
          "sha1": "afe3c7b840c6185cf4647bc72c46a6a6974bcf89",
          "md5": "b005d5f34aec98f5aac50d1c0877c39c"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-macosx64-2.1.3-metadata.jar",
          "url": "DLDateUtil-macosx64-2.1.3-metadata.jar",
          "size": 261,
          "sha512": "66e90491522537414d8e8210505ba56442c4835d93d1d69555ca19fdbc5c89e025548ff3fa9f3d4fbd6b53a94e6d3b1d34262330aee29b90fc37b7229270a38b",
          "sha256": "29a4b7cb1cc34c7884aa819d8579c40f5e685c6d560638f7cf70cc20ea2c6d7f",
          "sha1": "961c6c61967ccaffd2906af3e677d554600ea8b5",
          "md5": "c9aba9d503a0ca30dea0ae08ff9b5380"
        }
      ]
    }
  ]
}
