{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLJetpackComposeUtil/3.2.0/DLJetpackComposeUtil-3.2.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLJetpackComposeUtil",
    "version": "3.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-jvm-3.2.0.jar",
          "url": "DLJetpackComposeUtil-jvm-3.2.0.jar",
          "size": 833092,
          "sha512": "b83e14a519ad5e063fe28a1eb7f0026c1dfdd6005e614a5fb6f266dbb85c6526bdc8d44d1e9051abb0e8bd35d1ba31917b5b448077c55530f6568bf33ba46e05",
          "sha256": "613de0580e85d1377e417e76f82c9c5dab2d33eebc300197003ce882f665d579",
          "sha1": "3a6be0fad16c8ed6743bed3334aae9d8273eaf45",
          "md5": "21cb2cf883dfcf3b73ad62ce877d0424"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-jvm-3.2.0.jar",
          "url": "DLJetpackComposeUtil-jvm-3.2.0.jar",
          "size": 833092,
          "sha512": "b83e14a519ad5e063fe28a1eb7f0026c1dfdd6005e614a5fb6f266dbb85c6526bdc8d44d1e9051abb0e8bd35d1ba31917b5b448077c55530f6568bf33ba46e05",
          "sha256": "613de0580e85d1377e417e76f82c9c5dab2d33eebc300197003ce882f665d579",
          "sha1": "3a6be0fad16c8ed6743bed3334aae9d8273eaf45",
          "md5": "21cb2cf883dfcf3b73ad62ce877d0424"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "DLJetpackComposeUtil-jvm-3.2.0-sources.jar",
          "url": "DLJetpackComposeUtil-jvm-3.2.0-sources.jar",
          "size": 101738,
          "sha512": "2c0daae5ad444c00c852087b62c217f3f143a25a1c38f3f3bc356fbb77c28b47d6915fbab287d978731b21444aa000e7f87f65603908d23ed8f4f1e3bf813f8f",
          "sha256": "f39b31f2041de5f7b1fefb105e3debc8c620b470335dc0c3a0f64e00d50ba898",
          "sha1": "eb7149f6f1fc9bed6f3dd942571a2ce544e37f8a",
          "md5": "0a7fa8e8eab4c38ecab74a2e39a75b14"
        }
      ]
    }
  ]
}
