{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/2.3.0-alpha01/DLDateUtil-2.3.0-alpha01.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "2.3.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-macosArm64Main-2.3.0-alpha01.klib",
          "url": "DLDateUtil-macosarm64-2.3.0-alpha01.klib",
          "size": 92678,
          "sha512": "3a1660e81878e3556f20b04acffdc47b590777cc93999d30a4620c048c1765576c4f7826812202a2a3cd852feb322142f7460aad0d8c13d47c7f852418b0089f",
          "sha256": "fe58acd78eecb5b6379779df581ffd5dc2ba3c61d3f9dc92295f1062e1e2588e",
          "sha1": "b3427aca79e45391db1728bc3ac1058935900696",
          "md5": "f313fc61966f5f648cd8564d61782b47"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLDateUtil-macosarm64-2.3.0-alpha01-sources.jar",
          "url": "DLDateUtil-macosarm64-2.3.0-alpha01-sources.jar",
          "size": 20711,
          "sha512": "1a7e2c8a7d2d19933ecf19c7c3b0f11c25e7608b4dedd5b086e4f5d789dd4aa4d9f9dd62c04193cda628ad50f2c9054fa2f3ce25a32231edb209722cc1f45861",
          "sha256": "3226355c59e086e941ccde3df5dc183c94fee93de7e471d1f0dc38165205d03e",
          "sha1": "6b6911ce395d0504143be31a704f369eb86dd172",
          "md5": "3373755ef4b3167533a70abb517304c3"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-macosarm64-2.3.0-alpha01-metadata.jar",
          "url": "DLDateUtil-macosarm64-2.3.0-alpha01-metadata.jar",
          "size": 261,
          "sha512": "e5f83b52e4aa9ebb824838699d12a473bafb1bee8fe9b7b16c26286e7c1c1a18c10d25fbbfc60119a6d32b7b8e75580807ef952c694809cfadc9d18b459c7a4c",
          "sha256": "14b6cd0d95712d1e289549d1ef1bfece423a8710b555223c0c25734fc06bd3ab",
          "sha1": "e6a5b2d437b862860ef16eb2c9d7c702c12a8ae9",
          "md5": "b4624e38ff6856f439bb5b129e444513"
        }
      ]
    }
  ]
}
