{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/2.1.0/DLDateUtil-2.1.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-iosSimulatorArm64Main-2.1.0.klib",
          "url": "DLDateUtil-iossimulatorarm64-2.1.0.klib",
          "size": 76986,
          "sha512": "1780245a73e69619904bb94c7ab485d551e97f9e97f409455a719df41d81e1c8eba80e7b189d2df3d011a897d5e0fbcbae652af1ec826bde7213cd934bbe71f9",
          "sha256": "afb21f9f496fe613ef6b18f6122b7b685ae8c7cadaec7d61cc3e165e0d58e3db",
          "sha1": "d0e0d5e1c02604c3e7d328315508a3d375f744cc",
          "md5": "5a18c72eabe43fb75fa71f751b6fe5b0"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLDateUtil-iossimulatorarm64-2.1.0-sources.jar",
          "url": "DLDateUtil-iossimulatorarm64-2.1.0-sources.jar",
          "size": 17232,
          "sha512": "b8d79c6283ff88e837ddc3a09ba5bdf8699a2a4fe77e5fc8901d5cce63e8c9d4febfd42667699643513e15abe3162d38b6caa93b7e57235ef6af4b0b02099887",
          "sha256": "f7b7660b171231b2f4c2aff1359711b1694e753a21041add4b009f1d859055b8",
          "sha1": "29731f21fc212fa56c686b33b47c58e97a676243",
          "md5": "cfe31385e210ad62a83d8b501483b495"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-iossimulatorarm64-2.1.0-metadata.jar",
          "url": "DLDateUtil-iossimulatorarm64-2.1.0-metadata.jar",
          "size": 261,
          "sha512": "d3c992b099b719c3c8d10c82576b38c1ef9d0bb8243fcb71233bb12b6c9a44c53b6f0593d0840f2d3195bfd2a24402d6f044b7c7888e078778dc1854b7cb53a6",
          "sha256": "879a51da646f5161e48f5d093e477e1e7aae0695a5615b0fa6f3f6952c69d3b4",
          "sha1": "c6173b45cc17ee230e7471387740693d9d147caa",
          "md5": "ea5f9f6e68bccd9304e679e0091a1d4a"
        }
      ]
    }
  ]
}
