{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLLogUtil/0.1.2/DLLogUtil-0.1.2.module",
    "group": "com.github.D10NGYANG",
    "module": "DLLogUtil",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLLogUtil-release.aar",
          "url": "DLLogUtil-android-0.1.2.aar",
          "size": 10148,
          "sha512": "0f7f837bbbd5b302ab727329254c4b60689369f7c345154cbf5859af06cc9a9cbfd28855fa52f555657cbf393ec4f13513b225719bce3fcfd324f6ba65424ca2",
          "sha256": "30a455edcb95b787b8cf12c129fe2fe92f8beb0696ac016384ec0f0b60027076",
          "sha1": "6f244bb5a99d5cc3f4cff1708237e9f3cb27ab5e",
          "md5": "6be6982d588ac6ebdd203be613d184a7"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "DLLogUtil-release.aar",
          "url": "DLLogUtil-android-0.1.2.aar",
          "size": 10148,
          "sha512": "0f7f837bbbd5b302ab727329254c4b60689369f7c345154cbf5859af06cc9a9cbfd28855fa52f555657cbf393ec4f13513b225719bce3fcfd324f6ba65424ca2",
          "sha256": "30a455edcb95b787b8cf12c129fe2fe92f8beb0696ac016384ec0f0b60027076",
          "sha1": "6f244bb5a99d5cc3f4cff1708237e9f3cb27ab5e",
          "md5": "6be6982d588ac6ebdd203be613d184a7"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "DLLogUtil-android-0.1.2-sources.jar",
          "url": "DLLogUtil-android-0.1.2-sources.jar",
          "size": 4425,
          "sha512": "4a43118705d6cc67d6ee39d32d473ecd26458f6db97e03d94951b42ce71e2aa5805fb06060ced9ee3ffca0b6369aae60cf3cbe86ef4047540e0fe1d47af025b3",
          "sha256": "ba1148411d78631e027fa1e5ec40007cef8a4d0b71dddd4245d10eda6e521d1c",
          "sha1": "d33860dce44535342d87430d855429131994c57a",
          "md5": "7e2821b25bb6bfd7c1db63d534dc212a"
        }
      ]
    }
  ]
}
