{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLCryptoUtil/0.1.1/DLCryptoUtil-0.1.1.module",
    "group": "com.github.D10NGYANG",
    "module": "DLCryptoUtil",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "DLCryptoUtil-js-0.1.1.klib",
          "url": "DLCryptoUtil-js-0.1.1.klib",
          "size": 30746,
          "sha512": "f5e97a500f5d1cf42cddec2d4c9a6fa5593f58ca8d77e55e66e13544ab5d3be9a2ad6b4cfe8dd66f3e846173cd77a38496495fcb47a2d248d63f0fd1fad3a744",
          "sha256": "40524786c9ccee20e4508bf1bec47fc8aec61fcc52e0b34f0f415407c0d896ed",
          "sha1": "b525cb92cc4adaa5af1394c0cca7bf97bdc5e473",
          "md5": "80a8a1e3b0c0471a5fe5a7f3db9f20a0"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "DLCryptoUtil-js-0.1.1.klib",
          "url": "DLCryptoUtil-js-0.1.1.klib",
          "size": 30746,
          "sha512": "f5e97a500f5d1cf42cddec2d4c9a6fa5593f58ca8d77e55e66e13544ab5d3be9a2ad6b4cfe8dd66f3e846173cd77a38496495fcb47a2d248d63f0fd1fad3a744",
          "sha256": "40524786c9ccee20e4508bf1bec47fc8aec61fcc52e0b34f0f415407c0d896ed",
          "sha1": "b525cb92cc4adaa5af1394c0cca7bf97bdc5e473",
          "md5": "80a8a1e3b0c0471a5fe5a7f3db9f20a0"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "DLCryptoUtil-js-0.1.1-sources.jar",
          "url": "DLCryptoUtil-js-0.1.1-sources.jar",
          "size": 8494,
          "sha512": "7726fec7084606396cd1a2fb1a14c3fb69d3f2092fd774ea4d93391ff293e79b5f6ed0d382dc3e8e15ed2244c45084edb35aac1f523700e8bb144ff97f583a4b",
          "sha256": "a321a632bd6b5d5d4e731275c408975323f6a165da2b25889f1a7a60fb36c113",
          "sha1": "9aefbec01d7f990b52ccc37ab6a7a1027417e3ee",
          "md5": "6b82b4a7cce2637e98a44ab595182e00"
        }
      ]
    }
  ]
}
