{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "2.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-metadata-2.1.1.jar",
          "url": "DLDateUtil-2.1.1.jar",
          "size": 11564,
          "sha512": "d8d33bd24bec8f9d0d84ce188ad8ba512a441a251a26092c99a3d76d5f02904dab9c274b7840f65bb87d836738a479e998098577344a3181eca28708c3af9ae2",
          "sha256": "79353fa24905a529b28dbc07d65710bfedeb8ea62bd15552220ca959056be43d",
          "sha1": "56bf5c090f7257b39cf15a04c8e070c549c6e815",
          "md5": "e8dd715bfa62e7b7ccf866421a5ac1ba"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "DLDateUtil-kotlin-2.1.1-sources.jar",
          "url": "DLDateUtil-2.1.1-sources.jar",
          "size": 17258,
          "sha512": "e7110c4db22a2fca426dafe65ffde30426f1fe32969d480b3560d82384441b2b576321ca3767ce9f5f0732a9c88920c8dff9281eaaa6e38de151c12da43407c2",
          "sha256": "4ef01c563471fdffed520731c972180b18d41f44e1ff9470330b423229711e1b",
          "sha1": "bba88fe001b315a87f7a3aaee527c1a6dea2ad95",
          "md5": "7b1c0822b6333991fde1119b7b514c74"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLDateUtil-android/2.1.1/DLDateUtil-android-2.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-android",
        "version": "2.1.1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLDateUtil-android/2.1.1/DLDateUtil-android-2.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-android",
        "version": "2.1.1"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLDateUtil-android/2.1.1/DLDateUtil-android-2.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-android",
        "version": "2.1.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iosarm64/2.1.1/DLDateUtil-iosarm64-2.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iosarm64",
        "version": "2.1.1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iosarm64/2.1.1/DLDateUtil-iosarm64-2.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iosarm64",
        "version": "2.1.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iosarm64/2.1.1/DLDateUtil-iosarm64-2.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iosarm64",
        "version": "2.1.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iossimulatorarm64/2.1.1/DLDateUtil-iossimulatorarm64-2.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iossimulatorarm64",
        "version": "2.1.1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iossimulatorarm64/2.1.1/DLDateUtil-iossimulatorarm64-2.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iossimulatorarm64",
        "version": "2.1.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iossimulatorarm64/2.1.1/DLDateUtil-iossimulatorarm64-2.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iossimulatorarm64",
        "version": "2.1.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iosx64/2.1.1/DLDateUtil-iosx64-2.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iosx64",
        "version": "2.1.1"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iosx64/2.1.1/DLDateUtil-iosx64-2.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iosx64",
        "version": "2.1.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iosx64/2.1.1/DLDateUtil-iosx64-2.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iosx64",
        "version": "2.1.1"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLDateUtil-js/2.1.1/DLDateUtil-js-2.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-js",
        "version": "2.1.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLDateUtil-js/2.1.1/DLDateUtil-js-2.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-js",
        "version": "2.1.1"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLDateUtil-js/2.1.1/DLDateUtil-js-2.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-js",
        "version": "2.1.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLDateUtil-jvm/2.1.1/DLDateUtil-jvm-2.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-jvm",
        "version": "2.1.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLDateUtil-jvm/2.1.1/DLDateUtil-jvm-2.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-jvm",
        "version": "2.1.1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLDateUtil-jvm/2.1.1/DLDateUtil-jvm-2.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-jvm",
        "version": "2.1.1"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-linuxarm64/2.1.1/DLDateUtil-linuxarm64-2.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-linuxarm64",
        "version": "2.1.1"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-linuxarm64/2.1.1/DLDateUtil-linuxarm64-2.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-linuxarm64",
        "version": "2.1.1"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-linuxx64/2.1.1/DLDateUtil-linuxx64-2.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-linuxx64",
        "version": "2.1.1"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-linuxx64/2.1.1/DLDateUtil-linuxx64-2.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-linuxx64",
        "version": "2.1.1"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-macosarm64/2.1.1/DLDateUtil-macosarm64-2.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-macosarm64",
        "version": "2.1.1"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-macosarm64/2.1.1/DLDateUtil-macosarm64-2.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-macosarm64",
        "version": "2.1.1"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-macosarm64/2.1.1/DLDateUtil-macosarm64-2.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-macosarm64",
        "version": "2.1.1"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-macosx64/2.1.1/DLDateUtil-macosx64-2.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-macosx64",
        "version": "2.1.1"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-macosx64/2.1.1/DLDateUtil-macosx64-2.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-macosx64",
        "version": "2.1.1"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-macosx64/2.1.1/DLDateUtil-macosx64-2.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-macosx64",
        "version": "2.1.1"
      }
    }
  ]
}
