{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLBluetoothUtil/0.2.0/DLBluetoothUtil-0.2.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLBluetoothUtil",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "DLBluetoothUtil.klib",
          "url": "DLBluetoothUtil-iosarm64-0.2.0.klib",
          "size": 61417,
          "sha512": "76b2905e9b5087b6007419286a57c1ff702f424ecead8080d453d27c1471f775c55b5bb79882fd7dbf66994f3dc153cc6777de8d0abc9ad0a040b3bd22c353fb",
          "sha256": "67e48ad37dfaac7d2cdc4736b34519f68a7405cda4c138346847ab6a448a33d1",
          "sha1": "3d79e4437663bc602dc80aab6b4a7a5dc29aac02",
          "md5": "fc9dab804f182dc52dd8e9a9c41a342a"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLBluetoothUtil-iosarm64-0.2.0-sources.jar",
          "url": "DLBluetoothUtil-iosarm64-0.2.0-sources.jar",
          "size": 10037,
          "sha512": "8f86f8d223947b27b9ea849a74019d9d655ebf109aa44bc126000ee743241b0287586438b6708a847bfd79228c5949cc7041c89105c4fb2c9d64ac53ae7160d5",
          "sha256": "a2cdc8f6f30dde3865d58e9f9eab92bfa56fcee1d8c1e42898b92445cdb47806",
          "sha1": "54a0fa467904889e55df63c0b781517650a41093",
          "md5": "2955ed6b0d34ab7b81e263af114e4e8e"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "DLBluetoothUtil-iosarm64-0.2.0-metadata.jar",
          "url": "DLBluetoothUtil-iosarm64-0.2.0-metadata.jar",
          "size": 261,
          "sha512": "214c8cdded5431d828c311459784e6b4bb68f56261f37fb3b370b082fa8ae1673e9873d8650b6bdf3ff33c63c0dc2ee2f872d8ec2520910fa2ef47351a6cff8c",
          "sha256": "bf4b09ce1b43a1c2f41446bd263fd8cd1f14b8d5733a6bec940d70400f7f5a04",
          "sha1": "0bceb16eee9daee6289154669d5d5f3f4d63574a",
          "md5": "b29b27e9d4c76739547ad1af7a807b55"
        }
      ]
    }
  ]
}
