{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLJetpackComposeUtil/3.1.0/DLJetpackComposeUtil-3.1.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLJetpackComposeUtil",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-wasm-js-3.1.0.klib",
          "url": "DLJetpackComposeUtil-wasm-js-3.1.0.klib",
          "size": 638928,
          "sha512": "63ebe66ea2ba17bcb6b904b2eeb1bc81dff4b1083d2ecd68a9aa295cf7a88b7e3448ec68e3ad8a2773f7f293ddc9049994cbe5ce45f08e462dac51e75639e32c",
          "sha256": "a62796b992087949a28a6a1f5fd85227e2d7d6a8021cc0d383dca151796d4a9f",
          "sha1": "3df0dcd07cc02956acb7f59f6586acef525d920d",
          "md5": "4ad8bda1bda698bff778b552a88fb27a"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-wasm-js-3.1.0.klib",
          "url": "DLJetpackComposeUtil-wasm-js-3.1.0.klib",
          "size": 638928,
          "sha512": "63ebe66ea2ba17bcb6b904b2eeb1bc81dff4b1083d2ecd68a9aa295cf7a88b7e3448ec68e3ad8a2773f7f293ddc9049994cbe5ce45f08e462dac51e75639e32c",
          "sha256": "a62796b992087949a28a6a1f5fd85227e2d7d6a8021cc0d383dca151796d4a9f",
          "sha1": "3df0dcd07cc02956acb7f59f6586acef525d920d",
          "md5": "4ad8bda1bda698bff778b552a88fb27a"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "DLJetpackComposeUtil-wasm-js-3.1.0-sources.jar",
          "url": "DLJetpackComposeUtil-wasm-js-3.1.0-sources.jar",
          "size": 80951,
          "sha512": "2bcdc8ca4c0e58d6040228822aaacc5ac58d59cb8965701da288cf762d0ce814034baeed735876155294d5cd57b0a3175b2dfee0fa363cb383740184ec78d911",
          "sha256": "73d7e18d9a70350f3d3b1e96ef67ff1af770b8fbc1d8455c64aed645e855014d",
          "sha1": "2777364c173f85bbb43c9f2d8c39c4b47916f018",
          "md5": "5dd0d848b0fbc4f0d7a8c8b26e24e1b5"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-3.1.0.kotlin_resources.zip",
          "url": "DLJetpackComposeUtil-wasm-js-3.1.0-kotlin_resources.kotlin_resources.zip",
          "size": 10276,
          "sha512": "c6b3b565ae284c08171f4e407b80818cfeeb2638986409ae1c18d59e89ff24081b8089f828094dbdf3e1da326be67ebede3c0ef22933767c36acafd9cad426ba",
          "sha256": "5425a6d85939dc6645136952bc3a83f9476f9a53b85fd48d44b99274c2cbd927",
          "sha1": "bf99b3639644a2bd14f60e1fb822d71eeb89ad01",
          "md5": "b2d2a126aec682e466be8d0b015574d9"
        }
      ]
    }
  ]
}
