{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLTianDiTuApi/1.1.0/DLTianDiTuApi-1.1.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLTianDiTuApi",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLTianDiTuApi-iosSimulatorArm64Main-1.1.0.klib",
          "url": "DLTianDiTuApi-iossimulatorarm64-1.1.0.klib",
          "size": 112568,
          "sha512": "26a472234b405054468b9619356f5ab287bfcbec23ed855b7f92b35ffc379bcd18a78dc880d11b7b47a4359d2d10f0af0c3fffe0cead058ab7d184239ea1cd53",
          "sha256": "79de88a588a432cdd8d0216a4c3bfe4305988dc37e147d0bbe35223a34d3d845",
          "sha1": "569f928388f25f70be31ba6a1e4090c25a8de270",
          "md5": "b5c74cadadba3058717fe0527fe5628f"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLTianDiTuApi-iossimulatorarm64-1.1.0-sources.jar",
          "url": "DLTianDiTuApi-iossimulatorarm64-1.1.0-sources.jar",
          "size": 6741,
          "sha512": "e995fd07814e5a74a95204d799c654f7da718945c0da9e007b32c722f6f66af2530e821b6ae755d000b3f768b7ed5f5ba48599211dc0e8bed8834ec08ff7e6b0",
          "sha256": "0414baa275caeb80f95cda9aeef4ed8055384c749dae672dafeea476dc9d8b9c",
          "sha1": "0828114131dafc5114da91d86d312e29b9883d3e",
          "md5": "13050d4174ed636150e82130e94bd601"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLTianDiTuApi-iossimulatorarm64-1.1.0-metadata.jar",
          "url": "DLTianDiTuApi-iossimulatorarm64-1.1.0-metadata.jar",
          "size": 261,
          "sha512": "a6b03fcc8ed0b8cc8ee28551902a2036ec8791d13e1fac675547a0b836306504b5fc3d79b70dbee5583e60a1f012cc742f6fb87b8aa778a3b62ba2f13afce489",
          "sha256": "c26e05e5b7f500e798a4512ec19575f8413bdbd8ac4d9f5209dfaf357b75ad3f",
          "sha1": "093bf22d0d3d10d6d7b8297693e7ef7f7f3be8f8",
          "md5": "91df510240ab997ffc213d867c62bf99"
        }
      ]
    }
  ]
}
