{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLGpsUtil",
    "version": "2.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLGpsUtil-2.2.0.aar",
          "url": "DLGpsUtil-2.2.0.aar",
          "size": 22981,
          "sha512": "c06043565b7aab553c7a7e886281ae1eb4919786e54712de72be2d4b13a5802be054ee31f955311d78c106df10cc2fd77691ca9c946930df763a8fb0b6c30e2e",
          "sha256": "f66001372dc949962d7361c88569483c06771e6a82c6e7b0e3a357e84e908678",
          "sha1": "b458cc4b8f7f7da2895e62a6c692b05bf51625bb",
          "md5": "57e67a2eb9aa941a26342e29e7f7cd4a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLLatLngUtil-jvm",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "com.amap.api",
          "module": "location",
          "version": {
            "requires": "latest.integration"
          }
        }
      ],
      "files": [
        {
          "name": "DLGpsUtil-2.2.0.aar",
          "url": "DLGpsUtil-2.2.0.aar",
          "size": 22981,
          "sha512": "c06043565b7aab553c7a7e886281ae1eb4919786e54712de72be2d4b13a5802be054ee31f955311d78c106df10cc2fd77691ca9c946930df763a8fb0b6c30e2e",
          "sha256": "f66001372dc949962d7361c88569483c06771e6a82c6e7b0e3a357e84e908678",
          "sha1": "b458cc4b8f7f7da2895e62a6c692b05bf51625bb",
          "md5": "57e67a2eb9aa941a26342e29e7f7cd4a"
        }
      ]
    }
  ]
}
