{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLHttpUtil/1.1.0/DLHttpUtil-1.1.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLHttpUtil",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.12"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLHttpUtil.klib",
          "url": "DLHttpUtil-linuxarm64-1.1.0.klib",
          "size": 13028,
          "sha512": "90c4d66908a1fd68a00dec9ab4dddb09ea3c74a13a93d894c0614e1935a10f1033747cd42c13771c9bf068ed2e9afe2dc4b2bbe314ac8c5d70088432e910ec0e",
          "sha256": "228760ff428ae1c6c6e32910c934611571bf299c30bde4a21f02f44ac207e13b",
          "sha1": "5471723cec6ea5881a3ed6c9feb11eb14233fe4b",
          "md5": "914e54591456acdb92c1321840e9f720"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLHttpUtil-linuxarm64-1.1.0-sources.jar",
          "url": "DLHttpUtil-linuxarm64-1.1.0-sources.jar",
          "size": 2913,
          "sha512": "37be5199735fdcfcea2c7a63f5a4bb484bf40bb019ef8aa88d4021585b79bfacea1e22f2ff9d8209b7a1815831a67d4e2c7c521e6ab44fec866c1388a5def84a",
          "sha256": "e5a750526882cf9f6e02b8eab86ba1cb21d24b0677ae2af0bfc525935459af7a",
          "sha1": "ebc7642e7dc1c4d10a1d3b16fa514d78d68a8f31",
          "md5": "2ce7c4f734a184b63b90aa8d988649d3"
        }
      ]
    }
  ]
}
