{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLCommonUtil/0.0.3/DLCommonUtil-0.0.3.module",
    "group": "com.github.D10NGYANG",
    "module": "DLCommonUtil",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.ditchoom",
          "module": "buffer",
          "version": {
            "requires": "1.3.6"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil.klib",
          "url": "DLCommonUtil-iosarm64-0.0.3.klib",
          "size": 91629,
          "sha512": "308443cc88bd315674e8666e7ea5946f06c40023e1c225c1e11193e45cee61851ef32ff022592c17ca14eb16589fbd9e2803b0d454e62c9af2688f82a6a1372e",
          "sha256": "16fb872153921b1f4ca69249e684d94e6b9fdd147431c8f36211f5291c6e9ced",
          "sha1": "dfb39f5e57e51ed34243e34258da86e4c6a66175",
          "md5": "ee5f9181e1c8c19d50e55f6642ca72c9"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLCommonUtil-iosarm64-0.0.3-sources.jar",
          "url": "DLCommonUtil-iosarm64-0.0.3-sources.jar",
          "size": 26804,
          "sha512": "7797e98ebb05e0ff4dc72b7f7fc1b1ce3914211ba170b551b6f0dd2a5ac9f0350cb3017a9b200053ace1a92e4322720bfe2ed6c69871128c7bbcb7c83e816a78",
          "sha256": "13f21dc625b3d13d73dc056ac001a387e428933e876add6084d6bbdd910755f2",
          "sha1": "bcd641fa3df51b0e131161aa2c5d10d9b2648998",
          "md5": "7514a59f7f0e568c1bb7e3633adaec41"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.ditchoom",
          "module": "buffer",
          "version": {
            "requires": "1.3.6"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-iosarm64-0.0.3-metadata.jar",
          "url": "DLCommonUtil-iosarm64-0.0.3-metadata.jar",
          "size": 4070,
          "sha512": "cb5b5fca1784922c6dfbe10b6c40d5becbbd85dd4355d52e6938eeb0f87abc0aab9b0711747b2393bc8d96865b942fd411839889618c9c3d7c2db92c96d50d4d",
          "sha256": "745e4ad885f8e38a4d63953800f0e05d3723e009580327e7787e5d545917fcbe",
          "sha1": "a3b5ff3d23726998a98d3006d321cd31b4a35bfc",
          "md5": "90ab30388dd1ba7dc8a77c8710d123b0"
        }
      ]
    }
  ]
}
