{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLBluetoothUtil",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLBluetoothUtil-metadata-0.1.0.jar",
          "url": "DLBluetoothUtil-0.1.0.jar",
          "size": 5122,
          "sha512": "6e9b28d7dd2e56514e160e15cf0b8ae346878b6e9d4b808f892171a3e803c3def7ec849241314cc70137229983771e452dc506e9e12f36b1c3eb27dcb1b9065c",
          "sha256": "3b37d59c892511e01a2f635c9702ac02c5108a90eea8de70d1cd3f1512b63192",
          "sha1": "5912d3ec6d2e8f3140f46ba23d2df282d20f8ea6",
          "md5": "9e443a4153998e7df520ff228b30b06a"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "DLBluetoothUtil-kotlin-0.1.0-sources.jar",
          "url": "DLBluetoothUtil-0.1.0-sources.jar",
          "size": 4338,
          "sha512": "ebee286c1bc211f597b8c25e3852c07b5ce8609af4202fd478d3841aaed875a7ec8a6592a21ff333a0aa7dd3b18cd9a1047cdadffa99ca95b0371951f4465feb",
          "sha256": "581a687eced8857b68e7d2606d89bce2b4ce2ce2ea66807e57ab7e5a0c33ee01",
          "sha1": "8f1407ee6c42ecb386b56acd07956591e0b3d601",
          "md5": "177c9b210f83d2790b25db715a5a4701"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLBluetoothUtil-android/0.1.0/DLBluetoothUtil-android-0.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLBluetoothUtil-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLBluetoothUtil-android/0.1.0/DLBluetoothUtil-android-0.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLBluetoothUtil-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLBluetoothUtil-android/0.1.0/DLBluetoothUtil-android-0.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLBluetoothUtil-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLBluetoothUtil-iosarm64/0.1.0/DLBluetoothUtil-iosarm64-0.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLBluetoothUtil-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLBluetoothUtil-iosarm64/0.1.0/DLBluetoothUtil-iosarm64-0.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLBluetoothUtil-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLBluetoothUtil-iosarm64/0.1.0/DLBluetoothUtil-iosarm64-0.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLBluetoothUtil-iosarm64",
        "version": "0.1.0"
      }
    }
  ]
}
