{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLTianDiTuApi/0.5.8/DLTianDiTuApi-0.5.8.module",
    "group": "com.github.D10NGYANG",
    "module": "DLTianDiTuApi",
    "version": "0.5.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "DLTianDiTuApi-jvm-0.5.8.jar",
          "url": "DLTianDiTuApi-jvm-0.5.8.jar",
          "size": 141584,
          "sha512": "2269bf12b0f025c87fc28d8812c942d1ae0c74774a573fb0da238e6c27ce0a3acbbd3b2ffa4d950a366411590f5f8fa8123a296227a09d9445a4a671fb213941",
          "sha256": "833ae6064ac4bc333d657620649a9294fd2e4d04e6c866c2572c48fcd2001e45",
          "sha1": "850cb3c56bcda829dcf48934b90213010cb28fb0",
          "md5": "f21559ac1f74366681bc68e5f96b6b22"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLHttpUtil",
          "version": {
            "requires": "0.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "DLTianDiTuApi-jvm-0.5.8.jar",
          "url": "DLTianDiTuApi-jvm-0.5.8.jar",
          "size": 141584,
          "sha512": "2269bf12b0f025c87fc28d8812c942d1ae0c74774a573fb0da238e6c27ce0a3acbbd3b2ffa4d950a366411590f5f8fa8123a296227a09d9445a4a671fb213941",
          "sha256": "833ae6064ac4bc333d657620649a9294fd2e4d04e6c866c2572c48fcd2001e45",
          "sha1": "850cb3c56bcda829dcf48934b90213010cb28fb0",
          "md5": "f21559ac1f74366681bc68e5f96b6b22"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "DLTianDiTuApi-jvm-0.5.8-sources.jar",
          "url": "DLTianDiTuApi-jvm-0.5.8-sources.jar",
          "size": 5469,
          "sha512": "d238c283caf972418445334e9dde3b7efcc354b82196e703010a06930ce16fec3f1308f2fdcad171d55901b9cbf1230e042ad81aacd16eb4e0fceac3700e0810",
          "sha256": "f2b7119cebe892b5978627c10220a9709a3b67c90895bfa1b14f8cadcc70147e",
          "sha1": "220da6eae88f23a85d8abecf02332f80f7ac4f74",
          "md5": "deef194662c7ec67d99e7fb1b6a6574a"
        }
      ]
    }
  ]
}
