{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ImageCompress/1.0.0-beta18/ImageCompress-1.0.0-beta18.module",
    "group": "com.hailiao.util",
    "module": "ImageCompress",
    "version": "1.0.0-beta18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ImageCompress-release.aar",
          "url": "ImageCompress-android-1.0.0-beta18.aar",
          "size": 3893853,
          "sha512": "7f02d8d9962fe15c7d38fc8b002cd32475e95932fa5f9ac285cf2fc0a29611f5febd76e49b060b8155559082cfc190e9f57403e945088668b95be5e77d4c55d8",
          "sha256": "a0e91b0d9b5fe978c61c90d42c71e97dc14d8af09c2667eada8f5d04107ff4e2",
          "sha1": "446cc28eb535b76d43e11ee975da0c9fc904fc0c",
          "md5": "29840dc554c6d1460f061cb24623d566"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ImageCompress-release.aar",
          "url": "ImageCompress-android-1.0.0-beta18.aar",
          "size": 3893853,
          "sha512": "7f02d8d9962fe15c7d38fc8b002cd32475e95932fa5f9ac285cf2fc0a29611f5febd76e49b060b8155559082cfc190e9f57403e945088668b95be5e77d4c55d8",
          "sha256": "a0e91b0d9b5fe978c61c90d42c71e97dc14d8af09c2667eada8f5d04107ff4e2",
          "sha1": "446cc28eb535b76d43e11ee975da0c9fc904fc0c",
          "md5": "29840dc554c6d1460f061cb24623d566"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ImageCompress-android-1.0.0-beta18-sources.jar",
          "url": "ImageCompress-android-1.0.0-beta18-sources.jar",
          "size": 11165,
          "sha512": "c0ab63d6cef522b2a1b1f23767cbdc3a9235b7dc44c10c1be7c51a21c76056069b79989df76ed3eeaf1bb333034ceabbba5a42f911e5205f0d13e9d032962269",
          "sha256": "cc5533bc3b5778dccf88d0c816f5289e6abab6edefd8d69b495a7b0f30d5ccbf",
          "sha1": "873a12f4d590b23d9d9053b6b2a03e8d37adb644",
          "md5": "666c48762f8fecae375ab7ebf95f0213"
        }
      ]
    }
  ]
}
