{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLLatLngUtil/1.5.5/DLLatLngUtil-1.5.5.module",
    "group": "com.github.D10NGYANG",
    "module": "DLLatLngUtil",
    "version": "1.5.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil.klib",
          "url": "DLLatLngUtil-iosx64-1.5.5.klib",
          "size": 47163,
          "sha512": "d8ef795d05686114c1568802b5657c0c33b992959ad5da1792b48e9c4bf02dd9551637ad04b9c43698fe4f45e0bf95d92034168703c652b6026914ed491bdaa1",
          "sha256": "df975d6a6fb7736bd1d6ce00af9379a0d89211f3dcf7a977963ed854cc586dd7",
          "sha1": "fcb97798525b40b8ef241fa4ae05831a28898fca",
          "md5": "e11d89348a39afe0e9e01e3192d86e1f"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil-iosx64-1.5.5-metadata.jar",
          "url": "DLLatLngUtil-iosx64-1.5.5-metadata.jar",
          "size": 261,
          "sha512": "f278ed3e6e273e0dc63e6cf11c3cbaa0932d96587e37e747541ea84c9e00f59dcd38bdb7e22aab3fb4155d5345a4f3e42e66dd5bf85e33540c8a2caf901b911a",
          "sha256": "d5891d480a6c66c810197d95e988fe04683a56ea7f7f0409b02a36d829e44ca9",
          "sha1": "d1e616941715b6f855a308c52ab61747f56b720c",
          "md5": "6f425e5b89f67e9375f0f2f2ea9cd38b"
        }
      ]
    }
  ]
}
