{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLAppUtil",
    "version": "2.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLAppUtil-2.2.2.aar",
          "url": "DLAppUtil-2.2.2.aar",
          "size": 204809,
          "sha512": "e93d9de5d512e0cde996a865e8d6bcd0799f3fe478a8578632fac386823d1712d8b0ab0152a5d3fcf45f4056d13c8ff37722838a44571524f6a459aa857c6743",
          "sha256": "a6a77861f0f13d4beee0268c6ed2cb3d7c68a8a371af661f9ea141dcadfa71bb",
          "sha1": "6d4a2c890f10ad11c84753a2aab4edb3e9bf622f",
          "md5": "01ae8aded414e6c1271af8752477a907"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLAppUtil-2.2.2.aar",
          "url": "DLAppUtil-2.2.2.aar",
          "size": 204809,
          "sha512": "e93d9de5d512e0cde996a865e8d6bcd0799f3fe478a8578632fac386823d1712d8b0ab0152a5d3fcf45f4056d13c8ff37722838a44571524f6a459aa857c6743",
          "sha256": "a6a77861f0f13d4beee0268c6ed2cb3d7c68a8a371af661f9ea141dcadfa71bb",
          "sha1": "6d4a2c890f10ad11c84753a2aab4edb3e9bf622f",
          "md5": "01ae8aded414e6c1271af8752477a907"
        }
      ]
    }
  ]
}
