{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLAppUtil",
    "version": "2.5.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLAppUtil-2.5.5.aar",
          "url": "DLAppUtil-2.5.5.aar",
          "size": 185601,
          "sha512": "df74a664682eaf02733a8ca6a5d5d39b21dcc3d4e133729b954724cf85de04b8084463758f8c4b093f6e8613c8786d8d870f93293b3231e806f19606f975239a",
          "sha256": "a9f25af02b3d38df2740c44453384d21c9b6e2d6790e0c9d284a17dfc890ce2d",
          "sha1": "3de57ebfdbbb14991abc8e85b0af37dd82dd1c0f",
          "md5": "7e48d3dc083aa296f7fdfd40056186f7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLAppUtil-2.5.5.aar",
          "url": "DLAppUtil-2.5.5.aar",
          "size": 185601,
          "sha512": "df74a664682eaf02733a8ca6a5d5d39b21dcc3d4e133729b954724cf85de04b8084463758f8c4b093f6e8613c8786d8d870f93293b3231e806f19606f975239a",
          "sha256": "a9f25af02b3d38df2740c44453384d21c9b6e2d6790e0c9d284a17dfc890ce2d",
          "sha1": "3de57ebfdbbb14991abc8e85b0af37dd82dd1c0f",
          "md5": "7e48d3dc083aa296f7fdfd40056186f7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLAppUtil-2.5.5-sources.jar",
          "url": "DLAppUtil-2.5.5-sources.jar",
          "size": 40374,
          "sha512": "1f192173cf6c2d87b9d585089131f3d7af9d5481a7b81af387695a72fb19318c6694342fa67590b9c062c17b2298493a1494bfbf4830ffe3c259526b4699dfaa",
          "sha256": "f23ace03da57a6ebc77c60d3812eb50d510c28a1226fcb8066e22614ed5a18f8",
          "sha1": "c6a308ed97fb0723c073b2e03c9964cfe1ac9635",
          "md5": "6efbff71aac483d0a926611dd7dde2ff"
        }
      ]
    }
  ]
}
