{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLLatLngUtil/1.6.8/DLLatLngUtil-1.6.8.module",
    "group": "com.github.D10NGYANG",
    "module": "DLLatLngUtil",
    "version": "1.6.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil.klib",
          "url": "DLLatLngUtil-iosx64-1.6.8.klib",
          "size": 61902,
          "sha512": "3f625fef89da37de1f91ae0ed51a1da0733862e06d2dbfc385251192e9953757480412ee78b006f5c1120201590f0cbde9efa1ce80d528cd4798216fabcce291",
          "sha256": "946ceb78a238403bf8561497a3e25f12fe0658be709f326f4590020127193058",
          "sha1": "b07aca7564e0ed665ffe840844231c9840bc650c",
          "md5": "653e4ebd72afe4d1a74ca37de123c85e"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil-iosx64-1.6.8-metadata.jar",
          "url": "DLLatLngUtil-iosx64-1.6.8-metadata.jar",
          "size": 261,
          "sha512": "ad5788f06c3a7c3a7ced37a7e666dcdc39d8cecfa058035a5b3d71e9469bcae17003ca438196d9adc727d7878350a78c352883c2cdfe5a7dfd96a9ca0389d166",
          "sha256": "d95c3c612e1ba394e0e12b7b31d2f828a91d6009864bd50ced33c5e372773e1f",
          "sha1": "d43f747b55a1ed3fab0dd8370bd3c257ee22a59a",
          "md5": "2ec810eddc75b129f2460390e7eaa85c"
        }
      ]
    }
  ]
}
