{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLLogUtil/0.1.2/DLLogUtil-0.1.2.module",
    "group": "com.github.D10NGYANG",
    "module": "DLLogUtil",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "DLLogUtil-linuxX64Main-0.1.2.klib",
          "url": "DLLogUtil-linuxx64-0.1.2.klib",
          "size": 18220,
          "sha512": "e8bcee63315b8d786fb82a98a5f161711a929902c453208607b66446e30db61acf39e3d7bc1463ba6c98b17df590000c7aef51c72cd6d5603df5d71c81923a77",
          "sha256": "528841bcb713c28cd12967e3b9e3c500ade33d2aab8935ddea9573f8abfe2526",
          "sha1": "4e66c36844bdcf2a595e6ec99b7df332aad4d555",
          "md5": "05dff2b89f6831497a934c5e5f35a8f6"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLLogUtil-linuxx64-0.1.2-sources.jar",
          "url": "DLLogUtil-linuxx64-0.1.2-sources.jar",
          "size": 4717,
          "sha512": "3cea152e92c43e1ae7922cb8ff596592891784d2d1437d8cb554c499b07e81f8c013186bb9684137e434d552b4ac8456ee749dbb13e1820fa9a72a601790bd1c",
          "sha256": "0e0113478694b3eb7ec08cd22cbba01dacefb53c9524ca30deaae910a914713e",
          "sha1": "ba0a378e87da08585a8c7860b63183970384b186",
          "md5": "6872e061d06483f3e98ac65dd29d3156"
        }
      ]
    }
  ]
}
