{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLTianDiTuApi/1.1.0/DLTianDiTuApi-1.1.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLTianDiTuApi",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLTianDiTuApi-js-1.1.0.klib",
          "url": "DLTianDiTuApi-js-1.1.0.klib",
          "size": 112616,
          "sha512": "3861ca5311054297141f81e14b3bb6a2f9f1de53038ac32eb0e2d27cc484dceec72406f70ea0f201cf436e8328c2fa674011bb4d34936cf611f05e3ef114e4d5",
          "sha256": "643c77c5c24ec71a2bd1657e3440d38373eb2cb9b45f846e5095063c9669e7a9",
          "sha1": "af2ba3b72cdba70720e8afdf520645a9c3def40e",
          "md5": "77a39bb0181c1fa62e698dc6aa29ce6e"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLTianDiTuApi-js-1.1.0.klib",
          "url": "DLTianDiTuApi-js-1.1.0.klib",
          "size": 112616,
          "sha512": "3861ca5311054297141f81e14b3bb6a2f9f1de53038ac32eb0e2d27cc484dceec72406f70ea0f201cf436e8328c2fa674011bb4d34936cf611f05e3ef114e4d5",
          "sha256": "643c77c5c24ec71a2bd1657e3440d38373eb2cb9b45f846e5095063c9669e7a9",
          "sha1": "af2ba3b72cdba70720e8afdf520645a9c3def40e",
          "md5": "77a39bb0181c1fa62e698dc6aa29ce6e"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "DLTianDiTuApi-js-1.1.0-sources.jar",
          "url": "DLTianDiTuApi-js-1.1.0-sources.jar",
          "size": 6741,
          "sha512": "e995fd07814e5a74a95204d799c654f7da718945c0da9e007b32c722f6f66af2530e821b6ae755d000b3f768b7ed5f5ba48599211dc0e8bed8834ec08ff7e6b0",
          "sha256": "0414baa275caeb80f95cda9aeef4ed8055384c749dae672dafeea476dc9d8b9c",
          "sha1": "0828114131dafc5114da91d86d312e29b9883d3e",
          "md5": "13050d4174ed636150e82130e94bd601"
        }
      ]
    }
  ]
}
