{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ImageCompress/1.0.0-beta05/ImageCompress-1.0.0-beta05.module",
    "group": "com.hailiao.util",
    "module": "ImageCompress",
    "version": "1.0.0-beta05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ImageCompress-release.aar",
          "url": "ImageCompress-android-1.0.0-beta05.aar",
          "size": 3892090,
          "sha512": "d7eecbad37c0efe8f0c57daf2551a9330caf5ab91f798b8b437a4e5f67f4a5bd703f6c8c9b5d0b4d54ac5347b004a84ec3caf40954cd649cae4da04323169d91",
          "sha256": "9b6e7dcbefd496355dca0b4958c015e92704e43d1824a9a73011417eddb4c902",
          "sha1": "4884e012b732d08422d44ae7383442670e1527c6",
          "md5": "27bc4bc55bf66c2f7772e8388594c47a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ImageCompress-release.aar",
          "url": "ImageCompress-android-1.0.0-beta05.aar",
          "size": 3892090,
          "sha512": "d7eecbad37c0efe8f0c57daf2551a9330caf5ab91f798b8b437a4e5f67f4a5bd703f6c8c9b5d0b4d54ac5347b004a84ec3caf40954cd649cae4da04323169d91",
          "sha256": "9b6e7dcbefd496355dca0b4958c015e92704e43d1824a9a73011417eddb4c902",
          "sha1": "4884e012b732d08422d44ae7383442670e1527c6",
          "md5": "27bc4bc55bf66c2f7772e8388594c47a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ImageCompress-android-1.0.0-beta05-sources.jar",
          "url": "ImageCompress-android-1.0.0-beta05-sources.jar",
          "size": 10517,
          "sha512": "b0b608eec07e9a4fdb7f089fab6c7cc30a1f8ee11292264d41756971bb6087ef2f579625a9bef79942c311066a6f1b7470778627954d9d6691e2d54a801742f9",
          "sha256": "3bc3042d940f8470339867149a68807b0a15f4c57f5a10bc6fe6c8eb97f4e353",
          "sha1": "3582fed7279d6e037b178ba2872675910e62e8f8",
          "md5": "fa4dcbd13c3cdcd3bb72c9e424fe301b"
        }
      ]
    }
  ]
}
