{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "1.8.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-metadata-1.8.4.jar",
          "url": "DLDateUtil-1.8.4.jar",
          "size": 5617,
          "sha512": "6da9e7473ae55bc1f97d8d02adf59cd0cb5dc23da1de1633ef0f3e6dfa5542813d75415a50b48bb0029242d8d25aa7637a8c31fa76dccc33b99b3eb50aca29a8",
          "sha256": "51f814e96e0f300171f4fbdf4b7a7aa24b41ed1b8a2f3d921d10fb16418a0bd3",
          "sha1": "92ae7f5196a92d9d2ed3fd9a90f9a434fcdf19dc",
          "md5": "0609503b8e10b5ad1ea93d92af0cb5e5"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "DLDateUtil-kotlin-1.8.4-sources.jar",
          "url": "DLDateUtil-1.8.4-sources.jar",
          "size": 11373,
          "sha512": "3d877f11d865230c7177c53fd3abc20ade99c65adb16915e8492a9db80ed0112281cd215767a4b74705a1890f0470c850e632f2099d01c145e5e5a4cf266e2ca",
          "sha256": "83bfe469421c38653921fad26bac19bcae41128519d1275c84363db1f0d226e7",
          "sha1": "f99af8fa06a0161b9dd4b793ea0b660618f8ceac",
          "md5": "b00f0f014fe94b176c0aa2759eb83221"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iosarm64/1.8.4/DLDateUtil-iosarm64-1.8.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iosarm64",
        "version": "1.8.4"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iosarm64/1.8.4/DLDateUtil-iosarm64-1.8.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iosarm64",
        "version": "1.8.4"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iosarm64/1.8.4/DLDateUtil-iosarm64-1.8.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iosarm64",
        "version": "1.8.4"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iosx64/1.8.4/DLDateUtil-iosx64-1.8.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iosx64",
        "version": "1.8.4"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iosx64/1.8.4/DLDateUtil-iosx64-1.8.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iosx64",
        "version": "1.8.4"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iosx64/1.8.4/DLDateUtil-iosx64-1.8.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iosx64",
        "version": "1.8.4"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLDateUtil-js/1.8.4/DLDateUtil-js-1.8.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-js",
        "version": "1.8.4"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLDateUtil-js/1.8.4/DLDateUtil-js-1.8.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-js",
        "version": "1.8.4"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLDateUtil-js/1.8.4/DLDateUtil-js-1.8.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-js",
        "version": "1.8.4"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLDateUtil-jvm/1.8.4/DLDateUtil-jvm-1.8.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-jvm",
        "version": "1.8.4"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLDateUtil-jvm/1.8.4/DLDateUtil-jvm-1.8.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-jvm",
        "version": "1.8.4"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLDateUtil-jvm/1.8.4/DLDateUtil-jvm-1.8.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-jvm",
        "version": "1.8.4"
      }
    }
  ]
}
