{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLJetpackComposeUtil",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2023.01.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-systemuicontroller",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-flowlayout",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-1.3.0.aar",
          "url": "DLJetpackComposeUtil-1.3.0.aar",
          "size": 648838,
          "sha512": "c935728f09b1f38f4c2d61f3b7950786ba4cc778d7810795dca313bace0da84343b7ef41081f59da593f9ec5f9652c59cadf1397557fb71a09f6dee8b268d868",
          "sha256": "c5f4e9381be4dd26c51ff955991e2bf7b363b9e34526d3c44f6205e7715c3b22",
          "sha1": "f2796b52e36b16cca5803d250e8d2f91d9ac5e3a",
          "md5": "d6e8de73eb8f62e7cdf640be56a2e8e4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLDateUtil-jvm",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2023.01.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-systemuicontroller",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-flowlayout",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-1.3.0.aar",
          "url": "DLJetpackComposeUtil-1.3.0.aar",
          "size": 648838,
          "sha512": "c935728f09b1f38f4c2d61f3b7950786ba4cc778d7810795dca313bace0da84343b7ef41081f59da593f9ec5f9652c59cadf1397557fb71a09f6dee8b268d868",
          "sha256": "c5f4e9381be4dd26c51ff955991e2bf7b363b9e34526d3c44f6205e7715c3b22",
          "sha1": "f2796b52e36b16cca5803d250e8d2f91d9ac5e3a",
          "md5": "d6e8de73eb8f62e7cdf640be56a2e8e4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLJetpackComposeUtil-1.3.0-sources.jar",
          "url": "DLJetpackComposeUtil-1.3.0-sources.jar",
          "size": 36426,
          "sha512": "b8b0131d5ea57a084d230980b9bce8983418733b6f05419c957a2160c5d8e2e8da31ada3a7dc3da40c56c3def767c443e70423d6e966cee584fc4b4ac4494d7e",
          "sha256": "c0a418abfb3dd9a94c4590fc8d5f4d257ce6c66d2c7b23d21402605f2b48dd5e",
          "sha1": "a55365226ae61be04f88df88a6b0d62e2cf95d4c",
          "md5": "676a57108886a6aeb1b26aae4df36784"
        }
      ]
    }
  ]
}
