{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLJetpackComposeUtil/3.2.0/DLJetpackComposeUtil-3.2.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLJetpackComposeUtil",
    "version": "3.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-wasm-js-3.2.0.klib",
          "url": "DLJetpackComposeUtil-wasm-js-3.2.0.klib",
          "size": 689817,
          "sha512": "3ca578188169c96c9a99c9ef4f62e731ca3247e5bac5583c1ceb89be73b2119ccc6c82777e89ecf496c161acd510d8e444e35e2c493a719200ee9a191c16a851",
          "sha256": "130849c8b79f6850b66a515c2a632063bce6e9cf907e16564147abdbba2c9fa3",
          "sha1": "9510fea84109cb1a3a0004a7a1e0309bf2279ad1",
          "md5": "566e0d895d8e5203280d1356523a308a"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-wasm-js-3.2.0.klib",
          "url": "DLJetpackComposeUtil-wasm-js-3.2.0.klib",
          "size": 689817,
          "sha512": "3ca578188169c96c9a99c9ef4f62e731ca3247e5bac5583c1ceb89be73b2119ccc6c82777e89ecf496c161acd510d8e444e35e2c493a719200ee9a191c16a851",
          "sha256": "130849c8b79f6850b66a515c2a632063bce6e9cf907e16564147abdbba2c9fa3",
          "sha1": "9510fea84109cb1a3a0004a7a1e0309bf2279ad1",
          "md5": "566e0d895d8e5203280d1356523a308a"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "DLJetpackComposeUtil-wasm-js-3.2.0-sources.jar",
          "url": "DLJetpackComposeUtil-wasm-js-3.2.0-sources.jar",
          "size": 101774,
          "sha512": "7c2300bb88e5fe23762df24ee9fc6ce48f45558162a8190278ec788a08fde95db40701eb3b9cddb5235528e675562c271248d5fc1636dc26029580ce8c5914ad",
          "sha256": "a22610c1f97559dac14de09ccefc51d8728c3e6c4c5ad2e7faeefcc9bfd7fd85",
          "sha1": "8a81e8452da90350fda576b463526b6b3ead393a",
          "md5": "98b1759d778d7f1435ff3f509465df0a"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-3.2.0.kotlin_resources.zip",
          "url": "DLJetpackComposeUtil-wasm-js-3.2.0-kotlin_resources.kotlin_resources.zip",
          "size": 10276,
          "sha512": "3cc09518d1946df84967e52c4aa374855fd0c2caf8efa77efcb07b114dcc3216403b693d98d202d6783020ff1e93fb4d06c266d5f16c127ce079af7a97a08010",
          "sha256": "92a2bde8f367c0905e644b563fe7c3167a9e820fd4d6876f20df270c68dc59fc",
          "sha1": "35b8e994aaea9d4313c899d57fceba9cfabf1165",
          "md5": "c8cd4af9b67c8891296c33038d8f8aac"
        }
      ]
    }
  ]
}
