{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLLatLngUtil/1.7.1/DLLatLngUtil-1.7.1.module",
    "group": "com.github.D10NGYANG",
    "module": "DLLatLngUtil",
    "version": "1.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil.klib",
          "url": "DLLatLngUtil-iosx64-1.7.1.klib",
          "size": 61902,
          "sha512": "cf47e49940b81b50468635420da1c75d4e5439eb78f7fa99086aa17f238e55dfd1a242997459ee4eac30164b791abe5b501adedeed8218b199b1a62cc7263fae",
          "sha256": "1862bdaf60e1d12f04d135be782d6c69d7e302e3cfa492f1cc2c7d6f22b407e5",
          "sha1": "cda76d142ce5deae2d565a69b39f25f0e8082a90",
          "md5": "7bafb4eb78f52e62e83a8941bed39e74"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLLatLngUtil-iosx64-1.7.1-sources.jar",
          "url": "DLLatLngUtil-iosx64-1.7.1-sources.jar",
          "size": 14827,
          "sha512": "b26e7136df1894d888b2f12e2e74c34a37d297916f689f186db6e55052ac7f90b4f448850cb1ad2b2d6ccc4daa36f765d740fc773054e5ac2941d37d459653aa",
          "sha256": "6b813e321fe518f00312024523fb5b21d3a3d6100cebc9314e2aa8fb9214e3ed",
          "sha1": "b52b15eef847b1b4bcac396d514dd7ec5e2d0837",
          "md5": "f3e617b94fd0c111d3f8fcf895087f4f"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil-iosx64-1.7.1-metadata.jar",
          "url": "DLLatLngUtil-iosx64-1.7.1-metadata.jar",
          "size": 261,
          "sha512": "009ed1709e040f0c875c2d8fb1b6a2b369cc0f33bbcdcc4a0eb42faa3699d281262c207d382eb8d31effacd24a6c1c183409105847cb2271e1c9d146819cb27b",
          "sha256": "096e77c33da17772a25c17d38c728fbceaab32516926c61ec0f586645f4c159d",
          "sha1": "d4d23f4e7b9ff036721b9aca6344967608d05ed2",
          "md5": "0160c63b23f6a39f54c7caffe9e67fa2"
        }
      ]
    }
  ]
}
