{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/2.3.0/DLDateUtil-2.3.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-jvm-2.3.0.jar",
          "url": "DLDateUtil-jvm-2.3.0.jar",
          "size": 49259,
          "sha512": "a04a6af9a96c90540282ebbec1506f9269cfca26e1d2f71267b90ab3d61c4b6d4b9360aa3d25378fec35b386e9152190bcb1f26747c054cd6bf96cbe86c45aa9",
          "sha256": "0811a0f7bf116c6afad71d113c49286cb91548bc1a0accc5d3e5d2db0f79f956",
          "sha1": "d936abdc7c8c22fb08762dd6ace08b5380ab3d1c",
          "md5": "b7dd188e7d74b7e2cdf3af410716871a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-jvm-2.3.0.jar",
          "url": "DLDateUtil-jvm-2.3.0.jar",
          "size": 49259,
          "sha512": "a04a6af9a96c90540282ebbec1506f9269cfca26e1d2f71267b90ab3d61c4b6d4b9360aa3d25378fec35b386e9152190bcb1f26747c054cd6bf96cbe86c45aa9",
          "sha256": "0811a0f7bf116c6afad71d113c49286cb91548bc1a0accc5d3e5d2db0f79f956",
          "sha1": "d936abdc7c8c22fb08762dd6ace08b5380ab3d1c",
          "md5": "b7dd188e7d74b7e2cdf3af410716871a"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "DLDateUtil-jvm-2.3.0-sources.jar",
          "url": "DLDateUtil-jvm-2.3.0-sources.jar",
          "size": 21074,
          "sha512": "23acbb5a5be33434a106df43994f924dc16b78b91559308c9723a1eeecc361f13986fb97c99a95a2a5156f77b1c14d344f203145c9f65f60270c2a65174b7052",
          "sha256": "31d9e92f66451bf59078eac988fb662a1bf12edafb4d27194a38e3a3267c4436",
          "sha1": "fb5679389fcce7cd830ac356e6df1081cb6f6004",
          "md5": "96918358c0e00ae5a55d7ad6b060bf27"
        }
      ]
    }
  ]
}
