{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLLatLngUtil/1.7.4/DLLatLngUtil-1.7.4.module",
    "group": "com.github.D10NGYANG",
    "module": "DLLatLngUtil",
    "version": "1.7.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil.klib",
          "url": "DLLatLngUtil-iosx64-1.7.4.klib",
          "size": 61991,
          "sha512": "c7c510c8afd46029052cff11c2a39bc25381d34cf16359464f33ad2286cb119e079f88fdf1088639a1b5c15ddb30324946825748c2ac1d54cde9d4cc7b565dc5",
          "sha256": "87254c341db3bd9036459fda16886b064136f135c75054ca2ec1e65ef5e072fc",
          "sha1": "ccb81bf0b7f77599a50279388e0ba02eac27acf2",
          "md5": "74cc20e4fe04320c43dd6ed01a40768a"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLLatLngUtil-iosx64-1.7.4-sources.jar",
          "url": "DLLatLngUtil-iosx64-1.7.4-sources.jar",
          "size": 14827,
          "sha512": "b26e7136df1894d888b2f12e2e74c34a37d297916f689f186db6e55052ac7f90b4f448850cb1ad2b2d6ccc4daa36f765d740fc773054e5ac2941d37d459653aa",
          "sha256": "6b813e321fe518f00312024523fb5b21d3a3d6100cebc9314e2aa8fb9214e3ed",
          "sha1": "b52b15eef847b1b4bcac396d514dd7ec5e2d0837",
          "md5": "f3e617b94fd0c111d3f8fcf895087f4f"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil-iosx64-1.7.4-metadata.jar",
          "url": "DLLatLngUtil-iosx64-1.7.4-metadata.jar",
          "size": 261,
          "sha512": "79c25347421c93f4e0e8abe130dd42cb778ff1b13df3dfc252fcdef68699c0bef5d3629198bf3c5bc022c9545411b6aee5c6ab30ba3a6c554a170cd53aefbcda",
          "sha256": "594c7db383550e315013d6219532654bf5be334f5c25616f458ebbbb4ed2ae44",
          "sha1": "fa32147e2686ff6ba3ace9988ba497e2a1cfb698",
          "md5": "5133e819cfa9793ca12e0aa50a946829"
        }
      ]
    }
  ]
}
