{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLLatLngUtil/1.5.7/DLLatLngUtil-1.5.7.module",
    "group": "com.github.D10NGYANG",
    "module": "DLLatLngUtil",
    "version": "1.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil.klib",
          "url": "DLLatLngUtil-iosx64-1.5.7.klib",
          "size": 47163,
          "sha512": "d8ef795d05686114c1568802b5657c0c33b992959ad5da1792b48e9c4bf02dd9551637ad04b9c43698fe4f45e0bf95d92034168703c652b6026914ed491bdaa1",
          "sha256": "df975d6a6fb7736bd1d6ce00af9379a0d89211f3dcf7a977963ed854cc586dd7",
          "sha1": "fcb97798525b40b8ef241fa4ae05831a28898fca",
          "md5": "e11d89348a39afe0e9e01e3192d86e1f"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil-iosx64-1.5.7-metadata.jar",
          "url": "DLLatLngUtil-iosx64-1.5.7-metadata.jar",
          "size": 261,
          "sha512": "61fa4ffded975e6e032337deacfb1730036c662ffe522c57ecca4646b81f65bb8ed5e31925ac93c2626f66e696451c930024640a465dc06a97284608fad82cd1",
          "sha256": "b0e2b116c22d1cf51bd9ce5bb02512399032d82267501ed0487268661f97a3be",
          "sha1": "8241f24c9cf4693f21960ab85b2950bb27f686bf",
          "md5": "606975e34b0ae38c3bb5b741c8930868"
        }
      ]
    }
  ]
}
