{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ImageCompress/1.1.0/ImageCompress-1.1.0.module",
    "group": "com.hailiao.util",
    "module": "ImageCompress",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "ImageCompress.klib",
          "url": "ImageCompress-iosarm64-1.1.0.klib",
          "size": 36471,
          "sha512": "1dc18596a8b63e6f0ee76e4e4aeadd1459315ebaf12724587dadb57a96b3a1aa6770b9d5b669cc23a71acf1bb0238e2bc346bdb8e67f580ee112bb311a5a79de",
          "sha256": "832239a56f49e897092baf1405a5abd77c88899f972919a86e22c6b09d4859fa",
          "sha1": "986386c8acf59a240dcc6443c58ee8984dc5c570",
          "md5": "3c30a670b0ed49946b5cbc026e6bb41b"
        },
        {
          "name": "ImageCompress-cinterop-ImageCompress.klib",
          "url": "ImageCompress-iosarm64-1.1.0-cinterop-ImageCompress.klib",
          "size": 267422,
          "sha512": "adc4ac1434ba6208c2ab8943562d21f5248040e93fd2b6dc2954dc7574dc5cd85a0166ac4d6c2feebb54e8b7a5dd54d96f863ade08f7c4ec399270829ea05015",
          "sha256": "e3920a548c05178ffb6d42b46840197936926c1f871767c9d4bd1b02758f2880",
          "sha1": "05c4fa4e7cf9536a65314cf4169a5ecce0230e19",
          "md5": "7891c09e34be8197e652d9433d114f0d"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ImageCompress-iosarm64-1.1.0-sources.jar",
          "url": "ImageCompress-iosarm64-1.1.0-sources.jar",
          "size": 11225,
          "sha512": "e2d8e04f95856eda8dd3a1b0fa0ba7976a0c70785c41e991f6b57cf790114b46dcf6b0cf082e3d6173b9969bcd1926360138f6ca7744df062aa092646a81ee0c",
          "sha256": "0b07cac5bcaec33f222eb7ecbbabb3666b5320fc56ab9b9c972d224b224e64d6",
          "sha1": "2e65473a6fed9529812ecf33c2383308ca589ff7",
          "md5": "3a109a713d66319e42c16b773bd2bd40"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "ImageCompress-iosarm64-1.1.0-metadata.jar",
          "url": "ImageCompress-iosarm64-1.1.0-metadata.jar",
          "size": 4345,
          "sha512": "4203705005d3d273bb82ca5e419a2b6db6279e5a6993e8bea8e5f81f5599ae50f7b25cb74386b248cd2adaeba530da956cf91f0d7acd8f61e9ad3c7cde6ad327",
          "sha256": "1afe95e856d72e02e6cfaab7b53a970c196f601c718540d4f95f03efa442ab1d",
          "sha1": "46a44e4cf1a092882089f6d6dbd3b426ae92370d",
          "md5": "adb76af1518971efef9a4aebaf4e95fc"
        }
      ]
    }
  ]
}
