{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLCommonUtil",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.ditchoom",
          "module": "buffer",
          "version": {
            "requires": "1.3.38"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-metadata-0.1.0.jar",
          "url": "DLCommonUtil-0.1.0.jar",
          "size": 9765,
          "sha512": "9d6939dba86cd2fb14f11c97a4b79508a7701113650aa7345aaee49d2423f197f6735d231cc23adc22b79586138f96040c9d95a3fcf0762383f6a77ae9765ca3",
          "sha256": "580ba1da0a074ad0e49a87cd3e9594037562dce9b4b630433798193ad5a32dee",
          "sha1": "fe5d736c9d2277277e770c7d3d80dccdde1db23b",
          "md5": "3e37879e071bebc941bbdb12d39a6136"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "DLCommonUtil-kotlin-0.1.0-sources.jar",
          "url": "DLCommonUtil-0.1.0-sources.jar",
          "size": 27683,
          "sha512": "9dd13b3cd6ac10b298869eadfc181bde711bea926c60a1bcdabdec281f2e36851ec044aa261e8ea572655247963c69af85407964f502d370460a5d6b46759d36",
          "sha256": "6ce7d3a1e2c0c1cbe152f672aeb13b0203bee2ebc7fb4b6dbe99da5a07326198",
          "sha1": "36df68911e31e4dbdfc802ffab8b9ddec04e326b",
          "md5": "0ccebb75c002bbfb68a476c55cb0b6b2"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLCommonUtil-android/0.1.0/DLCommonUtil-android-0.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLCommonUtil-android/0.1.0/DLCommonUtil-android-0.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLCommonUtil-android/0.1.0/DLCommonUtil-android-0.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCommonUtil-iosarm64/0.1.0/DLCommonUtil-iosarm64-0.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCommonUtil-iosarm64/0.1.0/DLCommonUtil-iosarm64-0.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCommonUtil-iosarm64/0.1.0/DLCommonUtil-iosarm64-0.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCommonUtil-iossimulatorarm64/0.1.0/DLCommonUtil-iossimulatorarm64-0.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-iossimulatorarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCommonUtil-iossimulatorarm64/0.1.0/DLCommonUtil-iossimulatorarm64-0.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-iossimulatorarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCommonUtil-iossimulatorarm64/0.1.0/DLCommonUtil-iossimulatorarm64-0.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-iossimulatorarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLCommonUtil-js/0.1.0/DLCommonUtil-js-0.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-js",
        "version": "0.1.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLCommonUtil-js/0.1.0/DLCommonUtil-js-0.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-js",
        "version": "0.1.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLCommonUtil-js/0.1.0/DLCommonUtil-js-0.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-js",
        "version": "0.1.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLCommonUtil-jvm/0.1.0/DLCommonUtil-jvm-0.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-jvm",
        "version": "0.1.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLCommonUtil-jvm/0.1.0/DLCommonUtil-jvm-0.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-jvm",
        "version": "0.1.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLCommonUtil-jvm/0.1.0/DLCommonUtil-jvm-0.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-jvm",
        "version": "0.1.0"
      }
    }
  ]
}
