{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLCommonUtil/0.4.0/DLCommonUtil-0.4.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLCommonUtil",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0-RC.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil.klib",
          "url": "DLCommonUtil-iosarm64-0.4.0.klib",
          "size": 296078,
          "sha512": "63cdf5187ef94c40a3e35be5441f3adea5d7c24747360a2049c655248a6cde8563f5a7eebfe219f34e4c20d961f724f629807f5d264e70883859327669629fe6",
          "sha256": "2cdc2ce4e484c5d9da10eb7e9426f79ca6ad72c367b091369a8f357f3958a028",
          "sha1": "c9fe30ccd2906429e2eff9f5f0a933f640503903",
          "md5": "92671d8019c5a99c1ad3c92261dbd16c"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLCommonUtil-iosarm64-0.4.0-sources.jar",
          "url": "DLCommonUtil-iosarm64-0.4.0-sources.jar",
          "size": 190677,
          "sha512": "5f23c8508ec0a214b8b1c4b82e742f8e40dea900d778dd279300e74481fef31c494a589970ba59abf0ee0b7471962562a595f11031414857c11817d3b94c7a1f",
          "sha256": "54c781f5b4782b4e0f45d35982d0dbf79ffedbd03bf9eb16f1255474c5e18fb8",
          "sha1": "8e43448e0b139a2dbfeb611b87bf2a3021f898f0",
          "md5": "fbb257c0a1afca0fc846833810b99879"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0-RC.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-iosarm64-0.4.0-metadata.jar",
          "url": "DLCommonUtil-iosarm64-0.4.0-metadata.jar",
          "size": 5786,
          "sha512": "37fbadeaa2ef7214bd7ebe931a60fa9d7f9c05d08be9400d21692317041853bdeb82136f7ef795f7a648293d489ceeacd9584e2224fdb562d0366712e4a508bb",
          "sha256": "6f6fc0a448049908c274d604fe9e87e45b6fade4fffc5ce3797e4fa954560d34",
          "sha1": "efea25ca0ca0dfc1cdc8f72bef8c520011f7c984",
          "md5": "490209733189fd85247cf9c16aa5c5ca"
        }
      ]
    }
  ]
}
