{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLSerialPortUtil/0.2.0/DLSerialPortUtil-0.2.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLSerialPortUtil",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "DLSerialPortUtil-macosX64Main-0.2.0.klib",
          "url": "DLSerialPortUtil-macosx64-0.2.0.klib",
          "size": 33979,
          "sha512": "88dd4f0ce31a934b9315a5d950bfbc5be6f32f089884a528eabc418b905f106efe437e03f4c2940b05ce4780b86fd8ccf0a700ec9b3fcae40aea136cac11a53b",
          "sha256": "246c0d4059d949d69dc11d697e9e6f75eb39dc897731f2ac6397d0e35f7d2f3c",
          "sha1": "ba5934f9b5a2bc1b71dede30f7003c273c0aeb8c",
          "md5": "8eb513efd3dcf1c0a640bbd973329873"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLSerialPortUtil-macosx64-0.2.0-sources.jar",
          "url": "DLSerialPortUtil-macosx64-0.2.0-sources.jar",
          "size": 8501,
          "sha512": "bb974906ece8aef27d4bd1e62289381c5038e5535a88712122e85880a6219b2e2cb59c79b964fd3505861616f61bb5c494476328251cd3c2a06d43ab6dabb681",
          "sha256": "877131cf1dae62ef07a14814c2803f673c0a59b611644e36486ea6d19d1de6a4",
          "sha1": "8fd539c411ab5fad8c0d5fb392ab8014da563e9e",
          "md5": "3bf020350b18a02dbaa91deb63e0ad07"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "DLSerialPortUtil-macosx64-0.2.0-metadata.jar",
          "url": "DLSerialPortUtil-macosx64-0.2.0-metadata.jar",
          "size": 4331,
          "sha512": "51dac624ee1ee552e51558236211e7709b313f7ba19912ec9a9f26e5078b70a8d2c15ff27615a0a3d045e559d98db04992f3c7b072c8ab039e902e78dc68f271",
          "sha256": "ae847e350e21f55e9ca9df2c2ba2ddfcf073e4c741a8213e1581d69ccc107c5a",
          "sha1": "8642852660855467e300dbca3522e6640355c641",
          "md5": "31ec5138fa6a37fa5b6b7fb31adbdea5"
        }
      ]
    }
  ]
}
