{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLSerialPortUtil/0.4.2/DLSerialPortUtil-0.4.2.module",
    "group": "com.github.D10NGYANG",
    "module": "DLSerialPortUtil",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLLogUtil",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLSerialPortUtil-linuxX64Main-0.4.2.klib",
          "url": "DLSerialPortUtil-linuxx64-0.4.2.klib",
          "size": 38073,
          "sha512": "e8199fcc18c3e9d69918d5eaa18e8bfbf496146299ad38eb75d95839e708568762302fcb31fa90cda8e4b5c3923fcbf0622d905453a23b49ac0fb7efbf793623",
          "sha256": "23127b316fab84ce1056584c333169e15a2f3b0c2753c2b400ab332f1c4bbd37",
          "sha1": "f857ceba53f78631ab62bdbae3b3580d53ffd849",
          "md5": "2840d996545c190e8d23b2c802c996a2"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLSerialPortUtil-linuxx64-0.4.2-sources.jar",
          "url": "DLSerialPortUtil-linuxx64-0.4.2-sources.jar",
          "size": 9381,
          "sha512": "0d6834c7d2869ab54100cab835a3c1d6279ae9c71fa0749bcdc293a28e67c8ae9da2e22d125a323d73bd1c458335b4260e72ebfb1808670043c9882669503649",
          "sha256": "be17ad5146af424201fbe729f9483077eee945136bf0941d749f8ff6b0f18ea5",
          "sha1": "f840eebdf88efe5031d06bf21f6e1927c79007b1",
          "md5": "956571a489b91061e57eb4db5ff4b158"
        }
      ]
    }
  ]
}
