{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLLatLngUtil/1.5.1/DLLatLngUtil-1.5.1.module",
    "group": "com.github.D10NGYANG",
    "module": "DLLatLngUtil",
    "version": "1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil.klib",
          "url": "DLLatLngUtil-iosarm64-1.5.1.klib",
          "size": 36712,
          "sha512": "3062ba732b26b497d561726da86bc2fcfc274724f7f77dbb2964f15712a17265c0bbc15ff303576fc1f76dc39687b335b35d062d749e578bd7a03e8810f606e4",
          "sha256": "25f8b17436c27cbd8b7644ac97ccd75c1b3b3fbafd5c7aca0425b75b108e9918",
          "sha1": "f09f5d59d3c191d95330032ad2f4a54f65079247",
          "md5": "f854085dd0e270c4ea277630112729e6"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil-iosarm64-1.5.1-metadata.jar",
          "url": "DLLatLngUtil-iosarm64-1.5.1-metadata.jar",
          "size": 261,
          "sha512": "be34f332e6b96986fb345538ac202bf481c552c30b627525d4bf2e698195d9f3f4cb290cfeea42790748590bd1f2d7625718d6447cc8ad5372f7e2d8defa71e8",
          "sha256": "01dabc476e83ea25d07ced71dcc59f9be65576c14882459a100ace0d9877b616",
          "sha1": "816c2e3127a98abe42db4419682c862e567412b0",
          "md5": "5598e69a5f9e6e33c4588ca92b203f93"
        }
      ]
    }
  ]
}
