{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLPcmResampleUtil/0.2.5/DLPcmResampleUtil-0.2.5.module",
    "group": "com.github.D10NGYANG",
    "module": "DLPcmResampleUtil",
    "version": "0.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLPcmResampleUtil-linuxArm64Main-0.2.5.klib",
          "url": "DLPcmResampleUtil-linuxarm64-0.2.5.klib",
          "size": 222615,
          "sha512": "0d6fdb461519122e125da2b7376a4fa6b08d334f3e32e4f9682549572488b3584480eb369d3803b1be9c2ff4548b425867251dc8192ea584876c21f49c134ffb",
          "sha256": "fc109d55e0b63369eac3d8ae776999a96d6362020573676fc0e90bbcbafd7371",
          "sha1": "956cd9d8ddd13405011b63e461d7322d7d38f16b",
          "md5": "dbd60ba63990e0c76871afc07e3c92ed"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLPcmResampleUtil-linuxarm64-0.2.5-sources.jar",
          "url": "DLPcmResampleUtil-linuxarm64-0.2.5-sources.jar",
          "size": 29527,
          "sha512": "1a194d4e2857f7193e66f10520343b3936df7d348c00f3bda215e19056c48944d24e2e5f729ca375935618e6184615c890426f7d23562f343c79ee8acc1c407c",
          "sha256": "a5c1d6a53b898b6678bd2f030f75dd7fce53899ecf8781f4487223aaca919e51",
          "sha1": "3f9636b6b03ac896e64cca4922a78ef7598e1877",
          "md5": "32d19eca613b0166d22c4fd22eb7f266"
        }
      ]
    }
  ]
}
