{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLBluetoothUtil/0.1.23/DLBluetoothUtil-0.1.23.module",
    "group": "com.github.D10NGYANG",
    "module": "DLBluetoothUtil",
    "version": "0.1.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.bluetooth",
          "module": "bluetooth",
          "version": {
            "requires": "1.0.0-alpha02"
          }
        },
        {
          "group": "com.github.buhuiming",
          "module": "BleCore",
          "version": {
            "requires": "2.3.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "DLBluetoothUtil-release.aar",
          "url": "DLBluetoothUtil-android-0.1.23.aar",
          "size": 96371,
          "sha512": "76d2559d9508971896aa05c21763aa1590e398a31c019373f82e2ecf1bd3fa79ff7a305f8b47fde7183ccf993138ccd2ce23b875aef0f055f76cbdcb38a1b979",
          "sha256": "f54f2ccf330715f2442cf936e60105074cd17ebcc98cede2ec4bd7bdcb27cca3",
          "sha1": "b908ed5c72ddeac0369d80c0d3c6248453b3c53d",
          "md5": "3e836728962479ed84ec99dae87f53f2"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.bluetooth",
          "module": "bluetooth",
          "version": {
            "requires": "1.0.0-alpha02"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.github.buhuiming",
          "module": "BleCore",
          "version": {
            "requires": "2.3.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.9.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLAppUtil",
          "version": {
            "requires": "2.5.7"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.5.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "DLBluetoothUtil-release.aar",
          "url": "DLBluetoothUtil-android-0.1.23.aar",
          "size": 96371,
          "sha512": "76d2559d9508971896aa05c21763aa1590e398a31c019373f82e2ecf1bd3fa79ff7a305f8b47fde7183ccf993138ccd2ce23b875aef0f055f76cbdcb38a1b979",
          "sha256": "f54f2ccf330715f2442cf936e60105074cd17ebcc98cede2ec4bd7bdcb27cca3",
          "sha1": "b908ed5c72ddeac0369d80c0d3c6248453b3c53d",
          "md5": "3e836728962479ed84ec99dae87f53f2"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "DLBluetoothUtil-android-0.1.23-sources.jar",
          "url": "DLBluetoothUtil-android-0.1.23-sources.jar",
          "size": 12460,
          "sha512": "09e844f711b8b1de57601b51c55fe3bb0ebf6329c20b1cb77a580f04c7b1c22e31b2a876764f250e930953bb930f77eae7e6fdcac34b5a2dbf81794d3deb4571",
          "sha256": "3c9a591e2e3cb7a6562e3c0b12cec13155a7739e9152e8cff6fa72f11c41eeb8",
          "sha1": "fa05acabdae1cf5292e4b0843876b7cf34dfc9f4",
          "md5": "813e9209c3736d1b49b25670823d6d66"
        }
      ]
    }
  ]
}
