{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLCommonUtil/0.7.0/DLCommonUtil-0.7.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLCommonUtil",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-linuxArm64Main-0.7.0.klib",
          "url": "DLCommonUtil-linuxarm64-0.7.0.klib",
          "size": 302128,
          "sha512": "167422325b16e052c32e51b6404eda7d6e09574ed2cb5f21f3ed3aa4c8c5a00a66e9b2a7014d451da942cb62c0d749c3943a54875268dc82c798721cd2a20b93",
          "sha256": "cf7c075de2fe2168f2bca404bcd86749f73672b44a2fca7dfbeaa864a08ffa49",
          "sha1": "4b648534cc70c94102e0614221a0da983fa95b1d",
          "md5": "28cecf06d5296efe57ddb60293cb0bf7"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLCommonUtil-linuxarm64-0.7.0-sources.jar",
          "url": "DLCommonUtil-linuxarm64-0.7.0-sources.jar",
          "size": 195683,
          "sha512": "be5e28879be1094419fd1f4c18be73e18d4b2026303a988ce3e2aac39defae16b0eb6c2ca7de237dfe7c84306827fb974e113cec8bdd28c2a28563ddde0896af",
          "sha256": "e5f98ad8f349ed72b7129a58eab445983478be509af16d5fa2661b29199c6963",
          "sha1": "e3ec10bd36440b17fd2a40c7c598d9b38f2593cf",
          "md5": "2889fee22a5a9221e4fae953d589335d"
        }
      ]
    }
  ]
}
