{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLLatLngUtil",
    "version": "1.7.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil-metadata-1.7.5.jar",
          "url": "DLLatLngUtil-1.7.5.jar",
          "size": 7110,
          "sha512": "e50c7245e29d82d050645c371f9908112dfb8c25db09900b0c2becc7b0470487f0fd977a2674adf0b6ba7cdb7db3c37fc0915c2da2128143f8fb083aa8c672dd",
          "sha256": "6eb5519b3d67ec4868926770f5851bc808ae26c0d29318a2ff9b33b5e1a86103",
          "sha1": "bb5153cac13e3f734adfb41373bcf7f59cd85bf0",
          "md5": "6a558ee1551042171009222a607759b0"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "DLLatLngUtil-kotlin-1.7.5-sources.jar",
          "url": "DLLatLngUtil-1.7.5-sources.jar",
          "size": 14827,
          "sha512": "b26e7136df1894d888b2f12e2e74c34a37d297916f689f186db6e55052ac7f90b4f448850cb1ad2b2d6ccc4daa36f765d740fc773054e5ac2941d37d459653aa",
          "sha256": "6b813e321fe518f00312024523fb5b21d3a3d6100cebc9314e2aa8fb9214e3ed",
          "sha1": "b52b15eef847b1b4bcac396d514dd7ec5e2d0837",
          "md5": "f3e617b94fd0c111d3f8fcf895087f4f"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLLatLngUtil-iosarm64/1.7.5/DLLatLngUtil-iosarm64-1.7.5.module",
        "group": "com.github.D10NGYANG",
        "module": "DLLatLngUtil-iosarm64",
        "version": "1.7.5"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLLatLngUtil-iosarm64/1.7.5/DLLatLngUtil-iosarm64-1.7.5.module",
        "group": "com.github.D10NGYANG",
        "module": "DLLatLngUtil-iosarm64",
        "version": "1.7.5"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLLatLngUtil-iosarm64/1.7.5/DLLatLngUtil-iosarm64-1.7.5.module",
        "group": "com.github.D10NGYANG",
        "module": "DLLatLngUtil-iosarm64",
        "version": "1.7.5"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLLatLngUtil-iosx64/1.7.5/DLLatLngUtil-iosx64-1.7.5.module",
        "group": "com.github.D10NGYANG",
        "module": "DLLatLngUtil-iosx64",
        "version": "1.7.5"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLLatLngUtil-iosx64/1.7.5/DLLatLngUtil-iosx64-1.7.5.module",
        "group": "com.github.D10NGYANG",
        "module": "DLLatLngUtil-iosx64",
        "version": "1.7.5"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLLatLngUtil-iosx64/1.7.5/DLLatLngUtil-iosx64-1.7.5.module",
        "group": "com.github.D10NGYANG",
        "module": "DLLatLngUtil-iosx64",
        "version": "1.7.5"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLLatLngUtil-js/1.7.5/DLLatLngUtil-js-1.7.5.module",
        "group": "com.github.D10NGYANG",
        "module": "DLLatLngUtil-js",
        "version": "1.7.5"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLLatLngUtil-js/1.7.5/DLLatLngUtil-js-1.7.5.module",
        "group": "com.github.D10NGYANG",
        "module": "DLLatLngUtil-js",
        "version": "1.7.5"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLLatLngUtil-js/1.7.5/DLLatLngUtil-js-1.7.5.module",
        "group": "com.github.D10NGYANG",
        "module": "DLLatLngUtil-js",
        "version": "1.7.5"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLLatLngUtil-jvm/1.7.5/DLLatLngUtil-jvm-1.7.5.module",
        "group": "com.github.D10NGYANG",
        "module": "DLLatLngUtil-jvm",
        "version": "1.7.5"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLLatLngUtil-jvm/1.7.5/DLLatLngUtil-jvm-1.7.5.module",
        "group": "com.github.D10NGYANG",
        "module": "DLLatLngUtil-jvm",
        "version": "1.7.5"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLLatLngUtil-jvm/1.7.5/DLLatLngUtil-jvm-1.7.5.module",
        "group": "com.github.D10NGYANG",
        "module": "DLLatLngUtil-jvm",
        "version": "1.7.5"
      }
    }
  ]
}
