{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLJetpackComposeUtil/3.3.2/DLJetpackComposeUtil-3.3.2.module",
    "group": "com.github.D10NGYANG",
    "module": "DLJetpackComposeUtil",
    "version": "3.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-wasm-js-3.3.2.klib",
          "url": "DLJetpackComposeUtil-wasm-js-3.3.2.klib",
          "size": 706320,
          "sha512": "c4e9608c658dda00d99833434f5986113cc9edc4fc258cfd6594b43cb45b71b1b96058582b6cd17d28712e3722ea5154b88f5c415c3f9acf77465d8a012bf6f8",
          "sha256": "dd20f11b84ef740ee058be4afae7baa9ae3b90c6dccba11059fcdee6dc510d96",
          "sha1": "838e4558f3d3626235e82762202f997a2f28062c",
          "md5": "d309424fa7d51086ae1f4f496fc6434b"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-wasm-js-3.3.2.klib",
          "url": "DLJetpackComposeUtil-wasm-js-3.3.2.klib",
          "size": 706320,
          "sha512": "c4e9608c658dda00d99833434f5986113cc9edc4fc258cfd6594b43cb45b71b1b96058582b6cd17d28712e3722ea5154b88f5c415c3f9acf77465d8a012bf6f8",
          "sha256": "dd20f11b84ef740ee058be4afae7baa9ae3b90c6dccba11059fcdee6dc510d96",
          "sha1": "838e4558f3d3626235e82762202f997a2f28062c",
          "md5": "d309424fa7d51086ae1f4f496fc6434b"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "DLJetpackComposeUtil-wasm-js-3.3.2-sources.jar",
          "url": "DLJetpackComposeUtil-wasm-js-3.3.2-sources.jar",
          "size": 101986,
          "sha512": "9d6780c65682463c056182a186a3e45a2a11b135c16c33b873372a3ac7ff14dacfd924038e1e9a441b98d8afd0477cec3cbbea93fc23b58e098c108b06d95326",
          "sha256": "d088457bc509983029cdebe1979f9453f069041176c065edd1548844cac2c9a9",
          "sha1": "f91101fcb799ca9ee2e971a5b05d39fd714c121d",
          "md5": "cd173cab46a3ae142c0efa4dbffb66b0"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-3.3.2.kotlin_resources.zip",
          "url": "DLJetpackComposeUtil-wasm-js-3.3.2-kotlin_resources.kotlin_resources.zip",
          "size": 10276,
          "sha512": "fcacd1d206ef5160ee26948bcedc79e71d1d8a27f38399184ee1f50978f4b4337d9a732aac5b53a1a5038802428e395d2700693797581aa97d545dd4b28c02af",
          "sha256": "d63ec7244c1eddaddc28df904231399f5b7f74cc679a0ec883abfcaa894a9a23",
          "sha1": "b7cd18d5f0b6613c2a30be3f422ac175e660eb6a",
          "md5": "db38dc65ecd9f0bf6fbbf99f123850df"
        }
      ]
    }
  ]
}
