{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLLogUtil/0.1.2/DLLogUtil-0.1.2.module",
    "group": "com.github.D10NGYANG",
    "module": "DLLogUtil",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "DLLogUtil-iosArm64Main-0.1.2.klib",
          "url": "DLLogUtil-iosarm64-0.1.2.klib",
          "size": 19165,
          "sha512": "ef1d55d22887730e86af34964f5e18e53c90254caf9069fcd209a2eb97b3e105d428b97f4c53b858dc4ac3d4bd161cf86dd770658200b22aa666215624d4698a",
          "sha256": "754f9fa6e4cf40eeed1f52954b4a53d43b84d623e92811fb46d7361dc36e9b70",
          "sha1": "8b85d0a785d06347ea1fd74dc9139453a8516624",
          "md5": "c3d7a9270441a924e7a6d3b15797d368"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLLogUtil-iosarm64-0.1.2-sources.jar",
          "url": "DLLogUtil-iosarm64-0.1.2-sources.jar",
          "size": 4698,
          "sha512": "0ccf945092107689014e5930145842e013db0f2020012f1dfcfde3893e1881b92763363359ae76b395173e16a5eba3e53732bd2c7c3f576d81a859b0ebfb4644",
          "sha256": "d39b5f03d6651380a6de96f18c21ec6a72cf57d43651e9fc9548881bfa4ae6ae",
          "sha1": "2f67183c15aee7b5e9e19c9d560236f8e3ea767c",
          "md5": "cb3b7c68d2ebfce3bece76696796cade"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "DLLogUtil-iosarm64-0.1.2-metadata.jar",
          "url": "DLLogUtil-iosarm64-0.1.2-metadata.jar",
          "size": 2680,
          "sha512": "48612f41d78a45746951f41576ce24f62155bfda2f854fb719f14ad26101aedabb3d7bcf7dede0074f6080bb952d1ace3bbf5a7383d4c0380de30edc38d4e151",
          "sha256": "43fceada848a8b5e4990d397eb31552537054f82c800e228b3b3041f6be0b62b",
          "sha1": "3510b65b21b9bb43c0c404733f74bddbc52fc20a",
          "md5": "05f75dd215d8d7bdd66026d80161a875"
        }
      ]
    }
  ]
}
