{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ImageCompress/1.0.0-beta03/ImageCompress-1.0.0-beta03.module",
    "group": "com.hailiao.util",
    "module": "ImageCompress",
    "version": "1.0.0-beta03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ImageCompress-release.aar",
          "url": "ImageCompress-android-1.0.0-beta03.aar",
          "size": 3877604,
          "sha512": "4cff5160bebde9670f2ebe616cd104c49ff4bb33de65b731d0b7227d00d12de0539395c5403cd096486a2b0fdd5bdd5e2e7eb24a26e19af76fc3d1f41cf22f0c",
          "sha256": "7797343782e431908f7b3e8ec64d1eb9ab4aa0eb626ad3d4a1d5c0a6175916cf",
          "sha1": "d43e268b4c5682f527efbc5d82682f7c3cd97f77",
          "md5": "36de011291b22690bf5ab0213b9e3c5a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ImageCompress-release.aar",
          "url": "ImageCompress-android-1.0.0-beta03.aar",
          "size": 3877604,
          "sha512": "4cff5160bebde9670f2ebe616cd104c49ff4bb33de65b731d0b7227d00d12de0539395c5403cd096486a2b0fdd5bdd5e2e7eb24a26e19af76fc3d1f41cf22f0c",
          "sha256": "7797343782e431908f7b3e8ec64d1eb9ab4aa0eb626ad3d4a1d5c0a6175916cf",
          "sha1": "d43e268b4c5682f527efbc5d82682f7c3cd97f77",
          "md5": "36de011291b22690bf5ab0213b9e3c5a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ImageCompress-android-1.0.0-beta03-sources.jar",
          "url": "ImageCompress-android-1.0.0-beta03-sources.jar",
          "size": 4285,
          "sha512": "5025fbd1912d835de4c19c6801397585863add0cbdf83c4da0d080848219e75b336106733bbbd5817d8e45848bcba47b97b9acaec9249ae3968fa7647d90cbfc",
          "sha256": "4d6f957f3115aa95696ab56fcfd3ff46e15f3a01a7d043b0272724445f01f9dd",
          "sha1": "44351c8f7d87b8752ded11103bd68463d7c85087",
          "md5": "42d05d8a0888a85cc15a9625b171e77f"
        }
      ]
    }
  ]
}
