{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/2.3.1/DLDateUtil-2.3.1.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "2.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-iosX64Main-2.3.1.klib",
          "url": "DLDateUtil-iosx64-2.3.1.klib",
          "size": 94412,
          "sha512": "b83d82f8b130717f6d1630fb15ec6fe8ae5b1211f2f1ab75240d42bea13e52c7ee7b83c993fe59e2b291f4ebffadd0050544f94a391590d9ad366649a8227cba",
          "sha256": "96b7bf65c8545268603dfd3ccf2248b5a769983a2b869c6c03e91c20d89d381c",
          "sha1": "d080b44b29697e6dd8db25c2fc9110624c0dee1f",
          "md5": "744ceda7970b7502ac7395440dc8ad8c"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLDateUtil-iosx64-2.3.1-sources.jar",
          "url": "DLDateUtil-iosx64-2.3.1-sources.jar",
          "size": 21080,
          "sha512": "953123f22ca1bab8337e14eb7ae72468bb4bc8cfda101870babf688f28ef9a052d4710666c1e41cfca592ea2b72f1985206df35253bb2725749b2b0ee21bbbef",
          "sha256": "917128fe4961ed7e500c08691e152d79f1719117212fcf759ecf06b91d727aed",
          "sha1": "bcd5c894ffb1e6e97692f5938153db16c80311f8",
          "md5": "acd570a277f326e858bf775b1155a5e4"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-iosx64-2.3.1-metadata.jar",
          "url": "DLDateUtil-iosx64-2.3.1-metadata.jar",
          "size": 261,
          "sha512": "bc9ed0091da82e654497c8522da795992a795fff9c1ed211809b65a68cbf42025c250b7b106775821197f0d818aca3a8bca10582a806355628f1e55d6adbcfc1",
          "sha256": "7d8c5aafd59ee3ca71b8f162889668803a7ca7dbd529afbca2ad8e6dc29c3f6e",
          "sha1": "397e8fe50daaefffc2b567f1d792507ab171e682",
          "md5": "d853261bb46dae5ff5317d4fb65dc50d"
        }
      ]
    }
  ]
}
