{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLLatLngUtil/1.3/DLLatLngUtil-1.3.module",
    "group": "com.github.D10NGYANG",
    "module": "DLLatLngUtil",
    "version": "1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil-jvm-1.3.jar",
          "url": "DLLatLngUtil-jvm-1.3.jar",
          "size": 14476,
          "sha512": "02a8e9963fb8ea851736a1fb0a5fd8a2660ba123d41fc2b5d4e2593ab7d741e843eb5d8e6aa35df394dba6669ef4014dd4705b1a168ed3d0478286c3917f740b",
          "sha256": "33c5ac6c813dd192851ba67cb6b33780e6b4eccc2ece423c775dce1ba85c1fcf",
          "sha1": "6e674dda3dcd880a5105a0fa270e3eeb3c875f13",
          "md5": "e5fca4b05a2586d677e3691563b9ec41"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil-jvm-1.3.jar",
          "url": "DLLatLngUtil-jvm-1.3.jar",
          "size": 14476,
          "sha512": "02a8e9963fb8ea851736a1fb0a5fd8a2660ba123d41fc2b5d4e2593ab7d741e843eb5d8e6aa35df394dba6669ef4014dd4705b1a168ed3d0478286c3917f740b",
          "sha256": "33c5ac6c813dd192851ba67cb6b33780e6b4eccc2ece423c775dce1ba85c1fcf",
          "sha1": "6e674dda3dcd880a5105a0fa270e3eeb3c875f13",
          "md5": "e5fca4b05a2586d677e3691563b9ec41"
        }
      ]
    }
  ]
}
