{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLPcmResampleUtil/0.2.1/DLPcmResampleUtil-0.2.1.module",
    "group": "com.github.D10NGYANG",
    "module": "DLPcmResampleUtil",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLPcmResampleUtil.klib",
          "url": "DLPcmResampleUtil-iossimulatorarm64-0.2.1.klib",
          "size": 222916,
          "sha512": "e9a83ec7132cfab455decb7d191a46737c7097069f910edaf355432be7becb167cdea41a82b2ebc20325a0bc097ab51c6b345daa6301bceaf6c500d78b28d55a",
          "sha256": "62c00a9f9f59ba6615d95a51d8ee1f8ecb4b76a2170820f252fb6a41ee119063",
          "sha1": "1e05058e9f31e7bacb2909c5354198b6ec43ea79",
          "md5": "b0034539c8874edfd63eb13801b79bf0"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLPcmResampleUtil-iossimulatorarm64-0.2.1-sources.jar",
          "url": "DLPcmResampleUtil-iossimulatorarm64-0.2.1-sources.jar",
          "size": 29498,
          "sha512": "4f096ce098d2c99292b316414eb3dd74a967d7436f9ab3cc27668c15b81514c25b71a0967616101694f7b024753e6a426b61d9af5e6c6dbf6d905f427c173b6b",
          "sha256": "1fc4ed72daa9d1a5d7dc8b8182b3aaeeceff08defb1317c0daf5735f82058ec4",
          "sha1": "93bc0627a4523f6fa6bab1c6acd5561a5cf5bc7a",
          "md5": "f573a7abe1cfa719011b671905188cef"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLPcmResampleUtil-iossimulatorarm64-0.2.1-metadata.jar",
          "url": "DLPcmResampleUtil-iossimulatorarm64-0.2.1-metadata.jar",
          "size": 261,
          "sha512": "9020dcd4698a4977a4afe1ed0c845890c8ac4f92c0370203d5c60eb4fc65395838906596ffb6e0dee250132b7eb06f13298fd68968eb8bd985b9ade60bb83ea9",
          "sha256": "04ae9bd15a17867352d5c3bde5170dbcb17d22d1d77f49b9942b0a1f64440475",
          "sha1": "51d621f494c794b4cfc179788abfb140950a1adb",
          "md5": "a293a8d31fe989c3dd409e4d039b6956"
        }
      ]
    }
  ]
}
