{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ImageCompress/1.0.0-beta14/ImageCompress-1.0.0-beta14.module",
    "group": "com.hailiao.util",
    "module": "ImageCompress",
    "version": "1.0.0-beta14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ImageCompress-jvm-1.0.0-beta14.jar",
          "url": "ImageCompress-jvm-1.0.0-beta14.jar",
          "size": 763852,
          "sha512": "caab6b718acd3248769d5debf6aeae519d8d41dd2a863c3e3f7e66b62fc79c49a1ba6620efa3eedece368a8b1d10e25651c416b649dc93f7a1164dfbf8a80db0",
          "sha256": "25749ba229541096104a964d9fa02c117ccb65082a50210a04ba8d18057d3ccf",
          "sha1": "c174437f796b3e2f311355004bc44d679dabed66",
          "md5": "092a126456a98f9d1b0db1481502f0ef"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ImageCompress-jvm-1.0.0-beta14.jar",
          "url": "ImageCompress-jvm-1.0.0-beta14.jar",
          "size": 763852,
          "sha512": "caab6b718acd3248769d5debf6aeae519d8d41dd2a863c3e3f7e66b62fc79c49a1ba6620efa3eedece368a8b1d10e25651c416b649dc93f7a1164dfbf8a80db0",
          "sha256": "25749ba229541096104a964d9fa02c117ccb65082a50210a04ba8d18057d3ccf",
          "sha1": "c174437f796b3e2f311355004bc44d679dabed66",
          "md5": "092a126456a98f9d1b0db1481502f0ef"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ImageCompress-jvm-1.0.0-beta14-sources.jar",
          "url": "ImageCompress-jvm-1.0.0-beta14-sources.jar",
          "size": 10528,
          "sha512": "b3b692d4027bfc885408f5c5bc00359da970065552dd2eb78c6e772d111164a5c1e69ee3a72482beabcb93bb74a97944b4d43250a46f54ca215b6458282eadbf",
          "sha256": "765deb2e8f6330420d77864733578ed75b866e00be7dda63d85700d63e4f9ae3",
          "sha1": "81c5b9b64e8a98f7a5858b528b1bf04bbcf71937",
          "md5": "ea82db6e90e73340f1aecd2eb4edfd5f"
        }
      ]
    }
  ]
}
