{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDatastoreUtil/0.2.1/DLDatastoreUtil-0.2.1.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDatastoreUtil",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLDatastoreUtil-iosX64Main-0.2.1.klib",
          "url": "DLDatastoreUtil-iosx64-0.2.1.klib",
          "size": 10957,
          "sha512": "32c1ab552f07d299aaedafa2c469a3dc831c547628934286c68d890a83a4abc9c00925d82dd0b51f50f4a48825190f51578b38f4e5379afccce96da05897812d",
          "sha256": "cbd98cc7bba5b49b42ab20922335d2701d202fd087cbc89cbec45ec4d19284d1",
          "sha1": "0c3f1f547c1eee324f5de94c672e0f83f98cd8ea",
          "md5": "3229728964def8321f00501b0fbca80d"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLDatastoreUtil-iosx64-0.2.1-sources.jar",
          "url": "DLDatastoreUtil-iosx64-0.2.1-sources.jar",
          "size": 3667,
          "sha512": "0264a2e5d1b158f3057c0f42cebe8ee78a758938ff7f28077d020153eb6895c96580d45f2591e011877a3ccea55f5d4867bcf795596d468eba731b8f6a807c4a",
          "sha256": "4c6cc84482f9755a4c3f5ee1ecb8c31d15c330d00a0635c6433ab150bf73eaf1",
          "sha1": "05c4dd26d0b8e2a1e4d7416e5bc4a22c3142f279",
          "md5": "25cc034df759644962644db3f1a62883"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLDatastoreUtil-iosx64-0.2.1-metadata.jar",
          "url": "DLDatastoreUtil-iosx64-0.2.1-metadata.jar",
          "size": 2576,
          "sha512": "a466ca13b033754d60a1b7326406b084e2980102faa5ae1e77aebd10a6d63442d5f0110152a8911dd4285ed2b215f04fd8445023a622387ca67e382f51d3fcc6",
          "sha256": "4164ea31c788371c3cd1f8c17aba3e7624219d8dc2818d0c19f43061c4dd0d5b",
          "sha1": "d29cf42a3220ed4ceffaecdb24d97ded9868270e",
          "md5": "a7ab7c28cead659e960a8670bbde8106"
        }
      ]
    }
  ]
}
