{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLVoiceUtil",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLVoiceUtil-0.0.1.aar",
          "url": "DLVoiceUtil-0.0.1.aar",
          "size": 19636,
          "sha512": "44575306fb5393d1c96d2dea224a40bedbe2c19070c383f67cfa32f2b1a461f40cc2d4b9e07946500147f10f4910ea06a428f232af4ccf013298f910e3272334",
          "sha256": "02bad54d61e05ef031ffa5beedde9acc97de59afa45c4e2f5eba8c7980497ce2",
          "sha1": "ea3e130ab1c1224d32c9846a26ac5fe6d60cca38",
          "md5": "5b0c518645d7b5f868de39949a5a9871"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLVoiceUtil-0.0.1.aar",
          "url": "DLVoiceUtil-0.0.1.aar",
          "size": 19636,
          "sha512": "44575306fb5393d1c96d2dea224a40bedbe2c19070c383f67cfa32f2b1a461f40cc2d4b9e07946500147f10f4910ea06a428f232af4ccf013298f910e3272334",
          "sha256": "02bad54d61e05ef031ffa5beedde9acc97de59afa45c4e2f5eba8c7980497ce2",
          "sha1": "ea3e130ab1c1224d32c9846a26ac5fe6d60cca38",
          "md5": "5b0c518645d7b5f868de39949a5a9871"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLVoiceUtil-0.0.1-sources.jar",
          "url": "DLVoiceUtil-0.0.1-sources.jar",
          "size": 3920,
          "sha512": "e0b24c8e3c172b611d6f84b1484175980433d1227489cee73b4ace39e43d0b1c8463bd5a66e3d67aab37e5d3b13d7038946135fa56a0c819f13a8b38c70dbc26",
          "sha256": "bdfd899bef5035a39d387c61affd595958af8bed2ad8bfde11bb067f3b5deccc",
          "sha1": "bcae4bf8b9d3eab7476f8c11f928415639d445d8",
          "md5": "b7624ecef09f2ff7438fd560014787ea"
        }
      ]
    }
  ]
}
