{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ImageCompress/1.0.0-beta09/ImageCompress-1.0.0-beta09.module",
    "group": "com.hailiao.util",
    "module": "ImageCompress",
    "version": "1.0.0-beta09",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ImageCompress-jvm-1.0.0-beta09.jar",
          "url": "ImageCompress-jvm-1.0.0-beta09.jar",
          "size": 763659,
          "sha512": "c2fdafe6d6f6cea98475a0d3f625e1659db2c3c55c4d59b75e185719b24557f9519f6524f92fc34af7f3bf8b217e804cdd8946d19645df42242841002e0ee747",
          "sha256": "ff95a399b6a1e5380eef6007366298b6ea73d1fe6f0ed488a0f61279be2c988b",
          "sha1": "bd116655275f121f99a77aa5fcb5d2fcb57ba44e",
          "md5": "81ccb3595a2a9900dc957166aadb17bc"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ImageCompress-jvm-1.0.0-beta09.jar",
          "url": "ImageCompress-jvm-1.0.0-beta09.jar",
          "size": 763659,
          "sha512": "c2fdafe6d6f6cea98475a0d3f625e1659db2c3c55c4d59b75e185719b24557f9519f6524f92fc34af7f3bf8b217e804cdd8946d19645df42242841002e0ee747",
          "sha256": "ff95a399b6a1e5380eef6007366298b6ea73d1fe6f0ed488a0f61279be2c988b",
          "sha1": "bd116655275f121f99a77aa5fcb5d2fcb57ba44e",
          "md5": "81ccb3595a2a9900dc957166aadb17bc"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ImageCompress-jvm-1.0.0-beta09-sources.jar",
          "url": "ImageCompress-jvm-1.0.0-beta09-sources.jar",
          "size": 10488,
          "sha512": "02dfdf02288b18d94d7a863dd398e1c09908b5a3ed6486206262dbe608942ce34b7d3f6a9719ecab6007ecf8886bc9c7101af559858744b9dadc955f0d716195",
          "sha256": "a87f5c3d9271a2e224a1e2735b544a0131abd32912a0e1f8913463deced34b49",
          "sha1": "95c69d0f9e3da580005e45d58f53120d13126872",
          "md5": "c32543c88fa51eb88eb5494a547ab9b3"
        }
      ]
    }
  ]
}
