{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLCommonUtil/1.0.0/DLCommonUtil-1.0.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLCommonUtil",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-linuxX64Main-1.0.0.klib",
          "url": "DLCommonUtil-linuxx64-1.0.0.klib",
          "size": 268261,
          "sha512": "8adeb8fb9b0c0a7bb20f95a8be933352c433e15a843f0fb2bbaef57f1c19b15aab7e42a99d2b882a2fcf0f6981a4a8b113846cbd475615a6f195ea1f89e1ceaf",
          "sha256": "7977b5624cf8a27eba762aaf32596626352b8310f272bc4b41ad89153d5c454d",
          "sha1": "0664591518f55d9b1d7b819d0845a10237774ae9",
          "md5": "a6c8ddac6ee0700ea60a1cbdca201093"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLCommonUtil-linuxx64-1.0.0-sources.jar",
          "url": "DLCommonUtil-linuxx64-1.0.0-sources.jar",
          "size": 93501,
          "sha512": "a56f3b4d843f40a7deba93fadc907c85462f6f3e6b869cfec0ab12a05daffae130278d717df6b2b1ad530c1bb4d301fd56198dca50366b2bb20bd38f0b7139b9",
          "sha256": "d798cc1058b1e7e164cd211bf3acf96720c2db5b4b414d2252e262e4a62ec652",
          "sha1": "9d2aa64c5c50b299033be6d95bbbb58c2d89af75",
          "md5": "574b860564626256b8abf47c1b65c7a3"
        }
      ]
    }
  ]
}
