{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLJetpackComposeUtil",
    "version": "2.0.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.02"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.0-alpha13"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-2.0.19.aar",
          "url": "DLJetpackComposeUtil-2.0.19.aar",
          "size": 1121154,
          "sha512": "8a284aef99480ac7feebec011d94837aa2b6db2c4f03ca0a99e6aa9c6fb7185857ad0a8466bf232cd35be08662ebf09a811e2ff825bea2dca44e1635b895ec64",
          "sha256": "1396ffd1b6922ed6cce951c67e8b7a4488e33dc41cc761512a2bd5d7da5e996e",
          "sha1": "084fb841b904ca559add6a747b478d7cfa38c0cb",
          "md5": "9ee7b857cd70c6e34e71f652a7f78a9d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.github.raamcosta.compose-destinations",
          "module": "animations-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLDateUtil",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.0.9"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.02"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.0-alpha13"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-2.0.19.aar",
          "url": "DLJetpackComposeUtil-2.0.19.aar",
          "size": 1121154,
          "sha512": "8a284aef99480ac7feebec011d94837aa2b6db2c4f03ca0a99e6aa9c6fb7185857ad0a8466bf232cd35be08662ebf09a811e2ff825bea2dca44e1635b895ec64",
          "sha256": "1396ffd1b6922ed6cce951c67e8b7a4488e33dc41cc761512a2bd5d7da5e996e",
          "sha1": "084fb841b904ca559add6a747b478d7cfa38c0cb",
          "md5": "9ee7b857cd70c6e34e71f652a7f78a9d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLJetpackComposeUtil-2.0.19-sources.jar",
          "url": "DLJetpackComposeUtil-2.0.19-sources.jar",
          "size": 77346,
          "sha512": "fcd58d1de1abf94ce6c2b14fddca1dda0523b3675a8fac86bc6e35cbfa6059f242a6e2892921e456a877d32b9dccd6cfb660a42d26cffef4f3968984bac78568",
          "sha256": "1607fb417d1acd251147117594eb373b68616a161052fe84077ef30e51e25dd4",
          "sha1": "6bcdc1d673bb8e4c85f57e7f68c37aefe3100874",
          "md5": "37d0bd1e5fa2434921ece54c4dd017f3"
        }
      ]
    }
  ]
}
