{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLJetpackComposeUtil/3.3.3/DLJetpackComposeUtil-3.3.3.module",
    "group": "com.github.D10NGYANG",
    "module": "DLJetpackComposeUtil",
    "version": "3.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-iosSimulatorArm64Main-3.3.3.klib",
          "url": "DLJetpackComposeUtil-iossimulatorarm64-3.3.3.klib",
          "size": 711793,
          "sha512": "22714a123532bbef84638d71b26523c43688eb52930176ec507384b21bcceb7e2b5198ae2efe0c07c581bacd80c16da292bb067b406cc80111d5bc072ecdaa5d",
          "sha256": "1767743bb00e0674aff6ff0da315dbcb1476f940e308caca58ecfbf254eef18a",
          "sha1": "6cfabafb121d6d99e21ce92c65abae8fe264c794",
          "md5": "e3ffcfdd2b2b00d1413a01d3e723981c"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLJetpackComposeUtil-iossimulatorarm64-3.3.3-sources.jar",
          "url": "DLJetpackComposeUtil-iossimulatorarm64-3.3.3-sources.jar",
          "size": 102153,
          "sha512": "16a9a4bfa7450a0aa1a4773eeaa494dba20589cee1d9412ec6423a5e479aa0a3f945ee31e7d5fe5ddf5f64266a46be8cab03ae5572dbed96eeca500d4bfb7519",
          "sha256": "c36402c0e9d6ef68426866609996eddbb5bae92b036443817846d1e6173f7015",
          "sha1": "f667c89c9ff8674ab8f409f4b18ce04913691f9e",
          "md5": "e4af82cd25bcb69f123b8e3f82eca524"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-3.3.3.kotlin_resources.zip",
          "url": "DLJetpackComposeUtil-iossimulatorarm64-3.3.3-kotlin_resources.kotlin_resources.zip",
          "size": 10276,
          "sha512": "27538ec70ecc2d947532bb2c9045e9682046b978acf4de65d32855667d1f40645e137350e7be134e9ebdef93cab717c1989f019e01d94a7f7dc829eaaadf0019",
          "sha256": "7c1ee6ae26ee3d2e66a71d8ade68ee88803ed3762c103fe13b494ad2ceedd635",
          "sha1": "d93af7713bc3c122432aa98fa77198d33c6788ce",
          "md5": "e6d43140e5e33486ef56006bf51a56e0"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-iossimulatorarm64-3.3.3-metadata.jar",
          "url": "DLJetpackComposeUtil-iossimulatorarm64-3.3.3-metadata.jar",
          "size": 261,
          "sha512": "a64c5364d7b6870519e1961d97647c2bacb99cf80592127120a1a771e64140eec88dd059dff2a072a0394e26f842fadadd615c59f1e87fcce02221864231b840",
          "sha256": "07a82ad0ce1870e89f27095db4d3e5a070ce03351d31faaedd5719eda4b53e7c",
          "sha1": "8b297d167686a843b663f938aa37b5edd1dbd9b8",
          "md5": "4b2ae79dbb287ed20d3d801f1973ab3c"
        }
      ]
    }
  ]
}
