{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLJetpackComposeUtil",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2023.09.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.0-alpha12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-2.0.0.aar",
          "url": "DLJetpackComposeUtil-2.0.0.aar",
          "size": 893589,
          "sha512": "b8befd09f47749f3ece7115de5204717367cf01495ec1190d19b189b66658e18db4eb75e7f49e4f05926d3c6d1338173382670fc4233b1232ad422e5b2f514b2",
          "sha256": "7c3bd92ef34041b360f4a3c32346c92a50d68b7b7659c527e73f382c036cb088",
          "sha1": "7329f97a3c1bc20bf6bbd74af6e07e995d7a45c0",
          "md5": "e6cd4c9d455de1b933d25371abacd747"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.github.raamcosta.compose-destinations",
          "module": "animations-core",
          "version": {
            "requires": "1.9.53"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLDateUtil",
          "version": {
            "requires": "1.8.5"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2023.09.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.0-alpha12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-2.0.0.aar",
          "url": "DLJetpackComposeUtil-2.0.0.aar",
          "size": 893589,
          "sha512": "b8befd09f47749f3ece7115de5204717367cf01495ec1190d19b189b66658e18db4eb75e7f49e4f05926d3c6d1338173382670fc4233b1232ad422e5b2f514b2",
          "sha256": "7c3bd92ef34041b360f4a3c32346c92a50d68b7b7659c527e73f382c036cb088",
          "sha1": "7329f97a3c1bc20bf6bbd74af6e07e995d7a45c0",
          "md5": "e6cd4c9d455de1b933d25371abacd747"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLJetpackComposeUtil-2.0.0-sources.jar",
          "url": "DLJetpackComposeUtil-2.0.0-sources.jar",
          "size": 61796,
          "sha512": "b6a1ff972f6656b3bef5f6f078ee0f070ceea85155ffbe182efabd0903c6e7d292d34ac7335f9d8afefd16fa2d86d9db5c9afa61d7d360186cb18058e923b007",
          "sha256": "50c025c7bb2542b546cc949de91923f058be04550cd7d0bb9b3ae5a0382bec54",
          "sha1": "2c60f348c671394c96b7e8a1237dcb703ffb9192",
          "md5": "cda80eac8db760355f479c5466e3de2c"
        }
      ]
    }
  ]
}
