{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/2.1.1/DLDateUtil-2.1.1.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "2.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-jvm-2.1.1.jar",
          "url": "DLDateUtil-jvm-2.1.1.jar",
          "size": 40024,
          "sha512": "94d791c85982a8fa4d7fc5addfb7b9eb076549149f3d6b652668794df0dbd47f1243a82b18e653393a43e783e43e2c58f525fd1c63ffca9c9e06defcb074938c",
          "sha256": "691976aa9cbe0e79a5f02be0d27238d11fb4ccefe194badc032656fa5988d5c5",
          "sha1": "88cf72f2ba22953db07faec5b854e93ae45c6eed",
          "md5": "c1a666156e0a664e8e0691acfb68bc3c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-jvm-2.1.1.jar",
          "url": "DLDateUtil-jvm-2.1.1.jar",
          "size": 40024,
          "sha512": "94d791c85982a8fa4d7fc5addfb7b9eb076549149f3d6b652668794df0dbd47f1243a82b18e653393a43e783e43e2c58f525fd1c63ffca9c9e06defcb074938c",
          "sha256": "691976aa9cbe0e79a5f02be0d27238d11fb4ccefe194badc032656fa5988d5c5",
          "sha1": "88cf72f2ba22953db07faec5b854e93ae45c6eed",
          "md5": "c1a666156e0a664e8e0691acfb68bc3c"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "DLDateUtil-jvm-2.1.1-sources.jar",
          "url": "DLDateUtil-jvm-2.1.1-sources.jar",
          "size": 17258,
          "sha512": "e7110c4db22a2fca426dafe65ffde30426f1fe32969d480b3560d82384441b2b576321ca3767ce9f5f0732a9c88920c8dff9281eaaa6e38de151c12da43407c2",
          "sha256": "4ef01c563471fdffed520731c972180b18d41f44e1ff9470330b423229711e1b",
          "sha1": "bba88fe001b315a87f7a3aaee527c1a6dea2ad95",
          "md5": "7b1c0822b6333991fde1119b7b514c74"
        }
      ]
    }
  ]
}
