{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLCommonUtil/0.0.6/DLCommonUtil-0.0.6.module",
    "group": "com.github.D10NGYANG",
    "module": "DLCommonUtil",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.ditchoom",
          "module": "buffer",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil.klib",
          "url": "DLCommonUtil-iosarm64-0.0.6.klib",
          "size": 98398,
          "sha512": "a969999d3e83f20e135fa922e90c5b9044a572f5bc0eebfe32ad216d5c192ca38681ef66969b67ad6f168c6d2e5932b491dbf6ed204fa6bfeb739140c1139273",
          "sha256": "8ea0823efde8bc8f265a5fb1f3d7a9b462c1e163479a28e6859162b1ba781e4b",
          "sha1": "473bca9731b51f5a7a39d6d2ac8d22f3f7bc90d5",
          "md5": "61b73e63838efbc70c836e2bc3fac0d9"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLCommonUtil-iosarm64-0.0.6-sources.jar",
          "url": "DLCommonUtil-iosarm64-0.0.6-sources.jar",
          "size": 27103,
          "sha512": "d16564e2eb03edc63868c2ff2ea5bbb8586f5c725922a14d77a89bd37b7347c55453ec8eb3f5acc2709934aa75b66492e6097a951744e8a211ac61ac48796146",
          "sha256": "36014e20bf39bde0808d30e774f27bbb9ff19403cd78720faae522ebaa5035fe",
          "sha1": "c31d42272caa332071df6beb2e97c7927772f9c8",
          "md5": "9d77c9a36ace67d94160c52a93d76896"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.ditchoom",
          "module": "buffer",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-iosarm64-0.0.6-metadata.jar",
          "url": "DLCommonUtil-iosarm64-0.0.6-metadata.jar",
          "size": 4086,
          "sha512": "67fcf717674a56319ddd1b5adfab8e31f4e0878e7713f8196faabdcda6a2b5f3e8b090128c130faafb32e3f03b9a971f3f539661b3109dec55517a5dcbc15804",
          "sha256": "aab36e101c51f968c8ef480251e8a0f77dd1b38e73132a38e2680eba85834dcd",
          "sha1": "5cba7ddfb4a0491d3ba113f4570a56740387be8e",
          "md5": "48184fd03b28d8401811368803cbe04e"
        }
      ]
    }
  ]
}
