{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLSerialPortUtil/0.5.0/DLSerialPortUtil-0.5.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLSerialPortUtil",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLSerialPortUtil-wasm-js-0.5.0.klib",
          "url": "DLSerialPortUtil-wasm-js-0.5.0.klib",
          "size": 39496,
          "sha512": "27d803c083404483868d8255fa9d4e27babab24f5f28c8d1dac8f8365a7d45977d89f924003c6a73635055a00e11b1110697049bb3a369180a1405775601cb80",
          "sha256": "5f7e8781eed924bf6cb73e61b3c92c3527a77fd02e2d8eb537d6e61dc4db3d1d",
          "sha1": "3a0ef3d56e81ed2a121b82c83da03842396a6058",
          "md5": "d517dffb841ffcb6b8af7852bf0cffc2"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLLogUtil",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLSerialPortUtil-wasm-js-0.5.0.klib",
          "url": "DLSerialPortUtil-wasm-js-0.5.0.klib",
          "size": 39496,
          "sha512": "27d803c083404483868d8255fa9d4e27babab24f5f28c8d1dac8f8365a7d45977d89f924003c6a73635055a00e11b1110697049bb3a369180a1405775601cb80",
          "sha256": "5f7e8781eed924bf6cb73e61b3c92c3527a77fd02e2d8eb537d6e61dc4db3d1d",
          "sha1": "3a0ef3d56e81ed2a121b82c83da03842396a6058",
          "md5": "d517dffb841ffcb6b8af7852bf0cffc2"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "DLSerialPortUtil-wasm-js-0.5.0-sources.jar",
          "url": "DLSerialPortUtil-wasm-js-0.5.0-sources.jar",
          "size": 9220,
          "sha512": "c1530694825916b3783a0045d712bd86647bac857bcb97268b1b0beabb829070f0f2de6e84756ba790fa26e520e0a933bfd250cbaa4b8659c5f1ee50f51b7534",
          "sha256": "1579647a74009e2ec681fdf1f5c697f8203c02c15d9fad72232ea38edcec76e3",
          "sha1": "5cd59c36e80a17867457aea23b1aa9ea58ad8ba4",
          "md5": "06744e108eca32f78e0b373d5c4d2b03"
        }
      ]
    }
  ]
}
