{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLCommonUtil/0.4.1/DLCommonUtil-0.4.1.module",
    "group": "com.github.D10NGYANG",
    "module": "DLCommonUtil",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0-RC.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil.klib",
          "url": "DLCommonUtil-iossimulatorarm64-0.4.1.klib",
          "size": 296133,
          "sha512": "5b9ba2943ba96ed0e5a6ba7c864f33872fef04f47e087be70347bfcf107e030425ff8d2d6231f8efea2882b6ee1ae44147fe1c6f25a81d9f4ae5d8fd65c0eda6",
          "sha256": "e5ed7ec6047dff484bff1aa0787cab30a34938dc3cfdc44066dd1e1c7e69a34c",
          "sha1": "825e809f3bf8a8ce331926e6d954a4b3146b5b22",
          "md5": "e8e288bd8c4869e24ad4882bf04860d6"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLCommonUtil-iossimulatorarm64-0.4.1-sources.jar",
          "url": "DLCommonUtil-iossimulatorarm64-0.4.1-sources.jar",
          "size": 190671,
          "sha512": "35abc98df6435d11d30215f732cd569ed301dc22d8a4f9e01aa1408ec96963299c9c714f3a49eb8540f75f4c3d0d80bf6b2b8f6ecc1243e6df584b0550d56b3c",
          "sha256": "ab024e8ba6b5ad82bd740a04e088455c9096b4bdebd5669757d2425ed4b77c03",
          "sha1": "364a95e24433c816b9390e2a68108429bec1cb89",
          "md5": "ca59f94ad1b8a6ab4c71fcbca185aec9"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0-RC.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-iossimulatorarm64-0.4.1-metadata.jar",
          "url": "DLCommonUtil-iossimulatorarm64-0.4.1-metadata.jar",
          "size": 5786,
          "sha512": "eca3cdb16f5302128d82a949c7ed3a0a3b884001b76c0efdba78758a035a55c993e9d4f928dec7d5e4b666e540db0caa6ef8316d7ddb20797fb21fd202cfc00d",
          "sha256": "15c82e6e8a946a092769cea9dc1b91d863f39fdf1ce8b35984f97a8d200d1162",
          "sha1": "f06d38e6f1a36de739761eec189e376ad377c5ac",
          "md5": "d5ecd8e4e077b866e1e6012856693ec6"
        }
      ]
    }
  ]
}
