{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLCommonUtil/0.6.0/DLCommonUtil-0.6.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLCommonUtil",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-iosSimulatorArm64Main-0.6.0.klib",
          "url": "DLCommonUtil-iossimulatorarm64-0.6.0.klib",
          "size": 308948,
          "sha512": "d6374feeb6e673e8f8ce2a6ea8d3a4b22f11fbf24dd5313a7fce3cf71ec78e4d9b41e1512304870a0d1c1fd386d8f177ba947fcfd85f9087279aa32fed154165",
          "sha256": "2f7a44320c121335ae8e45e8c4d46887290f824541bb304b6042aeda7d1bb8af",
          "sha1": "6f714cbe2ed3307d944bbd31ce4ea0d82807ad8d",
          "md5": "e08eff432c7f6e2d6c4aec1f75b1d417"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLCommonUtil-iossimulatorarm64-0.6.0-sources.jar",
          "url": "DLCommonUtil-iossimulatorarm64-0.6.0-sources.jar",
          "size": 197080,
          "sha512": "7f6088bd7bd0a8635521ad9a4864ceb9ce109a86f864602138f2510bd029d7adc04a24819491355e26a108a71fd73b21e8353c8ac9b4ac99f7969a3e71e93a48",
          "sha256": "e592885cef3afc2c7aa0335622ca2a49ef36d6a2e3d0c26393bcbecb76914a30",
          "sha1": "2feb63499fa43431f71ec8109f66cb9ba7e530d0",
          "md5": "5fb3165d2a79e343876f70f45ef04329"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-iossimulatorarm64-0.6.0-metadata.jar",
          "url": "DLCommonUtil-iossimulatorarm64-0.6.0-metadata.jar",
          "size": 3940,
          "sha512": "b4ac7bf4087aeb0ad8ef335252b33e7bd5721408ac72ea87ecdbe8f712c718fa0c1d7aca838fe045dc68c76e5384d3c98324dd70769eb545dd04e1681de7d1b8",
          "sha256": "919c6cd9e5c7941c96805a3f18a0b018190728d7662467243237c304455bcb48",
          "sha1": "cd02997bec309a0dd650137b2b2714a9003b5731",
          "md5": "075d14c00b2d545591d151ea61380987"
        }
      ]
    }
  ]
}
