{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/2.1.0/DLDateUtil-2.1.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-js-2.1.0.klib",
          "url": "DLDateUtil-js-2.1.0.klib",
          "size": 77659,
          "sha512": "481e54bf5663099cbf02ed725256a147230b4e818326524c8bc25a18b26083a57a819ecbaebf7447451edb3e802e81ce740951f0459a5f19572c354443964a02",
          "sha256": "f45638ae44331260c2f2cd1c12ea82b85d3fa5b89e3d9f54a3a6911270bde400",
          "sha1": "cd3791c8cc9eea6eea961353b16ac456fa5c4c94",
          "md5": "a74f68a0b684c9079d9ef8ed16278104"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-js-2.1.0.klib",
          "url": "DLDateUtil-js-2.1.0.klib",
          "size": 77659,
          "sha512": "481e54bf5663099cbf02ed725256a147230b4e818326524c8bc25a18b26083a57a819ecbaebf7447451edb3e802e81ce740951f0459a5f19572c354443964a02",
          "sha256": "f45638ae44331260c2f2cd1c12ea82b85d3fa5b89e3d9f54a3a6911270bde400",
          "sha1": "cd3791c8cc9eea6eea961353b16ac456fa5c4c94",
          "md5": "a74f68a0b684c9079d9ef8ed16278104"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "DLDateUtil-js-2.1.0-sources.jar",
          "url": "DLDateUtil-js-2.1.0-sources.jar",
          "size": 17776,
          "sha512": "f5a06bf54bb75b85a3cb7feb5029d817ad7b75b73a26f8197f19b8f83c0b2426059da19793d33df78fddfe189a4b7b209d6268c4f0f23bca2374d4ca723097a7",
          "sha256": "f065b565da3e6af352892e8a7e25f1f27ff2008399474b6b53fb22b81aa793ce",
          "sha1": "d36f5df6088a382679368e4c83f31c2dcf988c24",
          "md5": "d8e151ddfdf7c5ab4821f8d01997e784"
        }
      ]
    }
  ]
}
