{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLJetpackComposeUtil",
    "version": "2.0.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.02"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.0-alpha13"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-2.0.18.aar",
          "url": "DLJetpackComposeUtil-2.0.18.aar",
          "size": 1119610,
          "sha512": "8b1bd93757ff536f39a3f7e31b31a056c1b1e3ab16570cb7cf1fea0a067391c9a51e6ea9db4a54576a99a9b48ccdeb619693031ae5eac86239a7e75a04a270d1",
          "sha256": "23287b0b6743dd1b5d2119fd6ed3c5e49ce91d45a0b76dc3c6e9ff5d60ccd962",
          "sha1": "c96b209289d22f3f4a1408bb61bc138e14749a5f",
          "md5": "c736e6d23cbda1b02c5f48a0c2b15540"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.github.raamcosta.compose-destinations",
          "module": "animations-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLDateUtil",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.0.9"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.02"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.0-alpha13"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-2.0.18.aar",
          "url": "DLJetpackComposeUtil-2.0.18.aar",
          "size": 1119610,
          "sha512": "8b1bd93757ff536f39a3f7e31b31a056c1b1e3ab16570cb7cf1fea0a067391c9a51e6ea9db4a54576a99a9b48ccdeb619693031ae5eac86239a7e75a04a270d1",
          "sha256": "23287b0b6743dd1b5d2119fd6ed3c5e49ce91d45a0b76dc3c6e9ff5d60ccd962",
          "sha1": "c96b209289d22f3f4a1408bb61bc138e14749a5f",
          "md5": "c736e6d23cbda1b02c5f48a0c2b15540"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLJetpackComposeUtil-2.0.18-sources.jar",
          "url": "DLJetpackComposeUtil-2.0.18-sources.jar",
          "size": 77329,
          "sha512": "76bba2b21cf3989c1d267acd1126d893ae465eae0c931075dfece8902d7d1bcefb4bbdad66f1f12b8b8b2c0b57326dbd5bfb99eb921e60f5c6f0bf6e4ea5dfd2",
          "sha256": "ad59c1f44856dc37e1d413d64e9bd9baf686d17a0e92f7f9e7434a9740f3d48b",
          "sha1": "1c2b063de3f4d97bda48f7fb965d65912b8de790",
          "md5": "c5d7da8094af119ba7fa09d80a2a468b"
        }
      ]
    }
  ]
}
