{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/1.9.2/DLDateUtil-1.9.2.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "1.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-jvm-1.9.2.jar",
          "url": "DLDateUtil-jvm-1.9.2.jar",
          "size": 28838,
          "sha512": "53afaac84e514fe0bbb8b46730a3b60e8134c5df198cc8db61f973b5013ce3d2bfa54def8e95b2acae95001c9d15b2620b8f13d932e7c597618f5d48b3b1c291",
          "sha256": "741477021a4e45b984606a6c1926fab2be93df392d9118182fa65b38d2f8710e",
          "sha1": "25c92ac269fbf11f9ced599806bbd042e480bd65",
          "md5": "570193bb6be9928b249550fdbf29a176"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-jvm-1.9.2.jar",
          "url": "DLDateUtil-jvm-1.9.2.jar",
          "size": 28838,
          "sha512": "53afaac84e514fe0bbb8b46730a3b60e8134c5df198cc8db61f973b5013ce3d2bfa54def8e95b2acae95001c9d15b2620b8f13d932e7c597618f5d48b3b1c291",
          "sha256": "741477021a4e45b984606a6c1926fab2be93df392d9118182fa65b38d2f8710e",
          "sha1": "25c92ac269fbf11f9ced599806bbd042e480bd65",
          "md5": "570193bb6be9928b249550fdbf29a176"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "DLDateUtil-jvm-1.9.2-sources.jar",
          "url": "DLDateUtil-jvm-1.9.2-sources.jar",
          "size": 11910,
          "sha512": "108bb3c148c15c16b4e240f2b11b8e20b6d7c94d6680034575999a56e166543c25e36f492bda7573695677f253071aae06e64b1ac6632f64e85fd8eaae28f0bf",
          "sha256": "5ebddfab1c84e1378c93f70a6b8be3d13a70603499e1be8db161532792516fa9",
          "sha1": "0b214b743f647748b262ec9ec3f56214c225ee52",
          "md5": "06ed913039b6a285aa1a38df9d1371ee"
        }
      ]
    }
  ]
}
