{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLBluetoothUtil/0.1.3/DLBluetoothUtil-0.1.3.module",
    "group": "com.github.D10NGYANG",
    "module": "DLBluetoothUtil",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0-RC.2"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "DLBluetoothUtil.klib",
          "url": "DLBluetoothUtil-iosarm64-0.1.3.klib",
          "size": 59535,
          "sha512": "cc6f8e8ad35192a6d60cf020f316d364a404850ab9492ed2ed296916a60483054cc79aa20413f7f2a9aa1071d18e6683560dbcd32a34111e61468214d462b416",
          "sha256": "66519bde51855d1f1dd247eecf194931815d755ff4d3e667234407e05c3913f7",
          "sha1": "13a1d1f123a4d54f776034aae86c85a36c52db18",
          "md5": "e831c4fb653d9063b308bb5b502d0941"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLBluetoothUtil-iosarm64-0.1.3-sources.jar",
          "url": "DLBluetoothUtil-iosarm64-0.1.3-sources.jar",
          "size": 9486,
          "sha512": "3f7b1c8e412f7ea9292995893f5d6f9fefb007ed3674e015d2ee3df2191ac943462a51ab55cfb36bfa560e8115cd180716f7af9981da3b396f67645d2e148693",
          "sha256": "04cc6807953ad833f981359d1e1764d6e30890b374f24246a9cbfeaadc88245e",
          "sha1": "426bc337f85d379aa634274be9a76bb8171a2af6",
          "md5": "046b89a24b9548794b85f862b2cc0107"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0-RC.2"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "DLBluetoothUtil-iosarm64-0.1.3-metadata.jar",
          "url": "DLBluetoothUtil-iosarm64-0.1.3-metadata.jar",
          "size": 261,
          "sha512": "07dbab57552f7cf7147d6ae180253111d1f54302ab6ecd45f43ba55576497780f96dc63f2d06ee48f18e37304ae8cbb99619fcd0c3f846cf364ee946784158b7",
          "sha256": "54ca72dc4a414fb96106b27f61818a787455801da76a5953fee430f71aece2d4",
          "sha1": "3ca48510643f13611a1614a5ba1ccfda819bda9f",
          "md5": "6f67a4c7c9dc99068eb5bb1dd49af438"
        }
      ]
    }
  ]
}
