{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/2.1.2/DLDateUtil-2.1.2.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "2.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-linuxArm64Main-2.1.2.klib",
          "url": "DLDateUtil-linuxarm64-2.1.2.klib",
          "size": 77526,
          "sha512": "6a119c33c04fb844cbe5e275afa539c48e655cb661025bbeedae993a4d385b0b100e54064cff9879dbd4642c7136ff9953bbf3cd75a01d0662b15ec692eced81",
          "sha256": "bce39dfe11ac7dd375ef3105afff63b76b6851a78d17eb0a29907c0e95119235",
          "sha1": "6a124640be317a1f5a52a1e3bd0d0eb95a029d66",
          "md5": "1a9aa4a3a6cc2f8afdcdfdc4060517d8"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLDateUtil-linuxarm64-2.1.2-sources.jar",
          "url": "DLDateUtil-linuxarm64-2.1.2-sources.jar",
          "size": 17269,
          "sha512": "1e62691bb797940348e3045d1c2a871eca8f87e7207565142e080256c4af34985862a82d2431b31730dd98370d84007e4ea007e3e47c4e722b629aa04b3dd877",
          "sha256": "2e0a12edb7838df703693d68368eaeec1db413d3153d4942abdacc8113df0c72",
          "sha1": "f3e60235b4f7f1aa2210c13d4b66d0be157c7ea3",
          "md5": "fad80f3f43425c01564714eec44f2345"
        }
      ]
    }
  ]
}
