{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLJetpackComposeUtil/3.1.0/DLJetpackComposeUtil-3.1.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLJetpackComposeUtil",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-iosSimulatorArm64Main-3.1.0.klib",
          "url": "DLJetpackComposeUtil-iossimulatorarm64-3.1.0.klib",
          "size": 615753,
          "sha512": "7fb436c60716d5bae43e8b30db8eea2ea7f0fef10fd94c6334f4c56279b00e5d4a55832f90efa4ca2b16f5c1b2de17c6d6f4c8e4cf74790c2fb5e49d71df061b",
          "sha256": "52d376f3e36e8f6fb9aa6ba19e5130bbe1a014360180efd47baad84f7779dcd6",
          "sha1": "e974034accc99ff432ce205aac2e9bf006fd774d",
          "md5": "4c01ec106d601333af6559ebd2ee53dd"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLJetpackComposeUtil-iossimulatorarm64-3.1.0-sources.jar",
          "url": "DLJetpackComposeUtil-iossimulatorarm64-3.1.0-sources.jar",
          "size": 81577,
          "sha512": "58f40bb311e6cbbca5e3f337dbb11800033a22062d12e4e4fefbaa30605d057c7f57ac3b0c85434e597f4fb0db68cc1e2f4d04725d0ffd8cb502233f490e0fc4",
          "sha256": "8da5914d720adefe9edeb500b4ed38c3ee44a4ac20eb7c19123b50a84351846f",
          "sha1": "eeebe4b3d6e4228794aa51f3e16b0662e78805b9",
          "md5": "b706d841b30566c293175984e1c86337"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-3.1.0.kotlin_resources.zip",
          "url": "DLJetpackComposeUtil-iossimulatorarm64-3.1.0-kotlin_resources.kotlin_resources.zip",
          "size": 10276,
          "sha512": "925fc564530ab6570e1501ee02233e5d8f35dde4861885a0a90aa3d71b05464a2bad051680a2e2276b5f6690b5dc8b74ca36b2399d74e16e436ad30c32de5b43",
          "sha256": "ad3d00041e0831e501e92fcc851c3b206749c3a64ad1cedcd544ff0d0d50e766",
          "sha1": "5be3e93e26b0ed214ab81053712883dbef130ce1",
          "md5": "8a35860102e6ad565e95a6c1ddad684b"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-iossimulatorarm64-3.1.0-metadata.jar",
          "url": "DLJetpackComposeUtil-iossimulatorarm64-3.1.0-metadata.jar",
          "size": 2482,
          "sha512": "0022006386ee95d7e48e3f358c28007afa48e3e2ec6ade655011f1ba52b7fff4768fc3881e13ca9f9cdf570793d8700e399354741c4cc936b3ec5704d2d382de",
          "sha256": "ed8614aa76248fbfb9e5b0c98de3e1778e508f8d7673ab511ad3a64d20f5ec53",
          "sha1": "1af98906d8d6aea486657a695ae83b2352c76a99",
          "md5": "0bce6febd933579aa638548ef183872d"
        }
      ]
    }
  ]
}
