{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ImageCompress/1.0.1/ImageCompress-1.0.1.module",
    "group": "com.hailiao.util",
    "module": "ImageCompress",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ImageCompress.klib",
          "url": "ImageCompress-iosarm64-1.0.1.klib",
          "size": 36471,
          "sha512": "7f7e38183222318d0b73222024c9f9e1fdf023ffbbecb51a7ce57c4323004b6ad35bb9698c6b7a3d0c7417ecb6d83e08883b262331f3003a2b009bcbf1ea371e",
          "sha256": "72f05e5aeab90f48c40ff943871bffbce2665271b5ada1dd68d7cb416692777b",
          "sha1": "e7f171b89abb7e3979476040ac1d832e6eff7759",
          "md5": "a0f4b0e6eefec5846867b4e662c3a0d4"
        },
        {
          "name": "ImageCompress-cinterop-ImageCompress.klib",
          "url": "ImageCompress-iosarm64-1.0.1-cinterop-ImageCompress.klib",
          "size": 267422,
          "sha512": "adc4ac1434ba6208c2ab8943562d21f5248040e93fd2b6dc2954dc7574dc5cd85a0166ac4d6c2feebb54e8b7a5dd54d96f863ade08f7c4ec399270829ea05015",
          "sha256": "e3920a548c05178ffb6d42b46840197936926c1f871767c9d4bd1b02758f2880",
          "sha1": "05c4fa4e7cf9536a65314cf4169a5ecce0230e19",
          "md5": "7891c09e34be8197e652d9433d114f0d"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ImageCompress-iosarm64-1.0.1-sources.jar",
          "url": "ImageCompress-iosarm64-1.0.1-sources.jar",
          "size": 11226,
          "sha512": "9926f488eada29241aa3f7889066dfd3d53a3099791fac07253aa67f39f7fec8d56ecdfdce11e7c46099165b152c071f8998669b8b040bf667f56b0c8e33de76",
          "sha256": "a511c28b1911eaef4bebbfe4c294681e438eb4d0dec4b7d037fdbbecfd9ce4ce",
          "sha1": "21094e5a2bdbd400b26804571e963c1650b36ff9",
          "md5": "20563619692a57cc62338ee0a703026e"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ImageCompress-iosarm64-1.0.1-metadata.jar",
          "url": "ImageCompress-iosarm64-1.0.1-metadata.jar",
          "size": 261,
          "sha512": "aeeb2f4ca364a6d9fd7e4083c01105b14be99ae0235e9ffd6bcca61cb2a3ee3504eee21096c8868a708137f544c41df31637b56c2c955f5ed5c6be412562c707",
          "sha256": "46225f7f80e14b56b309ada58af2090cf0214fd54214abae67b135c98ead2d1c",
          "sha1": "fad543e65e972da978401d9c18ae9e70bdba909f",
          "md5": "4a0a45b2f33e8b8ce1da19e737f77dda"
        }
      ]
    }
  ]
}
