{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLCommonUtil/0.0.5/DLCommonUtil-0.0.5.module",
    "group": "com.github.D10NGYANG",
    "module": "DLCommonUtil",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.github.biezhi",
          "module": "TinyPinyin",
          "version": {
            "requires": "2.0.3.RELEASE"
          }
        },
        {
          "group": "com.ditchoom",
          "module": "buffer",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-release.aar",
          "url": "DLCommonUtil-android-0.0.5.aar",
          "size": 53144,
          "sha512": "0eaf448a945e538597f511d4b358290a47b591a5df17c274adcc0f2e312881eeaacedaa6fcd50ede7307809ecbde20392ad6aa3f4899c6402ae78078a4cb4283",
          "sha256": "d4fff9804e26fe1acb37d966fe4ce40d0bda279277b307e5c0701671ce7bb33a",
          "sha1": "d6428b312c53d6499dd5aa9ed89fd053c9ea39b6",
          "md5": "71d353808cbe60e9cbf3072cdbf25a2f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.github.biezhi",
          "module": "TinyPinyin",
          "version": {
            "requires": "2.0.3.RELEASE"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.ditchoom",
          "module": "buffer",
          "version": {
            "requires": "1.3.7"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-release.aar",
          "url": "DLCommonUtil-android-0.0.5.aar",
          "size": 53144,
          "sha512": "0eaf448a945e538597f511d4b358290a47b591a5df17c274adcc0f2e312881eeaacedaa6fcd50ede7307809ecbde20392ad6aa3f4899c6402ae78078a4cb4283",
          "sha256": "d4fff9804e26fe1acb37d966fe4ce40d0bda279277b307e5c0701671ce7bb33a",
          "sha1": "d6428b312c53d6499dd5aa9ed89fd053c9ea39b6",
          "md5": "71d353808cbe60e9cbf3072cdbf25a2f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "DLCommonUtil-android-0.0.5-sources.jar",
          "url": "DLCommonUtil-android-0.0.5-sources.jar",
          "size": 27882,
          "sha512": "f5a3f047d1bab9789013b0ccbd45712029168f222303bd4f93548d4129a2739be5753970a1ae479a804d4565c2bd024f22853cd4cfdff3eb9b3de14d2272dad4",
          "sha256": "4c5e987e3f0b2cdc1ed3ad6954ec36c13239365e12bcba7f6b2ea950dfb55892",
          "sha1": "c1dfe90983c7e678c06019906833174b2ff1e869",
          "md5": "b6d87a060edcc4aa390387df4747e1f9"
        }
      ]
    }
  ]
}
