{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLQRCodeUtil",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "DLQRCodeUtil-0.1.1.aar",
          "url": "DLQRCodeUtil-0.1.1.aar",
          "size": 118963,
          "sha512": "a3a2295b8db0a051d578887c16839818bab5d4c3b010f442334afa7988d62ef3fc20e37b75c9062bf049f7c8885e1ae20cb8b502952044b239a0ac8e49ffc33e",
          "sha256": "59ee4b7f1876f03d5cd5c17892e9796b44c9bfd657c9b90c53677701045b772c",
          "sha1": "6f1dfc8133e3c2dea837b6fee12e8629c5419771",
          "md5": "1cb02a449e387784d4bbf9a786318324"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLJetpackComposeUtil",
          "version": {
            "requires": "2.0.24"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLAppUtil",
          "version": {
            "requires": "2.5.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "DLQRCodeUtil-0.1.1.aar",
          "url": "DLQRCodeUtil-0.1.1.aar",
          "size": 118963,
          "sha512": "a3a2295b8db0a051d578887c16839818bab5d4c3b010f442334afa7988d62ef3fc20e37b75c9062bf049f7c8885e1ae20cb8b502952044b239a0ac8e49ffc33e",
          "sha256": "59ee4b7f1876f03d5cd5c17892e9796b44c9bfd657c9b90c53677701045b772c",
          "sha1": "6f1dfc8133e3c2dea837b6fee12e8629c5419771",
          "md5": "1cb02a449e387784d4bbf9a786318324"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLQRCodeUtil-0.1.1-sources.jar",
          "url": "DLQRCodeUtil-0.1.1-sources.jar",
          "size": 5048,
          "sha512": "7989de044de25d05b923b2ddf422227afeaa36a16c9285b852d7af90b7386852ba769b99474ced279bbb2116995e972330daaa7093a8940a7e6fc88247c4d3ae",
          "sha256": "24700053a5eccb9ec3e64df76edc7cd55af9ec5e03da776099f4a6e1cb35b79e",
          "sha1": "e0b05cd4d9998993f577db170ccfe549ef179cf1",
          "md5": "81d6ceaa61972b5dec3bbd32e1877c29"
        }
      ]
    }
  ]
}
