{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLCryptoUtil/0.0.8/DLCryptoUtil-0.0.8.module",
    "group": "com.github.D10NGYANG",
    "module": "DLCryptoUtil",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "DLCryptoUtil-js-0.0.8.klib",
          "url": "DLCryptoUtil-js-0.0.8.klib",
          "size": 29373,
          "sha512": "0f9e9aab9de92313f464021bfb43365c9df8f2fb1f8e9e7c17a7d91c380e7942cc90307783b07cf4abb98112cab7304a670ea9ee44342ff6cb3ed4cd96ed20ec",
          "sha256": "120dab4725f79ec7dcb44e252e24dcae31a6c45e4859627646ec045d6f0031a3",
          "sha1": "5e65fa66067aabc693f8f5243e7a7f315905ca54",
          "md5": "d1d2dced0875933ec933c86efb36ddfa"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "DLCryptoUtil-js-0.0.8.klib",
          "url": "DLCryptoUtil-js-0.0.8.klib",
          "size": 29373,
          "sha512": "0f9e9aab9de92313f464021bfb43365c9df8f2fb1f8e9e7c17a7d91c380e7942cc90307783b07cf4abb98112cab7304a670ea9ee44342ff6cb3ed4cd96ed20ec",
          "sha256": "120dab4725f79ec7dcb44e252e24dcae31a6c45e4859627646ec045d6f0031a3",
          "sha1": "5e65fa66067aabc693f8f5243e7a7f315905ca54",
          "md5": "d1d2dced0875933ec933c86efb36ddfa"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "DLCryptoUtil-js-0.0.8-sources.jar",
          "url": "DLCryptoUtil-js-0.0.8-sources.jar",
          "size": 7793,
          "sha512": "6da7da6115d0435644c0f8582e6586f2507a7ced767ce27c96017adee51918c674c5780db57595d6e315b6a3fc8bb29d1313635e4a334d1372a57587b1d2f26e",
          "sha256": "c22a28dfb85c9b7242092f0993a50244410242ff9b1af0cee8a9c490072d8cff",
          "sha1": "861dd8fff50790c29cccd962856388ed8b3997aa",
          "md5": "0f6d9a453bddb58fe2d1a7c3fe3734cc"
        }
      ]
    }
  ]
}
