{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/2.1.3/DLDateUtil-2.1.3.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "2.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-iosSimulatorArm64Main-2.1.3.klib",
          "url": "DLDateUtil-iossimulatorarm64-2.1.3.klib",
          "size": 78280,
          "sha512": "40b9fac652fde3a45f771325841225e5dbb613a49aff9b5785fac1798f6f77b613b801b3da0add2adf2b88e8ee6e1b0234f056bbdd04c0a31c36dab96d3bfece",
          "sha256": "0de9933cbe872c7ce46178fc8be41ca5535f117f431a9d36ead86a03a3e3cd31",
          "sha1": "99de54e020a936b529741b4c6f338ad9cf27096f",
          "md5": "1017cfc47b1ab805ec39209b09c57bba"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLDateUtil-iossimulatorarm64-2.1.3-sources.jar",
          "url": "DLDateUtil-iossimulatorarm64-2.1.3-sources.jar",
          "size": 17463,
          "sha512": "bb3a3993bfaa48011c2d827153ee6aae326cf05d78463575db2b23bb4a1a7ebc39398d491c3419e5ab885bc296b5143445d65e6b401b06f887bfb7bb07946d4a",
          "sha256": "352121accf74b1ebeb34dc8f64c47432bd58599aec2da3583910e2d2d610ef88",
          "sha1": "afe3c7b840c6185cf4647bc72c46a6a6974bcf89",
          "md5": "b005d5f34aec98f5aac50d1c0877c39c"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-iossimulatorarm64-2.1.3-metadata.jar",
          "url": "DLDateUtil-iossimulatorarm64-2.1.3-metadata.jar",
          "size": 261,
          "sha512": "14dfe2745a20694a9fd2877e3873bd3e022d5bce73db0714377c5efde5790aa0cc92ccaee8bb174bd9915be199bc8629e4ad85820cc5483d5a432eea309a4cad",
          "sha256": "1a22bfd0fc344dc1452509f7acab0a749d2bc0536b71472096213d5ede236a18",
          "sha1": "c573f2634591de3cb6e6acc3182c6a50218651f2",
          "md5": "09fee5ea4811b88a2c0b7c623c8a2628"
        }
      ]
    }
  ]
}
