{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLCommonUtil/0.0.1/DLCommonUtil-0.0.1.module",
    "group": "com.github.D10NGYANG",
    "module": "DLCommonUtil",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil.klib",
          "url": "DLCommonUtil-iosarm64-0.0.1.klib",
          "size": 32771,
          "sha512": "452a517f9c11b710bb58c5093f5af5b738b3c7cd948dbccf5d4a27253f9edfb8e54d81b7767b84c8ec163e6286f14aa458353b719188fe430ed451e55b8e5d62",
          "sha256": "23397e10f04f364b59395dfdc867eb4c2848ff187685ba5cbf49fbee9f266b61",
          "sha1": "7630b2f316dfa40f626400080720eed35042e84d",
          "md5": "2e1c934c960e1dc50499149392e5c534"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLCommonUtil-iosarm64-0.0.1-sources.jar",
          "url": "DLCommonUtil-iosarm64-0.0.1-sources.jar",
          "size": 11130,
          "sha512": "2261ea3e5a275a32c8ab85ee70dcfb219cf0d059b8de9883b9518cbe9ec0e4ba258c410373718cce5f4ec5afb8087501d24b3ed1a962a4d25c5521c36e299d43",
          "sha256": "ca419c6d439e01cb078a695a1603ea21f05285a5def76011ec791016d13db194",
          "sha1": "e1d1709e65b6b3ccdf6e5e490d12324cff8b7bf2",
          "md5": "3336c1287864807ab913fe38c5f91d9a"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-iosarm64-0.0.1-metadata.jar",
          "url": "DLCommonUtil-iosarm64-0.0.1-metadata.jar",
          "size": 3584,
          "sha512": "c0371114be4b4731d20b69ec3de091b518a6e726b6098dbd676409cf2d68b90492475db2224923906834035359926c86f29e3364d896ae5be8ea17f11e31163d",
          "sha256": "2ce8d0ca069aafe0b73ca0d8545dac48acfd3aa33571cab1811300d409aaaa10",
          "sha1": "b968f44e5be0273b5d405e27f79d97834eec7dcf",
          "md5": "d13fd567dff17835d61b5399acf36010"
        }
      ]
    }
  ]
}
