{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLLatLngUtil/1.7.5/DLLatLngUtil-1.7.5.module",
    "group": "com.github.D10NGYANG",
    "module": "DLLatLngUtil",
    "version": "1.7.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil-js-1.7.5.klib",
          "url": "DLLatLngUtil-js-1.7.5.klib",
          "size": 62222,
          "sha512": "5e70cbd4f85dfafd0bac340baf136a1ec15c02e44419204b270631bb66b3c51ae208bb690b25bdb6b5b653914587f725b802ec9b2db9299d560f4c3690cb22cf",
          "sha256": "833b0fd5a744f60f53f7f536b348816c2001aff6d152e0a5bdb19fbdd21c3b31",
          "sha1": "6d63854b14f1750ad90727344c818f4859646530",
          "md5": "68fd5403d1f0ca497dc62421f94a7ef0"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil-js-1.7.5.klib",
          "url": "DLLatLngUtil-js-1.7.5.klib",
          "size": 62222,
          "sha512": "5e70cbd4f85dfafd0bac340baf136a1ec15c02e44419204b270631bb66b3c51ae208bb690b25bdb6b5b653914587f725b802ec9b2db9299d560f4c3690cb22cf",
          "sha256": "833b0fd5a744f60f53f7f536b348816c2001aff6d152e0a5bdb19fbdd21c3b31",
          "sha1": "6d63854b14f1750ad90727344c818f4859646530",
          "md5": "68fd5403d1f0ca497dc62421f94a7ef0"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "DLLatLngUtil-js-1.7.5-sources.jar",
          "url": "DLLatLngUtil-js-1.7.5-sources.jar",
          "size": 14827,
          "sha512": "b26e7136df1894d888b2f12e2e74c34a37d297916f689f186db6e55052ac7f90b4f448850cb1ad2b2d6ccc4daa36f765d740fc773054e5ac2941d37d459653aa",
          "sha256": "6b813e321fe518f00312024523fb5b21d3a3d6100cebc9314e2aa8fb9214e3ed",
          "sha1": "b52b15eef847b1b4bcac396d514dd7ec5e2d0837",
          "md5": "f3e617b94fd0c111d3f8fcf895087f4f"
        }
      ]
    }
  ]
}
