{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLSerialPortUtil",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLLogUtil",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLSerialPortUtil-metadata-0.6.0.jar",
          "url": "DLSerialPortUtil-0.6.0.jar",
          "size": 11016,
          "sha512": "65e77df5f684bbee989af29b899d1e5802af642e611f5798d623b5888aeed899c6031d9236bb89646a877060ece3fdcf4a91ba337fcef6522ae71861c65e1a52",
          "sha256": "df01bbd5ffd98ee16ca013634ead1fbeb8ae26e3cbc3ad68e84a38aa15b94fab",
          "sha1": "9d17d20ae0598ab15b9dab40b93f7cf5ca086158",
          "md5": "e8d1bec44104296bbb2e80dd77eb1f41"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "DLSerialPortUtil-kotlin-0.6.0-sources.jar",
          "url": "DLSerialPortUtil-0.6.0-sources.jar",
          "size": 14540,
          "sha512": "1eb81f627985ff1d17f43483f84a98e8d4e3f61c1bd742e02b0625305bbd6132950c397a5d79289fc6ad3c77b0127e4ffa27883f6d80ae5eb552ad830f61f1e0",
          "sha256": "9b2b5c8ea2dae69d65c848b9f644883e883059c5d1208bf6518dbab398f9d3be",
          "sha1": "ac6c9d3c5e3d58808428e2ed89cd04b8af5960b5",
          "md5": "63e73514e22110ff3f2e76a8d63b46ec"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-android/0.6.0/DLSerialPortUtil-android-0.6.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-android",
        "version": "0.6.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-android/0.6.0/DLSerialPortUtil-android-0.6.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-android",
        "version": "0.6.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-android/0.6.0/DLSerialPortUtil-android-0.6.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-android",
        "version": "0.6.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-js/0.6.0/DLSerialPortUtil-js-0.6.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-js",
        "version": "0.6.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-js/0.6.0/DLSerialPortUtil-js-0.6.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-js",
        "version": "0.6.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-js/0.6.0/DLSerialPortUtil-js-0.6.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-js",
        "version": "0.6.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-jvm/0.6.0/DLSerialPortUtil-jvm-0.6.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-jvm",
        "version": "0.6.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-jvm/0.6.0/DLSerialPortUtil-jvm-0.6.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-jvm",
        "version": "0.6.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-jvm/0.6.0/DLSerialPortUtil-jvm-0.6.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-jvm",
        "version": "0.6.0"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-linuxarm64/0.6.0/DLSerialPortUtil-linuxarm64-0.6.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-linuxarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-linuxarm64/0.6.0/DLSerialPortUtil-linuxarm64-0.6.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-linuxarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-linuxx64/0.6.0/DLSerialPortUtil-linuxx64-0.6.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-linuxx64",
        "version": "0.6.0"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-linuxx64/0.6.0/DLSerialPortUtil-linuxx64-0.6.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-linuxx64",
        "version": "0.6.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-macosarm64/0.6.0/DLSerialPortUtil-macosarm64-0.6.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-macosarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-macosarm64/0.6.0/DLSerialPortUtil-macosarm64-0.6.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-macosarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-macosarm64/0.6.0/DLSerialPortUtil-macosarm64-0.6.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-macosarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-macosx64/0.6.0/DLSerialPortUtil-macosx64-0.6.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-macosx64",
        "version": "0.6.0"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-macosx64/0.6.0/DLSerialPortUtil-macosx64-0.6.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-macosx64",
        "version": "0.6.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-macosx64/0.6.0/DLSerialPortUtil-macosx64-0.6.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-macosx64",
        "version": "0.6.0"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-wasm-js/0.6.0/DLSerialPortUtil-wasm-js-0.6.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-wasm-js",
        "version": "0.6.0"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-wasm-js/0.6.0/DLSerialPortUtil-wasm-js-0.6.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-wasm-js",
        "version": "0.6.0"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-wasm-js/0.6.0/DLSerialPortUtil-wasm-js-0.6.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-wasm-js",
        "version": "0.6.0"
      }
    }
  ]
}
