{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLMapboxUtil",
    "version": "1.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mapbox.maps",
          "module": "android",
          "version": {
            "requires": "10.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "DLMapboxUtil-1.1.8.aar",
          "url": "DLMapboxUtil-1.1.8.aar",
          "size": 958867,
          "sha512": "1582168ca303c12a1c973247e29bb88d5f735243a44f78b8d678cc2c53f0c40eaeaa3e626d3a45ec9278c521e90f67139081a4e640ede36483ff640f3cfb5367",
          "sha256": "6b9eaf7421e1a567e1b5acd9c8944517a24a411979b7e2c71d00dc7dc189d420",
          "sha1": "03a295a9fa23e39ad2d9c775b95af9ce33759210",
          "md5": "20e52df71d745df4bf0ce40b78a1d8b7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.github.raamcosta.compose-destinations",
          "module": "animations-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLJetpackComposeUtil",
          "version": {
            "requires": "2.0.22"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLAppUtil",
          "version": {
            "requires": "2.5.4"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLTianDiTuApi",
          "version": {
            "requires": "0.5.9"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLHttpUtil",
          "version": {
            "requires": "0.9.3"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLDatastoreUtil",
          "version": {
            "requires": "0.0.8"
          }
        },
        {
          "group": "com.mapbox.maps",
          "module": "android",
          "version": {
            "requires": "10.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "DLMapboxUtil-1.1.8.aar",
          "url": "DLMapboxUtil-1.1.8.aar",
          "size": 958867,
          "sha512": "1582168ca303c12a1c973247e29bb88d5f735243a44f78b8d678cc2c53f0c40eaeaa3e626d3a45ec9278c521e90f67139081a4e640ede36483ff640f3cfb5367",
          "sha256": "6b9eaf7421e1a567e1b5acd9c8944517a24a411979b7e2c71d00dc7dc189d420",
          "sha1": "03a295a9fa23e39ad2d9c775b95af9ce33759210",
          "md5": "20e52df71d745df4bf0ce40b78a1d8b7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLMapboxUtil-1.1.8-sources.jar",
          "url": "DLMapboxUtil-1.1.8-sources.jar",
          "size": 59053,
          "sha512": "6081679cb65369b4a8c607a3cc61f97dabb817f4d1fa8cd2613f5f2fb9d3f5f65ab236f41b1e0f58f7300f4dba7cfd77f51353ac7388ce7351cfb73a33e0b1c3",
          "sha256": "2fec761255726dde99685bc3c94179aaf629e28d920bc3eee183d5590b7b95de",
          "sha1": "87eeb94d193718a129eec976af5191e56c54573d",
          "md5": "205f8221cbfef1304c44e579d7b86409"
        }
      ]
    }
  ]
}
