{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLCommonUtil/0.0.2/DLCommonUtil-0.0.2.module",
    "group": "com.github.D10NGYANG",
    "module": "DLCommonUtil",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil.klib",
          "url": "DLCommonUtil-iosx64-0.0.2.klib",
          "size": 32755,
          "sha512": "d01228ff9166238292bfafcf1adfd9a94a5bc237941a8c2c4f11ec076005d9bb83ced5723c894336c870802855a5148d9e351ac45fe7af56af9478cdb8459543",
          "sha256": "8a23db518474449a0e659dcb3d8db2ad3119cb6c5f4bf092252656672dda24b0",
          "sha1": "c91a0a7393894b4a4ba36cc8ffb1ba280e791c5c",
          "md5": "20ad67bca216fe97f3db3720306b466a"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLCommonUtil-iosx64-0.0.2-sources.jar",
          "url": "DLCommonUtil-iosx64-0.0.2-sources.jar",
          "size": 11130,
          "sha512": "2261ea3e5a275a32c8ab85ee70dcfb219cf0d059b8de9883b9518cbe9ec0e4ba258c410373718cce5f4ec5afb8087501d24b3ed1a962a4d25c5521c36e299d43",
          "sha256": "ca419c6d439e01cb078a695a1603ea21f05285a5def76011ec791016d13db194",
          "sha1": "e1d1709e65b6b3ccdf6e5e490d12324cff8b7bf2",
          "md5": "3336c1287864807ab913fe38c5f91d9a"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-iosx64-0.0.2-metadata.jar",
          "url": "DLCommonUtil-iosx64-0.0.2-metadata.jar",
          "size": 3585,
          "sha512": "ac1fa31581e275f9eab4d779e9ec608beda07ec955f9731d2bb4f1b49c477195f5259e8fd0dd35eeb1ea20cd1d0f76437b6e2178631fc7f1b1b14a29ed756b0e",
          "sha256": "e8dcf7cfe763c00ebfc23b1f8f396c4bfa933cbf9e3dae2a7ac21e10bcc3ab86",
          "sha1": "6989ef62b561415eb8baab063f32cabf4bf2c861",
          "md5": "4a09a8dc47ceb05d6db481ffba2cd361"
        }
      ]
    }
  ]
}
