{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLJetpackComposeUtil",
    "version": "3.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-metadata-3.3.4.jar",
          "url": "DLJetpackComposeUtil-3.3.4.jar",
          "size": 50515,
          "sha512": "771c686494d296f5ea8a32a9dd49acbabb3fb5e1840b5cf2b0c1162a27d200ddfaf347800a67891c3980cd8176ec57646b0d4b00e2ac24130c4174ba5b3d508e",
          "sha256": "e5a05efe142014c942a2a7cd7c611354c990e50cbd3d68eaed6b034108108358",
          "sha1": "ed4da3f4f065d39e6d163c34f5bd14603bece608",
          "md5": "5416ba0af1b6df67aaa72da8afc9cb0f"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "DLJetpackComposeUtil-kotlin-3.3.4-sources.jar",
          "url": "DLJetpackComposeUtil-3.3.4-sources.jar",
          "size": 101075,
          "sha512": "05eac0eb7ccfd67c6f4a268366dddafbe2da9807d32771a1196de3c43bb8afe899652016630ecea5246e2184375c872939241b045cbf65081439b52a737f4221",
          "sha256": "1d74d55ba47e077259afca5df09d01a7c964bb897cb8ca6995f6017dedb1949c",
          "sha1": "fd14ec03086e3c76cbf140f8804c371bd4f63d56",
          "md5": "845973e85c57ac66e9756f0ab54ed9da"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-android/3.3.4/DLJetpackComposeUtil-android-3.3.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-android",
        "version": "3.3.4"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-android/3.3.4/DLJetpackComposeUtil-android-3.3.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-android",
        "version": "3.3.4"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-android/3.3.4/DLJetpackComposeUtil-android-3.3.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-android",
        "version": "3.3.4"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iosarm64/3.3.4/DLJetpackComposeUtil-iosarm64-3.3.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iosarm64",
        "version": "3.3.4"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iosarm64/3.3.4/DLJetpackComposeUtil-iosarm64-3.3.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iosarm64",
        "version": "3.3.4"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iosarm64/3.3.4/DLJetpackComposeUtil-iosarm64-3.3.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iosarm64",
        "version": "3.3.4"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iosarm64/3.3.4/DLJetpackComposeUtil-iosarm64-3.3.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iosarm64",
        "version": "3.3.4"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iossimulatorarm64/3.3.4/DLJetpackComposeUtil-iossimulatorarm64-3.3.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iossimulatorarm64",
        "version": "3.3.4"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iossimulatorarm64/3.3.4/DLJetpackComposeUtil-iossimulatorarm64-3.3.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iossimulatorarm64",
        "version": "3.3.4"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iossimulatorarm64/3.3.4/DLJetpackComposeUtil-iossimulatorarm64-3.3.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iossimulatorarm64",
        "version": "3.3.4"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iossimulatorarm64/3.3.4/DLJetpackComposeUtil-iossimulatorarm64-3.3.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iossimulatorarm64",
        "version": "3.3.4"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-js/3.3.4/DLJetpackComposeUtil-js-3.3.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-js",
        "version": "3.3.4"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-js/3.3.4/DLJetpackComposeUtil-js-3.3.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-js",
        "version": "3.3.4"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-js/3.3.4/DLJetpackComposeUtil-js-3.3.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-js",
        "version": "3.3.4"
      }
    },
    {
      "name": "jsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-js/3.3.4/DLJetpackComposeUtil-js-3.3.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-js",
        "version": "3.3.4"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-jvm/3.3.4/DLJetpackComposeUtil-jvm-3.3.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-jvm",
        "version": "3.3.4"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-jvm/3.3.4/DLJetpackComposeUtil-jvm-3.3.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-jvm",
        "version": "3.3.4"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-jvm/3.3.4/DLJetpackComposeUtil-jvm-3.3.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-jvm",
        "version": "3.3.4"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-wasm-js/3.3.4/DLJetpackComposeUtil-wasm-js-3.3.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-wasm-js",
        "version": "3.3.4"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-wasm-js/3.3.4/DLJetpackComposeUtil-wasm-js-3.3.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-wasm-js",
        "version": "3.3.4"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-wasm-js/3.3.4/DLJetpackComposeUtil-wasm-js-3.3.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-wasm-js",
        "version": "3.3.4"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-wasm-js/3.3.4/DLJetpackComposeUtil-wasm-js-3.3.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-wasm-js",
        "version": "3.3.4"
      }
    }
  ]
}
