{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLJetpackComposeUtil/3.3.5/DLJetpackComposeUtil-3.3.5.module",
    "group": "com.github.D10NGYANG",
    "module": "DLJetpackComposeUtil",
    "version": "3.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-js-3.3.5.klib",
          "url": "DLJetpackComposeUtil-js-3.3.5.klib",
          "size": 4193799,
          "sha512": "e4bed080dd44af4033dd973cd4c181cc77b0d49df5ca879eb66e52d8b1d12c33ec4b742be00e40447b84ccac2b6a2b0fbe2ee2347614044695fa25f8efd1d2e9",
          "sha256": "d881953449396f50e13ca898b0a6fd3981ad378ae7c6662675b5c0b0f9aac280",
          "sha1": "d5b850c32812509732e20b870685f39c7960dbda",
          "md5": "004e6ddce26fa3e3c545edab88843d83"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.11.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-js-3.3.5.klib",
          "url": "DLJetpackComposeUtil-js-3.3.5.klib",
          "size": 4193799,
          "sha512": "e4bed080dd44af4033dd973cd4c181cc77b0d49df5ca879eb66e52d8b1d12c33ec4b742be00e40447b84ccac2b6a2b0fbe2ee2347614044695fa25f8efd1d2e9",
          "sha256": "d881953449396f50e13ca898b0a6fd3981ad378ae7c6662675b5c0b0f9aac280",
          "sha1": "d5b850c32812509732e20b870685f39c7960dbda",
          "md5": "004e6ddce26fa3e3c545edab88843d83"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "DLJetpackComposeUtil-js-3.3.5-sources.jar",
          "url": "DLJetpackComposeUtil-js-3.3.5-sources.jar",
          "size": 104256,
          "sha512": "70d6fcb1fbfeb4ba01e66ca3a1571a38dd7b0e8a96af15cb60a990a9a39d403e45e22e84857a3d6b338bc7b572f03d08357d2b26741273c26d2f23422bb10e0d",
          "sha256": "8e6289734b25a3515d8ed826562005b68ce615191bf2b64172ff728524d9bca2",
          "sha1": "e4bb17325b07becddd81d5d409d26dca557fa83d",
          "md5": "e77e3ec232342430a49e2942750619d5"
        }
      ]
    },
    {
      "name": "jsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.11.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-3.3.5.kotlin_resources.zip",
          "url": "DLJetpackComposeUtil-js-3.3.5-kotlin_resources.kotlin_resources.zip",
          "size": 10276,
          "sha512": "b0db8ff060087fff9ba4d4ca2bf6d37101f443e547691a93a082caf0b6268ab495c616cc648d2c86f9b31315cf460cf307764ac871538b785acf982894835f85",
          "sha256": "7fac824799250fbf7557b9ac0e7633cfbe3a53d3b91b2e55a81ce8eabf851022",
          "sha1": "a2b7eb83c08178bee343c6e2a717d0a389c4509e",
          "md5": "0b35b0bcb66646835b0e3570aa9dfc80"
        }
      ]
    }
  ]
}
