{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLCommonUtil/1.0.1/DLCommonUtil-1.0.1.module",
    "group": "com.github.D10NGYANG",
    "module": "DLCommonUtil",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil.aar",
          "url": "DLCommonUtil-android-1.0.1.aar",
          "size": 141769,
          "sha512": "9f7ad1fbd0233e8884e12f6073811a35b06e2aabfb9e2b8ba9a240f3189f2cfa975abb2671b905b8794f79f1097beefd7db1454663ed72e25ce5ee8dd239ff02",
          "sha256": "af4acd7c4db48f4525db8a3ce31c6b0a4e0f754948baad2e12c4a6b559e7910f",
          "sha1": "79116e2ac6dd91f2de3506cde5a242955c8d1a2e",
          "md5": "4e3bff4c47233be9e96f4a4c96c3881b"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil.aar",
          "url": "DLCommonUtil-android-1.0.1.aar",
          "size": 141769,
          "sha512": "9f7ad1fbd0233e8884e12f6073811a35b06e2aabfb9e2b8ba9a240f3189f2cfa975abb2671b905b8794f79f1097beefd7db1454663ed72e25ce5ee8dd239ff02",
          "sha256": "af4acd7c4db48f4525db8a3ce31c6b0a4e0f754948baad2e12c4a6b559e7910f",
          "sha1": "79116e2ac6dd91f2de3506cde5a242955c8d1a2e",
          "md5": "4e3bff4c47233be9e96f4a4c96c3881b"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "DLCommonUtil-android-1.0.1-sources.jar",
          "url": "DLCommonUtil-android-1.0.1-sources.jar",
          "size": 96638,
          "sha512": "3f80e538aefff80d14c4a0d6241a7e98e2594ed555a9f0c3c951554212c3fcac5330d97337cb4ba3e9d2ae836a23735477d81ebd1c022c2b6ff5399154f75e85",
          "sha256": "5ae8e0d006030cf15cef05576db9fda9762c1e07046556f877c0b5c5f4ea7ef4",
          "sha1": "3dc22759deb3c077349252db31ac9b9d5132619c",
          "md5": "00c49686e48d79dfff9de774466b99b0"
        }
      ]
    }
  ]
}
