{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/2.1.0/DLDateUtil-2.1.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-macosX64Main-2.1.0.klib",
          "url": "DLDateUtil-macosx64-2.1.0.klib",
          "size": 76901,
          "sha512": "7da0a596e7c51db515553ced9b42ab1ac023239f3925a34b6e2d7fd67ebdace75b1ef08443f8b4cf9315defd20901420267a05f928ab752d0309eac08d43313b",
          "sha256": "ce5a99a80a544949cec0aea233251a3d1b657ac2a1f0ae75022df02be185baf7",
          "sha1": "f2c7dcee5b1ec4253c0e3597dbb8bf9ebfa81354",
          "md5": "6c032406b7421833458b3634f616fc3c"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLDateUtil-macosx64-2.1.0-sources.jar",
          "url": "DLDateUtil-macosx64-2.1.0-sources.jar",
          "size": 17232,
          "sha512": "b8d79c6283ff88e837ddc3a09ba5bdf8699a2a4fe77e5fc8901d5cce63e8c9d4febfd42667699643513e15abe3162d38b6caa93b7e57235ef6af4b0b02099887",
          "sha256": "f7b7660b171231b2f4c2aff1359711b1694e753a21041add4b009f1d859055b8",
          "sha1": "29731f21fc212fa56c686b33b47c58e97a676243",
          "md5": "cfe31385e210ad62a83d8b501483b495"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-macosx64-2.1.0-metadata.jar",
          "url": "DLDateUtil-macosx64-2.1.0-metadata.jar",
          "size": 261,
          "sha512": "45d0f4122715c2f0afcb699734dd172b0a39f60cd5e2c380875a5cb033efbc97998354288a9d5180001eef78339bd7df1928c1f64f7b74c124d7bf8050085b99",
          "sha256": "a5eb89ef96d45ec6381816c84b8a563f5570434c1752ac420125b08c67f92e1e",
          "sha1": "b73623783f378ebb363e5b25bc634507377b58ff",
          "md5": "847ffe2fe1584ab72d85c1d3b6bb332f"
        }
      ]
    }
  ]
}
