{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLBluetoothUtil/0.1.10/DLBluetoothUtil-0.1.10.module",
    "group": "com.github.D10NGYANG",
    "module": "DLBluetoothUtil",
    "version": "0.1.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.bluetooth",
          "module": "bluetooth",
          "version": {
            "requires": "1.0.0-alpha02"
          }
        },
        {
          "group": "com.github.buhuiming",
          "module": "BleCore",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLBluetoothUtil-release.aar",
          "url": "DLBluetoothUtil-android-0.1.10.aar",
          "size": 87205,
          "sha512": "116b85087ced2777664b8410e9fa310068d71dc06a85bc2b8a9ec1900dd8d629778dae1f203abdd7b82a08e02e69ee3a986289d317f76a6e724ac3350a4b30df",
          "sha256": "d6898d843f9557d57860d0d9aeef71a683b103cec4d348aaa0529e440269b190",
          "sha1": "a5f22d1d223b235987d351da84d8b5abf5e1c528",
          "md5": "6e434efbe9b14056db3f65aaacde8bad"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.bluetooth",
          "module": "bluetooth",
          "version": {
            "requires": "1.0.0-alpha02"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.github.buhuiming",
          "module": "BleCore",
          "version": {
            "requires": "2.3.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.9.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0-RC.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLAppUtil",
          "version": {
            "requires": "2.5.7"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0-RC.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.5.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "DLBluetoothUtil-release.aar",
          "url": "DLBluetoothUtil-android-0.1.10.aar",
          "size": 87205,
          "sha512": "116b85087ced2777664b8410e9fa310068d71dc06a85bc2b8a9ec1900dd8d629778dae1f203abdd7b82a08e02e69ee3a986289d317f76a6e724ac3350a4b30df",
          "sha256": "d6898d843f9557d57860d0d9aeef71a683b103cec4d348aaa0529e440269b190",
          "sha1": "a5f22d1d223b235987d351da84d8b5abf5e1c528",
          "md5": "6e434efbe9b14056db3f65aaacde8bad"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "DLBluetoothUtil-android-0.1.10-sources.jar",
          "url": "DLBluetoothUtil-android-0.1.10-sources.jar",
          "size": 11850,
          "sha512": "90c2db58c61b736c079fa705476587c41f67f09e99697e7985628f3ee8ffcfabb63b2b78ba420c8e7a055adf0ec5dd374811fcfaeb7a835d2101d86e7f8de01b",
          "sha256": "88704ebdd3ba522755ab368181d0580d0474e61befbc7aa60448f93ad97729db",
          "sha1": "5f387a41c7742be6f01af353c26153933f23cbd2",
          "md5": "f0700a5a4766e2ba3198c5fb9ff09788"
        }
      ]
    }
  ]
}
