{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLSerialPortUtil/0.2.0/DLSerialPortUtil-0.2.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLSerialPortUtil",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.licheedev",
          "module": "android-serialport",
          "version": {
            "requires": "2.1.5"
          }
        },
        {
          "group": "com.github.mik3y",
          "module": "usb-serial-for-android",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLSerialPortUtil-release.aar",
          "url": "DLSerialPortUtil-android-0.2.0.aar",
          "size": 60021,
          "sha512": "68a1750b046f2ebb06b5ae8cca7383e1b7df51ebe6f976d1deaed9b295db323bc09157d2bd93d3025bf3405462ac87cc15d51bb1bb347dbdf792deb386ba2946",
          "sha256": "b5becdeea01f5d19df46866ef84c269658e9304cc37e6a1fe68696ec464b8c71",
          "sha1": "e02a88b603c025a36859b56f674a623da6e4b15d",
          "md5": "879e421364c3a5712ce025141ded4de7"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.licheedev",
          "module": "android-serialport",
          "version": {
            "requires": "2.1.5"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.github.mik3y",
          "module": "usb-serial-for-android",
          "version": {
            "requires": "3.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "DLSerialPortUtil-release.aar",
          "url": "DLSerialPortUtil-android-0.2.0.aar",
          "size": 60021,
          "sha512": "68a1750b046f2ebb06b5ae8cca7383e1b7df51ebe6f976d1deaed9b295db323bc09157d2bd93d3025bf3405462ac87cc15d51bb1bb347dbdf792deb386ba2946",
          "sha256": "b5becdeea01f5d19df46866ef84c269658e9304cc37e6a1fe68696ec464b8c71",
          "sha1": "e02a88b603c025a36859b56f674a623da6e4b15d",
          "md5": "879e421364c3a5712ce025141ded4de7"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "DLSerialPortUtil-android-0.2.0-sources.jar",
          "url": "DLSerialPortUtil-android-0.2.0-sources.jar",
          "size": 10632,
          "sha512": "f6f28bd314fb19e3870a046f436294a145da1e3bca38c36ba97055cf3b31c5c32e7ee6434f9c6a9199abb4b1193e05999a094fe6df89e743782adf73eb04bae4",
          "sha256": "78a8806bfdc7c3aacc5eea3db2215b5378c741253f52c6811cebc479f392c3b5",
          "sha1": "2c2641d022240d3c5120e1e8a5394b1d5406f9d0",
          "md5": "914591658400dc56dfd782344884d8c3"
        }
      ]
    }
  ]
}
