{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ImageCompress/1.0.0-beta12/ImageCompress-1.0.0-beta12.module",
    "group": "com.hailiao.util",
    "module": "ImageCompress",
    "version": "1.0.0-beta12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ImageCompress-jvm-1.0.0-beta12.jar",
          "url": "ImageCompress-jvm-1.0.0-beta12.jar",
          "size": 763734,
          "sha512": "8347dc3dc48c1a9c27d9e357e026127ea6ba2b8d89e4dd0f19af27d36dc7eba90fcd61e15d41f865292d5e55a2836d5c8e94fd6c7539aa2680074e4d9aa9ae31",
          "sha256": "3bd6cc1b38df0710a06f482221af057974feba8d829c2b2037b85866055b4ccf",
          "sha1": "b52cba0d8bba4a8480232684cbe59b1e9db50a99",
          "md5": "6c9fdc3cf6a5a9b3b0c0846b0e5e1f2e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ImageCompress-jvm-1.0.0-beta12.jar",
          "url": "ImageCompress-jvm-1.0.0-beta12.jar",
          "size": 763734,
          "sha512": "8347dc3dc48c1a9c27d9e357e026127ea6ba2b8d89e4dd0f19af27d36dc7eba90fcd61e15d41f865292d5e55a2836d5c8e94fd6c7539aa2680074e4d9aa9ae31",
          "sha256": "3bd6cc1b38df0710a06f482221af057974feba8d829c2b2037b85866055b4ccf",
          "sha1": "b52cba0d8bba4a8480232684cbe59b1e9db50a99",
          "md5": "6c9fdc3cf6a5a9b3b0c0846b0e5e1f2e"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ImageCompress-jvm-1.0.0-beta12-sources.jar",
          "url": "ImageCompress-jvm-1.0.0-beta12-sources.jar",
          "size": 10508,
          "sha512": "8897480daf1bc334b635aed5aadc63442b3f5e73f5f7b8ccadf2edc0403acdc4b71fb6a51d1266aa7603fe3c897d3f11f17f9391cab1bae4f27591c3dc53b00e",
          "sha256": "455881df4d098e165f0d58865bfbba3e4334870c92ad7000c47655dfb8608f6a",
          "sha1": "12df7549960e98ae76a696873731f691115047a1",
          "md5": "6e7c934af490581ad92b920d720e75a9"
        }
      ]
    }
  ]
}
