{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLCryptoUtil/0.1.0/DLCryptoUtil-0.1.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLCryptoUtil",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "DLCryptoUtil-js-0.1.0.klib",
          "url": "DLCryptoUtil-js-0.1.0.klib",
          "size": 30746,
          "sha512": "10d916cd808d5f47182927f12026988cd3e2bc9c3c0a91bcf7fb7a67e5d6911ab5b39388da37ce754ce4321b7963ef00c5c307634851247246aeadd70b1e05bf",
          "sha256": "5a4e46db14d713380dada21b46042ba5e4e18677a7842e311d0759557dd246fe",
          "sha1": "0a1bc35a42fc4241a537ae8ed210b109796b56e8",
          "md5": "b78c9c7998a002c0de913806a0a0a2ec"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "DLCryptoUtil-js-0.1.0.klib",
          "url": "DLCryptoUtil-js-0.1.0.klib",
          "size": 30746,
          "sha512": "10d916cd808d5f47182927f12026988cd3e2bc9c3c0a91bcf7fb7a67e5d6911ab5b39388da37ce754ce4321b7963ef00c5c307634851247246aeadd70b1e05bf",
          "sha256": "5a4e46db14d713380dada21b46042ba5e4e18677a7842e311d0759557dd246fe",
          "sha1": "0a1bc35a42fc4241a537ae8ed210b109796b56e8",
          "md5": "b78c9c7998a002c0de913806a0a0a2ec"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "DLCryptoUtil-js-0.1.0-sources.jar",
          "url": "DLCryptoUtil-js-0.1.0-sources.jar",
          "size": 8494,
          "sha512": "7726fec7084606396cd1a2fb1a14c3fb69d3f2092fd774ea4d93391ff293e79b5f6ed0d382dc3e8e15ed2244c45084edb35aac1f523700e8bb144ff97f583a4b",
          "sha256": "a321a632bd6b5d5d4e731275c408975323f6a165da2b25889f1a7a60fb36c113",
          "sha1": "9aefbec01d7f990b52ccc37ab6a7a1027417e3ee",
          "md5": "6b82b4a7cce2637e98a44ab595182e00"
        }
      ]
    }
  ]
}
