{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/2.3.1/DLDateUtil-2.3.1.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "2.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-linuxArm64Main-2.3.1.klib",
          "url": "DLDateUtil-linuxarm64-2.3.1.klib",
          "size": 94438,
          "sha512": "01cf5ac9fb9ddbbedb27d8060ebfd12ee9ea81e47f2f2590f3a90212920fdd8e7dcb24c272467d427a34ce346fc04ff302334f0c67053a0db7fba47bb48f7b09",
          "sha256": "2203aff05e0fd81de09aa739563fef76f95873483060ddbe777c29b2099f7f65",
          "sha1": "c0dd3f4fdf1824d6da68cac7a889783ebdd18fc7",
          "md5": "0e007346f21446c43941a5dc22115028"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLDateUtil-linuxarm64-2.3.1-sources.jar",
          "url": "DLDateUtil-linuxarm64-2.3.1-sources.jar",
          "size": 21080,
          "sha512": "953123f22ca1bab8337e14eb7ae72468bb4bc8cfda101870babf688f28ef9a052d4710666c1e41cfca592ea2b72f1985206df35253bb2725749b2b0ee21bbbef",
          "sha256": "917128fe4961ed7e500c08691e152d79f1719117212fcf759ecf06b91d727aed",
          "sha1": "bcd5c894ffb1e6e97692f5938153db16c80311f8",
          "md5": "acd570a277f326e858bf775b1155a5e4"
        }
      ]
    }
  ]
}
