{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLJetpackComposeUtil",
    "version": "3.0.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.5.2"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLDateUtil",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-metadata-3.0.0-alpha02.jar",
          "url": "DLJetpackComposeUtil-3.0.0-alpha02.jar",
          "size": 47148,
          "sha512": "36314344898ca6b9ac3d5f9d03b781404188f10abf750f5dbd6949d65432bd36e6994b641e3e245659604a2a28bb9ba3b3fc2f6b1c44684b8484c141014e099f",
          "sha256": "b4589e105fe048b7e0c3da1e47a01e92f3b7da26848755e2842031da5025db1e",
          "sha1": "d2d308e8981e44383651983831e2ef5467f5811c",
          "md5": "13f80d44c63fa216e1b9f0559081669e"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "DLJetpackComposeUtil-kotlin-3.0.0-alpha02-sources.jar",
          "url": "DLJetpackComposeUtil-3.0.0-alpha02-sources.jar",
          "size": 77228,
          "sha512": "f4131299f442683d4f9bdfe06ba8860acebfab3f2b1535e714665e866bd20e6a9b0e01b2bbfc172b3fc9beaa8f147feb3cc7e1189a3c17c02463b15b2b8ce98f",
          "sha256": "ab7d97ea922893999f34ce2d11b1ca06a3c3e0f41cb8492b4552b7c3f5cdc70c",
          "sha1": "feb4a8b9fe8febad86e0ae2148f62941c5d4e698",
          "md5": "260d837d1b6ce52c5e6ae529f4e0688b"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-android/3.0.0-alpha02/DLJetpackComposeUtil-android-3.0.0-alpha02.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-android",
        "version": "3.0.0-alpha02"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-android/3.0.0-alpha02/DLJetpackComposeUtil-android-3.0.0-alpha02.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-android",
        "version": "3.0.0-alpha02"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-android/3.0.0-alpha02/DLJetpackComposeUtil-android-3.0.0-alpha02.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-android",
        "version": "3.0.0-alpha02"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iosarm64/3.0.0-alpha02/DLJetpackComposeUtil-iosarm64-3.0.0-alpha02.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iosarm64",
        "version": "3.0.0-alpha02"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iosarm64/3.0.0-alpha02/DLJetpackComposeUtil-iosarm64-3.0.0-alpha02.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iosarm64",
        "version": "3.0.0-alpha02"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iosarm64/3.0.0-alpha02/DLJetpackComposeUtil-iosarm64-3.0.0-alpha02.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iosarm64",
        "version": "3.0.0-alpha02"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iosarm64/3.0.0-alpha02/DLJetpackComposeUtil-iosarm64-3.0.0-alpha02.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iosarm64",
        "version": "3.0.0-alpha02"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iossimulatorarm64/3.0.0-alpha02/DLJetpackComposeUtil-iossimulatorarm64-3.0.0-alpha02.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iossimulatorarm64",
        "version": "3.0.0-alpha02"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iossimulatorarm64/3.0.0-alpha02/DLJetpackComposeUtil-iossimulatorarm64-3.0.0-alpha02.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iossimulatorarm64",
        "version": "3.0.0-alpha02"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iossimulatorarm64/3.0.0-alpha02/DLJetpackComposeUtil-iossimulatorarm64-3.0.0-alpha02.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iossimulatorarm64",
        "version": "3.0.0-alpha02"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iossimulatorarm64/3.0.0-alpha02/DLJetpackComposeUtil-iossimulatorarm64-3.0.0-alpha02.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iossimulatorarm64",
        "version": "3.0.0-alpha02"
      }
    }
  ]
}
