{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-metadata-2.1.0.jar",
          "url": "DLDateUtil-2.1.0.jar",
          "size": 11564,
          "sha512": "d8d33bd24bec8f9d0d84ce188ad8ba512a441a251a26092c99a3d76d5f02904dab9c274b7840f65bb87d836738a479e998098577344a3181eca28708c3af9ae2",
          "sha256": "79353fa24905a529b28dbc07d65710bfedeb8ea62bd15552220ca959056be43d",
          "sha1": "56bf5c090f7257b39cf15a04c8e070c549c6e815",
          "md5": "e8dd715bfa62e7b7ccf866421a5ac1ba"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "DLDateUtil-kotlin-2.1.0-sources.jar",
          "url": "DLDateUtil-2.1.0-sources.jar",
          "size": 17232,
          "sha512": "b8d79c6283ff88e837ddc3a09ba5bdf8699a2a4fe77e5fc8901d5cce63e8c9d4febfd42667699643513e15abe3162d38b6caa93b7e57235ef6af4b0b02099887",
          "sha256": "f7b7660b171231b2f4c2aff1359711b1694e753a21041add4b009f1d859055b8",
          "sha1": "29731f21fc212fa56c686b33b47c58e97a676243",
          "md5": "cfe31385e210ad62a83d8b501483b495"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLDateUtil-android/2.1.0/DLDateUtil-android-2.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-android",
        "version": "2.1.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLDateUtil-android/2.1.0/DLDateUtil-android-2.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-android",
        "version": "2.1.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLDateUtil-android/2.1.0/DLDateUtil-android-2.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-android",
        "version": "2.1.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iosarm64/2.1.0/DLDateUtil-iosarm64-2.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iosarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iosarm64/2.1.0/DLDateUtil-iosarm64-2.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iosarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iosarm64/2.1.0/DLDateUtil-iosarm64-2.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iosarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iossimulatorarm64/2.1.0/DLDateUtil-iossimulatorarm64-2.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iossimulatorarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iossimulatorarm64/2.1.0/DLDateUtil-iossimulatorarm64-2.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iossimulatorarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iossimulatorarm64/2.1.0/DLDateUtil-iossimulatorarm64-2.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iossimulatorarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iosx64/2.1.0/DLDateUtil-iosx64-2.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iosx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iosx64/2.1.0/DLDateUtil-iosx64-2.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iosx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iosx64/2.1.0/DLDateUtil-iosx64-2.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iosx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLDateUtil-js/2.1.0/DLDateUtil-js-2.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-js",
        "version": "2.1.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLDateUtil-js/2.1.0/DLDateUtil-js-2.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-js",
        "version": "2.1.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLDateUtil-js/2.1.0/DLDateUtil-js-2.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-js",
        "version": "2.1.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLDateUtil-jvm/2.1.0/DLDateUtil-jvm-2.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-jvm",
        "version": "2.1.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLDateUtil-jvm/2.1.0/DLDateUtil-jvm-2.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-jvm",
        "version": "2.1.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLDateUtil-jvm/2.1.0/DLDateUtil-jvm-2.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-jvm",
        "version": "2.1.0"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-linuxarm64/2.1.0/DLDateUtil-linuxarm64-2.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-linuxarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-linuxarm64/2.1.0/DLDateUtil-linuxarm64-2.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-linuxarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-linuxx64/2.1.0/DLDateUtil-linuxx64-2.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-linuxx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-linuxx64/2.1.0/DLDateUtil-linuxx64-2.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-linuxx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-macosarm64/2.1.0/DLDateUtil-macosarm64-2.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-macosarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-macosarm64/2.1.0/DLDateUtil-macosarm64-2.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-macosarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-macosarm64/2.1.0/DLDateUtil-macosarm64-2.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-macosarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-macosx64/2.1.0/DLDateUtil-macosx64-2.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-macosx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-macosx64/2.1.0/DLDateUtil-macosx64-2.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-macosx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-macosx64/2.1.0/DLDateUtil-macosx64-2.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-macosx64",
        "version": "2.1.0"
      }
    }
  ]
}
