{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ImageCompress/1.0.0-beta04/ImageCompress-1.0.0-beta04.module",
    "group": "com.hailiao.util",
    "module": "ImageCompress",
    "version": "1.0.0-beta04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ImageCompress-jvm-1.0.0-beta04.jar",
          "url": "ImageCompress-jvm-1.0.0-beta04.jar",
          "size": 752758,
          "sha512": "9d1e4194f72aca1c879342bb8d94f242091ce663805f4c21cbac406e3eb3e6a49f1374497ffc105d427543bbb0b5371c0b88f48106fc9032f3ea977fd06c5313",
          "sha256": "0018b65c11b4aafc1366c259d8bc5c617b3e333e53456911f9b4b6400ed7687c",
          "sha1": "3f0ededf303c42ba577c8f4ab4db43d94d6c937c",
          "md5": "97efeb72d1d6f2f82edb52033658a48c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ImageCompress-jvm-1.0.0-beta04.jar",
          "url": "ImageCompress-jvm-1.0.0-beta04.jar",
          "size": 752758,
          "sha512": "9d1e4194f72aca1c879342bb8d94f242091ce663805f4c21cbac406e3eb3e6a49f1374497ffc105d427543bbb0b5371c0b88f48106fc9032f3ea977fd06c5313",
          "sha256": "0018b65c11b4aafc1366c259d8bc5c617b3e333e53456911f9b4b6400ed7687c",
          "sha1": "3f0ededf303c42ba577c8f4ab4db43d94d6c937c",
          "md5": "97efeb72d1d6f2f82edb52033658a48c"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ImageCompress-jvm-1.0.0-beta04-sources.jar",
          "url": "ImageCompress-jvm-1.0.0-beta04-sources.jar",
          "size": 5515,
          "sha512": "35c87857bdb6fd0c6eb4ec229b4021bdc8d488f3b6a277616aa9f7f8b4d897af4435449daca8d2421ed18c71030a7d95e6d3c34497e7ba0bfd8534026c620a1a",
          "sha256": "ec0242a1ef15397cf4292484ada4d71738d6e87068a2e65acbcf6190b56d593a",
          "sha1": "8e8ef4db3ffe724984f55af41a39ef07436d9bb9",
          "md5": "60046ee3b1d93502966b314e06c9cdc8"
        }
      ]
    }
  ]
}
