{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLMqttUtil",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.paho",
          "module": "org.eclipse.paho.client.mqttv3",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "org.eclipse.paho",
          "module": "org.eclipse.paho.android.service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "DLMqttUtil-0.0.7.aar",
          "url": "DLMqttUtil-0.0.7.aar",
          "size": 38138,
          "sha512": "f394a399dedeca784c3eba0fc616678c392770dd3c89a3326149673fd39071446870546b54ef760bccf6320ff144b9d264623371d3932cefed0cdc5eb9f415d4",
          "sha256": "64c4487801c5a93c91f76a5f413a22f6c3157061bf5f294409085169a9dec6ea",
          "sha1": "d0c11781e99282ee1edd9afbfc061459476733a3",
          "md5": "a01b9f737be84bf97688783724530655"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.eclipse.paho",
          "module": "org.eclipse.paho.client.mqttv3",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "org.eclipse.paho",
          "module": "org.eclipse.paho.android.service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "DLMqttUtil-0.0.7.aar",
          "url": "DLMqttUtil-0.0.7.aar",
          "size": 38138,
          "sha512": "f394a399dedeca784c3eba0fc616678c392770dd3c89a3326149673fd39071446870546b54ef760bccf6320ff144b9d264623371d3932cefed0cdc5eb9f415d4",
          "sha256": "64c4487801c5a93c91f76a5f413a22f6c3157061bf5f294409085169a9dec6ea",
          "sha1": "d0c11781e99282ee1edd9afbfc061459476733a3",
          "md5": "a01b9f737be84bf97688783724530655"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLMqttUtil-0.0.7-sources.jar",
          "url": "DLMqttUtil-0.0.7-sources.jar",
          "size": 7030,
          "sha512": "362d47716212770cefeaa6fcd2473c7392d8b46c7509ddbbc6e2c30339e1193976d78d0b3425f08b13efcc07d0c68330696e8446af1864efc68db9c2c850de2a",
          "sha256": "8047704388ac8af2a59fa8a2c775369478ed2110a24180d5b39bd373ca9f586b",
          "sha1": "327af06cfc0333360c6eb5d3d7d8e36d42886a71",
          "md5": "a83b6af6e32d411102cee8e2647828ec"
        }
      ]
    }
  ]
}
