{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLCommonUtil/0.0.3/DLCommonUtil-0.0.3.module",
    "group": "com.github.D10NGYANG",
    "module": "DLCommonUtil",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.ditchoom",
          "module": "buffer",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-js-0.0.3.klib",
          "url": "DLCommonUtil-js-0.0.3.klib",
          "size": 100926,
          "sha512": "fce8dfda27e3bfe4f69a12f7003c69846d1b5a3901d93af0ca4714ba76adbb819bfa060245cc1f0f1023b9ba61a203d56ad0f0e563a2d79d72b34df9a76a85e1",
          "sha256": "8b0f87924f797b509c2227bc04e36c75821cae154ba65b35c9f49e4c956041dd",
          "sha1": "8d95b85b5101ebc27d6069ec61c49ec35cbd9310",
          "md5": "cbc7d5ade20af6fb926b79e37aac2f5c"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.ditchoom",
          "module": "buffer",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-js-0.0.3.klib",
          "url": "DLCommonUtil-js-0.0.3.klib",
          "size": 100926,
          "sha512": "fce8dfda27e3bfe4f69a12f7003c69846d1b5a3901d93af0ca4714ba76adbb819bfa060245cc1f0f1023b9ba61a203d56ad0f0e563a2d79d72b34df9a76a85e1",
          "sha256": "8b0f87924f797b509c2227bc04e36c75821cae154ba65b35c9f49e4c956041dd",
          "sha1": "8d95b85b5101ebc27d6069ec61c49ec35cbd9310",
          "md5": "cbc7d5ade20af6fb926b79e37aac2f5c"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "DLCommonUtil-js-0.0.3-sources.jar",
          "url": "DLCommonUtil-js-0.0.3-sources.jar",
          "size": 28504,
          "sha512": "bd6ab444ae2d413266cdb82f3dd278b7a615c321322485c57c22dac07ec385a4e21f9a34f76a642148ea6226f1a1d402849f2422c345f6b9c99b18dc67113bbf",
          "sha256": "51ac3d6a26a2c6b30506e990cb5946c5c00f9f530a591df122c41e4ebd1336e5",
          "sha1": "1dd9c294516df00c0ac188f8b055e1f4fa8688da",
          "md5": "3405181593c477c32b752cff8e8f906c"
        }
      ]
    }
  ]
}
