{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLLogUtil/0.2.0/DLLogUtil-0.2.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLLogUtil",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLLogUtil-js-0.2.0.klib",
          "url": "DLLogUtil-js-0.2.0.klib",
          "size": 16521,
          "sha512": "5797bf2cb0e5b77d4f33c45d2fbfb1dcfdac0fcaed41d422ac640d843c3e9c66a906b5e49695063a200d0b7616247132808a4085d3980b2c581ded5794ffe152",
          "sha256": "29af1edb50ae18229feb825b546209186b9fda6520837e8a2bed354416504c75",
          "sha1": "787fefb0c16fe0578ab3832e60c4fb5e19dcc2c7",
          "md5": "614997f05e28491554783e33dd387880"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "DLLogUtil-js-0.2.0.klib",
          "url": "DLLogUtil-js-0.2.0.klib",
          "size": 16521,
          "sha512": "5797bf2cb0e5b77d4f33c45d2fbfb1dcfdac0fcaed41d422ac640d843c3e9c66a906b5e49695063a200d0b7616247132808a4085d3980b2c581ded5794ffe152",
          "sha256": "29af1edb50ae18229feb825b546209186b9fda6520837e8a2bed354416504c75",
          "sha1": "787fefb0c16fe0578ab3832e60c4fb5e19dcc2c7",
          "md5": "614997f05e28491554783e33dd387880"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "DLLogUtil-js-0.2.0-sources.jar",
          "url": "DLLogUtil-js-0.2.0-sources.jar",
          "size": 4426,
          "sha512": "e6c2b6d46742e283bc51ba44d2fc1094e9e520e3e055289c9aec704a5df6a5a45ad3d46a6f77cac05a992326e355b512a502e60541ef2e17d7d4d2b6723fc536",
          "sha256": "e420066a52235a3a8009208df0c8a70602d27213457fe6712f9ef74ba8407784",
          "sha1": "03cc6cb9f05d0e8d99351f92fe29907718b17c14",
          "md5": "45dd2eea6fcfbece487d26b6addf7418"
        }
      ]
    }
  ]
}
