{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLQRCodeUtil",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.0-alpha04"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLQRCodeUtil-0.0.4.aar",
          "url": "DLQRCodeUtil-0.0.4.aar",
          "size": 120623,
          "sha512": "232d9d86f6660e1b5ca030ce86e89b5e5b40d42886e6ed776abff57812f0f537c894260b288d997c869e00e28c848fb04d34f34671b24436bce9b71f261e3a20",
          "sha256": "a2ecfeba69e187cf26f4b0824cec5e9a15e672949010d2ddd866ab08f1ca6e28",
          "sha1": "e65593533384983d3fcfa1f738a59d7c5f9d38b2",
          "md5": "4f3f4c286423e797053c69af47a29315"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLJetpackComposeUtil",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.0-alpha04"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLQRCodeUtil-0.0.4.aar",
          "url": "DLQRCodeUtil-0.0.4.aar",
          "size": 120623,
          "sha512": "232d9d86f6660e1b5ca030ce86e89b5e5b40d42886e6ed776abff57812f0f537c894260b288d997c869e00e28c848fb04d34f34671b24436bce9b71f261e3a20",
          "sha256": "a2ecfeba69e187cf26f4b0824cec5e9a15e672949010d2ddd866ab08f1ca6e28",
          "sha1": "e65593533384983d3fcfa1f738a59d7c5f9d38b2",
          "md5": "4f3f4c286423e797053c69af47a29315"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLQRCodeUtil-0.0.4-sources.jar",
          "url": "DLQRCodeUtil-0.0.4-sources.jar",
          "size": 5261,
          "sha512": "3b7846dfc4b3c80ccf25edb70e17a86cf7676d03eab50f02eaf98b55211150ab443141622b1e898fa2719e6f22801516639772343934ab11cb1269b21f25a124",
          "sha256": "bd3d5a1e8177dabcf2961e054127fe77af55b4b35751195fb318c00390d4d5fa",
          "sha1": "e7b46e70670e9a26d8266578b4e7d3feb892b3ed",
          "md5": "7b44ee96c9c895b051ccbbffd6c689fb"
        }
      ]
    }
  ]
}
