{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLCommonUtil/0.0.4/DLCommonUtil-0.0.4.module",
    "group": "com.github.D10NGYANG",
    "module": "DLCommonUtil",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "com.ditchoom",
          "module": "buffer",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-js-0.0.4.klib",
          "url": "DLCommonUtil-js-0.0.4.klib",
          "size": 107846,
          "sha512": "3ce21e2c4b69dfc3d09582621766e92ad7954e73570da27506a148fb508057ab0377fba8e185d4451580233c61f943bf8c0a0f28261aa03be8afe6cfc133d237",
          "sha256": "c9537363a80828a8bc229cea35e5e7fe877a3ac00493b4d774326e72e327a48f",
          "sha1": "1478d6e8ebc8ec6b9faab79894ff7effc170f3ed",
          "md5": "496ba7049b1e5bc2f092901736766ce5"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "com.ditchoom",
          "module": "buffer",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-js-0.0.4.klib",
          "url": "DLCommonUtil-js-0.0.4.klib",
          "size": 107846,
          "sha512": "3ce21e2c4b69dfc3d09582621766e92ad7954e73570da27506a148fb508057ab0377fba8e185d4451580233c61f943bf8c0a0f28261aa03be8afe6cfc133d237",
          "sha256": "c9537363a80828a8bc229cea35e5e7fe877a3ac00493b4d774326e72e327a48f",
          "sha1": "1478d6e8ebc8ec6b9faab79894ff7effc170f3ed",
          "md5": "496ba7049b1e5bc2f092901736766ce5"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "DLCommonUtil-js-0.0.4-sources.jar",
          "url": "DLCommonUtil-js-0.0.4-sources.jar",
          "size": 28803,
          "sha512": "9d4b6c15f39ed608dedff8880f5e996730e1f6bfdd15654a873bab72f15204935212f126e32640c7a2216a7760220fe25f334fdb64fd7b9f85b9102dfa8d6c5d",
          "sha256": "b08d971ad2a625c024de6248c4b027d3aa5f075d59f9d26fb68baf195f4ac933",
          "sha1": "089db92962f48f72d05e1aa047286f30079ff83f",
          "md5": "aac2ed8c1e00949edb48477b9dc3f75f"
        }
      ]
    }
  ]
}
