{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ImageCompress/1.0.0-beta05/ImageCompress-1.0.0-beta05.module",
    "group": "com.hailiao.util",
    "module": "ImageCompress",
    "version": "1.0.0-beta05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ImageCompress.klib",
          "url": "ImageCompress-iosarm64-1.0.0-beta05.klib",
          "size": 37551,
          "sha512": "2ba7918ed8a820854095f474d61e82bafb0a6aaa73761669d4b16a9e98c162d808842c64cd0feb732ba886b1b93e679d92f3c56af674bcddaf3ba013a57966a8",
          "sha256": "a075b41d25990312d8443f395e7bbdb95816040438f2c75d2a8a6a89dd9b85dd",
          "sha1": "03fb9a18fd96785d23f997cecc11a2711476e399",
          "md5": "115a32d64dac73d2c59c7f699774e25a"
        },
        {
          "name": "ImageCompress-cinterop-ImageCompress.klib",
          "url": "ImageCompress-iosarm64-1.0.0-beta05-cinterop-ImageCompress.klib",
          "size": 267434,
          "sha512": "45e0313e50896b1d6cc65b67251159ace9b80249dbe27eb67d46d58a4cd228469d5f1bb4a3dce82f25250016cd51f24d74121ccc560f88f0067386344e046c89",
          "sha256": "fda78a1fb1f256fec0b8669605406c0a0fa7c1b9bcd9eaf55b32d8c144299d31",
          "sha1": "7c2d9a57ef891ec4dc993b76eba96e65623610b0",
          "md5": "2d23ddcc1d7b81bcab3d70f2bcddde7a"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ImageCompress-iosarm64-1.0.0-beta05-sources.jar",
          "url": "ImageCompress-iosarm64-1.0.0-beta05-sources.jar",
          "size": 11258,
          "sha512": "001bfb596a7fe7401df5ba70a46826a469843aac5d99370eff4e1a89a4e143896e5c480e2155e91c5ce05750094eeb52ad445a7c6e02a1056b6f2f4a05016704",
          "sha256": "5c325f0ac5eb9075c28d0e7e020ee46f4ee9bf956c100767af82cdf6efe9547f",
          "sha1": "d028c6fe0b2e47f40efb9bf1d1f3590e02d39033",
          "md5": "fb0e9028d811ec85685aacf5fcadd1be"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ImageCompress-iosarm64-1.0.0-beta05-metadata.jar",
          "url": "ImageCompress-iosarm64-1.0.0-beta05-metadata.jar",
          "size": 261,
          "sha512": "e9156c2190f295843d55b70a235edd76580d714d4d1efb1359e8232950e61b6a9fe3ed3baa8d2827f2243c4dfb7631e08a631053d949346ec997157eab02750c",
          "sha256": "5a5932227cad6c4ffc07e7b8fc5b3b182ac2a4cd1a65f7465f8f8295c6c3fcc1",
          "sha1": "77469ce1f91280be817654be1e27e580a4e4282f",
          "md5": "c026044bde2c127c50a112112bbfaa59"
        }
      ]
    }
  ]
}
