{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLCommonUtil/0.6.0/DLCommonUtil-0.6.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLCommonUtil",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-linuxArm64Main-0.6.0.klib",
          "url": "DLCommonUtil-linuxarm64-0.6.0.klib",
          "size": 302329,
          "sha512": "cf95e3bf162da9c5deba5ff018728a9ec6e4b59788451b9b312ea46f4c48ee5625f73274edbe64d232feded0a394672ad37dc78f7d0e04197054d89e4e7d37e9",
          "sha256": "9ee821a82ba85fc25f5c4f19a92289bc155154bff7a4180065564425b9f5ab8e",
          "sha1": "8bffa7ab27bab43d623d12a83405546eaf4cd0e7",
          "md5": "b11e5d57d130276db1f088c25d5b4fe9"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLCommonUtil-linuxarm64-0.6.0-sources.jar",
          "url": "DLCommonUtil-linuxarm64-0.6.0-sources.jar",
          "size": 195653,
          "sha512": "5c4404daa74dcadbe14081fd86389b59a9dc04026d119dedc011c2b0577ce44588d495c95aff1411b6adf994aea3a712b42e4bfdfffd5649518d21beb54aaa67",
          "sha256": "69c18027514d56513ff34b50f45eeed0b55896e9c1c3fd36787351c5c0944135",
          "sha1": "5438c13b7e2fca96593f6c9e2eb62aa7fd3749da",
          "md5": "f2d2eadb79cba12df0c0c449586e018e"
        }
      ]
    }
  ]
}
