{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLCommonUtil/0.8.0/DLCommonUtil-0.8.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLCommonUtil",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-iosArm64Main-0.8.0.klib",
          "url": "DLCommonUtil-iosarm64-0.8.0.klib",
          "size": 308559,
          "sha512": "2356b8d48c6fab34ca8833df80dbe1bc970a319d1c4660f5e4083d017f6592149958ac06e59c53e1454648d10b510a0137058a42aca1ed75a22e3f0fd3cea4c1",
          "sha256": "dd6004772f83a348646be0c87440b02fd60c488dd8986ed9581c5206c1274604",
          "sha1": "76d00eb78d1e999b5bd911f5cd3338861d43cf88",
          "md5": "b98ff6fe632386533c230350d1ceb599"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLCommonUtil-iosarm64-0.8.0-sources.jar",
          "url": "DLCommonUtil-iosarm64-0.8.0-sources.jar",
          "size": 197110,
          "sha512": "f0af423b58d6de35a4e89409fd8b3eddca3cd0edbf93383f7ea89a93f32963d60a60db237f5cc593e796927af2c0768fe775e7a3d98e4ac76accf6111962687d",
          "sha256": "ce1d824dd30881fdc331cbf09a0dba274061afefd43f79c3f0f26cdb55386a16",
          "sha1": "36d62d8afd00f41460789b3b88f6ffd66c1d646d",
          "md5": "2b29ea8515dbd3cd102f4c9200e5b56e"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-iosarm64-0.8.0-metadata.jar",
          "url": "DLCommonUtil-iosarm64-0.8.0-metadata.jar",
          "size": 3796,
          "sha512": "86e829f9db2495baeabb0486a9c4222343f019b6921672e183eae33e95166d9e38f7079304961dd225f5723f220cc6c34ce147992f4fbc22ee823b9ad2a5786f",
          "sha256": "03dc4aee1b404d6e57956faa89cca6cd2a3ff095a99d1f802ccdb4bde689f320",
          "sha1": "cf1ca981b6bfa6f823d17ca4a665bd7066297006",
          "md5": "502305086c7dd03f5b9556fa3886fe65"
        }
      ]
    }
  ]
}
