{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/1.8.6/DLDateUtil-1.8.6.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "1.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil.klib",
          "url": "DLDateUtil-iosarm64-1.8.6.klib",
          "size": 57844,
          "sha512": "af132c3367ddcc042f0279fbcb750c3c722d199cdc0aa3fdd0ba6ac841fd38b9f169f9bdf47e8b4c74271a3ec685d329ddd697f496ebcdc9342be400ce75e38e",
          "sha256": "77965aef0d43ad83f7966917a18cbc78b8acde910c4e3b79e1047bf5acd4dd72",
          "sha1": "9e10f1f43a5c89dfa8442ba48d40735f1c92691b",
          "md5": "87ceed16d622c02e533bb37fb849d9dd"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLDateUtil-iosarm64-1.8.6-sources.jar",
          "url": "DLDateUtil-iosarm64-1.8.6-sources.jar",
          "size": 11910,
          "sha512": "108bb3c148c15c16b4e240f2b11b8e20b6d7c94d6680034575999a56e166543c25e36f492bda7573695677f253071aae06e64b1ac6632f64e85fd8eaae28f0bf",
          "sha256": "5ebddfab1c84e1378c93f70a6b8be3d13a70603499e1be8db161532792516fa9",
          "sha1": "0b214b743f647748b262ec9ec3f56214c225ee52",
          "md5": "06ed913039b6a285aa1a38df9d1371ee"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-iosarm64-1.8.6-metadata.jar",
          "url": "DLDateUtil-iosarm64-1.8.6-metadata.jar",
          "size": 261,
          "sha512": "9b97204f3df50a5765db6647dd0c45e763217720835a817f536d208cd1bdbbf6816c206e91f88a658fc2eadd1d9020b7900d3841a978e0497d59b7d53e2e21db",
          "sha256": "1b6eb41d38eaa176f9b46d63317eab6a712d410dec4c2180e791b9bfa83f9aba",
          "sha1": "f1469c361b047c566184e14f5c6f91297a495650",
          "md5": "4adfa555cc22aaf99e45461ed44bec88"
        }
      ]
    }
  ]
}
