{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hailiao.util",
    "module": "ImageCompress",
    "version": "1.0.0-beta15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ImageCompress-metadata-1.0.0-beta15.jar",
          "url": "ImageCompress-1.0.0-beta15.jar",
          "size": 5320,
          "sha512": "8bf2b3c4eb22cde557899378f1bc0730b70788175b55e4ed2b009c7c2dc9a265b1bfda6378b399154366e2aa4eef59d9ead63971475c33ca4199a3ecb2813a75",
          "sha256": "7ce63a556346b06dc0c7dc20a96bf3eb92119f6cedee787715dc8ff56d24ac2b",
          "sha1": "cf1ce36e2684bdb7156e055e6abbbdb7302f73fc",
          "md5": "8f23b69a32ccfbd6ec12ceddba59a786"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ImageCompress-kotlin-1.0.0-beta15-sources.jar",
          "url": "ImageCompress-1.0.0-beta15-sources.jar",
          "size": 6314,
          "sha512": "fd3f0f4de3e559716466a47d01618762956b03e4b392e1cbf969c1cecde636e099b921f49ad6c7ae08dd3c221a60564217df3280fd921abab85d71a766d6de51",
          "sha256": "86c91b3fb0405f79e5e5b436a3139818f546b899889eed1413d6f32b57be1f92",
          "sha1": "49df22b4daea31b88d9590e9b62a50b9ad66f5c6",
          "md5": "a2d460e45a92151c38ac7edfced371ea"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ImageCompress-android/1.0.0-beta15/ImageCompress-android-1.0.0-beta15.module",
        "group": "com.hailiao.util",
        "module": "ImageCompress-android",
        "version": "1.0.0-beta15"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ImageCompress-android/1.0.0-beta15/ImageCompress-android-1.0.0-beta15.module",
        "group": "com.hailiao.util",
        "module": "ImageCompress-android",
        "version": "1.0.0-beta15"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ImageCompress-android/1.0.0-beta15/ImageCompress-android-1.0.0-beta15.module",
        "group": "com.hailiao.util",
        "module": "ImageCompress-android",
        "version": "1.0.0-beta15"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ImageCompress-iosarm64/1.0.0-beta15/ImageCompress-iosarm64-1.0.0-beta15.module",
        "group": "com.hailiao.util",
        "module": "ImageCompress-iosarm64",
        "version": "1.0.0-beta15"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ImageCompress-iosarm64/1.0.0-beta15/ImageCompress-iosarm64-1.0.0-beta15.module",
        "group": "com.hailiao.util",
        "module": "ImageCompress-iosarm64",
        "version": "1.0.0-beta15"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ImageCompress-iosarm64/1.0.0-beta15/ImageCompress-iosarm64-1.0.0-beta15.module",
        "group": "com.hailiao.util",
        "module": "ImageCompress-iosarm64",
        "version": "1.0.0-beta15"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ImageCompress-jvm/1.0.0-beta15/ImageCompress-jvm-1.0.0-beta15.module",
        "group": "com.hailiao.util",
        "module": "ImageCompress-jvm",
        "version": "1.0.0-beta15"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ImageCompress-jvm/1.0.0-beta15/ImageCompress-jvm-1.0.0-beta15.module",
        "group": "com.hailiao.util",
        "module": "ImageCompress-jvm",
        "version": "1.0.0-beta15"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ImageCompress-jvm/1.0.0-beta15/ImageCompress-jvm-1.0.0-beta15.module",
        "group": "com.hailiao.util",
        "module": "ImageCompress-jvm",
        "version": "1.0.0-beta15"
      }
    }
  ]
}
