{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLLatLngUtil/1.7.0/DLLatLngUtil-1.7.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLLatLngUtil",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil-js-1.7.0.klib",
          "url": "DLLatLngUtil-js-1.7.0.klib",
          "size": 62122,
          "sha512": "f58a8727f86f4675c174b1e64df7748814cab9939cb9629cd6ac93f75a482195743a2f7ba24413c7e74bf00339c9d6e2697f1fff58ea45f4e25d2e65575839aa",
          "sha256": "22969f7b327b0abd25d169328b156a8ee79b7fd2c60a492da54e209af8297dcb",
          "sha1": "44276fa5035f4b0a197b4e472252712f9fb916c7",
          "md5": "078e755398c72a570f0a2dc96bce0aca"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil-js-1.7.0.klib",
          "url": "DLLatLngUtil-js-1.7.0.klib",
          "size": 62122,
          "sha512": "f58a8727f86f4675c174b1e64df7748814cab9939cb9629cd6ac93f75a482195743a2f7ba24413c7e74bf00339c9d6e2697f1fff58ea45f4e25d2e65575839aa",
          "sha256": "22969f7b327b0abd25d169328b156a8ee79b7fd2c60a492da54e209af8297dcb",
          "sha1": "44276fa5035f4b0a197b4e472252712f9fb916c7",
          "md5": "078e755398c72a570f0a2dc96bce0aca"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "DLLatLngUtil-js-1.7.0-sources.jar",
          "url": "DLLatLngUtil-js-1.7.0-sources.jar",
          "size": 14827,
          "sha512": "b26e7136df1894d888b2f12e2e74c34a37d297916f689f186db6e55052ac7f90b4f448850cb1ad2b2d6ccc4daa36f765d740fc773054e5ac2941d37d459653aa",
          "sha256": "6b813e321fe518f00312024523fb5b21d3a3d6100cebc9314e2aa8fb9214e3ed",
          "sha1": "b52b15eef847b1b4bcac396d514dd7ec5e2d0837",
          "md5": "f3e617b94fd0c111d3f8fcf895087f4f"
        }
      ]
    }
  ]
}
