{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/2.3.0-alpha01/DLDateUtil-2.3.0-alpha01.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "2.3.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-macosX64Main-2.3.0-alpha01.klib",
          "url": "DLDateUtil-macosx64-2.3.0-alpha01.klib",
          "size": 92666,
          "sha512": "fc79df3451eacb1e91ef8403917215cf22477b24e83ad961f5fc7f197695aecd44c341f05f447d6510f4126603849e78ae3f72aae1217047a21bb7efb43c6114",
          "sha256": "003096ed57bc948293a7eec64bc3888ff0627970bf6a3ab7df38b4d68bc9b17e",
          "sha1": "c9a45248907619d11ad2648fb0b508f76e63b371",
          "md5": "6555a1362b05b1e826e47aac6ef93387"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLDateUtil-macosx64-2.3.0-alpha01-sources.jar",
          "url": "DLDateUtil-macosx64-2.3.0-alpha01-sources.jar",
          "size": 20711,
          "sha512": "1a7e2c8a7d2d19933ecf19c7c3b0f11c25e7608b4dedd5b086e4f5d789dd4aa4d9f9dd62c04193cda628ad50f2c9054fa2f3ce25a32231edb209722cc1f45861",
          "sha256": "3226355c59e086e941ccde3df5dc183c94fee93de7e471d1f0dc38165205d03e",
          "sha1": "6b6911ce395d0504143be31a704f369eb86dd172",
          "md5": "3373755ef4b3167533a70abb517304c3"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-macosx64-2.3.0-alpha01-metadata.jar",
          "url": "DLDateUtil-macosx64-2.3.0-alpha01-metadata.jar",
          "size": 261,
          "sha512": "6269f438bee552ec6440f6d431adc6c684d2bec58d1e567eab1428b91db7ee230d0f9e21b20182852be415c167a4c1fe373884556162bb9c6f469fe1ac6d783e",
          "sha256": "b16f58e34aaeeeae447d6f3c1b5c5fc0a3cb9a83ec9536ecbc78e1f57f7175be",
          "sha1": "8608a5996877cf5abc623834382b497608c9add6",
          "md5": "62f4006be5d1d17bbbd1bebffc734dc2"
        }
      ]
    }
  ]
}
