{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hailiao.util",
    "module": "ImageCompress",
    "version": "1.0.0-beta05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ImageCompress-metadata-1.0.0-beta05.jar",
          "url": "ImageCompress-1.0.0-beta05.jar",
          "size": 5315,
          "sha512": "c08ceac1bc480dde68217c155c085277937ebc4471594adce8f7b97d93cf8f597329801bc437720deb74ea1d84e02a36b89bf23c40891f9639f4c31cc396e789",
          "sha256": "efd4bd606c2de81a96d58a4944af034a17846229847065b7ec4e1a180906eb67",
          "sha1": "ef3fa4ccefc651ae678b81e26e21a74fb162e800",
          "md5": "c8be00aa63d61f4d3109e6f4eb540124"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ImageCompress-kotlin-1.0.0-beta05-sources.jar",
          "url": "ImageCompress-1.0.0-beta05-sources.jar",
          "size": 6231,
          "sha512": "059f75608ab4921c0141aaf2f927522bd5fb3d759f02271fb98f2cc7a827c30997f81b5bbbf98c1bff7ab0b02b06a3975a1d187091022a1018b9f3e07e25daae",
          "sha256": "cc59b0c0bd2717742d413680fbcd4b0487427e2e7e08da151176de37ecdc93cf",
          "sha1": "9d7e8288a556aa20130821f5bc54a45e1bcb4f3c",
          "md5": "038193fe73b45315b5e1e5538f66bcb2"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ImageCompress-android/1.0.0-beta05/ImageCompress-android-1.0.0-beta05.module",
        "group": "com.hailiao.util",
        "module": "ImageCompress-android",
        "version": "1.0.0-beta05"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ImageCompress-android/1.0.0-beta05/ImageCompress-android-1.0.0-beta05.module",
        "group": "com.hailiao.util",
        "module": "ImageCompress-android",
        "version": "1.0.0-beta05"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ImageCompress-android/1.0.0-beta05/ImageCompress-android-1.0.0-beta05.module",
        "group": "com.hailiao.util",
        "module": "ImageCompress-android",
        "version": "1.0.0-beta05"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ImageCompress-iosarm64/1.0.0-beta05/ImageCompress-iosarm64-1.0.0-beta05.module",
        "group": "com.hailiao.util",
        "module": "ImageCompress-iosarm64",
        "version": "1.0.0-beta05"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ImageCompress-iosarm64/1.0.0-beta05/ImageCompress-iosarm64-1.0.0-beta05.module",
        "group": "com.hailiao.util",
        "module": "ImageCompress-iosarm64",
        "version": "1.0.0-beta05"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ImageCompress-iosarm64/1.0.0-beta05/ImageCompress-iosarm64-1.0.0-beta05.module",
        "group": "com.hailiao.util",
        "module": "ImageCompress-iosarm64",
        "version": "1.0.0-beta05"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ImageCompress-jvm/1.0.0-beta05/ImageCompress-jvm-1.0.0-beta05.module",
        "group": "com.hailiao.util",
        "module": "ImageCompress-jvm",
        "version": "1.0.0-beta05"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ImageCompress-jvm/1.0.0-beta05/ImageCompress-jvm-1.0.0-beta05.module",
        "group": "com.hailiao.util",
        "module": "ImageCompress-jvm",
        "version": "1.0.0-beta05"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ImageCompress-jvm/1.0.0-beta05/ImageCompress-jvm-1.0.0-beta05.module",
        "group": "com.hailiao.util",
        "module": "ImageCompress-jvm",
        "version": "1.0.0-beta05"
      }
    }
  ]
}
