{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLCommonUtil/0.5.0/DLCommonUtil-0.5.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLCommonUtil",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0-RC.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil.klib",
          "url": "DLCommonUtil-linuxx64-0.5.0.klib",
          "size": 293533,
          "sha512": "64157db65b8a11a309327e3a38b9e95177a01604997f7117dc7a85f138dfc3562d22307cc7afb5e3dbb4b320b94896a70b539665921dc167f198435baf0ac939",
          "sha256": "a64457bb11b5dc311fddefd6b4dc30ec6bf94bbc9aaff73c17951c09aed3f0be",
          "sha1": "c0033f8af6ee12d33fd2ab54bb06a2e1c759c650",
          "md5": "9d1a71db9df923cdfef7cc9d5cf171a6"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLCommonUtil-linuxx64-0.5.0-sources.jar",
          "url": "DLCommonUtil-linuxx64-0.5.0-sources.jar",
          "size": 189671,
          "sha512": "da0141f47f4982edc111a9eba89ee2d2aa025f1165aa0356692eb09a8f63626c283833b4b9e5b5dda878365d2790f8584b6eb20cc2bc188c7db5bca1ed6636b0",
          "sha256": "dedbdf96d9add1b4ceb9836c398416e4bf679210fae37f916fe9134cfdbcad98",
          "sha1": "08078510b74e82f8cd90a0dcd2d78f214ba4e5dc",
          "md5": "67a1912b7ee884decc66f12a82881b23"
        }
      ]
    }
  ]
}
