{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ImageCompress/1.0.0-beta06/ImageCompress-1.0.0-beta06.module",
    "group": "com.hailiao.util",
    "module": "ImageCompress",
    "version": "1.0.0-beta06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ImageCompress-jvm-1.0.0-beta06.jar",
          "url": "ImageCompress-jvm-1.0.0-beta06.jar",
          "size": 763617,
          "sha512": "f9531af91fb0beebd42d2ae03658a6d38a1d77a37c67b2e3e8082921213b0daf94077bb3d82157f79a6bd42af68b2a51fdfabf10e5815c9dd301ba70c434e3aa",
          "sha256": "4d39f5432c89398fc9e35a7055ba51e79966a3b8499b2fb688ac546a48bd4869",
          "sha1": "030a6d8bed1a4eb160c6f07c3b0f68f3d6096a46",
          "md5": "6136298e2431425828bf5ab4e74224c1"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ImageCompress-jvm-1.0.0-beta06.jar",
          "url": "ImageCompress-jvm-1.0.0-beta06.jar",
          "size": 763617,
          "sha512": "f9531af91fb0beebd42d2ae03658a6d38a1d77a37c67b2e3e8082921213b0daf94077bb3d82157f79a6bd42af68b2a51fdfabf10e5815c9dd301ba70c434e3aa",
          "sha256": "4d39f5432c89398fc9e35a7055ba51e79966a3b8499b2fb688ac546a48bd4869",
          "sha1": "030a6d8bed1a4eb160c6f07c3b0f68f3d6096a46",
          "md5": "6136298e2431425828bf5ab4e74224c1"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ImageCompress-jvm-1.0.0-beta06-sources.jar",
          "url": "ImageCompress-jvm-1.0.0-beta06-sources.jar",
          "size": 10444,
          "sha512": "6867877b546169b86a854143684a671df7a822793bfc5b112a69012db25ad6bffcce1fae95c3c7ff1088020aa40d4610452afd63b1152183323c109ca536e6e3",
          "sha256": "f91ec4603e2b5d1f7ea4b2a96fbef7a1e78a44c11840d30c2460659b749ad5f3",
          "sha1": "483f25c2a29aa99cb6d7dda335783821f6c9f22d",
          "md5": "23409799488cd11b5676b3492473ea0d"
        }
      ]
    }
  ]
}
