{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLAppUtil",
    "version": "2.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLAppUtil-2.4.5.aar",
          "url": "DLAppUtil-2.4.5.aar",
          "size": 104278,
          "sha512": "2f57e3d1dc0dba265d5d040441f9bbf5f01a7a9839e89afe7128910e886894027d677b0fa3ba5d06a4024064e69a18a7486317386ea6974a6acb31ea909e4049",
          "sha256": "b5426455883b2e441bc3e1f85e49a50db72fdb580bd0958bae86a77e881d3aeb",
          "sha1": "b6bb7fe6b92ecaf57abf71f31f2c719acc13e80f",
          "md5": "2de8beec4effe557c83be677bf612198"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLAppUtil-2.4.5.aar",
          "url": "DLAppUtil-2.4.5.aar",
          "size": 104278,
          "sha512": "2f57e3d1dc0dba265d5d040441f9bbf5f01a7a9839e89afe7128910e886894027d677b0fa3ba5d06a4024064e69a18a7486317386ea6974a6acb31ea909e4049",
          "sha256": "b5426455883b2e441bc3e1f85e49a50db72fdb580bd0958bae86a77e881d3aeb",
          "sha1": "b6bb7fe6b92ecaf57abf71f31f2c719acc13e80f",
          "md5": "2de8beec4effe557c83be677bf612198"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLAppUtil-2.4.5-sources.jar",
          "url": "DLAppUtil-2.4.5-sources.jar",
          "size": 33197,
          "sha512": "815e8ac14b29626545fd009bdfa63887da409fd29deafdfa2c6dfc7bc7d17f648aa9aab2ca3902337a983192edf530dabd8623b68ccf46738eb069eaf128adae",
          "sha256": "7dda3683a15d5c7befb99a7d8181f60c604fe86e10a002580614bef72e007623",
          "sha1": "2c9b0af89cc9fae72ecd6ba7666f6005386d1167",
          "md5": "33d642ed8326f199b59b19e8df280ed8"
        }
      ]
    }
  ]
}
