{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLSerialPortUtil/0.1.0/DLSerialPortUtil-0.1.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLSerialPortUtil",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "DLSerialPortUtil-linuxArm64Main-0.1.0.klib",
          "url": "DLSerialPortUtil-linuxarm64-0.1.0.klib",
          "size": 33129,
          "sha512": "73b1a44c7450c8b6b4df1a67424a8f827baf6cbed1c74d17e2e0e54426425096df58a52e51f8151513b3b382e47cdbbebd6da076c137a6b39a5b91b4f45c4db9",
          "sha256": "556b022afc47287fd9faa5375ab0c7abd6b281661fd6a9d82546cf8b7317f67c",
          "sha1": "5cd45ca30836a8d497b4c22c425135282cf16d0c",
          "md5": "0c5810045546a50c94444ae0e727c523"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLSerialPortUtil-linuxarm64-0.1.0-sources.jar",
          "url": "DLSerialPortUtil-linuxarm64-0.1.0-sources.jar",
          "size": 8059,
          "sha512": "a920dc6315ff640272ceaad2f22bfdbd85f246839e69bebdb11b9abd8097ce4a4b0fa3e7cca7220f1674837f4d4b0c40aaa73078bbe560740746719774acd5f0",
          "sha256": "a1abaa51fe827a76a75834715f017c9550bae46d2776921ac914ee3f9363f5c6",
          "sha1": "6337b9071a94c352cc16d5e078190505478b8bf1",
          "md5": "3b4bbe77ca1b85d96f8295fd7da90704"
        }
      ]
    }
  ]
}
