{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLBluetoothUtil",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLBluetoothUtil-metadata-0.5.0.jar",
          "url": "DLBluetoothUtil-0.5.0.jar",
          "size": 6544,
          "sha512": "67f5a770204186954f6581ce7a5c851008d1eda98f85c82d82f8a1961805aabf34c72a9d4ccad7ec2f122bcc72b31c88b7e3c77ec14b4cac0949fba16722b630",
          "sha256": "2e6d8bede37ab246c8b58c1e0710a96510d64738fc06f891a922b52c087059d3",
          "sha1": "5540ea0c6d55d307f65f2804582f0c643c7e7edc",
          "md5": "c533d3dc976aa8d1d4b408a14071b7c5"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "DLBluetoothUtil-kotlin-0.5.0-sources.jar",
          "url": "DLBluetoothUtil-0.5.0-sources.jar",
          "size": 5490,
          "sha512": "0c9e4191729104dbe557adf634e44ee0a41afb7f3574ae1d6299b767929dfab421f5b2a1e59a36d5bc32be1d7165c61a3d35d6fe9cbe345af16add9eb35ab40b",
          "sha256": "f02c6d4ca9021262b961b9ac07f33c05398c928fb5f3840e2d3c6ef5d5713964",
          "sha1": "141f7a4ce92e6f088401d4cab46c9b3ad8122e3d",
          "md5": "47a51a24ba4d9ac3fb9c58f647337890"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLBluetoothUtil-android/0.5.0/DLBluetoothUtil-android-0.5.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLBluetoothUtil-android",
        "version": "0.5.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLBluetoothUtil-android/0.5.0/DLBluetoothUtil-android-0.5.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLBluetoothUtil-android",
        "version": "0.5.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLBluetoothUtil-android/0.5.0/DLBluetoothUtil-android-0.5.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLBluetoothUtil-android",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLBluetoothUtil-iosarm64/0.5.0/DLBluetoothUtil-iosarm64-0.5.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLBluetoothUtil-iosarm64",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLBluetoothUtil-iosarm64/0.5.0/DLBluetoothUtil-iosarm64-0.5.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLBluetoothUtil-iosarm64",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLBluetoothUtil-iosarm64/0.5.0/DLBluetoothUtil-iosarm64-0.5.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLBluetoothUtil-iosarm64",
        "version": "0.5.0"
      }
    }
  ]
}
