{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLJetpackComposeUtil",
    "version": "2.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2023.09.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.0-alpha12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-2.0.2.aar",
          "url": "DLJetpackComposeUtil-2.0.2.aar",
          "size": 915646,
          "sha512": "633ff0e3f01f64f04328cd1eebafed2f1d908c83245af3d7e8cf58cfcc4587915aea082fb1cce7dc0035ba4066a3e4206b4da3197aa997a71d999c477fc4f66e",
          "sha256": "0728b14b2117f8fcffc629c736c74aaf68d81104d26cc1d61a7b4ca017e8c14a",
          "sha1": "7a54646df79266ebe4431f1140464cae9d86af7a",
          "md5": "942cb01353b0ecd5f672b0da320c94d0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.github.raamcosta.compose-destinations",
          "module": "animations-core",
          "version": {
            "requires": "1.9.53"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLDateUtil",
          "version": {
            "requires": "1.8.5"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2023.09.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.0-alpha12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-2.0.2.aar",
          "url": "DLJetpackComposeUtil-2.0.2.aar",
          "size": 915646,
          "sha512": "633ff0e3f01f64f04328cd1eebafed2f1d908c83245af3d7e8cf58cfcc4587915aea082fb1cce7dc0035ba4066a3e4206b4da3197aa997a71d999c477fc4f66e",
          "sha256": "0728b14b2117f8fcffc629c736c74aaf68d81104d26cc1d61a7b4ca017e8c14a",
          "sha1": "7a54646df79266ebe4431f1140464cae9d86af7a",
          "md5": "942cb01353b0ecd5f672b0da320c94d0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLJetpackComposeUtil-2.0.2-sources.jar",
          "url": "DLJetpackComposeUtil-2.0.2-sources.jar",
          "size": 63319,
          "sha512": "026fb06b9427af15dac9c5fa3e0915539fbb7ce2ea1980f81d9986c151c78a7a1a2d3d33d68b9a5b0644810e9311055fb0c1daf9631229503e6fbd892ba0a9f4",
          "sha256": "49e395464fe7f7cc6f2ebff3c50b16bc458743b9fa31f2c6c27c177bc1dc971e",
          "sha1": "4077d54de5e44fecba36952cf4eed968ebea6603",
          "md5": "0dc9a16a53d44c64355b79e45a9cf6c6"
        }
      ]
    }
  ]
}
