{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLSerialPortUtil/0.3.1/DLSerialPortUtil-0.3.1.module",
    "group": "com.github.D10NGYANG",
    "module": "DLSerialPortUtil",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "DLSerialPortUtil-macosX64Main-0.3.1.klib",
          "url": "DLSerialPortUtil-macosx64-0.3.1.klib",
          "size": 34255,
          "sha512": "bce79858ac269e66c2b7714129a76a19ed8a4b0b114ad5f2be9b06bba361d1e947d34b1f7f7006a6f55282e8e52f58eefeb89c4dd89c892ece8bea715897141a",
          "sha256": "27a91a1dbc6f5ab2162f015f39e206946c5ca9097a352626f98e880cab9d5642",
          "sha1": "839ec0e7dfd5d81c7e3ebbc49b8c3eeb4b7bc76d",
          "md5": "c0c5e18d737e2ec84d24744cc20eee2f"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLSerialPortUtil-macosx64-0.3.1-sources.jar",
          "url": "DLSerialPortUtil-macosx64-0.3.1-sources.jar",
          "size": 8583,
          "sha512": "ffd9e3c57d8f1cc0042f46388479ae6696be4ccca3a14b7717fb3c2a4d336aca5ca392843ee50b2b2aa30b55d62c3585bc27d5fb392b61e3b9004293b26b5a2d",
          "sha256": "2a7691514d97931e0f0e98c89cab960352742ddef1c2c665304f4eeb3cc48171",
          "sha1": "b4664efaaf673b5c4546f96974bfc4d48c4eed86",
          "md5": "ee2a5714e6389926037396e9ab6dfea0"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "DLSerialPortUtil-macosx64-0.3.1-metadata.jar",
          "url": "DLSerialPortUtil-macosx64-0.3.1-metadata.jar",
          "size": 4349,
          "sha512": "5c97fd00d566c8ede5dee17931467736d67184e128cddb0adad9e6bc616438c541313c0d81b13ebf09fba89560085127db43b850b74a66bb5bb3e248aea86bcc",
          "sha256": "c634e441b4ae05ec521ecf70067b96fba472bb011b65d2a71485efffc1eef793",
          "sha1": "0e94f56f069b7f7dcced6fe4410539def486fd84",
          "md5": "d142b5e7fc3f1bcff494115ef02e01d0"
        }
      ]
    }
  ]
}
