{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLAppUtil",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLAppUtil-2.4.0.aar",
          "url": "DLAppUtil-2.4.0.aar",
          "size": 90855,
          "sha512": "53d183b3b0323d3f58e3927dc5031703175a0e963639eed9427aa363ad3bda0dcbfe1fe528f699964acf8d06f418f71d5f6de10ccd87b8cc9db7ebdf3bbc567c",
          "sha256": "e6adc796e958847c0d5e3a6a58f3f4359b9061ad1726b3360066962f545bcb56",
          "sha1": "9f3c57a93c82fceb3cccb572acaa8384c1526c1b",
          "md5": "4a1e2f3ed720b067e41617ae8f6571b9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLAppUtil-2.4.0.aar",
          "url": "DLAppUtil-2.4.0.aar",
          "size": 90855,
          "sha512": "53d183b3b0323d3f58e3927dc5031703175a0e963639eed9427aa363ad3bda0dcbfe1fe528f699964acf8d06f418f71d5f6de10ccd87b8cc9db7ebdf3bbc567c",
          "sha256": "e6adc796e958847c0d5e3a6a58f3f4359b9061ad1726b3360066962f545bcb56",
          "sha1": "9f3c57a93c82fceb3cccb572acaa8384c1526c1b",
          "md5": "4a1e2f3ed720b067e41617ae8f6571b9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLAppUtil-2.4.0-sources.jar",
          "url": "DLAppUtil-2.4.0-sources.jar",
          "size": 29916,
          "sha512": "b9c58e9291553623a6f42c1d3a66b77b054d3bc02d97881fc3436a6a82476233ba182b8333c1a4e6e02e7659619dd162e1c04f65dc59f05560620906aabef3e9",
          "sha256": "892c2c0247c026294a0fb283053c94dbc184232f462da9f73d3bfb17b22843f7",
          "sha1": "5073715aa36301835c4e6754ac83914db417e577",
          "md5": "c21e840b5beea6792f2469e4cd703cfc"
        }
      ]
    }
  ]
}
