{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/2.0.0/DLDateUtil-2.0.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil.klib",
          "url": "DLDateUtil-linuxx64-2.0.0.klib",
          "size": 60389,
          "sha512": "4e602561dcc41d1bc4cb85151a3f721f478bf5616703922951d78c0001735ca736c5d0a71de4af2cd7c27a5bd5bf377212ee3a42a757f42201b828d5f7e529b5",
          "sha256": "627c7241068c7dbb20f10dd35632d9e8acc22269c2e96360c4a0346a78ca5981",
          "sha1": "89309524a53b46939ea8f9c813069399c370ef50",
          "md5": "0c3f010d0889b8a92676cde0c2581b1f"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLDateUtil-linuxx64-2.0.0-sources.jar",
          "url": "DLDateUtil-linuxx64-2.0.0-sources.jar",
          "size": 11809,
          "sha512": "ea24f10dc8a5188c1d85b6e5ef2923981267b1637d1ea93f0db5b16ced012a2492114cadbe499edd71d21f25a5d58a3dbff605f9c7633c75c4958cb35e9dd4cf",
          "sha256": "5e697495954e3d8372f25f09fc7e23e8d63052f7c68ec7bb4bcd3fd948e4e0a2",
          "sha1": "b32b254f6a56032ae2491674fce7f99506dbce91",
          "md5": "8da7f0d3f956d1700fa3513a283e2ffa"
        }
      ]
    }
  ]
}
