{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/2.0.0/DLDateUtil-2.0.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-jvm-2.0.0.jar",
          "url": "DLDateUtil-jvm-2.0.0.jar",
          "size": 28518,
          "sha512": "42ce455cfbfcff5216e75e299448e9124aa36185ed407ffa4989c3377b0b5a1131d51479fc618e0a6646d9851d87e59b9ec7f1fc6649a3b7382dd62edef960b5",
          "sha256": "45b38bcb8158d1bb0d77c50fde1c8e01192a7be423536e36293843df9aa08911",
          "sha1": "f306fd4d70b5758271c358074becc9ab384411a6",
          "md5": "23aab990725921ba8078eb1f91e14810"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-jvm-2.0.0.jar",
          "url": "DLDateUtil-jvm-2.0.0.jar",
          "size": 28518,
          "sha512": "42ce455cfbfcff5216e75e299448e9124aa36185ed407ffa4989c3377b0b5a1131d51479fc618e0a6646d9851d87e59b9ec7f1fc6649a3b7382dd62edef960b5",
          "sha256": "45b38bcb8158d1bb0d77c50fde1c8e01192a7be423536e36293843df9aa08911",
          "sha1": "f306fd4d70b5758271c358074becc9ab384411a6",
          "md5": "23aab990725921ba8078eb1f91e14810"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "DLDateUtil-jvm-2.0.0-sources.jar",
          "url": "DLDateUtil-jvm-2.0.0-sources.jar",
          "size": 11809,
          "sha512": "ea24f10dc8a5188c1d85b6e5ef2923981267b1637d1ea93f0db5b16ced012a2492114cadbe499edd71d21f25a5d58a3dbff605f9c7633c75c4958cb35e9dd4cf",
          "sha256": "5e697495954e3d8372f25f09fc7e23e8d63052f7c68ec7bb4bcd3fd948e4e0a2",
          "sha1": "b32b254f6a56032ae2491674fce7f99506dbce91",
          "md5": "8da7f0d3f956d1700fa3513a283e2ffa"
        }
      ]
    }
  ]
}
