{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/2.3.1/DLDateUtil-2.3.1.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "2.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-js-2.3.1.klib",
          "url": "DLDateUtil-js-2.3.1.klib",
          "size": 95558,
          "sha512": "a9baa27bc17c857cc14ce3087f75cf654952ab1bb8b9d0fe8d99c6321728c9928ed6a5268424de6fe51877eb754d7e0580d991ac69adfeed384536cadc5a9894",
          "sha256": "c7473f289d9f207d6b9492e027833f5812ce6d0c4da7b90cb71f06caf5fd7c08",
          "sha1": "25dfa5b25b60745c06f5edeb363967f642f7c24f",
          "md5": "a9b72d5d0e26036da7886351a5bcd2d9"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-js-2.3.1.klib",
          "url": "DLDateUtil-js-2.3.1.klib",
          "size": 95558,
          "sha512": "a9baa27bc17c857cc14ce3087f75cf654952ab1bb8b9d0fe8d99c6321728c9928ed6a5268424de6fe51877eb754d7e0580d991ac69adfeed384536cadc5a9894",
          "sha256": "c7473f289d9f207d6b9492e027833f5812ce6d0c4da7b90cb71f06caf5fd7c08",
          "sha1": "25dfa5b25b60745c06f5edeb363967f642f7c24f",
          "md5": "a9b72d5d0e26036da7886351a5bcd2d9"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "DLDateUtil-js-2.3.1-sources.jar",
          "url": "DLDateUtil-js-2.3.1-sources.jar",
          "size": 21624,
          "sha512": "68f662243946d6013d5e25f49b9681079cf1fd6c20c874663a2e28552f80a9b58d22f182047db1c81b73d538d9b531871fa95a7a4ea66df0706367eee1c4343d",
          "sha256": "5e14b447c2e386a020c9b2fba327d8ae579e8d06b514d05ab422bf9243c0bda5",
          "sha1": "3ec2c0d2989a75a4b62b334a9804fc6e014de0ff",
          "md5": "7ffa1e0b344a39d1e0133d56aca43497"
        }
      ]
    }
  ]
}
