{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLCommonUtil/0.4.1/DLCommonUtil-0.4.1.module",
    "group": "com.github.D10NGYANG",
    "module": "DLCommonUtil",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-js-0.4.1.klib",
          "url": "DLCommonUtil-js-0.4.1.klib",
          "size": 291439,
          "sha512": "6ed79bf49e2118efb13483a5ace28fc0544ed448ef1ce10872e6c6e85b060c4cfb18e88dc6de186da69aff7a55efe77127733d5a4c9d416c18e3196e11f4f46e",
          "sha256": "4895ae35ee8de701a043808c0e5bb83a4ef57b8b87f8376fdd1819faed5859b6",
          "sha1": "3bcdff0bf28c756a80e56d5734d3df1c63560cec",
          "md5": "fd027743422e5c82a79d73267c34a004"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0-RC.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-js-0.4.1.klib",
          "url": "DLCommonUtil-js-0.4.1.klib",
          "size": 291439,
          "sha512": "6ed79bf49e2118efb13483a5ace28fc0544ed448ef1ce10872e6c6e85b060c4cfb18e88dc6de186da69aff7a55efe77127733d5a4c9d416c18e3196e11f4f46e",
          "sha256": "4895ae35ee8de701a043808c0e5bb83a4ef57b8b87f8376fdd1819faed5859b6",
          "sha1": "3bcdff0bf28c756a80e56d5734d3df1c63560cec",
          "md5": "fd027743422e5c82a79d73267c34a004"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "DLCommonUtil-js-0.4.1-sources.jar",
          "url": "DLCommonUtil-js-0.4.1-sources.jar",
          "size": 189848,
          "sha512": "e58766707ad62eaf2f09a7976bb2bd8a55131a9b2ca66ea2fee8b625817b6d25a1a5d99b8d8f175a866751571caa2a7f68566690eba9147a57b65f467f411b2a",
          "sha256": "8a3f29341bc78bada5ec1873771e3ac6c62fc4340b1ca88de1efefc5fd7243f4",
          "sha1": "8d6ecbe4b297f4f96423f3c3c33f12493841b6bf",
          "md5": "352fa295c3e9695ef7f7ae44ddb6aff9"
        }
      ]
    }
  ]
}
