{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hailiao.util",
    "module": "ImageCompress",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ImageCompress-metadata-1.0.0.jar",
          "url": "ImageCompress-1.0.0.jar",
          "size": 5320,
          "sha512": "8bf2b3c4eb22cde557899378f1bc0730b70788175b55e4ed2b009c7c2dc9a265b1bfda6378b399154366e2aa4eef59d9ead63971475c33ca4199a3ecb2813a75",
          "sha256": "7ce63a556346b06dc0c7dc20a96bf3eb92119f6cedee787715dc8ff56d24ac2b",
          "sha1": "cf1ce36e2684bdb7156e055e6abbbdb7302f73fc",
          "md5": "8f23b69a32ccfbd6ec12ceddba59a786"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ImageCompress-kotlin-1.0.0-sources.jar",
          "url": "ImageCompress-1.0.0-sources.jar",
          "size": 6317,
          "sha512": "a08de8d738bfe06668a86855351bbe29aecb2ea459d14fd6aef6d1196f24cc391b041644be0318065107ed3f32d85c4c294e41383d4c89b24c6f378f31f3a4e0",
          "sha256": "b88be094138713d5fbec8fe8c33b940bf692e2faf11f0e39b3bc7d0755d21acd",
          "sha1": "1ad7e8a32700d934e77fe4f729ee35259081241e",
          "md5": "34f55c7db1e030271e6d97a348c11ddd"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ImageCompress-android/1.0.0/ImageCompress-android-1.0.0.module",
        "group": "com.hailiao.util",
        "module": "ImageCompress-android",
        "version": "1.0.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ImageCompress-android/1.0.0/ImageCompress-android-1.0.0.module",
        "group": "com.hailiao.util",
        "module": "ImageCompress-android",
        "version": "1.0.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ImageCompress-android/1.0.0/ImageCompress-android-1.0.0.module",
        "group": "com.hailiao.util",
        "module": "ImageCompress-android",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ImageCompress-iosarm64/1.0.0/ImageCompress-iosarm64-1.0.0.module",
        "group": "com.hailiao.util",
        "module": "ImageCompress-iosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ImageCompress-iosarm64/1.0.0/ImageCompress-iosarm64-1.0.0.module",
        "group": "com.hailiao.util",
        "module": "ImageCompress-iosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ImageCompress-iosarm64/1.0.0/ImageCompress-iosarm64-1.0.0.module",
        "group": "com.hailiao.util",
        "module": "ImageCompress-iosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ImageCompress-jvm/1.0.0/ImageCompress-jvm-1.0.0.module",
        "group": "com.hailiao.util",
        "module": "ImageCompress-jvm",
        "version": "1.0.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ImageCompress-jvm/1.0.0/ImageCompress-jvm-1.0.0.module",
        "group": "com.hailiao.util",
        "module": "ImageCompress-jvm",
        "version": "1.0.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ImageCompress-jvm/1.0.0/ImageCompress-jvm-1.0.0.module",
        "group": "com.hailiao.util",
        "module": "ImageCompress-jvm",
        "version": "1.0.0"
      }
    }
  ]
}
