{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/1.8.1/DLDateUtil-1.8.1.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "1.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil.klib",
          "url": "DLDateUtil-iosarm64-1.8.1.klib",
          "size": 56636,
          "sha512": "255dcf88941081a87cb3a305f95e9528299269434a78c725ab7a429c00caaae092489481f51aaa86964ce6da8181644fa1ad633ad8b11da66fafe087d32ed54c",
          "sha256": "560270494c6398b14e7fe2155b486c846923f83e534e0ef6f83d09d870971c31",
          "sha1": "26af838b99a3534ed98ccd5b93471781fb9194f2",
          "md5": "bc587e4d58e154af2bce4d2f78b73cee"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLDateUtil-iosarm64-1.8.1-sources.jar",
          "url": "DLDateUtil-iosarm64-1.8.1-sources.jar",
          "size": 11373,
          "sha512": "3d877f11d865230c7177c53fd3abc20ade99c65adb16915e8492a9db80ed0112281cd215767a4b74705a1890f0470c850e632f2099d01c145e5e5a4cf266e2ca",
          "sha256": "83bfe469421c38653921fad26bac19bcae41128519d1275c84363db1f0d226e7",
          "sha1": "f99af8fa06a0161b9dd4b793ea0b660618f8ceac",
          "md5": "b00f0f014fe94b176c0aa2759eb83221"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-iosarm64-1.8.1-metadata.jar",
          "url": "DLDateUtil-iosarm64-1.8.1-metadata.jar",
          "size": 261,
          "sha512": "f9c4e5e7b9bb0a2b86b6f8364af1202eab66429cfefed8ef64c791bcc5e97a38c6dfddfe35f1ea134c995335429e78bc34fa7efaa134dc1f01fbdc285c82b4fa",
          "sha256": "d2a60fbce5cedb47beb29a0b9b43cc1e78bc347fe0388c69a60f738c116bfa1d",
          "sha1": "cab8764fd52b70b14df03a8ca157db9b1718e10a",
          "md5": "bb30d22340b63f79f08eef13bafebf1a"
        }
      ]
    }
  ]
}
