{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLTianDiTuApi",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "DLTianDiTuApi-metadata-0.5.1.jar",
          "url": "DLTianDiTuApi-0.5.1.jar",
          "size": 647,
          "sha512": "f9c081b46244233787a52aabb776722b019e9521c3a89a6b4e55a669be9cfee3411764e79d1de9563bc03c6e61e4fe541deee4b30affd96a14de6dd2fdca1dc9",
          "sha256": "089e24417bf9f6c34eec5720eebb2cbcc82ea2855ecef90133eb17e1079d5868",
          "sha1": "28cbbd267e2cdbea0a637d71db8f57b788a419c0",
          "md5": "ba0b1a9fde0b67f9902aec928b1936fb"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "DLTianDiTuApi-kotlin-0.5.1-sources.jar",
          "url": "DLTianDiTuApi-0.5.1-sources.jar",
          "size": 4908,
          "sha512": "b1661a72a79fbcafe14497aeb3f212e59218e2889c3cdc8be61f1aab10bcfc007c35a7d6779e6f9985b7191cfc2e2dd2909fdd7bf3ce93ba8ac78f5b79bdb89a",
          "sha256": "31c276faa513b9f0eb4d5d93ed8b16f87f628678014b6c85e1fab9843d11f585",
          "sha1": "77631559a4ba25e472e4f545bd9471e077da0ea2",
          "md5": "cecd1657a63d9f94384304200a38806c"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLTianDiTuApi-jvm/0.5.1/DLTianDiTuApi-jvm-0.5.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLTianDiTuApi-jvm",
        "version": "0.5.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLTianDiTuApi-jvm/0.5.1/DLTianDiTuApi-jvm-0.5.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLTianDiTuApi-jvm",
        "version": "0.5.1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLTianDiTuApi-jvm/0.5.1/DLTianDiTuApi-jvm-0.5.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLTianDiTuApi-jvm",
        "version": "0.5.1"
      }
    }
  ]
}
