{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/1.8.4/DLDateUtil-1.8.4.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "1.8.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-js-1.8.4.klib",
          "url": "DLDateUtil-js-1.8.4.klib",
          "size": 56709,
          "sha512": "05b8175bc44838240cc74c03b8a6c5a72c7a16ffb01736aa993cb23717462e6c02c0b3136f2024b4e96536cdb1ce1d5046aee53e18dcc8728ae569e9e5112573",
          "sha256": "c953f51e417e4c48966218bbc82bc90da894146b4c41419a45f5278392a148db",
          "sha1": "1857bd6695f1c5bdea4b064b670c66ef1dd77919",
          "md5": "50af33fc2300b10aa77912218bfca301"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-js-1.8.4.klib",
          "url": "DLDateUtil-js-1.8.4.klib",
          "size": 56709,
          "sha512": "05b8175bc44838240cc74c03b8a6c5a72c7a16ffb01736aa993cb23717462e6c02c0b3136f2024b4e96536cdb1ce1d5046aee53e18dcc8728ae569e9e5112573",
          "sha256": "c953f51e417e4c48966218bbc82bc90da894146b4c41419a45f5278392a148db",
          "sha1": "1857bd6695f1c5bdea4b064b670c66ef1dd77919",
          "md5": "50af33fc2300b10aa77912218bfca301"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "DLDateUtil-js-1.8.4-sources.jar",
          "url": "DLDateUtil-js-1.8.4-sources.jar",
          "size": 11917,
          "sha512": "6223841bfd57f64ff9251ac3a73a326cb3ebfc644f080db2405a6d85e645860eb9cdb9cc2bc2986fc798cc68af77e4bbdf5748cd51ed3938d7be562f719b3d99",
          "sha256": "332659b7002de14e0abe9aa60628acacdc538fc30e6e07e5b064582ec7e92c58",
          "sha1": "9be9596caa09686b5eba10516004b4ab0f71e097",
          "md5": "d3e6a8cf3381ad66762f8c354f2fbfb6"
        }
      ]
    }
  ]
}
