{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLCommonUtil/0.5.4/DLCommonUtil-0.5.4.module",
    "group": "com.github.D10NGYANG",
    "module": "DLCommonUtil",
    "version": "0.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil.klib",
          "url": "DLCommonUtil-macosarm64-0.5.4.klib",
          "size": 311093,
          "sha512": "0793fdf228ed7dcfdacafc00b0390d6a1061f3aeb49214c99e314f533f5c6167da4f989609e47c433d1f0527199e3946944349bd50f62ca1ff29407479682bbc",
          "sha256": "bddccfe6c67926d304ca96375868913d4c270c9f71ba2dc01b41d7acd3feacea",
          "sha1": "d3443828193760a975da917bd110b54f7dcedd56",
          "md5": "441fab4371d0e6ca93d535692a359afc"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLCommonUtil-macosarm64-0.5.4-sources.jar",
          "url": "DLCommonUtil-macosarm64-0.5.4-sources.jar",
          "size": 197040,
          "sha512": "084e22ed96ee1c5764096f15b1771121e8b86af0481d081d4c388aa3d5ed5fe3ef96d9380520cb29284136d112701b5d18d74c25a90bf62957a1abf994ac210a",
          "sha256": "2dfbce73a81858bd27818c63b8e7404e0c5bf0ad676a7f932bd11da9f011957f",
          "sha1": "19230a7af716e8671eb22a74b94fd50763b27feb",
          "md5": "96e50774c1c56b9e1c426f55c66c2680"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-macosarm64-0.5.4-metadata.jar",
          "url": "DLCommonUtil-macosarm64-0.5.4-metadata.jar",
          "size": 3943,
          "sha512": "f9f1955b60985682ca3aac763970c2ecb93afeecd70201900d40e7712e4648627962df1c09f5f3f73adfd25021f2905edbeeda9edcb04faf946a3c107917660e",
          "sha256": "5c4bcb77c662fb2116845dd9e93fc2be420b541b6b69cb7c6697565e57519321",
          "sha1": "ac7ef2fb1e0f19e79fd9cfac9f4da89840a78370",
          "md5": "ae222b1eec7545257f6dc0cb7bc78af6"
        }
      ]
    }
  ]
}
