{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLQRCodeUtil",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.0-alpha07"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "DLQRCodeUtil-0.0.6.aar",
          "url": "DLQRCodeUtil-0.0.6.aar",
          "size": 120647,
          "sha512": "592b99e27c9984a4d8a9f804f43589f3171e985c3d5ab8fa74c621c84f16af0b69ec8b2c9fb5581cf7887246c4f7588e5f0a1f81a726a660cfcdfc4886ac6ee9",
          "sha256": "10eb0da8cf383ae89be397993a07490c8dad0ec119fb0691e1667f9a8daac6fd",
          "sha1": "f6856739c55886093e224e03d5f53a8806cbed74",
          "md5": "90b2ebbcafb31b6dad56f19610fa7682"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLJetpackComposeUtil",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.0-alpha07"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "DLQRCodeUtil-0.0.6.aar",
          "url": "DLQRCodeUtil-0.0.6.aar",
          "size": 120647,
          "sha512": "592b99e27c9984a4d8a9f804f43589f3171e985c3d5ab8fa74c621c84f16af0b69ec8b2c9fb5581cf7887246c4f7588e5f0a1f81a726a660cfcdfc4886ac6ee9",
          "sha256": "10eb0da8cf383ae89be397993a07490c8dad0ec119fb0691e1667f9a8daac6fd",
          "sha1": "f6856739c55886093e224e03d5f53a8806cbed74",
          "md5": "90b2ebbcafb31b6dad56f19610fa7682"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLQRCodeUtil-0.0.6-sources.jar",
          "url": "DLQRCodeUtil-0.0.6-sources.jar",
          "size": 5261,
          "sha512": "3b7846dfc4b3c80ccf25edb70e17a86cf7676d03eab50f02eaf98b55211150ab443141622b1e898fa2719e6f22801516639772343934ab11cb1269b21f25a124",
          "sha256": "bd3d5a1e8177dabcf2961e054127fe77af55b4b35751195fb318c00390d4d5fa",
          "sha1": "e7b46e70670e9a26d8266578b4e7d3feb892b3ed",
          "md5": "7b44ee96c9c895b051ccbbffd6c689fb"
        }
      ]
    }
  ]
}
