{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLSerialPortUtil/0.3.0/DLSerialPortUtil-0.3.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLSerialPortUtil",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "DLSerialPortUtil-macosX64Main-0.3.0.klib",
          "url": "DLSerialPortUtil-macosx64-0.3.0.klib",
          "size": 34255,
          "sha512": "bce79858ac269e66c2b7714129a76a19ed8a4b0b114ad5f2be9b06bba361d1e947d34b1f7f7006a6f55282e8e52f58eefeb89c4dd89c892ece8bea715897141a",
          "sha256": "27a91a1dbc6f5ab2162f015f39e206946c5ca9097a352626f98e880cab9d5642",
          "sha1": "839ec0e7dfd5d81c7e3ebbc49b8c3eeb4b7bc76d",
          "md5": "c0c5e18d737e2ec84d24744cc20eee2f"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLSerialPortUtil-macosx64-0.3.0-sources.jar",
          "url": "DLSerialPortUtil-macosx64-0.3.0-sources.jar",
          "size": 8583,
          "sha512": "ffd9e3c57d8f1cc0042f46388479ae6696be4ccca3a14b7717fb3c2a4d336aca5ca392843ee50b2b2aa30b55d62c3585bc27d5fb392b61e3b9004293b26b5a2d",
          "sha256": "2a7691514d97931e0f0e98c89cab960352742ddef1c2c665304f4eeb3cc48171",
          "sha1": "b4664efaaf673b5c4546f96974bfc4d48c4eed86",
          "md5": "ee2a5714e6389926037396e9ab6dfea0"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "DLSerialPortUtil-macosx64-0.3.0-metadata.jar",
          "url": "DLSerialPortUtil-macosx64-0.3.0-metadata.jar",
          "size": 4349,
          "sha512": "2e336999f3af042c80419e2cdd6635808483c1b131780a252e13a84a6491728d68000e3d040c79b3ea1def9d6db0bd6bbe65d562b67e14ebb74754868d4ab752",
          "sha256": "234a0a0274aadb462ea8b7eab496772de482d78a54046748f2023f1f3418d784",
          "sha1": "7717c90dee64731673b7db0de5868b8e0fa5fb67",
          "md5": "2179f0efccf39e10911bdf4bd0c32fd0"
        }
      ]
    }
  ]
}
