{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ImageCompress/1.0.0-beta16/ImageCompress-1.0.0-beta16.module",
    "group": "com.hailiao.util",
    "module": "ImageCompress",
    "version": "1.0.0-beta16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ImageCompress.klib",
          "url": "ImageCompress-iosarm64-1.0.0-beta16.klib",
          "size": 37919,
          "sha512": "254b1462089fa3002a5c8e2d09210b34aac1cea74eec4fd29d0f841ef3606b3d370ee096056d4f38220913d6ad3708b478b0565976d43e4e2df0ccacb0c75640",
          "sha256": "7d45c9627b6830734bfbfb92df853253fc01e2e307332e059f2161ba59f732ec",
          "sha1": "d263fb623e4204479e0a402852e544762a4e109f",
          "md5": "8b7df32f1c7f9adf4470fc10a6c1c1b9"
        },
        {
          "name": "ImageCompress-cinterop-ImageCompress.klib",
          "url": "ImageCompress-iosarm64-1.0.0-beta16-cinterop-ImageCompress.klib",
          "size": 267434,
          "sha512": "45e0313e50896b1d6cc65b67251159ace9b80249dbe27eb67d46d58a4cd228469d5f1bb4a3dce82f25250016cd51f24d74121ccc560f88f0067386344e046c89",
          "sha256": "fda78a1fb1f256fec0b8669605406c0a0fa7c1b9bcd9eaf55b32d8c144299d31",
          "sha1": "7c2d9a57ef891ec4dc993b76eba96e65623610b0",
          "md5": "2d23ddcc1d7b81bcab3d70f2bcddde7a"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ImageCompress-iosarm64-1.0.0-beta16-sources.jar",
          "url": "ImageCompress-iosarm64-1.0.0-beta16-sources.jar",
          "size": 11341,
          "sha512": "5af2a29f8925c51df87e0533a1c88fddcc0f8ed13ff9651c9c8c3fb39913f220dc9782d8c34ac4bdde1bf6a085fc33ed25a5deb53904cf51d3df7e3e3ebd35f8",
          "sha256": "2a89693e7e34a444c38536dee9a41cc5c507ca97dccb2c798d596687568dac70",
          "sha1": "ddd272e0a10a0d22df4d240506285c0a798109f9",
          "md5": "352ed28d1edf1b3d38dc5f6040779bf0"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ImageCompress-iosarm64-1.0.0-beta16-metadata.jar",
          "url": "ImageCompress-iosarm64-1.0.0-beta16-metadata.jar",
          "size": 261,
          "sha512": "7d270d7632b39d246fa2e716948cacfaeb32cfbbb07673a44268dac2682f09469fb7e5e54319174f6b739a43f92adc0de45e6b6717a55da9893ad8a703b341ad",
          "sha256": "d89959a63f255553c95ca1749008f31e1fbb5f5f0b74b1fd1891d98a25e036b2",
          "sha1": "658885491aa0bf0931b8c8a31a3ae7e4384c56f5",
          "md5": "1ad2114ecc8875b1905b58c130698ea7"
        }
      ]
    }
  ]
}
