{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLLatLngUtil/1.7.3/DLLatLngUtil-1.7.3.module",
    "group": "com.github.D10NGYANG",
    "module": "DLLatLngUtil",
    "version": "1.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil.klib",
          "url": "DLLatLngUtil-iosx64-1.7.3.klib",
          "size": 61902,
          "sha512": "11359261ded1891f53d208f254cd65d29408449d26884b6a27c46c244ee622239ff902327cca51ddfd39ff8e381408a2ed4e9ebca446cb2077fc84cc80e0ff23",
          "sha256": "9c4bc1d480eed1b4e9481b8b2f6d5b5a8a095542d65f8f374e147334b22f7550",
          "sha1": "dfd0c8ebb1441a95c55aa927867dce22741b7256",
          "md5": "149e512434deea9a24a9e4909fedf550"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLLatLngUtil-iosx64-1.7.3-sources.jar",
          "url": "DLLatLngUtil-iosx64-1.7.3-sources.jar",
          "size": 14827,
          "sha512": "b26e7136df1894d888b2f12e2e74c34a37d297916f689f186db6e55052ac7f90b4f448850cb1ad2b2d6ccc4daa36f765d740fc773054e5ac2941d37d459653aa",
          "sha256": "6b813e321fe518f00312024523fb5b21d3a3d6100cebc9314e2aa8fb9214e3ed",
          "sha1": "b52b15eef847b1b4bcac396d514dd7ec5e2d0837",
          "md5": "f3e617b94fd0c111d3f8fcf895087f4f"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil-iosx64-1.7.3-metadata.jar",
          "url": "DLLatLngUtil-iosx64-1.7.3-metadata.jar",
          "size": 261,
          "sha512": "3969c6e2b4baad768a30aa651942ef6d7ab2afcb57d1ec04c90c52e9c88bc4153b09a7551ece2d71b6a91fbd5f19fddd9ed4ac4fc3c140c4c1d68601906a7985",
          "sha256": "ceef4e21f4381fab284469ef04205c259c7bf83d217f07822d241937b4a08b32",
          "sha1": "6934c7e818225cdaba6c2a60de30ae19a98de514",
          "md5": "8c274530b7ae1987c8901f8125a95fee"
        }
      ]
    }
  ]
}
