{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLCryptoUtil",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLCryptoUtil-metadata-0.0.6.jar",
          "url": "DLCryptoUtil-0.0.6.jar",
          "size": 4389,
          "sha512": "4784692ae4194803ae0806a6e5843add531b59a142dcfe7e36ab0428da3bfc91578b5d1ceb8fb69e8460e942bfee506ea372d61380d76e046c097ee49e670f75",
          "sha256": "6d029bcd6d619d4ba6e8be201b6f52e4b42e1e46a0578a93bbe50782058b9c23",
          "sha1": "a8150c2f20d0e6b4b63ed525a42bb8fe897ad4d0",
          "md5": "ebf43b8c9b96a5bf7759ab18f9da1f1e"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "DLCryptoUtil-kotlin-0.0.6-sources.jar",
          "url": "DLCryptoUtil-0.0.6-sources.jar",
          "size": 3530,
          "sha512": "d83e742d0757feaa08b503ac8de9b370da8aab2def1f2cd4b924bf4dea3bdacb7a92ab142ecdcc91bc3b1377ad2a18df1dc7f7863df15f4595d3aecbf4b7c33a",
          "sha256": "835c8e664d8307803a43814d9fbe6b660ce1a046e043788f93cb1854b40ac2fd",
          "sha1": "c3d1f3a544a4c4e3d5f3a88d34c61639c51f152c",
          "md5": "6e08a4169fb36821c7352e46c2326581"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLCryptoUtil-js/0.0.6/DLCryptoUtil-js-0.0.6.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCryptoUtil-js",
        "version": "0.0.6"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLCryptoUtil-js/0.0.6/DLCryptoUtil-js-0.0.6.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCryptoUtil-js",
        "version": "0.0.6"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLCryptoUtil-js/0.0.6/DLCryptoUtil-js-0.0.6.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCryptoUtil-js",
        "version": "0.0.6"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLCryptoUtil-jvm/0.0.6/DLCryptoUtil-jvm-0.0.6.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCryptoUtil-jvm",
        "version": "0.0.6"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLCryptoUtil-jvm/0.0.6/DLCryptoUtil-jvm-0.0.6.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCryptoUtil-jvm",
        "version": "0.0.6"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLCryptoUtil-jvm/0.0.6/DLCryptoUtil-jvm-0.0.6.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCryptoUtil-jvm",
        "version": "0.0.6"
      }
    }
  ]
}
