{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/1.9.0/DLDateUtil-1.9.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil.klib",
          "url": "DLDateUtil-iossimulatorarm64-1.9.0.klib",
          "size": 60862,
          "sha512": "b6900c68a2b4c327599d17f9e3a8195b4b3b0249626493b66c6b8d8497aa03a7c1ed3735244b679f1ce8e65c7d0e9d1056ba7f92cac082382a662dbe235cb595",
          "sha256": "18fbac90ecf35d28bc1f89dacca3bfba46b6cce9fb60f274e2102d8f10859b96",
          "sha1": "fa86bbb9c912b22dded88bc503a92ccadc3b83f2",
          "md5": "6089c278af47e8eea26fb80f4b007ff1"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLDateUtil-iossimulatorarm64-1.9.0-sources.jar",
          "url": "DLDateUtil-iossimulatorarm64-1.9.0-sources.jar",
          "size": 11910,
          "sha512": "108bb3c148c15c16b4e240f2b11b8e20b6d7c94d6680034575999a56e166543c25e36f492bda7573695677f253071aae06e64b1ac6632f64e85fd8eaae28f0bf",
          "sha256": "5ebddfab1c84e1378c93f70a6b8be3d13a70603499e1be8db161532792516fa9",
          "sha1": "0b214b743f647748b262ec9ec3f56214c225ee52",
          "md5": "06ed913039b6a285aa1a38df9d1371ee"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-iossimulatorarm64-1.9.0-metadata.jar",
          "url": "DLDateUtil-iossimulatorarm64-1.9.0-metadata.jar",
          "size": 261,
          "sha512": "a6e99f20b2fa15ef610e316dd01e693e7e0d92332d195389b64d5b692ead001eb8c0975ce568240780bb38804abd9c390186fbbc769d53aab199112a0c398a9d",
          "sha256": "79c6c96a4d7abb04fad1bce3fcf6e1376bafefd350d2ceca3440b64543b1bdfa",
          "sha1": "3111f18ef8790f60ceb7764895ba8f5370dbdcce",
          "md5": "8a8579a773537a894d636a8d381bd391"
        }
      ]
    }
  ]
}
