{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDatastoreUtil/0.2.1/DLDatastoreUtil-0.2.1.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDatastoreUtil",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLDatastoreUtil-iosSimulatorArm64Main-0.2.1.klib",
          "url": "DLDatastoreUtil-iossimulatorarm64-0.2.1.klib",
          "size": 11060,
          "sha512": "c0983baccdf2365348da32b687427730c5342ba192b2160e5ea4b34c19020597e8893fb67651c95980e755d4f58ef0bb1ec8cd6ab55b9714b32386c01d9c46ef",
          "sha256": "b0ccc778ef9dba2e7768482738c3d9c059b60b9d11e61ab2206e02e9e4d113b5",
          "sha1": "84315b6dfe3623b5830966ec20d1b925f4672892",
          "md5": "0422e5a693f6f6a57b39e89914a9507d"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLDatastoreUtil-iossimulatorarm64-0.2.1-sources.jar",
          "url": "DLDatastoreUtil-iossimulatorarm64-0.2.1-sources.jar",
          "size": 3667,
          "sha512": "0264a2e5d1b158f3057c0f42cebe8ee78a758938ff7f28077d020153eb6895c96580d45f2591e011877a3ccea55f5d4867bcf795596d468eba731b8f6a807c4a",
          "sha256": "4c6cc84482f9755a4c3f5ee1ecb8c31d15c330d00a0635c6433ab150bf73eaf1",
          "sha1": "05c4dd26d0b8e2a1e4d7416e5bc4a22c3142f279",
          "md5": "25cc034df759644962644db3f1a62883"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLDatastoreUtil-iossimulatorarm64-0.2.1-metadata.jar",
          "url": "DLDatastoreUtil-iossimulatorarm64-0.2.1-metadata.jar",
          "size": 2576,
          "sha512": "edf79d2bd389cdc8be44fa836e87d56f448131be947d40685003828111cb610ca3b9d79e60803622058af7f3147599ba18824faa1277da5e528116bd7ea6d7a0",
          "sha256": "2ca580577e32aa35475913aa13d90f3fce4c22a293c88b3261443181e9284b98",
          "sha1": "47ea3028fff7c10f7b276a086cb24cbfc176b418",
          "md5": "ebb4fa4ef91fd91dfa2985d8defc77d1"
        }
      ]
    }
  ]
}
