{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLLatLngUtil/1.7.0/DLLatLngUtil-1.7.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLLatLngUtil",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil.klib",
          "url": "DLLatLngUtil-iosx64-1.7.0.klib",
          "size": 61902,
          "sha512": "36ce354ceeddfd6d3da94061ae5a71d66a36381f82cdd625f7efe3a4bee27330f9b14210ad2001d82a567bfba487bd18922461e30801f1d2392922cc07b5ab22",
          "sha256": "8969be87b29d1986a0c8891cc99a84bdb31002f1f0bafe4223bae30f2ac78d14",
          "sha1": "0e9717b48fc2bd3209efc02ee688641d39a180e1",
          "md5": "659ed58f47f993fb02ea5233a6eb12a3"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLLatLngUtil-iosx64-1.7.0-sources.jar",
          "url": "DLLatLngUtil-iosx64-1.7.0-sources.jar",
          "size": 14827,
          "sha512": "b26e7136df1894d888b2f12e2e74c34a37d297916f689f186db6e55052ac7f90b4f448850cb1ad2b2d6ccc4daa36f765d740fc773054e5ac2941d37d459653aa",
          "sha256": "6b813e321fe518f00312024523fb5b21d3a3d6100cebc9314e2aa8fb9214e3ed",
          "sha1": "b52b15eef847b1b4bcac396d514dd7ec5e2d0837",
          "md5": "f3e617b94fd0c111d3f8fcf895087f4f"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil-iosx64-1.7.0-metadata.jar",
          "url": "DLLatLngUtil-iosx64-1.7.0-metadata.jar",
          "size": 261,
          "sha512": "02e9c15fb2570a60e962f3513437a2aba599ee9bc1b23dfe563c3d9930d4686074a23e1967d4ea1c65d9980979dd9bcd9c6e1a8f55e7e9f69a973212a0142ccd",
          "sha256": "c97f5020ed759cfdd38e9da927b29b5126c9b343632df92f920bd0dfc7fbcced",
          "sha1": "b05218b90481bd9456eb612ba8692b04c8f5ca6a",
          "md5": "ba3453acd13b1fc8aec85f215a3512f6"
        }
      ]
    }
  ]
}
