{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/2.1.3/DLDateUtil-2.1.3.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "2.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-linuxArm64Main-2.1.3.klib",
          "url": "DLDateUtil-linuxarm64-2.1.3.klib",
          "size": 78211,
          "sha512": "322f79599f16cc23f009c69097ed1fc7a74b76dc892ad7fda1053f6123140920ef340f2375348d6603ffc929fa6afca86aea8591c0329eed124cac1bdb73d7ec",
          "sha256": "1d3306d88e0b902f9bcedc8baa28e1a9065ab9ed6699ce38484eb8e66f9faaec",
          "sha1": "880cd8b87d1fcc8728d4c292a7998eaac188b1e8",
          "md5": "6a5f05cf6b11e8eba0b1184edaea0b97"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLDateUtil-linuxarm64-2.1.3-sources.jar",
          "url": "DLDateUtil-linuxarm64-2.1.3-sources.jar",
          "size": 17463,
          "sha512": "bb3a3993bfaa48011c2d827153ee6aae326cf05d78463575db2b23bb4a1a7ebc39398d491c3419e5ab885bc296b5143445d65e6b401b06f887bfb7bb07946d4a",
          "sha256": "352121accf74b1ebeb34dc8f64c47432bd58599aec2da3583910e2d2d610ef88",
          "sha1": "afe3c7b840c6185cf4647bc72c46a6a6974bcf89",
          "md5": "b005d5f34aec98f5aac50d1c0877c39c"
        }
      ]
    }
  ]
}
