{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLHttpUtil/1.1.0/DLHttpUtil-1.1.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLHttpUtil",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "DLHttpUtil-jvm-1.1.0.jar",
          "url": "DLHttpUtil-jvm-1.1.0.jar",
          "size": 14209,
          "sha512": "7fc38260bd246c09575f132610d31db89b46fb5040439a83d5d55be7683b9905fd79ce36fb9cdcabeff5162ae3fb24663c307ca3a15b1b8d450aacf6944a17c2",
          "sha256": "6fac764e6f2a6922c78ebfd4961c3e29a056ec62897cc804a241f4bd0bc7bf24",
          "sha1": "4a48128fe36b6d822a3bb97c09d877def055e4a7",
          "md5": "fc7b234c6d0a5478ea148a0bd72f3ad0"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.12"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLHttpUtil-jvm-1.1.0.jar",
          "url": "DLHttpUtil-jvm-1.1.0.jar",
          "size": 14209,
          "sha512": "7fc38260bd246c09575f132610d31db89b46fb5040439a83d5d55be7683b9905fd79ce36fb9cdcabeff5162ae3fb24663c307ca3a15b1b8d450aacf6944a17c2",
          "sha256": "6fac764e6f2a6922c78ebfd4961c3e29a056ec62897cc804a241f4bd0bc7bf24",
          "sha1": "4a48128fe36b6d822a3bb97c09d877def055e4a7",
          "md5": "fc7b234c6d0a5478ea148a0bd72f3ad0"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "DLHttpUtil-jvm-1.1.0-sources.jar",
          "url": "DLHttpUtil-jvm-1.1.0-sources.jar",
          "size": 2913,
          "sha512": "37be5199735fdcfcea2c7a63f5a4bb484bf40bb019ef8aa88d4021585b79bfacea1e22f2ff9d8209b7a1815831a67d4e2c7c521e6ab44fec866c1388a5def84a",
          "sha256": "e5a750526882cf9f6e02b8eab86ba1cb21d24b0677ae2af0bfc525935459af7a",
          "sha1": "ebc7642e7dc1c4d10a1d3b16fa514d78d68a8f31",
          "md5": "2ce7c4f734a184b63b90aa8d988649d3"
        }
      ]
    }
  ]
}
