{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLCommonUtil/0.5.4/DLCommonUtil-0.5.4.module",
    "group": "com.github.D10NGYANG",
    "module": "DLCommonUtil",
    "version": "0.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-jvm-0.5.4.jar",
          "url": "DLCommonUtil-jvm-0.5.4.jar",
          "size": 242376,
          "sha512": "15fb4464e2170071b0154f38ec8d47772aa180378d806051f9bb1dc6023144889d57c620e86733a463adf340fb3046f18039136ff2adf957a993d74205c4234c",
          "sha256": "a457fc42f78b481f74a852985d74253128ee4f817f5f37c774ac607e86315a46",
          "sha1": "fd8f3ed4f83fd76d1b8a4f307185e510b181aca5",
          "md5": "a6ef628cc601f47b75aae536a1f3f6e4"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-jvm-0.5.4.jar",
          "url": "DLCommonUtil-jvm-0.5.4.jar",
          "size": 242376,
          "sha512": "15fb4464e2170071b0154f38ec8d47772aa180378d806051f9bb1dc6023144889d57c620e86733a463adf340fb3046f18039136ff2adf957a993d74205c4234c",
          "sha256": "a457fc42f78b481f74a852985d74253128ee4f817f5f37c774ac607e86315a46",
          "sha1": "fd8f3ed4f83fd76d1b8a4f307185e510b181aca5",
          "md5": "a6ef628cc601f47b75aae536a1f3f6e4"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "DLCommonUtil-jvm-0.5.4-sources.jar",
          "url": "DLCommonUtil-jvm-0.5.4-sources.jar",
          "size": 196154,
          "sha512": "5b5c397fec1a9f6805082c4fbfcf2eff386641cf180c0326018d92b678ab3b0042960c3caba9982f961816a149abe5fff2ec3e87aa9bf34d77321ce8764b607a",
          "sha256": "dd30a527fd10dc3a2b8187640678556cbf28575d245c31cca65c7986777698f1",
          "sha1": "8171885805d82178a1910da89243bce9631f024e",
          "md5": "209917fc42e8d3b837267eb1c0e00deb"
        }
      ]
    }
  ]
}
