{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/2.2.0/DLDateUtil-2.2.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "2.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-macosX64Main-2.2.0.klib",
          "url": "DLDateUtil-macosx64-2.2.0.klib",
          "size": 77510,
          "sha512": "3d80febf73783c64108bbb459476e82bcb4faeed42909b3311e4fbfcee2e3f2b08ef3099bed03200425ae3e0e84d64d7c129539d2047f2a3ea339d7f869a9c8e",
          "sha256": "6f9e2ecc84e9186a6b68b0cc79617b324763138b613cf45179824003e7f45901",
          "sha1": "92d4f13988dc74098b18648aa85ea492b81f8cfc",
          "md5": "410947f30991b95c3eac11433d0afff7"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLDateUtil-macosx64-2.2.0-sources.jar",
          "url": "DLDateUtil-macosx64-2.2.0-sources.jar",
          "size": 17269,
          "sha512": "1e62691bb797940348e3045d1c2a871eca8f87e7207565142e080256c4af34985862a82d2431b31730dd98370d84007e4ea007e3e47c4e722b629aa04b3dd877",
          "sha256": "2e0a12edb7838df703693d68368eaeec1db413d3153d4942abdacc8113df0c72",
          "sha1": "f3e60235b4f7f1aa2210c13d4b66d0be157c7ea3",
          "md5": "fad80f3f43425c01564714eec44f2345"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-macosx64-2.2.0-metadata.jar",
          "url": "DLDateUtil-macosx64-2.2.0-metadata.jar",
          "size": 261,
          "sha512": "ad34091e20e0dd0500f9748848d1f22d5ffed0d949d36768768d87b00349eda66c9508d2ed640ee4924b380f5a8e1e91883b4c44ba77719835f6b8a6b9db8fd2",
          "sha256": "3eef2ea2e0fd8206718acbf37fe329a03126d4f677b757c672fd89e278f4f326",
          "sha1": "dfc71d13ffe800cc04e06e09a51aae4976b327bc",
          "md5": "239766b7033d200cf4b7d7979c8c094e"
        }
      ]
    }
  ]
}
