{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLMapboxUtil",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mapbox.maps",
          "module": "android",
          "version": {
            "requires": "10.16.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLMapboxUtil-1.1.2.aar",
          "url": "DLMapboxUtil-1.1.2.aar",
          "size": 975966,
          "sha512": "f96cbac11220565516e2c535cc182f274192653a34515c578f7b38127d6fb6d1d3afd7f242dbd2ab8c026631f321c47a9f5a829477ca76d75e70227dae2745ad",
          "sha256": "8e02c94dab78a19bcb6f628bf402f3e5436a9ab29d77aea83385781b16f38f54",
          "sha1": "01579124047927714ee3232972372310cacb5d36",
          "md5": "c3f4375d340028f3e2d35d225075027b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.github.raamcosta.compose-destinations",
          "module": "animations-core",
          "version": {
            "requires": "1.9.54"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLJetpackComposeUtil",
          "version": {
            "requires": "2.0.11"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLAppUtil",
          "version": {
            "requires": "2.4.12"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLTianDiTuApi",
          "version": {
            "requires": "0.5.5"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLHttpUtil",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLDatastoreUtil",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "com.mapbox.maps",
          "module": "android",
          "version": {
            "requires": "10.16.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLMapboxUtil-1.1.2.aar",
          "url": "DLMapboxUtil-1.1.2.aar",
          "size": 975966,
          "sha512": "f96cbac11220565516e2c535cc182f274192653a34515c578f7b38127d6fb6d1d3afd7f242dbd2ab8c026631f321c47a9f5a829477ca76d75e70227dae2745ad",
          "sha256": "8e02c94dab78a19bcb6f628bf402f3e5436a9ab29d77aea83385781b16f38f54",
          "sha1": "01579124047927714ee3232972372310cacb5d36",
          "md5": "c3f4375d340028f3e2d35d225075027b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLMapboxUtil-1.1.2-sources.jar",
          "url": "DLMapboxUtil-1.1.2-sources.jar",
          "size": 58186,
          "sha512": "0d34a0e9359ef40b3a8f35851232cc7997bfdaae237684f0b9913a2625702252a577a3954da4075ac99db59a07351acc38460b1236e1b0581eaad0c8032e9503",
          "sha256": "c8d330f6cb8cfc477bf0f69fab1a977628f3a51b2d02b1816e231e9633385997",
          "sha1": "251f7486017cad1ea867cd7377d18075b6dbe28d",
          "md5": "884b63c09f50ae55bf51e1eb4565ce03"
        }
      ]
    }
  ]
}
