{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/2.2.0/DLDateUtil-2.2.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "2.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-macosArm64Main-2.2.0.klib",
          "url": "DLDateUtil-macosarm64-2.2.0.klib",
          "size": 77526,
          "sha512": "c1b04e3d2058630a4aa2cac05c1f2342cb084abfa0876774cb84587b4562464c5ce4da099874b60415bc10e5083020b528e04b453fe0358f5ff02cec34298f4d",
          "sha256": "b8bdd62d17ed5ac65ebd324d79e3dd89ee2c22245f4991d4ec065e6af2601dc4",
          "sha1": "4ef5b8e67252af0b7ec54f437525b3986bac7596",
          "md5": "ff167e0beb3abd14d477292061f1f79d"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLDateUtil-macosarm64-2.2.0-sources.jar",
          "url": "DLDateUtil-macosarm64-2.2.0-sources.jar",
          "size": 17269,
          "sha512": "1e62691bb797940348e3045d1c2a871eca8f87e7207565142e080256c4af34985862a82d2431b31730dd98370d84007e4ea007e3e47c4e722b629aa04b3dd877",
          "sha256": "2e0a12edb7838df703693d68368eaeec1db413d3153d4942abdacc8113df0c72",
          "sha1": "f3e60235b4f7f1aa2210c13d4b66d0be157c7ea3",
          "md5": "fad80f3f43425c01564714eec44f2345"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-macosarm64-2.2.0-metadata.jar",
          "url": "DLDateUtil-macosarm64-2.2.0-metadata.jar",
          "size": 261,
          "sha512": "4ce9b6f8d216ed427c9ccaebfdc97df515d8ed58e75e8ab76ab3201e32e71612f2a8a44fbe5d905338eacf98b0fb5496b6ac835c96765e4fdc674554c1ef87a4",
          "sha256": "ad3c790a2d1e2d37943472954286f378a5ac866f33901fab2d5f9d5ef0dfcb33",
          "sha1": "147a243dc764b122865634dc8311198b462eca05",
          "md5": "a0fec70541b6ef0d6f24c9551dd3a64c"
        }
      ]
    }
  ]
}
