{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLCommonUtil/1.0.1/DLCommonUtil-1.0.1.module",
    "group": "com.github.D10NGYANG",
    "module": "DLCommonUtil",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-linuxX64Main-1.0.1.klib",
          "url": "DLCommonUtil-linuxx64-1.0.1.klib",
          "size": 280617,
          "sha512": "b0fdddec3de546cc84551b9a17abe9d41c32c53fdb829ec7a43a48d678c15d76a55d3ea9218dee9c98753445647b9dd6b0fdc09711ea23797189399979188849",
          "sha256": "8af7cc9eeedcef42e2bbd62c184a13ddfbe2dbd4e7d226f7ef5980f604c12b77",
          "sha1": "9ae964f5300470156ae6b9f9f0c23a20ae06a7dd",
          "md5": "71e5e45b89dbca566315e71d7cf26461"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLCommonUtil-linuxx64-1.0.1-sources.jar",
          "url": "DLCommonUtil-linuxx64-1.0.1-sources.jar",
          "size": 96212,
          "sha512": "3487df5efdef43a1827717b6e256b1a74abe78b34a3d005ca7453dd7811a2934bb1c0639cae888278859af36249a0c23f8d4880aa9cdba785b1ace0fb08ad563",
          "sha256": "d54f7ecc27613a156161ab09fdf5e82f6d49d45ba4fc69554c066e71ac5e4cdf",
          "sha1": "76152f5fd1b29ee0ca1b7342afdfd2a65fab3390",
          "md5": "9e91a44d83024a861baa352e120ae22f"
        }
      ]
    }
  ]
}
