{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLLatLngUtil",
    "version": "1.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil-metadata-1.5.3.jar",
          "url": "DLLatLngUtil-1.5.3.jar",
          "size": 6598,
          "sha512": "20a073d1c6542ac114947ea3af03e24fdd79cfbcc040e4ba4a39ae1187f44fd841be75fb67a238774c09deac306731dc785c4d09fd4999c8fc19c7fde4ee3159",
          "sha256": "8aaafe4d49192224d7271ae870d1491185b4d0d4b409984576ae762d6b5c3d3d",
          "sha1": "54091c61ae73f932f9d946d773aa20ad102304d1",
          "md5": "66edf5c6fda0e2eca19bb15496340ddd"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLLatLngUtil-iosarm64/1.5.3/DLLatLngUtil-iosarm64-1.5.3.module",
        "group": "com.github.D10NGYANG",
        "module": "DLLatLngUtil-iosarm64",
        "version": "1.5.3"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLLatLngUtil-iosarm64/1.5.3/DLLatLngUtil-iosarm64-1.5.3.module",
        "group": "com.github.D10NGYANG",
        "module": "DLLatLngUtil-iosarm64",
        "version": "1.5.3"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLLatLngUtil-iosx64/1.5.3/DLLatLngUtil-iosx64-1.5.3.module",
        "group": "com.github.D10NGYANG",
        "module": "DLLatLngUtil-iosx64",
        "version": "1.5.3"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLLatLngUtil-iosx64/1.5.3/DLLatLngUtil-iosx64-1.5.3.module",
        "group": "com.github.D10NGYANG",
        "module": "DLLatLngUtil-iosx64",
        "version": "1.5.3"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLLatLngUtil-js/1.5.3/DLLatLngUtil-js-1.5.3.module",
        "group": "com.github.D10NGYANG",
        "module": "DLLatLngUtil-js",
        "version": "1.5.3"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLLatLngUtil-js/1.5.3/DLLatLngUtil-js-1.5.3.module",
        "group": "com.github.D10NGYANG",
        "module": "DLLatLngUtil-js",
        "version": "1.5.3"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLLatLngUtil-jvm/1.5.3/DLLatLngUtil-jvm-1.5.3.module",
        "group": "com.github.D10NGYANG",
        "module": "DLLatLngUtil-jvm",
        "version": "1.5.3"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLLatLngUtil-jvm/1.5.3/DLLatLngUtil-jvm-1.5.3.module",
        "group": "com.github.D10NGYANG",
        "module": "DLLatLngUtil-jvm",
        "version": "1.5.3"
      }
    }
  ]
}
