{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLBluetoothUtil/0.6.0/DLBluetoothUtil-0.6.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLBluetoothUtil",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLBluetoothUtil-wasm-js-0.6.0.klib",
          "url": "DLBluetoothUtil-wasm-js-0.6.0.klib",
          "size": 60710,
          "sha512": "2e57b5d11a50be243cd5e3b181dacbd00d4781a2b1c822c0021b8a2be8990dfbb13bbd8cded528874d639b2799fb637e801abe7a760757b914b983baf7e808d3",
          "sha256": "56456b50d7cdc223c8aa69512194b25f40977dbcc28055c119752c853b4bd0ed",
          "sha1": "4e6cf009c9f7cd176d9e538515bb8abe78e904de",
          "md5": "081df2f62bbc9db55e7847c50a0393b0"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLLogUtil",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLBluetoothUtil-wasm-js-0.6.0.klib",
          "url": "DLBluetoothUtil-wasm-js-0.6.0.klib",
          "size": 60710,
          "sha512": "2e57b5d11a50be243cd5e3b181dacbd00d4781a2b1c822c0021b8a2be8990dfbb13bbd8cded528874d639b2799fb637e801abe7a760757b914b983baf7e808d3",
          "sha256": "56456b50d7cdc223c8aa69512194b25f40977dbcc28055c119752c853b4bd0ed",
          "sha1": "4e6cf009c9f7cd176d9e538515bb8abe78e904de",
          "md5": "081df2f62bbc9db55e7847c50a0393b0"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "DLBluetoothUtil-wasm-js-0.6.0-sources.jar",
          "url": "DLBluetoothUtil-wasm-js-0.6.0-sources.jar",
          "size": 14108,
          "sha512": "2044186672398d88ba278fb619ee14a9ccdae1da1f425d68e9d03fc899b5e79f113f40113aa12540095b4c61c0135740f31c177927915fa0dd67fdc7531c4f0b",
          "sha256": "4bd3922774d35e0480ee6b68334cda7e9a574768272ffd648650870ce130e936",
          "sha1": "f15b088892091a08ca23c090f709cf657b2d891f",
          "md5": "bd06c227479802ef0e7710f70cfcf382"
        }
      ]
    }
  ]
}
