{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLMapboxUtil",
    "version": "1.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mapbox.maps",
          "module": "android",
          "version": {
            "requires": "10.16.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "DLMapboxUtil-1.1.4.aar",
          "url": "DLMapboxUtil-1.1.4.aar",
          "size": 975576,
          "sha512": "3a1bb3416ead532ce3228c191be6c97654dba97347d13a52f0394b7fedcf7965f6692d0cdbc9ecb96c0db14ea3285ab8ce1b157cdda52f1983c69a2b1276911e",
          "sha256": "22d7804b0a768bfcce86aa6b9475500dcfac8805474d15986a004762540bf884",
          "sha1": "8aa762c5c4387580425454d137f71d4df66aeae2",
          "md5": "b73d8df7f05636725ede3a50cdb43658"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.github.raamcosta.compose-destinations",
          "module": "animations-core",
          "version": {
            "requires": "1.9.55"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLJetpackComposeUtil",
          "version": {
            "requires": "2.0.13"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLAppUtil",
          "version": {
            "requires": "2.4.14"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLTianDiTuApi",
          "version": {
            "requires": "0.5.6"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLHttpUtil",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLDatastoreUtil",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "com.mapbox.maps",
          "module": "android",
          "version": {
            "requires": "10.16.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "DLMapboxUtil-1.1.4.aar",
          "url": "DLMapboxUtil-1.1.4.aar",
          "size": 975576,
          "sha512": "3a1bb3416ead532ce3228c191be6c97654dba97347d13a52f0394b7fedcf7965f6692d0cdbc9ecb96c0db14ea3285ab8ce1b157cdda52f1983c69a2b1276911e",
          "sha256": "22d7804b0a768bfcce86aa6b9475500dcfac8805474d15986a004762540bf884",
          "sha1": "8aa762c5c4387580425454d137f71d4df66aeae2",
          "md5": "b73d8df7f05636725ede3a50cdb43658"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLMapboxUtil-1.1.4-sources.jar",
          "url": "DLMapboxUtil-1.1.4-sources.jar",
          "size": 58186,
          "sha512": "0d34a0e9359ef40b3a8f35851232cc7997bfdaae237684f0b9913a2625702252a577a3954da4075ac99db59a07351acc38460b1236e1b0581eaad0c8032e9503",
          "sha256": "c8d330f6cb8cfc477bf0f69fab1a977628f3a51b2d02b1816e231e9633385997",
          "sha1": "251f7486017cad1ea867cd7377d18075b6dbe28d",
          "md5": "884b63c09f50ae55bf51e1eb4565ce03"
        }
      ]
    }
  ]
}
