{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLJetpackComposeUtil/3.2.0/DLJetpackComposeUtil-3.2.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLJetpackComposeUtil",
    "version": "3.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-js-3.2.0.klib",
          "url": "DLJetpackComposeUtil-js-3.2.0.klib",
          "size": 4136801,
          "sha512": "4874f0cffb88112623bbf58d83f7463449539c343962e3c3bfc39c8a606a84b91f80ef82a074f58419479e48f96ea47834fb409191675cb405d80d9bbee2a098",
          "sha256": "804e13cda1ff887bc3aeb19ea827588b4cc4c943e0140dd5f89ab92212e56ac6",
          "sha1": "7f9b31ed706e8ccabc9a54b0f5f3918dc103abb9",
          "md5": "1a23bd668240d5ea2b1b183d29564b7a"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-js-3.2.0.klib",
          "url": "DLJetpackComposeUtil-js-3.2.0.klib",
          "size": 4136801,
          "sha512": "4874f0cffb88112623bbf58d83f7463449539c343962e3c3bfc39c8a606a84b91f80ef82a074f58419479e48f96ea47834fb409191675cb405d80d9bbee2a098",
          "sha256": "804e13cda1ff887bc3aeb19ea827588b4cc4c943e0140dd5f89ab92212e56ac6",
          "sha1": "7f9b31ed706e8ccabc9a54b0f5f3918dc103abb9",
          "md5": "1a23bd668240d5ea2b1b183d29564b7a"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "DLJetpackComposeUtil-js-3.2.0-sources.jar",
          "url": "DLJetpackComposeUtil-js-3.2.0-sources.jar",
          "size": 101726,
          "sha512": "88e3f2fd11c3216bac3b0222375efcc87d30282c4d097b936f707d8e8ea7dc701072ac99a1d1b86f17212e79c06cf46e9e1778be1747cc1f9e393ee6b72f7ffd",
          "sha256": "33c3839737903c55cc65c9acc8201231ae78f4e2550b850be99a9263d49ca9f1",
          "sha1": "d871d16370b3b1c7fa3157413ffac9d03f6672e3",
          "md5": "92d37c4bd6a15c5bcb3600287414e9f9"
        }
      ]
    },
    {
      "name": "jsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-3.2.0.kotlin_resources.zip",
          "url": "DLJetpackComposeUtil-js-3.2.0-kotlin_resources.kotlin_resources.zip",
          "size": 10276,
          "sha512": "caa0e17f319c3b21fc61d214ff2d31dc7a34cc63c0de6c97f0b90edfa3f598237aa696a9d19cdfe9989f2beb92e46c723e4b32fba5d5a19ffa42600095a5181d",
          "sha256": "c3ccc6711f7dc7064127a4633841669c836dfb9353532a26acbfb95b618c8f8b",
          "sha1": "f55dc45c215198b126d50eda6bbc8af5fc00499d",
          "md5": "3145cc374d8057484e834bebccea4758"
        }
      ]
    }
  ]
}
