{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/2.1.1/DLDateUtil-2.1.1.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "2.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-macosArm64Main-2.1.1.klib",
          "url": "DLDateUtil-macosarm64-2.1.1.klib",
          "size": 77400,
          "sha512": "73d115542a49a21d8f00bc77e770909b76ca6f760ef9e973877eb226e9191b56b8c71158333c8470424def02d187094c24779cc8593c4e10c7ab133e78449e01",
          "sha256": "11ed5b06c4a74f925e5060df2c9d6de16ef0e8e183082a4656a3c34fd4ba0fad",
          "sha1": "86fa28d2306f633b03ff9b1b95c93475cded5114",
          "md5": "1fa9ee8314083e8c7da5e85319dbbfd3"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLDateUtil-macosarm64-2.1.1-sources.jar",
          "url": "DLDateUtil-macosarm64-2.1.1-sources.jar",
          "size": 17258,
          "sha512": "e7110c4db22a2fca426dafe65ffde30426f1fe32969d480b3560d82384441b2b576321ca3767ce9f5f0732a9c88920c8dff9281eaaa6e38de151c12da43407c2",
          "sha256": "4ef01c563471fdffed520731c972180b18d41f44e1ff9470330b423229711e1b",
          "sha1": "bba88fe001b315a87f7a3aaee527c1a6dea2ad95",
          "md5": "7b1c0822b6333991fde1119b7b514c74"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-macosarm64-2.1.1-metadata.jar",
          "url": "DLDateUtil-macosarm64-2.1.1-metadata.jar",
          "size": 261,
          "sha512": "3a33960e381eec0b8a3cdaaa4f68eebf60a42943802b7651d81e7a3c3d215eaca5382e1f1325dca90ec8f92e8d484b6d3d3147d9cf3fa77a6d18ad23cb864a2b",
          "sha256": "5154a43bf059e32e4dbcfadd625182fdc29642e02af0bc87a492ba97f3f14610",
          "sha1": "336909ad3fe5ec8e064536cf2fecc997b3ce48fb",
          "md5": "b98be0b9d0cb26f781bba650cacac56d"
        }
      ]
    }
  ]
}
