{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLCommonUtil/0.7.0/DLCommonUtil-0.7.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLCommonUtil",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-iosX64Main-0.7.0.klib",
          "url": "DLCommonUtil-iosx64-0.7.0.klib",
          "size": 308546,
          "sha512": "9f41934fbc16153bab5831d637f058ee5fc4c7b1db31097c0167105a51d4ca70c68958f7613790e218bb6a137e31d2e27451eadccec8d56dfc1d5cbe056bc75a",
          "sha256": "1bda276cca8fda1426a1670c0432905b8be3efc0845a4b8bddf49647afc1ba8b",
          "sha1": "5a7071382009866407c7934c1a06f0f20987e1f8",
          "md5": "bca93547b43656ff8d51764ea1f8200d"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLCommonUtil-iosx64-0.7.0-sources.jar",
          "url": "DLCommonUtil-iosx64-0.7.0-sources.jar",
          "size": 197110,
          "sha512": "f0af423b58d6de35a4e89409fd8b3eddca3cd0edbf93383f7ea89a93f32963d60a60db237f5cc593e796927af2c0768fe775e7a3d98e4ac76accf6111962687d",
          "sha256": "ce1d824dd30881fdc331cbf09a0dba274061afefd43f79c3f0f26cdb55386a16",
          "sha1": "36d62d8afd00f41460789b3b88f6ffd66c1d646d",
          "md5": "2b29ea8515dbd3cd102f4c9200e5b56e"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-iosx64-0.7.0-metadata.jar",
          "url": "DLCommonUtil-iosx64-0.7.0-metadata.jar",
          "size": 3796,
          "sha512": "5cdcf7887f272733e3045a844274aaef2c25694fc6dcb60291a08e97693a00bd36c5cbd25928af525135ff813c23fa1eb2952fc25762aa3d421fb727e85948ac",
          "sha256": "23e22a7f76605b337070a684be44cc954157cb1b367858a11e3e727994fa6165",
          "sha1": "d058ef610724e589fb0d0640fae6c91184ca22b2",
          "md5": "ca2926875899602b8fb03562472c2163"
        }
      ]
    }
  ]
}
