{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLTianDiTuApi/0.5.5/DLTianDiTuApi-0.5.5.module",
    "group": "com.github.D10NGYANG",
    "module": "DLTianDiTuApi",
    "version": "0.5.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "DLTianDiTuApi-jvm-0.5.5.jar",
          "url": "DLTianDiTuApi-jvm-0.5.5.jar",
          "size": 141487,
          "sha512": "0e2279f3c82123fd3798a99b585b179024965d4b799235f83a545318801365342ab45a51a3dda02fb2ed695f1cd01537819a4087f2594e39bc645452cf387802",
          "sha256": "11b71b2d871068bf612233be566d40c809586f1beaf498a8eeed51eb8fd10444",
          "sha1": "e7956890868fb9c75c9b008db9a1acf7ca589ba7",
          "md5": "851a169ec70e891e054acd1d4a28d5e0"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLHttpUtil",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLTianDiTuApi-jvm-0.5.5.jar",
          "url": "DLTianDiTuApi-jvm-0.5.5.jar",
          "size": 141487,
          "sha512": "0e2279f3c82123fd3798a99b585b179024965d4b799235f83a545318801365342ab45a51a3dda02fb2ed695f1cd01537819a4087f2594e39bc645452cf387802",
          "sha256": "11b71b2d871068bf612233be566d40c809586f1beaf498a8eeed51eb8fd10444",
          "sha1": "e7956890868fb9c75c9b008db9a1acf7ca589ba7",
          "md5": "851a169ec70e891e054acd1d4a28d5e0"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "DLTianDiTuApi-jvm-0.5.5-sources.jar",
          "url": "DLTianDiTuApi-jvm-0.5.5-sources.jar",
          "size": 4908,
          "sha512": "b1661a72a79fbcafe14497aeb3f212e59218e2889c3cdc8be61f1aab10bcfc007c35a7d6779e6f9985b7191cfc2e2dd2909fdd7bf3ce93ba8ac78f5b79bdb89a",
          "sha256": "31c276faa513b9f0eb4d5d93ed8b16f87f628678014b6c85e1fab9843d11f585",
          "sha1": "77631559a4ba25e472e4f545bd9471e077da0ea2",
          "md5": "cecd1657a63d9f94384304200a38806c"
        }
      ]
    }
  ]
}
