{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLLatLngUtil/1.7.5/DLLatLngUtil-1.7.5.module",
    "group": "com.github.D10NGYANG",
    "module": "DLLatLngUtil",
    "version": "1.7.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil.klib",
          "url": "DLLatLngUtil-iosarm64-1.7.5.klib",
          "size": 62009,
          "sha512": "3f82f5b176f78c3d0ec52ea6637f479d0f66ecf11d3832024086cacf396dd51ab28b4a4d883dcca35dfd9c8bebdae65ea798c6feb18b1b57f8b508506bd4a96e",
          "sha256": "8b100f354cc49668915374a746f9ade91b4165790e1875fb7d35f71df43fad6d",
          "sha1": "d348ca35b0f25f2206bbd5b2e990da5dc81c52fa",
          "md5": "643048bc2e07e319fc2fd725d08d1b3b"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLLatLngUtil-iosarm64-1.7.5-sources.jar",
          "url": "DLLatLngUtil-iosarm64-1.7.5-sources.jar",
          "size": 14827,
          "sha512": "b26e7136df1894d888b2f12e2e74c34a37d297916f689f186db6e55052ac7f90b4f448850cb1ad2b2d6ccc4daa36f765d740fc773054e5ac2941d37d459653aa",
          "sha256": "6b813e321fe518f00312024523fb5b21d3a3d6100cebc9314e2aa8fb9214e3ed",
          "sha1": "b52b15eef847b1b4bcac396d514dd7ec5e2d0837",
          "md5": "f3e617b94fd0c111d3f8fcf895087f4f"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil-iosarm64-1.7.5-metadata.jar",
          "url": "DLLatLngUtil-iosarm64-1.7.5-metadata.jar",
          "size": 261,
          "sha512": "2fd94858efa02ba6d17ffb20b1bdd5b6fcd080178616122e8612e8ff66447911eef84f81307da7c66d8cdb28ba13c469501074aa93fed27ddb3d4a29c2c3712d",
          "sha256": "3a013c2748e46e60b85e8dcd2491430bf3cf3c92160274efdf1c06d587faeca5",
          "sha1": "9e8a0759d9c06163f0d630bc1fcca8ba43d6a08d",
          "md5": "e02297538071a7b6de82cc9605c5443f"
        }
      ]
    }
  ]
}
