{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLJetpackComposeUtil",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2023.04.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-systemuicontroller",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-flowlayout",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-1.3.3.aar",
          "url": "DLJetpackComposeUtil-1.3.3.aar",
          "size": 656026,
          "sha512": "25acebe8d1683e79a8b79031d18adc62038eacfbebe3f90c2085447925413d42a2212a55963c5269734bddf7f3d334bb1e0bc3e7f75e87b1eb2f4e0b5462dfe5",
          "sha256": "1d6fd5616a89c9df78a3dfbb0d15e0091b887658265190379494a24b1fd9452b",
          "sha1": "9970dfbf0c2165f3f569977ffbd7d2d89aec3c7b",
          "md5": "3236c7ac9a269c79db6122bde34bccd5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLDateUtil-jvm",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2023.04.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-systemuicontroller",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-flowlayout",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-1.3.3.aar",
          "url": "DLJetpackComposeUtil-1.3.3.aar",
          "size": 656026,
          "sha512": "25acebe8d1683e79a8b79031d18adc62038eacfbebe3f90c2085447925413d42a2212a55963c5269734bddf7f3d334bb1e0bc3e7f75e87b1eb2f4e0b5462dfe5",
          "sha256": "1d6fd5616a89c9df78a3dfbb0d15e0091b887658265190379494a24b1fd9452b",
          "sha1": "9970dfbf0c2165f3f569977ffbd7d2d89aec3c7b",
          "md5": "3236c7ac9a269c79db6122bde34bccd5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLJetpackComposeUtil-1.3.3-sources.jar",
          "url": "DLJetpackComposeUtil-1.3.3-sources.jar",
          "size": 36863,
          "sha512": "539bf92bb87976ff16bda169c044f6defd8b03b694fd52fd4f096c81330519a35c007fdfc20c7570db8857851b511fb2579d6a90a2bd69e0c5b4ca0b08907a18",
          "sha256": "2c8c881d73bbd37185169247ed7e9792fada13fabf47d05f9175a42a0d726db4",
          "sha1": "e0d61d6199ee2bf45c0d97362da594d1b86c242e",
          "md5": "c97f5fd667fe4db49912bea3da6017dc"
        }
      ]
    }
  ]
}
