{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLCryptoUtil/0.0.5/DLCryptoUtil-0.0.5.module",
    "group": "com.github.D10NGYANG",
    "module": "DLCryptoUtil",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLCryptoUtil-js-0.0.5.klib",
          "url": "DLCryptoUtil-js-0.0.5.klib",
          "size": 27322,
          "sha512": "85768a151a184f02c19119e63a0cbe56c18ccfbc9e57deb0d734f1796a99bea7b4b1cbdfe511bd9d0395ee00255611e0c9bd99546272f13d882437448b2c5d0b",
          "sha256": "3c3a74280b41eab0616599b361d366a34b6d60bf3d0b8691ccdb0d5e33a3cf35",
          "sha1": "f5354f756d2d5f2b87a49f03f3789a6768cde0d5",
          "md5": "3cf5bea1d7f5a7eb8f1c04415c0c2adb"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLCryptoUtil-js-0.0.5.klib",
          "url": "DLCryptoUtil-js-0.0.5.klib",
          "size": 27322,
          "sha512": "85768a151a184f02c19119e63a0cbe56c18ccfbc9e57deb0d734f1796a99bea7b4b1cbdfe511bd9d0395ee00255611e0c9bd99546272f13d882437448b2c5d0b",
          "sha256": "3c3a74280b41eab0616599b361d366a34b6d60bf3d0b8691ccdb0d5e33a3cf35",
          "sha1": "f5354f756d2d5f2b87a49f03f3789a6768cde0d5",
          "md5": "3cf5bea1d7f5a7eb8f1c04415c0c2adb"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "DLCryptoUtil-js-0.0.5-sources.jar",
          "url": "DLCryptoUtil-js-0.0.5-sources.jar",
          "size": 7793,
          "sha512": "6da7da6115d0435644c0f8582e6586f2507a7ced767ce27c96017adee51918c674c5780db57595d6e315b6a3fc8bb29d1313635e4a334d1372a57587b1d2f26e",
          "sha256": "c22a28dfb85c9b7242092f0993a50244410242ff9b1af0cee8a9c490072d8cff",
          "sha1": "861dd8fff50790c29cccd962856388ed8b3997aa",
          "md5": "0f6d9a453bddb58fe2d1a7c3fe3734cc"
        }
      ]
    }
  ]
}
