{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLJetpackComposeUtil/3.3.0/DLJetpackComposeUtil-3.3.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLJetpackComposeUtil",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-wasm-js-3.3.0.klib",
          "url": "DLJetpackComposeUtil-wasm-js-3.3.0.klib",
          "size": 705107,
          "sha512": "1959722b4811245d5d4fe90f3804f1080ac6364336602058a1c1436d9665524a126a3fca571fac5dc504f954a256d90ffd367847f23bf86583e7eddfc9502608",
          "sha256": "b7dbfbe4047ef523e2a57fb936751c2c8559fe67996be0979dfefed4a2a46b37",
          "sha1": "e142a15a013540f297457ab4f3e74e41623afcb7",
          "md5": "b070fe923816e04fe59c683a16eb1bea"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-wasm-js-3.3.0.klib",
          "url": "DLJetpackComposeUtil-wasm-js-3.3.0.klib",
          "size": 705107,
          "sha512": "1959722b4811245d5d4fe90f3804f1080ac6364336602058a1c1436d9665524a126a3fca571fac5dc504f954a256d90ffd367847f23bf86583e7eddfc9502608",
          "sha256": "b7dbfbe4047ef523e2a57fb936751c2c8559fe67996be0979dfefed4a2a46b37",
          "sha1": "e142a15a013540f297457ab4f3e74e41623afcb7",
          "md5": "b070fe923816e04fe59c683a16eb1bea"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "DLJetpackComposeUtil-wasm-js-3.3.0-sources.jar",
          "url": "DLJetpackComposeUtil-wasm-js-3.3.0-sources.jar",
          "size": 101874,
          "sha512": "304a2de4ee391363a130fad5d228311e7f36d9061d52a72fb90cd3e04e9f6672e33e51fc5caff91c4c8a40742044fa43464632e483768c83a2e93a3f1032aa6d",
          "sha256": "965e7b02989ab7621e074cf1bdde8b3221c475639c8b538d254eb901f9c523a1",
          "sha1": "f441f3379edd11f41635485dbd2b1d45e750e314",
          "md5": "17e56614cfa820f747c18ed77905bf6a"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-3.3.0.kotlin_resources.zip",
          "url": "DLJetpackComposeUtil-wasm-js-3.3.0-kotlin_resources.kotlin_resources.zip",
          "size": 10276,
          "sha512": "fcacd1d206ef5160ee26948bcedc79e71d1d8a27f38399184ee1f50978f4b4337d9a732aac5b53a1a5038802428e395d2700693797581aa97d545dd4b28c02af",
          "sha256": "d63ec7244c1eddaddc28df904231399f5b7f74cc679a0ec883abfcaa894a9a23",
          "sha1": "b7cd18d5f0b6613c2a30be3f422ac175e660eb6a",
          "md5": "db38dc65ecd9f0bf6fbbf99f123850df"
        }
      ]
    }
  ]
}
