{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLLatLngUtil/1.7.1/DLLatLngUtil-1.7.1.module",
    "group": "com.github.D10NGYANG",
    "module": "DLLatLngUtil",
    "version": "1.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil.klib",
          "url": "DLLatLngUtil-iosarm64-1.7.1.klib",
          "size": 61919,
          "sha512": "f0a3a4d50fc0082586be662ee24b493c2d42f14d06acf29fd997a57b4ac9a3fdebabdf80f6ca5f20d6c14b57fad76dea4ffe0322ec2a4fa23aa47dcc3d46dddc",
          "sha256": "080203d7ef79522eaa67c367e7b06a9b4f9b6729440436befcd0a05284cec32d",
          "sha1": "5c2ac5ffd0c1b6ba8ade1229348cdb70780c6ea2",
          "md5": "db5a1363561c1ff46a777291da843e14"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLLatLngUtil-iosarm64-1.7.1-sources.jar",
          "url": "DLLatLngUtil-iosarm64-1.7.1-sources.jar",
          "size": 14827,
          "sha512": "b26e7136df1894d888b2f12e2e74c34a37d297916f689f186db6e55052ac7f90b4f448850cb1ad2b2d6ccc4daa36f765d740fc773054e5ac2941d37d459653aa",
          "sha256": "6b813e321fe518f00312024523fb5b21d3a3d6100cebc9314e2aa8fb9214e3ed",
          "sha1": "b52b15eef847b1b4bcac396d514dd7ec5e2d0837",
          "md5": "f3e617b94fd0c111d3f8fcf895087f4f"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil-iosarm64-1.7.1-metadata.jar",
          "url": "DLLatLngUtil-iosarm64-1.7.1-metadata.jar",
          "size": 261,
          "sha512": "029edc4e24710026f8a74311e409b8d4bfa3b74c07328455d3239c061d2b707193dfdfb33bc9ad9c20188e88b26c65890a3ad03fd1b34ab4c5b7df4f614c6c51",
          "sha256": "fd273b85648d11bde3ab50a2435452beaad0a4f95779fe73443a0ce4d53c1f4e",
          "sha1": "6e17d71d23244bb42f6f8399b247bdd47f248dcb",
          "md5": "3ee993d2bf49afc7ffa6c332edb9f406"
        }
      ]
    }
  ]
}
