{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLAppUtil",
    "version": "2.4.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLAppUtil-2.4.8.aar",
          "url": "DLAppUtil-2.4.8.aar",
          "size": 133599,
          "sha512": "3e0fa07f637a7029498fd47dbe0403fd53484f19630974d8b969d15f0f5dd140c20c70f5319cb9e064eeee2756fcdd0d0f63d0057c613dc095862a0e1d64ca93",
          "sha256": "c46fba60cafc6d09014b1678e147e7ac9bf221d843c7a42b1a8bd731f391c90f",
          "sha1": "261c06eecc1122ede13170211179d86ad4a15677",
          "md5": "5197984112077c765f14ffadaaefb7c9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLAppUtil-2.4.8.aar",
          "url": "DLAppUtil-2.4.8.aar",
          "size": 133599,
          "sha512": "3e0fa07f637a7029498fd47dbe0403fd53484f19630974d8b969d15f0f5dd140c20c70f5319cb9e064eeee2756fcdd0d0f63d0057c613dc095862a0e1d64ca93",
          "sha256": "c46fba60cafc6d09014b1678e147e7ac9bf221d843c7a42b1a8bd731f391c90f",
          "sha1": "261c06eecc1122ede13170211179d86ad4a15677",
          "md5": "5197984112077c765f14ffadaaefb7c9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLAppUtil-2.4.8-sources.jar",
          "url": "DLAppUtil-2.4.8-sources.jar",
          "size": 36243,
          "sha512": "e452ba1fcb2801d666d92eecb3d88ab0310a30735e01e344338dd8c3d86cc2b88250584b01c7dc4e78cc851b221773515b8ecdc313f46ac8c6a1315e171b4a67",
          "sha256": "4fe2a75c85e554ef6f97a8729fbf53dce11577bb713040474d2893b051759fa3",
          "sha1": "7783b55c78a91de239cafb70bb144566ab2b8ad8",
          "md5": "dc17175009c745da0ce62ad37d2bed93"
        }
      ]
    }
  ]
}
