{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLMapboxUtil",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mapbox.maps",
          "module": "android",
          "version": {
            "requires": "10.19.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLMapboxUtil-1.3.0.aar",
          "url": "DLMapboxUtil-1.3.0.aar",
          "size": 766598,
          "sha512": "259e3870860b20111a8fea1f3d1c7b1ab0184bfb5954686b6a727d5aae03fbe744298a2ee96ae7ae8285d7642e2f1c5a1c9a0d1aa61873d50947522300badcaf",
          "sha256": "2de887a0ec0f40749fb0177b9362c8bb2e5d56d25f42bf9a8bf02464392eee52",
          "sha1": "1f4cb9398fbe1d62263a39f78102022f11fa3058",
          "md5": "858b7e3bc92fa5f6ab97b84f905489df"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.github.raamcosta.compose-destinations",
          "module": "animations-core",
          "version": {
            "requires": "1.11.9"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLJetpackComposeUtil",
          "version": {
            "requires": "2.0.31"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLAppUtil",
          "version": {
            "requires": "2.5.9"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLTianDiTuApi",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLDatastoreUtil",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.mapbox.maps",
          "module": "android",
          "version": {
            "requires": "10.19.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLMapboxUtil-1.3.0.aar",
          "url": "DLMapboxUtil-1.3.0.aar",
          "size": 766598,
          "sha512": "259e3870860b20111a8fea1f3d1c7b1ab0184bfb5954686b6a727d5aae03fbe744298a2ee96ae7ae8285d7642e2f1c5a1c9a0d1aa61873d50947522300badcaf",
          "sha256": "2de887a0ec0f40749fb0177b9362c8bb2e5d56d25f42bf9a8bf02464392eee52",
          "sha1": "1f4cb9398fbe1d62263a39f78102022f11fa3058",
          "md5": "858b7e3bc92fa5f6ab97b84f905489df"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLMapboxUtil-1.3.0-sources.jar",
          "url": "DLMapboxUtil-1.3.0-sources.jar",
          "size": 59281,
          "sha512": "4a62726e84d78089afc6f1bd7109aa8a25babbbf6f8b240bef933ab4b684f6507409412fcd9ed786fd66cf461e615c2375c3aef266e59f03e9216e2dd6d5b7f0",
          "sha256": "fbb706aba627c1c6300b64c7264324747ee12fa1ccb0e5da62b911fe3c89f82d",
          "sha1": "14826ba97e5a510e273e03a17d37688b9a4b82c2",
          "md5": "3aa1f4104313e8c5bbf635494e40d366"
        }
      ]
    }
  ]
}
