{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLAppUtil",
    "version": "2.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLAppUtil-2.2.3.aar",
          "url": "DLAppUtil-2.2.3.aar",
          "size": 204066,
          "sha512": "48d6645bf0327ada470b20862bb4faca8830f256bccd87b2160154350f9875f81d1e733557e45f0d71f8f0b0326a16c4aee8a461723270fd0946b57d7bae7f6f",
          "sha256": "4f40bed43d6751a2442893f46f1e7e23e35a41d2f076952a7af5570c674f952b",
          "sha1": "6a3f3c24069312dc170752dd45e369db902fed59",
          "md5": "22f9a2860a86c1b30b9d7d2191f8c2c8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLAppUtil-2.2.3.aar",
          "url": "DLAppUtil-2.2.3.aar",
          "size": 204066,
          "sha512": "48d6645bf0327ada470b20862bb4faca8830f256bccd87b2160154350f9875f81d1e733557e45f0d71f8f0b0326a16c4aee8a461723270fd0946b57d7bae7f6f",
          "sha256": "4f40bed43d6751a2442893f46f1e7e23e35a41d2f076952a7af5570c674f952b",
          "sha1": "6a3f3c24069312dc170752dd45e369db902fed59",
          "md5": "22f9a2860a86c1b30b9d7d2191f8c2c8"
        }
      ]
    }
  ]
}
