{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ImageCompress/1.1.0/ImageCompress-1.1.0.module",
    "group": "com.hailiao.util",
    "module": "ImageCompress",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "ImageCompress.klib",
          "url": "ImageCompress-linuxx64-1.1.0.klib",
          "size": 26678,
          "sha512": "c258b411201b98e1d469d0e9f2f1cfb7b2c0d2320f59615bb849e92b76a854757dd7ebce0db48bca614a7a2362aa2b0bf11c4c1afe8494870ea94b16edcf6bca",
          "sha256": "ef49f2194ee4caaed06cf72739bedf97f07748bd0e7844764e00479a8047a9af",
          "sha1": "4ad87d7a44725eaf831e05bf13b5b3245761dd24",
          "md5": "9d1ea1ded5cf7955c809f741e432db4a"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ImageCompress-linuxx64-1.1.0-sources.jar",
          "url": "ImageCompress-linuxx64-1.1.0-sources.jar",
          "size": 10026,
          "sha512": "ea4e94ac9f0edc34473cc9789ea612aba568344fd09e2e5424ff168c816ce307c773fa78906db05ada70922e1a940cf34f9fd05f1049989268313e234ce2f5ba",
          "sha256": "5c5efa5d064d62302a9bce272d415f5f5d024d7a05f044bcc77e6172388c2b45",
          "sha1": "ee0e5c3d0befc432a10892457057548fbc5993a2",
          "md5": "6599b6ddc6e1fcea4a75186bd86dbb24"
        }
      ]
    }
  ]
}
