{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLVoiceUtil/0.2.0/DLVoiceUtil-0.2.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLVoiceUtil",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "library-release.aar",
          "url": "DLVoiceUtil-android-0.2.0.aar",
          "size": 67946,
          "sha512": "019b5d0eda13b9edb939848067fd732824b525c9a5e9dba9c698df8866854895846d5bffd489908fd6e76e7f9f6d618c08544d2a0626611016400ca21d1d39b2",
          "sha256": "feb5af4740278c62da820258b8b1f5161a45632789c40f08d00c02b1db567bfb",
          "sha1": "553b52ae093533c78ac5375cd8f33ef580c28330",
          "md5": "0ddadba29a599b8ad127edbf23bc9492"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0-RC.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0-RC.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.5.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "library-release.aar",
          "url": "DLVoiceUtil-android-0.2.0.aar",
          "size": 67946,
          "sha512": "019b5d0eda13b9edb939848067fd732824b525c9a5e9dba9c698df8866854895846d5bffd489908fd6e76e7f9f6d618c08544d2a0626611016400ca21d1d39b2",
          "sha256": "feb5af4740278c62da820258b8b1f5161a45632789c40f08d00c02b1db567bfb",
          "sha1": "553b52ae093533c78ac5375cd8f33ef580c28330",
          "md5": "0ddadba29a599b8ad127edbf23bc9492"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "library-android-0.2.0-sources.jar",
          "url": "DLVoiceUtil-android-0.2.0-sources.jar",
          "size": 10761,
          "sha512": "ae9443e3ea112b9e1ccf39f52917efbb1747f9b6d572d61e81ecca069b1ed976fce2dc311aab02068ce7136517e52e0661bdaa1e9981e990fb3a3deb081d546d",
          "sha256": "d17e8ff38cc938559c2af77b2957167b1505be8b2946d020bdff7edf6289d7a2",
          "sha1": "033627f1bebb0430c2aedd382dfb9972564b0d84",
          "md5": "39e4d3ae57bae48a942f1f02800939fe"
        }
      ]
    }
  ]
}
