{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLJetpackComposeUtil",
    "version": "2.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2023.10.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.0-alpha13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-2.0.14.aar",
          "url": "DLJetpackComposeUtil-2.0.14.aar",
          "size": 1113664,
          "sha512": "7bcf818066636c0298a9f11448f37793b60923671cd63fac18ed00485020a4e4d20fc6a7c8848df6a6b8c0adc4f15d266e3592b84742364c44ffddacc64d1f39",
          "sha256": "f257d8c41cd589ebaa841ebf5e254e5abad7f15b965e4d84115d07c0bd17b2e8",
          "sha1": "3c1676da507c81b134f38ff142acac45ee1d2529",
          "md5": "e4d0558eed310d895ce425e05d012354"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.github.raamcosta.compose-destinations",
          "module": "animations-core",
          "version": {
            "requires": "1.9.62"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLDateUtil",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.0.8"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2023.10.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.0-alpha13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-2.0.14.aar",
          "url": "DLJetpackComposeUtil-2.0.14.aar",
          "size": 1113664,
          "sha512": "7bcf818066636c0298a9f11448f37793b60923671cd63fac18ed00485020a4e4d20fc6a7c8848df6a6b8c0adc4f15d266e3592b84742364c44ffddacc64d1f39",
          "sha256": "f257d8c41cd589ebaa841ebf5e254e5abad7f15b965e4d84115d07c0bd17b2e8",
          "sha1": "3c1676da507c81b134f38ff142acac45ee1d2529",
          "md5": "e4d0558eed310d895ce425e05d012354"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLJetpackComposeUtil-2.0.14-sources.jar",
          "url": "DLJetpackComposeUtil-2.0.14-sources.jar",
          "size": 77218,
          "sha512": "7ff79e0542e8233d450cf4265d08c8fa4f5e747dbf2080da4e2b0b6f999e0d5b3b736aa62153250746675eed4e9db12f4874b7a36fb8f87cc8b85a965a6fb158",
          "sha256": "4043a1005cb8870c6d6755f40c9e771b8c90ad5a7e6d1080ae67b93c0d9d082a",
          "sha1": "231190a9cb29a5d0aca05eddd8a74a7127d48674",
          "md5": "2c7775ae223bdc2bcefb14850f00e7b3"
        }
      ]
    }
  ]
}
