{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLHttpUtil/0.8.0/DLHttpUtil-0.8.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLHttpUtil",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLHttpUtil-jvm-0.8.0.jar",
          "url": "DLHttpUtil-jvm-0.8.0.jar",
          "size": 34373,
          "sha512": "bac46b6cb919129c1929bfec93739df865c23bf5aa4a481cdd1d38d6e809721127f9b632a6eae005048cf70284e5e2aa0035e379e0f763760bdece3a7dfaa1a4",
          "sha256": "9aa5a03512295ae4669a632ca7a48fcfe18586968765f1b26d6b606c2305456c",
          "sha1": "181a137d1b7ba90756c3ddfc5c542ca5cfb25779",
          "md5": "a9971095431a7566611c1131b7340b89"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLHttpUtil-jvm-0.8.0.jar",
          "url": "DLHttpUtil-jvm-0.8.0.jar",
          "size": 34373,
          "sha512": "bac46b6cb919129c1929bfec93739df865c23bf5aa4a481cdd1d38d6e809721127f9b632a6eae005048cf70284e5e2aa0035e379e0f763760bdece3a7dfaa1a4",
          "sha256": "9aa5a03512295ae4669a632ca7a48fcfe18586968765f1b26d6b606c2305456c",
          "sha1": "181a137d1b7ba90756c3ddfc5c542ca5cfb25779",
          "md5": "a9971095431a7566611c1131b7340b89"
        }
      ]
    }
  ]
}
