{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLBluetoothUtil/0.1.15/DLBluetoothUtil-0.1.15.module",
    "group": "com.github.D10NGYANG",
    "module": "DLBluetoothUtil",
    "version": "0.1.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0-RC.2"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "DLBluetoothUtil.klib",
          "url": "DLBluetoothUtil-iosarm64-0.1.15.klib",
          "size": 61197,
          "sha512": "deea46cc6d94fe0f4fc4a15f2fd95784219e12bf54ffad624af4bb7215cb31b921df60c478cf848b805c4be2ecb563f32b1bdfb2dc74b57418256b954f6ffab9",
          "sha256": "ba33fc8a59bf691d325a2f525347bd96ef839916a09aa3ecdadc6347ea88ae85",
          "sha1": "47befb0617d45e48110cdee3ba33fb15fe02269d",
          "md5": "89a37af33e68a8737d2a51067b3682d6"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLBluetoothUtil-iosarm64-0.1.15-sources.jar",
          "url": "DLBluetoothUtil-iosarm64-0.1.15-sources.jar",
          "size": 9751,
          "sha512": "69b6cc428c4bfb3a1306ef316e20691b1db54e35b0f510c5384ce316fa868f7e156d299e0faf31d116239f5c185e42672953d47fc16848708c9fc1d0bea1c795",
          "sha256": "b001272f370a225e9494ff22c1ae28462bdb26bddd66f35eebd3ea811bc2fc66",
          "sha1": "072a19e50a8f3f55e7d7142adff59351d4057439",
          "md5": "2378d67be4a24f609c7eb67b47e792cd"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0-RC.2"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "DLBluetoothUtil-iosarm64-0.1.15-metadata.jar",
          "url": "DLBluetoothUtil-iosarm64-0.1.15-metadata.jar",
          "size": 261,
          "sha512": "fc3218c6bd92db4be3ccd2358520096cf6373abbd5710e12b4d458e5ad6886970b000835624b6355b3dd988b08dbfdd4bd2dcfd30fff316fb32fb403c976b8db",
          "sha256": "5be02ca5f2d86541cd7ff720865c3dc42bbd5d45c878012454f9ead6fb89b14a",
          "sha1": "68c6b44b2cffe25098008c0c4837f08c7ef9b18a",
          "md5": "36833d2ac56da7104bc23712ed2fe21f"
        }
      ]
    }
  ]
}
