{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLVoiceUtil/0.2.2/DLVoiceUtil-0.2.2.module",
    "group": "com.github.D10NGYANG",
    "module": "DLVoiceUtil",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "library-release.aar",
          "url": "DLVoiceUtil-android-0.2.2.aar",
          "size": 67943,
          "sha512": "f791a7aea8ba3cb33ccb447873f5049eaa755a32c687242b06712ec57cd8b0084c424e5f153375bd9fc76eab7de8981121816d321c301750bbf4d6b0d5c77270",
          "sha256": "9e3c48ae8821d959aafc979745e0602a5ab30879a8a2de2201a1f9b2fd13fd83",
          "sha1": "b6534f3cf8edbd0ecede25e6116d622b698083c1",
          "md5": "05396d1bed970aeecb18bef6e35cdd2c"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0-RC.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0-RC.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.5.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "library-release.aar",
          "url": "DLVoiceUtil-android-0.2.2.aar",
          "size": 67943,
          "sha512": "f791a7aea8ba3cb33ccb447873f5049eaa755a32c687242b06712ec57cd8b0084c424e5f153375bd9fc76eab7de8981121816d321c301750bbf4d6b0d5c77270",
          "sha256": "9e3c48ae8821d959aafc979745e0602a5ab30879a8a2de2201a1f9b2fd13fd83",
          "sha1": "b6534f3cf8edbd0ecede25e6116d622b698083c1",
          "md5": "05396d1bed970aeecb18bef6e35cdd2c"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "library-android-0.2.2-sources.jar",
          "url": "DLVoiceUtil-android-0.2.2-sources.jar",
          "size": 10761,
          "sha512": "c3ad9788d008d801869888bbacb7c03b79c9a66c10e72a3689c17284afd0cbffbd1efeda75e5b41be40510044cd12187fda9f17147eca4940b0d9baa49d419c0",
          "sha256": "313154f5b1ae46fd480796ab9bb380d0cb869f45a92804dfd8712a85c09670af",
          "sha1": "8a9fa1024af8724414a5a9e3b5e53912279f4556",
          "md5": "08c9afc8dd0c7ee579c65ccf6bd9a5cf"
        }
      ]
    }
  ]
}
