{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLLogUtil/0.1.1/DLLogUtil-0.1.1.module",
    "group": "com.github.D10NGYANG",
    "module": "DLLogUtil",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLLogUtil-js-0.1.1.klib",
          "url": "DLLogUtil-js-0.1.1.klib",
          "size": 15923,
          "sha512": "444d7aab5772fad0b21b269f2ca3773dd7d7f8a47922382210c19f7255ca3f8f258e8c942ad4350653b7e9a330a95c02df8ab8b068de095a69f1267245c10a17",
          "sha256": "8a582c82845f041f7ebb852881bafcdce26f5fdef67994e19441b1e004e5ea0d",
          "sha1": "cac01770a7ab726ce4202c0981fde4565cadf816",
          "md5": "8272b2de5c6b413b12352189fe245443"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "DLLogUtil-js-0.1.1.klib",
          "url": "DLLogUtil-js-0.1.1.klib",
          "size": 15923,
          "sha512": "444d7aab5772fad0b21b269f2ca3773dd7d7f8a47922382210c19f7255ca3f8f258e8c942ad4350653b7e9a330a95c02df8ab8b068de095a69f1267245c10a17",
          "sha256": "8a582c82845f041f7ebb852881bafcdce26f5fdef67994e19441b1e004e5ea0d",
          "sha1": "cac01770a7ab726ce4202c0981fde4565cadf816",
          "md5": "8272b2de5c6b413b12352189fe245443"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "DLLogUtil-js-0.1.1-sources.jar",
          "url": "DLLogUtil-js-0.1.1-sources.jar",
          "size": 4328,
          "sha512": "f6d1316bb2907056439f42ad9f96da7602aec0837f920314a3da0eda1fb913f2ef8a3c03fa2511fca2be671a42089ab72b18c474b4b92903f4d69b330a3a01f0",
          "sha256": "5e9f13b6d4a8e81a567e5e52871ae92cbe5484e5b20f495f6655d2a59e395292",
          "sha1": "375977dd800152ef024414f5953a665a93055a0f",
          "md5": "6dcdcc113507cb678efda95c264ceafb"
        }
      ]
    }
  ]
}
