{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLBluetoothUtil/0.4.0/DLBluetoothUtil-0.4.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLBluetoothUtil",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLBluetoothUtil-iosArm64Main-0.4.0.klib",
          "url": "DLBluetoothUtil-iosarm64-0.4.0.klib",
          "size": 77854,
          "sha512": "5c87f763c7bfbaf84e136d1f8e1eb7867ee83f177744a39c0c9075d86dda00808125dff44dded2cb2e01e4b825e732783bbcd9146814d1000c843a3872a3eb54",
          "sha256": "f58c426283e960669c6284878b5d7fc76b78ebf091545c41a5fc503fa19d6955",
          "sha1": "4be367174f677701f801082605c36abe7112f9dd",
          "md5": "3864d870bc3b8e286dc3e55b2960db0f"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLBluetoothUtil-iosarm64-0.4.0-sources.jar",
          "url": "DLBluetoothUtil-iosarm64-0.4.0-sources.jar",
          "size": 11812,
          "sha512": "d96ce8fe60f7b423fdc6e79b4d95bc45a4bff3b44517572633635a329830a41539cb81c9af46258bdcbc77c80a5675a8bf2475ff2a29f43858255221119a335d",
          "sha256": "f85be25cd8a420580624ea293300525c1ba71238cf8a7eaa6ab24e239c394ab2",
          "sha1": "63e90938e484d5ce4f872a619b76742c1f78eec1",
          "md5": "d0466dc1fdf8298bf752a1416f883c0d"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLBluetoothUtil-iosarm64-0.4.0-metadata.jar",
          "url": "DLBluetoothUtil-iosarm64-0.4.0-metadata.jar",
          "size": 261,
          "sha512": "698c57dae61016d5664f1a69ffd326f8749971a5dc0deaff8b8ee932cddcef5bde27912cbaed1374386a931401eec3e3bc5d1105b31c0ecfccfefd61bcd01978",
          "sha256": "dff6b2e2c399b37575bba4b4cfd2627cc9e3b9e6eae0fd48682c49004527f8bf",
          "sha1": "b2ccf3649dfc7b9d02e05303bb473149683bf7a5",
          "md5": "4c28da3d2e9a542e465e0c87643880d2"
        }
      ]
    }
  ]
}
