{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLCryptoUtil/0.0.6/DLCryptoUtil-0.0.6.module",
    "group": "com.github.D10NGYANG",
    "module": "DLCryptoUtil",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLCryptoUtil-js-0.0.6.klib",
          "url": "DLCryptoUtil-js-0.0.6.klib",
          "size": 27325,
          "sha512": "1fbb21e85ef9b1ea87def950472ecf7afc7137df0726ddb68c5c2ab323abb876bdb2d98df835e84980be341a41674089c54a9aab26b6006f5ef6e33db572fc39",
          "sha256": "de43e552f6e72e486876a565c37eaf5a3ddfe5c40cc4d426003469604715a652",
          "sha1": "e2a61f4f09298094f5ef31e95c1e49a2b4deef3a",
          "md5": "6de7bbbb784c59d24d56428259218824"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLCryptoUtil-js-0.0.6.klib",
          "url": "DLCryptoUtil-js-0.0.6.klib",
          "size": 27325,
          "sha512": "1fbb21e85ef9b1ea87def950472ecf7afc7137df0726ddb68c5c2ab323abb876bdb2d98df835e84980be341a41674089c54a9aab26b6006f5ef6e33db572fc39",
          "sha256": "de43e552f6e72e486876a565c37eaf5a3ddfe5c40cc4d426003469604715a652",
          "sha1": "e2a61f4f09298094f5ef31e95c1e49a2b4deef3a",
          "md5": "6de7bbbb784c59d24d56428259218824"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "DLCryptoUtil-js-0.0.6-sources.jar",
          "url": "DLCryptoUtil-js-0.0.6-sources.jar",
          "size": 7793,
          "sha512": "6da7da6115d0435644c0f8582e6586f2507a7ced767ce27c96017adee51918c674c5780db57595d6e315b6a3fc8bb29d1313635e4a334d1372a57587b1d2f26e",
          "sha256": "c22a28dfb85c9b7242092f0993a50244410242ff9b1af0cee8a9c490072d8cff",
          "sha1": "861dd8fff50790c29cccd962856388ed8b3997aa",
          "md5": "0f6d9a453bddb58fe2d1a7c3fe3734cc"
        }
      ]
    }
  ]
}
