{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLBluetoothUtil/0.6.2/DLBluetoothUtil-0.6.2.module",
    "group": "com.github.D10NGYANG",
    "module": "DLBluetoothUtil",
    "version": "0.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "DLBluetoothUtil-js-0.6.2.klib",
          "url": "DLBluetoothUtil-js-0.6.2.klib",
          "size": 52994,
          "sha512": "7f63768e1bd31de10d9a121c41d03bd0ad5e3f6510acbbf586304c3d08555d73f82f4d1e378a95748b3ad06e8c344c817ecde1b47a378f91c9cfe9102ac4f8cb",
          "sha256": "63270bfbc0d661e8b438f0c3608df694dac3382b84f4e921542bb34dbbd85607",
          "sha1": "4240deee2b825fea538682389b648f50673696de",
          "md5": "2be1ce4c0e05371a0d8b378c3c73e0d4"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLLogUtil",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLBluetoothUtil-js-0.6.2.klib",
          "url": "DLBluetoothUtil-js-0.6.2.klib",
          "size": 52994,
          "sha512": "7f63768e1bd31de10d9a121c41d03bd0ad5e3f6510acbbf586304c3d08555d73f82f4d1e378a95748b3ad06e8c344c817ecde1b47a378f91c9cfe9102ac4f8cb",
          "sha256": "63270bfbc0d661e8b438f0c3608df694dac3382b84f4e921542bb34dbbd85607",
          "sha1": "4240deee2b825fea538682389b648f50673696de",
          "md5": "2be1ce4c0e05371a0d8b378c3c73e0d4"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "DLBluetoothUtil-js-0.6.2-sources.jar",
          "url": "DLBluetoothUtil-js-0.6.2-sources.jar",
          "size": 12836,
          "sha512": "d72f623df59e05b1698b0b2d13a5a8283dff7f98e9a523fc1ea5bf9b91da3982a8e36dfefc6193aa8e902f225dabc1a0de091b98cbd1621565486385f088d5aa",
          "sha256": "1c54df503c7565797a7d673b95619d8b423f80d9472e19d868e47aa7b96cdd36",
          "sha1": "55332507572da71719321bccd036c6dc71da10f0",
          "md5": "805c58dd8bfc83db4490e43ce100979e"
        }
      ]
    }
  ]
}
