{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/2.3.0-alpha01/DLDateUtil-2.3.0-alpha01.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "2.3.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-iosX64Main-2.3.0-alpha01.klib",
          "url": "DLDateUtil-iosx64-2.3.0-alpha01.klib",
          "size": 92653,
          "sha512": "2cf2a822238a78139fd7de05c792300b1f06c9a39f4c2dde0ed5641e177656efc2e1a73115b5f9d8d79f2e48be1859803f573203da78ee2c48df36147155079c",
          "sha256": "a0ec7e2aad377f585948f57f7ca63b6e969e86b41b2c4a06aac0d2bcae4ffc0c",
          "sha1": "a9bceb0b6634031e68b6b7beb48ff76fc4365d50",
          "md5": "7b6bbd951ef0321acffc315f53e48e69"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLDateUtil-iosx64-2.3.0-alpha01-sources.jar",
          "url": "DLDateUtil-iosx64-2.3.0-alpha01-sources.jar",
          "size": 20711,
          "sha512": "1a7e2c8a7d2d19933ecf19c7c3b0f11c25e7608b4dedd5b086e4f5d789dd4aa4d9f9dd62c04193cda628ad50f2c9054fa2f3ce25a32231edb209722cc1f45861",
          "sha256": "3226355c59e086e941ccde3df5dc183c94fee93de7e471d1f0dc38165205d03e",
          "sha1": "6b6911ce395d0504143be31a704f369eb86dd172",
          "md5": "3373755ef4b3167533a70abb517304c3"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-iosx64-2.3.0-alpha01-metadata.jar",
          "url": "DLDateUtil-iosx64-2.3.0-alpha01-metadata.jar",
          "size": 261,
          "sha512": "430ae1752aaf9cf8a50f1874a151f77bcdf731743ad78dfaac9c06f3b2a681399c0f85f3810351f1243f1056c0c4798c9e1643d24a9102c9912ab18eae0b7cf3",
          "sha256": "6d5727bc23d7ce83478d3f2fcb9b73cd8ee2c458a3e799f7ddf1572db330287d",
          "sha1": "5e72a99dc29df28a7aec7164c5dc6a50525d21fc",
          "md5": "779ec63bd134e91b24ad8da72dbef49a"
        }
      ]
    }
  ]
}
