{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLCommonUtil/0.0.9/DLCommonUtil-0.0.9.module",
    "group": "com.github.D10NGYANG",
    "module": "DLCommonUtil",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.github.biezhi",
          "module": "TinyPinyin",
          "version": {
            "requires": "2.0.3.RELEASE"
          }
        },
        {
          "group": "com.ditchoom",
          "module": "buffer",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-release.aar",
          "url": "DLCommonUtil-android-0.0.9.aar",
          "size": 55704,
          "sha512": "168dee189606406354d0d7e51e78e420901c5c2267b075cb540d9e488d316456ff1fb1542a5d58e452471e1874a8eec8d99c512cac65a0e27f06ff47f0a6a954",
          "sha256": "b075292f413989b3922738af863034aa51affae876eb767ed36b875aab60c76e",
          "sha1": "81f8a62c2005b5ac463f3d07a2901744f2e8c87d",
          "md5": "1812a773107af22050ba0b508eab356f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.github.biezhi",
          "module": "TinyPinyin",
          "version": {
            "requires": "2.0.3.RELEASE"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.ditchoom",
          "module": "buffer",
          "version": {
            "requires": "1.3.7"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-release.aar",
          "url": "DLCommonUtil-android-0.0.9.aar",
          "size": 55704,
          "sha512": "168dee189606406354d0d7e51e78e420901c5c2267b075cb540d9e488d316456ff1fb1542a5d58e452471e1874a8eec8d99c512cac65a0e27f06ff47f0a6a954",
          "sha256": "b075292f413989b3922738af863034aa51affae876eb767ed36b875aab60c76e",
          "sha1": "81f8a62c2005b5ac463f3d07a2901744f2e8c87d",
          "md5": "1812a773107af22050ba0b508eab356f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "DLCommonUtil-android-0.0.9-sources.jar",
          "url": "DLCommonUtil-android-0.0.9-sources.jar",
          "size": 28462,
          "sha512": "c3a32b2dacc55f6d198be76058795debec429dc7289278dc4d307bd400343d71243ed3023d9a0cab6091e2533a1e9023532ff3f3ecb7fb013f2e86b552879bee",
          "sha256": "51af75dc11b81c206576c83cc71f774f4b3901d8a22fb634f3f84e1581ef6c60",
          "sha1": "c8748e86b1947d3b6a1de9b90db033e28f7e1cfb",
          "md5": "c58ada43e7cdde0d80657af3a1488843"
        }
      ]
    }
  ]
}
