{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLCommonUtil",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-metadata-0.1.1.jar",
          "url": "DLCommonUtil-0.1.1.jar",
          "size": 10484,
          "sha512": "90a105500f2149722894fff3bdbc381e941b1e45c9ecb264bdb7707422ecc20014c97470b4a57cb22bbdecbbc6d3a4dc36881a099162880c2b3b63cf0d32ab2c",
          "sha256": "9f7e96138eda982afa40013fc44c8aa1501a281677be77ef7987388a1af27d47",
          "sha1": "2e7acf023ba0d32c3e049587e2784817ee8c2ed4",
          "md5": "2475f0410eb67c8a012343860ae30a96"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "DLCommonUtil-kotlin-0.1.1-sources.jar",
          "url": "DLCommonUtil-0.1.1-sources.jar",
          "size": 28929,
          "sha512": "4b03b86dbba21ea75f2b083d0896ae999a20f3fe695dce54b20c5cf2aa751e4f280716d926a998f3cc8a7fd5f671fcb753b3015e91e792dadaded4cb003372db",
          "sha256": "e6378a3f86f04a10551926279773cd75b85a0b3fba9e1833fac0ab7754315133",
          "sha1": "c5865b48c540c7c26abd2edebc5f2f0436ff0216",
          "md5": "0e0bf6e0afb21675ced38c8f1626aa0a"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLCommonUtil-android/0.1.1/DLCommonUtil-android-0.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-android",
        "version": "0.1.1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLCommonUtil-android/0.1.1/DLCommonUtil-android-0.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-android",
        "version": "0.1.1"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLCommonUtil-android/0.1.1/DLCommonUtil-android-0.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-android",
        "version": "0.1.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCommonUtil-iosarm64/0.1.1/DLCommonUtil-iosarm64-0.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-iosarm64",
        "version": "0.1.1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCommonUtil-iosarm64/0.1.1/DLCommonUtil-iosarm64-0.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-iosarm64",
        "version": "0.1.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCommonUtil-iosarm64/0.1.1/DLCommonUtil-iosarm64-0.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-iosarm64",
        "version": "0.1.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCommonUtil-iossimulatorarm64/0.1.1/DLCommonUtil-iossimulatorarm64-0.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-iossimulatorarm64",
        "version": "0.1.1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCommonUtil-iossimulatorarm64/0.1.1/DLCommonUtil-iossimulatorarm64-0.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-iossimulatorarm64",
        "version": "0.1.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCommonUtil-iossimulatorarm64/0.1.1/DLCommonUtil-iossimulatorarm64-0.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-iossimulatorarm64",
        "version": "0.1.1"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLCommonUtil-js/0.1.1/DLCommonUtil-js-0.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-js",
        "version": "0.1.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLCommonUtil-js/0.1.1/DLCommonUtil-js-0.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-js",
        "version": "0.1.1"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLCommonUtil-js/0.1.1/DLCommonUtil-js-0.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-js",
        "version": "0.1.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLCommonUtil-jvm/0.1.1/DLCommonUtil-jvm-0.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-jvm",
        "version": "0.1.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLCommonUtil-jvm/0.1.1/DLCommonUtil-jvm-0.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-jvm",
        "version": "0.1.1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLCommonUtil-jvm/0.1.1/DLCommonUtil-jvm-0.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-jvm",
        "version": "0.1.1"
      }
    }
  ]
}
