{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLLatLngUtil",
    "version": "1.7.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil-metadata-1.7.4.jar",
          "url": "DLLatLngUtil-1.7.4.jar",
          "size": 7109,
          "sha512": "d58f49dea4f710bdcf22c27787a3d5c06cf9749cca19f79013c902b6416598395e7d4ac33aeea80556fd28648582cc4f668e0b87bd68bb43aa332e8a27105c11",
          "sha256": "32c91150086cb600800ad0cc95e4c984adb9b71fc05203f173e9e4bbe5b2cb0d",
          "sha1": "90dbc2b4980be80949e2cabaff5510c0082b9e74",
          "md5": "3e785508d96b02df7d8fea0f374cf068"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "DLLatLngUtil-kotlin-1.7.4-sources.jar",
          "url": "DLLatLngUtil-1.7.4-sources.jar",
          "size": 14827,
          "sha512": "b26e7136df1894d888b2f12e2e74c34a37d297916f689f186db6e55052ac7f90b4f448850cb1ad2b2d6ccc4daa36f765d740fc773054e5ac2941d37d459653aa",
          "sha256": "6b813e321fe518f00312024523fb5b21d3a3d6100cebc9314e2aa8fb9214e3ed",
          "sha1": "b52b15eef847b1b4bcac396d514dd7ec5e2d0837",
          "md5": "f3e617b94fd0c111d3f8fcf895087f4f"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLLatLngUtil-iosarm64/1.7.4/DLLatLngUtil-iosarm64-1.7.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLLatLngUtil-iosarm64",
        "version": "1.7.4"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLLatLngUtil-iosarm64/1.7.4/DLLatLngUtil-iosarm64-1.7.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLLatLngUtil-iosarm64",
        "version": "1.7.4"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLLatLngUtil-iosarm64/1.7.4/DLLatLngUtil-iosarm64-1.7.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLLatLngUtil-iosarm64",
        "version": "1.7.4"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLLatLngUtil-iosx64/1.7.4/DLLatLngUtil-iosx64-1.7.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLLatLngUtil-iosx64",
        "version": "1.7.4"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLLatLngUtil-iosx64/1.7.4/DLLatLngUtil-iosx64-1.7.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLLatLngUtil-iosx64",
        "version": "1.7.4"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLLatLngUtil-iosx64/1.7.4/DLLatLngUtil-iosx64-1.7.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLLatLngUtil-iosx64",
        "version": "1.7.4"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLLatLngUtil-js/1.7.4/DLLatLngUtil-js-1.7.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLLatLngUtil-js",
        "version": "1.7.4"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLLatLngUtil-js/1.7.4/DLLatLngUtil-js-1.7.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLLatLngUtil-js",
        "version": "1.7.4"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLLatLngUtil-js/1.7.4/DLLatLngUtil-js-1.7.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLLatLngUtil-js",
        "version": "1.7.4"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLLatLngUtil-jvm/1.7.4/DLLatLngUtil-jvm-1.7.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLLatLngUtil-jvm",
        "version": "1.7.4"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLLatLngUtil-jvm/1.7.4/DLLatLngUtil-jvm-1.7.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLLatLngUtil-jvm",
        "version": "1.7.4"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLLatLngUtil-jvm/1.7.4/DLLatLngUtil-jvm-1.7.4.module",
        "group": "com.github.D10NGYANG",
        "module": "DLLatLngUtil-jvm",
        "version": "1.7.4"
      }
    }
  ]
}
