{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/1.9.1/DLDateUtil-1.9.1.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "1.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-js-1.9.1.klib",
          "url": "DLDateUtil-js-1.9.1.klib",
          "size": 61112,
          "sha512": "ab60c9d0789fd5b72f354c438b0d676de3c81eea7a4a307ec01d399986ebd2d943c50af13d0607b5bc05c3ae03a75c75784188e57b076409aa2e44ba7c9b1cc0",
          "sha256": "dc25d3c7fc0d064caf195f8b8b9a21e5a622dc6796fc38bc1295602d8024c9e1",
          "sha1": "a697fb753e30c5802d4c10331fc6b7fe6ec0f3ca",
          "md5": "822d44fc782c6109e35e3e7fd2e3f2a8"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-js-1.9.1.klib",
          "url": "DLDateUtil-js-1.9.1.klib",
          "size": 61112,
          "sha512": "ab60c9d0789fd5b72f354c438b0d676de3c81eea7a4a307ec01d399986ebd2d943c50af13d0607b5bc05c3ae03a75c75784188e57b076409aa2e44ba7c9b1cc0",
          "sha256": "dc25d3c7fc0d064caf195f8b8b9a21e5a622dc6796fc38bc1295602d8024c9e1",
          "sha1": "a697fb753e30c5802d4c10331fc6b7fe6ec0f3ca",
          "md5": "822d44fc782c6109e35e3e7fd2e3f2a8"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "DLDateUtil-js-1.9.1-sources.jar",
          "url": "DLDateUtil-js-1.9.1-sources.jar",
          "size": 12454,
          "sha512": "00fde855d7981466d1f24fb3bb6a4d725f1b21971316c5e652c5d73b299169ed39bdc3911822c05d741ed7ffb654eecbf0ac7b22377c6130a4e93f1cf1b4ef10",
          "sha256": "50a02fb9f3baffe6a8eae568f372c2e89b4dbc6a93f2e7ec1bc92776455dd876",
          "sha1": "c3870c3d4fcb51101e193db107d0604506248b80",
          "md5": "ba98566f91acc795a2ae24a029af97ec"
        }
      ]
    }
  ]
}
