{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/2.1.3/DLDateUtil-2.1.3.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "2.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-linuxX64Main-2.1.3.klib",
          "url": "DLDateUtil-linuxx64-2.1.3.klib",
          "size": 78194,
          "sha512": "c0a8ea7cb18472682b1db6cd471a64c5e89b24fc4776faa41131aa4bc1d9de0cd8018bcd88ec852a56a7d67123eb295fba3b6b930b94d99f9c858540794b530b",
          "sha256": "89813fe69e7a8668a84a943c588d50f98d09132a266d2990399172b06d4b34dc",
          "sha1": "76d369f2d217d0ff4d829a0e357d919705791839",
          "md5": "db75bd560c4e0d988f9444f03846480c"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLDateUtil-linuxx64-2.1.3-sources.jar",
          "url": "DLDateUtil-linuxx64-2.1.3-sources.jar",
          "size": 17463,
          "sha512": "bb3a3993bfaa48011c2d827153ee6aae326cf05d78463575db2b23bb4a1a7ebc39398d491c3419e5ab885bc296b5143445d65e6b401b06f887bfb7bb07946d4a",
          "sha256": "352121accf74b1ebeb34dc8f64c47432bd58599aec2da3583910e2d2d610ef88",
          "sha1": "afe3c7b840c6185cf4647bc72c46a6a6974bcf89",
          "md5": "b005d5f34aec98f5aac50d1c0877c39c"
        }
      ]
    }
  ]
}
