{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLPcmResampleUtil/0.2.5/DLPcmResampleUtil-0.2.5.module",
    "group": "com.github.D10NGYANG",
    "module": "DLPcmResampleUtil",
    "version": "0.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLPcmResampleUtil-release.aar",
          "url": "DLPcmResampleUtil-android-0.2.5.aar",
          "size": 63490,
          "sha512": "d4982273c868974525a298660a165e63261c7540c428781ffb2219cad314d62c113878049e0fc0416fc03e7155e07648b5e8190801c776e43f82781add80ea7a",
          "sha256": "1cd1072c19f79dcfda5dc700af9cca37ae50ec830e36f4e643c569b5ea2e06d9",
          "sha1": "d686e1849e4af8d12d8654c2f82ec581e6e05feb",
          "md5": "64b6912d11f90cc4a4047068f445d8ad"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.7.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "DLPcmResampleUtil-release.aar",
          "url": "DLPcmResampleUtil-android-0.2.5.aar",
          "size": 63490,
          "sha512": "d4982273c868974525a298660a165e63261c7540c428781ffb2219cad314d62c113878049e0fc0416fc03e7155e07648b5e8190801c776e43f82781add80ea7a",
          "sha256": "1cd1072c19f79dcfda5dc700af9cca37ae50ec830e36f4e643c569b5ea2e06d9",
          "sha1": "d686e1849e4af8d12d8654c2f82ec581e6e05feb",
          "md5": "64b6912d11f90cc4a4047068f445d8ad"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "DLPcmResampleUtil-android-0.2.5-sources.jar",
          "url": "DLPcmResampleUtil-android-0.2.5-sources.jar",
          "size": 29527,
          "sha512": "1a194d4e2857f7193e66f10520343b3936df7d348c00f3bda215e19056c48944d24e2e5f729ca375935618e6184615c890426f7d23562f343c79ee8acc1c407c",
          "sha256": "a5c1d6a53b898b6678bd2f030f75dd7fce53899ecf8781f4487223aaca919e51",
          "sha1": "3f9636b6b03ac896e64cca4922a78ef7598e1877",
          "md5": "32d19eca613b0166d22c4fd22eb7f266"
        }
      ]
    }
  ]
}
