{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLBluetoothUtil/0.8.0/DLBluetoothUtil-0.8.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLBluetoothUtil",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "DLBluetoothUtil-wasm-js-0.8.0.klib",
          "url": "DLBluetoothUtil-wasm-js-0.8.0.klib",
          "size": 65134,
          "sha512": "6e4f67ceb8a88ea48c085561c1ca55be35c01ffe1405c65ec9bf4885401e603717c8423ce325a5b0571b6d4f631202b2339af51983d855a8ac4dab8a323fd93a",
          "sha256": "6eda030a858b89eab809208e0794ed1ff1bed228d67ea2f009984a66ed8f3774",
          "sha1": "69cf2534787bc60319c4a2212183de0d17f3ee88",
          "md5": "3738dffa7d4a89cf04d2ff983283e11b"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLLogUtil",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLBluetoothUtil-wasm-js-0.8.0.klib",
          "url": "DLBluetoothUtil-wasm-js-0.8.0.klib",
          "size": 65134,
          "sha512": "6e4f67ceb8a88ea48c085561c1ca55be35c01ffe1405c65ec9bf4885401e603717c8423ce325a5b0571b6d4f631202b2339af51983d855a8ac4dab8a323fd93a",
          "sha256": "6eda030a858b89eab809208e0794ed1ff1bed228d67ea2f009984a66ed8f3774",
          "sha1": "69cf2534787bc60319c4a2212183de0d17f3ee88",
          "md5": "3738dffa7d4a89cf04d2ff983283e11b"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "DLBluetoothUtil-wasm-js-0.8.0-sources.jar",
          "url": "DLBluetoothUtil-wasm-js-0.8.0-sources.jar",
          "size": 14829,
          "sha512": "c029d3e91f4d7b27a6cf25f4979ea2de87248c6028cdb53e6eac815289b2d735714a006de44bb211be34d7cbe2b88b70585396dc64d4dc627939bd18737621a7",
          "sha256": "617fbf8905579da69e714b8263be17af8147a36ae28a45f19336168790900c76",
          "sha1": "288a70cdc7ef09f1893aea639c3bb3ac3d67ade4",
          "md5": "4fc4842b97471d61f69d6c62b05eef08"
        }
      ]
    }
  ]
}
