{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLTianDiTuApi",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLTianDiTuApi-metadata-1.1.0.jar",
          "url": "DLTianDiTuApi-1.1.0.jar",
          "size": 11015,
          "sha512": "f94093b484bb57501cde3e02e1d724e6fb26392d4b847865468f099aac03d0f17f66f34d467ba6459aba1e7ecc82a4ff44e0899772d6c0d98eec9d51930d8451",
          "sha256": "1578a7b9dc1f67e26b7b4a26d0640734d6cafccf72c9ea0fe6455ba54cc39a34",
          "sha1": "8903c85e07718cb05635431a573851413edd3f0d",
          "md5": "fe29ad8f86091554030504bbc5f75bcf"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "DLTianDiTuApi-kotlin-1.1.0-sources.jar",
          "url": "DLTianDiTuApi-1.1.0-sources.jar",
          "size": 6741,
          "sha512": "e995fd07814e5a74a95204d799c654f7da718945c0da9e007b32c722f6f66af2530e821b6ae755d000b3f768b7ed5f5ba48599211dc0e8bed8834ec08ff7e6b0",
          "sha256": "0414baa275caeb80f95cda9aeef4ed8055384c749dae672dafeea476dc9d8b9c",
          "sha1": "0828114131dafc5114da91d86d312e29b9883d3e",
          "md5": "13050d4174ed636150e82130e94bd601"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLTianDiTuApi-iosarm64/1.1.0/DLTianDiTuApi-iosarm64-1.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLTianDiTuApi-iosarm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLTianDiTuApi-iosarm64/1.1.0/DLTianDiTuApi-iosarm64-1.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLTianDiTuApi-iosarm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLTianDiTuApi-iosarm64/1.1.0/DLTianDiTuApi-iosarm64-1.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLTianDiTuApi-iosarm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLTianDiTuApi-iossimulatorarm64/1.1.0/DLTianDiTuApi-iossimulatorarm64-1.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLTianDiTuApi-iossimulatorarm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLTianDiTuApi-iossimulatorarm64/1.1.0/DLTianDiTuApi-iossimulatorarm64-1.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLTianDiTuApi-iossimulatorarm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLTianDiTuApi-iossimulatorarm64/1.1.0/DLTianDiTuApi-iossimulatorarm64-1.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLTianDiTuApi-iossimulatorarm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLTianDiTuApi-iosx64/1.1.0/DLTianDiTuApi-iosx64-1.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLTianDiTuApi-iosx64",
        "version": "1.1.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLTianDiTuApi-iosx64/1.1.0/DLTianDiTuApi-iosx64-1.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLTianDiTuApi-iosx64",
        "version": "1.1.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLTianDiTuApi-iosx64/1.1.0/DLTianDiTuApi-iosx64-1.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLTianDiTuApi-iosx64",
        "version": "1.1.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLTianDiTuApi-js/1.1.0/DLTianDiTuApi-js-1.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLTianDiTuApi-js",
        "version": "1.1.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLTianDiTuApi-js/1.1.0/DLTianDiTuApi-js-1.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLTianDiTuApi-js",
        "version": "1.1.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLTianDiTuApi-js/1.1.0/DLTianDiTuApi-js-1.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLTianDiTuApi-js",
        "version": "1.1.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLTianDiTuApi-jvm/1.1.0/DLTianDiTuApi-jvm-1.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLTianDiTuApi-jvm",
        "version": "1.1.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLTianDiTuApi-jvm/1.1.0/DLTianDiTuApi-jvm-1.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLTianDiTuApi-jvm",
        "version": "1.1.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLTianDiTuApi-jvm/1.1.0/DLTianDiTuApi-jvm-1.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLTianDiTuApi-jvm",
        "version": "1.1.0"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLTianDiTuApi-linuxarm64/1.1.0/DLTianDiTuApi-linuxarm64-1.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLTianDiTuApi-linuxarm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLTianDiTuApi-linuxarm64/1.1.0/DLTianDiTuApi-linuxarm64-1.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLTianDiTuApi-linuxarm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLTianDiTuApi-linuxx64/1.1.0/DLTianDiTuApi-linuxx64-1.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLTianDiTuApi-linuxx64",
        "version": "1.1.0"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLTianDiTuApi-linuxx64/1.1.0/DLTianDiTuApi-linuxx64-1.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLTianDiTuApi-linuxx64",
        "version": "1.1.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLTianDiTuApi-macosarm64/1.1.0/DLTianDiTuApi-macosarm64-1.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLTianDiTuApi-macosarm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLTianDiTuApi-macosarm64/1.1.0/DLTianDiTuApi-macosarm64-1.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLTianDiTuApi-macosarm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLTianDiTuApi-macosarm64/1.1.0/DLTianDiTuApi-macosarm64-1.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLTianDiTuApi-macosarm64",
        "version": "1.1.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLTianDiTuApi-macosx64/1.1.0/DLTianDiTuApi-macosx64-1.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLTianDiTuApi-macosx64",
        "version": "1.1.0"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLTianDiTuApi-macosx64/1.1.0/DLTianDiTuApi-macosx64-1.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLTianDiTuApi-macosx64",
        "version": "1.1.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLTianDiTuApi-macosx64/1.1.0/DLTianDiTuApi-macosx64-1.1.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLTianDiTuApi-macosx64",
        "version": "1.1.0"
      }
    }
  ]
}
