{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/2.3.0-alpha01/DLDateUtil-2.3.0-alpha01.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "2.3.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-iosSimulatorArm64Main-2.3.0-alpha01.klib",
          "url": "DLDateUtil-iossimulatorarm64-2.3.0-alpha01.klib",
          "size": 92731,
          "sha512": "7a4a8f5e5634e61667932e263965223878fdda6a8f2606d5554ad907742ca21e9b6e271f60018646964bf386d0712db1e6366a5e7c9dd3228ca6b031fa073dcf",
          "sha256": "a42f865cc173ad3ff011023cc8ffbfd4dec2fb6f493507d0818becea49fc1966",
          "sha1": "e2d319208926bf07046ee44b91a066d3d74b271c",
          "md5": "21b33e463f09455012efee1561adfe66"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLDateUtil-iossimulatorarm64-2.3.0-alpha01-sources.jar",
          "url": "DLDateUtil-iossimulatorarm64-2.3.0-alpha01-sources.jar",
          "size": 20711,
          "sha512": "1a7e2c8a7d2d19933ecf19c7c3b0f11c25e7608b4dedd5b086e4f5d789dd4aa4d9f9dd62c04193cda628ad50f2c9054fa2f3ce25a32231edb209722cc1f45861",
          "sha256": "3226355c59e086e941ccde3df5dc183c94fee93de7e471d1f0dc38165205d03e",
          "sha1": "6b6911ce395d0504143be31a704f369eb86dd172",
          "md5": "3373755ef4b3167533a70abb517304c3"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-iossimulatorarm64-2.3.0-alpha01-metadata.jar",
          "url": "DLDateUtil-iossimulatorarm64-2.3.0-alpha01-metadata.jar",
          "size": 261,
          "sha512": "56ab168724902197562dea66d7228fa405c908a9b668f612879c3c0959321a3a198f0fa4061a7ee3d2d30c06b09bb6fbe81178b98a6ba5ababab65d4b73da33e",
          "sha256": "b3285b341d5b6ffaf37989bf32e9dfff4a1373cea59ad14c1b76482961d97f01",
          "sha1": "c33ccb47cb16f24f2eb4a96dda29594e27d5835e",
          "md5": "a858529551fe023cbfd4fd2859a87864"
        }
      ]
    }
  ]
}
