{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLSerialPortUtil/0.6.1/DLSerialPortUtil-0.6.1.module",
    "group": "com.github.D10NGYANG",
    "module": "DLSerialPortUtil",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLLogUtil",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLSerialPortUtil-linuxX64Main-0.6.1.klib",
          "url": "DLSerialPortUtil-linuxx64-0.6.1.klib",
          "size": 53519,
          "sha512": "ae2d04b2c9c72616401b91bae836e68afffb774c6399132af7cfde246709ac82a283371e4e11985c910222c0a7fc848a2710b743b08605ce9a95e391c41bbbeb",
          "sha256": "e305e60218a06dfb80bbd2175fd76ec874aeece7518dd68cf7829ff6d914bf0b",
          "sha1": "eee21bbe322fbdb7848e8fa2f900fe83704ee357",
          "md5": "11f2618f16080e91e483ffcb72873dc1"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLSerialPortUtil-linuxx64-0.6.1-sources.jar",
          "url": "DLSerialPortUtil-linuxx64-0.6.1-sources.jar",
          "size": 12390,
          "sha512": "9bff4a6cd0652223d3fec359fcc70c499ace70340a06df2e68e215921db54839f323d6deeb7a06c8d9c68ce9eb603a72c37746a4f52a828fb4167949aa2ba062",
          "sha256": "03eb9352cf8dde6bacf085ed493067750cc5e424917e468e6b08fd397fe4d483",
          "sha1": "d707df324bea7055208557ef892bf31b649ff158",
          "md5": "355e5eefbbfe78b3a1aefbe83754609e"
        }
      ]
    }
  ]
}
