{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLJetpackComposeUtil",
    "version": "2.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2023.10.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.0-alpha13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-2.0.8.aar",
          "url": "DLJetpackComposeUtil-2.0.8.aar",
          "size": 1084487,
          "sha512": "e9469265ead2a080757bb75278701f47f78661950048485f45a9b0653504d9ac7795613acea5ada6709390676934cc305f63e4ecd94c496cdbd6fb9d6ad32861",
          "sha256": "fd9a8b03802ebaa8997a9596e66cdd65586adfcf65b94e936a71f26e53e56085",
          "sha1": "34d7f31477cbce0e81b8725e51abbe2463c4ad72",
          "md5": "0029fd2918b50881a04503f107a5e4ae"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.github.raamcosta.compose-destinations",
          "module": "animations-core",
          "version": {
            "requires": "1.9.54"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLDateUtil",
          "version": {
            "requires": "1.8.7"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2023.10.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.0-alpha13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-2.0.8.aar",
          "url": "DLJetpackComposeUtil-2.0.8.aar",
          "size": 1084487,
          "sha512": "e9469265ead2a080757bb75278701f47f78661950048485f45a9b0653504d9ac7795613acea5ada6709390676934cc305f63e4ecd94c496cdbd6fb9d6ad32861",
          "sha256": "fd9a8b03802ebaa8997a9596e66cdd65586adfcf65b94e936a71f26e53e56085",
          "sha1": "34d7f31477cbce0e81b8725e51abbe2463c4ad72",
          "md5": "0029fd2918b50881a04503f107a5e4ae"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLJetpackComposeUtil-2.0.8-sources.jar",
          "url": "DLJetpackComposeUtil-2.0.8-sources.jar",
          "size": 74995,
          "sha512": "85050660e35d3cdb6c71a80709ab6640dca99d8e24714ba4b19948b642e0bc97ac9af5b300c1512233c1a41562743770dcb4501d11ec6131030fd708d4ccbba8",
          "sha256": "e7ae6dbd3d3689c5b95edb176df28f4abd1b40d0b84490516d1b2cdb9bb874a5",
          "sha1": "30bf3ea3daa6667c04d0a50c59baf0edf8a4e57a",
          "md5": "bab67260d2977bed5ac97058aa7da119"
        }
      ]
    }
  ]
}
