{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLCommonUtil/0.8.0/DLCommonUtil-0.8.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLCommonUtil",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-release.aar",
          "url": "DLCommonUtil-android-0.8.0.aar",
          "size": 190119,
          "sha512": "8ec692db3d0cfd9b6a68c2f67c87f9d648488e349213ab50b3f10ea30870965fffd6a9bd0620083c34854fbf002c698ed6e5cb801a1c9de0f6807598254fce59",
          "sha256": "d33792fd54cd38a5ed0b0df524750aa4a8cc27347a4f17d93f691154c183333a",
          "sha1": "51bb68c262c51595266730235b7a5bf3e88aa62f",
          "md5": "bfb28f78af947382e30d725789af9329"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-release.aar",
          "url": "DLCommonUtil-android-0.8.0.aar",
          "size": 190119,
          "sha512": "8ec692db3d0cfd9b6a68c2f67c87f9d648488e349213ab50b3f10ea30870965fffd6a9bd0620083c34854fbf002c698ed6e5cb801a1c9de0f6807598254fce59",
          "sha256": "d33792fd54cd38a5ed0b0df524750aa4a8cc27347a4f17d93f691154c183333a",
          "sha1": "51bb68c262c51595266730235b7a5bf3e88aa62f",
          "md5": "bfb28f78af947382e30d725789af9329"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "DLCommonUtil-android-0.8.0-sources.jar",
          "url": "DLCommonUtil-android-0.8.0-sources.jar",
          "size": 197049,
          "sha512": "e7f1b546c9226e5ffa1393ba8cf0dd2372fd5f5240267b9938c1103278626633cea9bed6271fe6c0578f453a74e15853c55b77e01064a2538ca7a15f2d0c4faf",
          "sha256": "89ae84650ba98524821a2df48ada6db3b0ef74996bf1667ec09cf1cec11559e6",
          "sha1": "6f151065b1a48727d25efb4a59a9eeb307bd6c57",
          "md5": "71bed4dcdc88a74a48afd9b72891fddb"
        }
      ]
    }
  ]
}
