{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLBluetoothUtil/0.1.26/DLBluetoothUtil-0.1.26.module",
    "group": "com.github.D10NGYANG",
    "module": "DLBluetoothUtil",
    "version": "0.1.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "DLBluetoothUtil.klib",
          "url": "DLBluetoothUtil-iosarm64-0.1.26.klib",
          "size": 61417,
          "sha512": "76b2905e9b5087b6007419286a57c1ff702f424ecead8080d453d27c1471f775c55b5bb79882fd7dbf66994f3dc153cc6777de8d0abc9ad0a040b3bd22c353fb",
          "sha256": "67e48ad37dfaac7d2cdc4736b34519f68a7405cda4c138346847ab6a448a33d1",
          "sha1": "3d79e4437663bc602dc80aab6b4a7a5dc29aac02",
          "md5": "fc9dab804f182dc52dd8e9a9c41a342a"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLBluetoothUtil-iosarm64-0.1.26-sources.jar",
          "url": "DLBluetoothUtil-iosarm64-0.1.26-sources.jar",
          "size": 10037,
          "sha512": "8f86f8d223947b27b9ea849a74019d9d655ebf109aa44bc126000ee743241b0287586438b6708a847bfd79228c5949cc7041c89105c4fb2c9d64ac53ae7160d5",
          "sha256": "a2cdc8f6f30dde3865d58e9f9eab92bfa56fcee1d8c1e42898b92445cdb47806",
          "sha1": "54a0fa467904889e55df63c0b781517650a41093",
          "md5": "2955ed6b0d34ab7b81e263af114e4e8e"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "DLBluetoothUtil-iosarm64-0.1.26-metadata.jar",
          "url": "DLBluetoothUtil-iosarm64-0.1.26-metadata.jar",
          "size": 261,
          "sha512": "197b51fd82812e5b32b50fed46dcebcf1b470776af99a9921de272ef3ebdd95e784e5c81ce930a8003330bab932b37a9ac7007bd02b64d02ecf6d254fea768f2",
          "sha256": "94a7568d3a57b4afef8b3c27b24baa457e746414b7f3a6570ff3b894864d164e",
          "sha1": "80abc2cd1104935efd30ccd2ab20f679fcf4a542",
          "md5": "269c73b0f02b502519f41c7e867dcead"
        }
      ]
    }
  ]
}
