{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDatastoreUtil/0.2.0/DLDatastoreUtil-0.2.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDatastoreUtil",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLDatastoreUtil-release.aar",
          "url": "DLDatastoreUtil-android-0.2.0.aar",
          "size": 10908,
          "sha512": "a894f3d3f0fb1c38b8be0f660ca3829385cec569bce540c5ebffdeef0f1aa9eaf9da9cfb06bc43a9b3c1444d13ce6a1f6e933b1ab78c2254be48108cae87840e",
          "sha256": "16e2191e3ef598a6ad795cd46341290cdebde54e8f8afb06d6b8f47d888970b5",
          "sha1": "2430875ba742279036aa41364d2eb50ef02c946d",
          "md5": "b25c197263e263a2247467674f835000"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "DLDatastoreUtil-release.aar",
          "url": "DLDatastoreUtil-android-0.2.0.aar",
          "size": 10908,
          "sha512": "a894f3d3f0fb1c38b8be0f660ca3829385cec569bce540c5ebffdeef0f1aa9eaf9da9cfb06bc43a9b3c1444d13ce6a1f6e933b1ab78c2254be48108cae87840e",
          "sha256": "16e2191e3ef598a6ad795cd46341290cdebde54e8f8afb06d6b8f47d888970b5",
          "sha1": "2430875ba742279036aa41364d2eb50ef02c946d",
          "md5": "b25c197263e263a2247467674f835000"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "DLDatastoreUtil-android-0.2.0-sources.jar",
          "url": "DLDatastoreUtil-android-0.2.0-sources.jar",
          "size": 3983,
          "sha512": "a01396375fdaf75b08958b520e86696cf81aa721d020e8623b353f04574d7e893ca99f7dd83f0d255e5bc6290929caa708ff552d9b575fdaf226f8687aa52fca",
          "sha256": "8fdc7cbadecea30c2fb330560256f823750034f05148129e1f49f7a7eacbe8b8",
          "sha1": "56de805bf115b060819f8bde3e7780e02131a781",
          "md5": "0df0d12e9aaa90e1ff95e1bd54308971"
        }
      ]
    }
  ]
}
