{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLAppUtil",
    "version": "2.4.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLAppUtil-2.4.11.aar",
          "url": "DLAppUtil-2.4.11.aar",
          "size": 147185,
          "sha512": "8982527c8a08bbdee2599c860329c943aa26a1174402950891482c9e1a30af09000b7ab08cfc39feee21ac72fcfb83041df493a6d017256d2bd0f31dc429f1ae",
          "sha256": "c4887ce8e3219cd62b089835031ae2dd088a77e38d9275e4b68e67637861277d",
          "sha1": "c8b4e3f72808e688d9a5495a5c2800782292b36f",
          "md5": "06e13d743e138b0c7bdb46f3fcf523d4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLAppUtil-2.4.11.aar",
          "url": "DLAppUtil-2.4.11.aar",
          "size": 147185,
          "sha512": "8982527c8a08bbdee2599c860329c943aa26a1174402950891482c9e1a30af09000b7ab08cfc39feee21ac72fcfb83041df493a6d017256d2bd0f31dc429f1ae",
          "sha256": "c4887ce8e3219cd62b089835031ae2dd088a77e38d9275e4b68e67637861277d",
          "sha1": "c8b4e3f72808e688d9a5495a5c2800782292b36f",
          "md5": "06e13d743e138b0c7bdb46f3fcf523d4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLAppUtil-2.4.11-sources.jar",
          "url": "DLAppUtil-2.4.11-sources.jar",
          "size": 38447,
          "sha512": "cac0ef108ef2392119c2226485385d70314a9853d18fcba860fb20d6c9e98d007ea4018be5f248830462321d6e8ce232e9fbba7b07b0f95aaf92adecf945a738",
          "sha256": "85ad1199960a6d7f42bb7dd7354e1ea415fd89a46eb3ed007bbaa4b4fe86c40f",
          "sha1": "8fb8a609ef708d7a2834dbca75cd5a4a954680fe",
          "md5": "50cb5469faa7462708060ad8e6019ce4"
        }
      ]
    }
  ]
}
