{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLCommonUtil/0.0.8/DLCommonUtil-0.0.8.module",
    "group": "com.github.D10NGYANG",
    "module": "DLCommonUtil",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.ditchoom",
          "module": "buffer",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil.klib",
          "url": "DLCommonUtil-iossimulatorarm64-0.0.8.klib",
          "size": 98484,
          "sha512": "6ecc86537bc3253aaa2f9b156de505ea5c2b61d900a17dfa0f45be0e64daef2d6e762e4aff4a755f45e2c50b67f269c959897919927a33c7009483a3249dc80c",
          "sha256": "e3b7c6175c9a2989ba9fc1e68002691e246e2080fe072bee37cb8b5e6e7a7830",
          "sha1": "6c8d292f5256566427cc229f573b3031c04f6a34",
          "md5": "8f52770d8cdbc038db68442ae7ea2b9e"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLCommonUtil-iossimulatorarm64-0.0.8-sources.jar",
          "url": "DLCommonUtil-iossimulatorarm64-0.0.8-sources.jar",
          "size": 27103,
          "sha512": "d16564e2eb03edc63868c2ff2ea5bbb8586f5c725922a14d77a89bd37b7347c55453ec8eb3f5acc2709934aa75b66492e6097a951744e8a211ac61ac48796146",
          "sha256": "36014e20bf39bde0808d30e774f27bbb9ff19403cd78720faae522ebaa5035fe",
          "sha1": "c31d42272caa332071df6beb2e97c7927772f9c8",
          "md5": "9d77c9a36ace67d94160c52a93d76896"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.ditchoom",
          "module": "buffer",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-iossimulatorarm64-0.0.8-metadata.jar",
          "url": "DLCommonUtil-iossimulatorarm64-0.0.8-metadata.jar",
          "size": 4086,
          "sha512": "c7dcd144dce5ef620cc3ce6b0db81745f4ff86c6815bb82d903d59e9faeba3cc2224e3b21395236c11f342dbf11c5193c77e9d1dc83189fe71a8f77726a34621",
          "sha256": "78eb7ab341f00381c0ebb9c0fd06d51ea38c6014d93039288a84975edf97c5f3",
          "sha1": "52b5f59546111a29ac9ba248933faf545dd69f71",
          "md5": "82be0bd42b59196f063be2b68f746313"
        }
      ]
    }
  ]
}
