{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLAppUtil",
    "version": "2.5.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLAppUtil-2.5.9.aar",
          "url": "DLAppUtil-2.5.9.aar",
          "size": 184039,
          "sha512": "778fb446036f6798b4248302269a0dc53ec32203ae32ea7d42f3e103cb42b585fa0e6013e24395d6d5e6ce50087b15da5dc231c7be1ff022e471a007556d763f",
          "sha256": "c285960a115d35fe4d7829d0b3816039072960ea5202eca1cc0cfcf551577362",
          "sha1": "56201c72528a8c264b0a02a0b61bcd75e01dec38",
          "md5": "363469b25392aee29e524f7ce932d924"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0-RC.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0-RC.2"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLAppUtil-2.5.9.aar",
          "url": "DLAppUtil-2.5.9.aar",
          "size": 184039,
          "sha512": "778fb446036f6798b4248302269a0dc53ec32203ae32ea7d42f3e103cb42b585fa0e6013e24395d6d5e6ce50087b15da5dc231c7be1ff022e471a007556d763f",
          "sha256": "c285960a115d35fe4d7829d0b3816039072960ea5202eca1cc0cfcf551577362",
          "sha1": "56201c72528a8c264b0a02a0b61bcd75e01dec38",
          "md5": "363469b25392aee29e524f7ce932d924"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLAppUtil-2.5.9-sources.jar",
          "url": "DLAppUtil-2.5.9-sources.jar",
          "size": 40611,
          "sha512": "1735556fc522bcde62f08a329e21be17e2e19c8304d559142f2fa01531f1794d1e7c6e55624930ff5715c15410d8b538d051848a333459641f4e5f7aefbaa1a3",
          "sha256": "9c03448a16608a202d0d3bba5f1f82a163605720140c2d217dcaf144ed45a9c6",
          "sha1": "e4f403c09f2cc3b608b42772818f8e1dff9272be",
          "md5": "58cd47283f9c2ecf5806ccd71e57fcc3"
        }
      ]
    }
  ]
}
