{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLJetpackComposeUtil",
    "version": "2.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2023.10.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.0-alpha13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-2.0.7.aar",
          "url": "DLJetpackComposeUtil-2.0.7.aar",
          "size": 1084481,
          "sha512": "66db6448409a84227f47fd3e17ad92488ca8e695a2649e416a63e1b21ed07aa7e0438332f3bcfa3e4a42de9355640bed423c6c6069b79e2e443493a5cee85054",
          "sha256": "6ed54f1d6e80fd223d9b8694dc4642869a68ae86d217058c5a3a5e9881fc1e78",
          "sha1": "72b155c1811eb139f389dabf5937d176347dcc8a",
          "md5": "074ab54ff758a78bf23a489c852a6125"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.github.raamcosta.compose-destinations",
          "module": "animations-core",
          "version": {
            "requires": "1.9.54"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLDateUtil",
          "version": {
            "requires": "1.8.7"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2023.10.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.0-alpha13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-2.0.7.aar",
          "url": "DLJetpackComposeUtil-2.0.7.aar",
          "size": 1084481,
          "sha512": "66db6448409a84227f47fd3e17ad92488ca8e695a2649e416a63e1b21ed07aa7e0438332f3bcfa3e4a42de9355640bed423c6c6069b79e2e443493a5cee85054",
          "sha256": "6ed54f1d6e80fd223d9b8694dc4642869a68ae86d217058c5a3a5e9881fc1e78",
          "sha1": "72b155c1811eb139f389dabf5937d176347dcc8a",
          "md5": "074ab54ff758a78bf23a489c852a6125"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLJetpackComposeUtil-2.0.7-sources.jar",
          "url": "DLJetpackComposeUtil-2.0.7-sources.jar",
          "size": 74990,
          "sha512": "3ad585348f9f4adfde1c776cc49d20014e3d0a744b7a3c91d3588bf539e86713de2235a125510e75271650e38b09e6ea7435cd8fcbfc5850d008c4370ba250b0",
          "sha256": "0465a862207a69b8c71480850591496144c4c514890281eef64011e6796edfa5",
          "sha1": "a7f44ef9cee6985afc121ad083cd9b5fde00ac66",
          "md5": "7676366ae34fd22770f53c056ee753f8"
        }
      ]
    }
  ]
}
