{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/2.3.0-alpha01/DLDateUtil-2.3.0-alpha01.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "2.3.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-iosArm64Main-2.3.0-alpha01.klib",
          "url": "DLDateUtil-iosarm64-2.3.0-alpha01.klib",
          "size": 92665,
          "sha512": "60eec44b17bc3782eee5ae61415c55c0fd834b6ba028fb06f547bd53530f45698f2f4684da11d4be7ec7bcffc13e02bbca383ca988b26fe92a4b6c3e3d2af0eb",
          "sha256": "b6a410dbc5165a6aeb99f1254f601cb44e28be1a2e05ee30ab20d04cc07b8893",
          "sha1": "97ebea8c469ea021cce66a041b364b909d3ce542",
          "md5": "e299be7fc4b21a355cb3fcc2fc6398b9"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLDateUtil-iosarm64-2.3.0-alpha01-sources.jar",
          "url": "DLDateUtil-iosarm64-2.3.0-alpha01-sources.jar",
          "size": 20711,
          "sha512": "1a7e2c8a7d2d19933ecf19c7c3b0f11c25e7608b4dedd5b086e4f5d789dd4aa4d9f9dd62c04193cda628ad50f2c9054fa2f3ce25a32231edb209722cc1f45861",
          "sha256": "3226355c59e086e941ccde3df5dc183c94fee93de7e471d1f0dc38165205d03e",
          "sha1": "6b6911ce395d0504143be31a704f369eb86dd172",
          "md5": "3373755ef4b3167533a70abb517304c3"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-iosarm64-2.3.0-alpha01-metadata.jar",
          "url": "DLDateUtil-iosarm64-2.3.0-alpha01-metadata.jar",
          "size": 261,
          "sha512": "7548540db26a0097f044eba4705c16297b1113ceac1014e1c415c96338f9f78a107dc71b8a5746ade1e320b4d6f8949c983b6804a973e4a5a080d16a591dbe61",
          "sha256": "bfd522b34184d88737032c4a89fd6191cab6242232c60798ec33ae2177169713",
          "sha1": "eef0f93d30fbb2b4d8276372621ebd1fc79f1d40",
          "md5": "d0b365271e01db4057cf6a56ce78edb5"
        }
      ]
    }
  ]
}
