{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLAppUtil",
    "version": "2.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLAppUtil-2.4.4.aar",
          "url": "DLAppUtil-2.4.4.aar",
          "size": 104191,
          "sha512": "135165ede809c78edf4f4ca2b6d82456fff20dd926eb6ffd646752554455f817e524a9a76d19496d9d43e8e4476da0c22648e4e4eb3ff6bc41fb922677193da1",
          "sha256": "5ef9850a970701a4bf388bc273074cdc25db06126313d10e79c4db7c0d939ae6",
          "sha1": "bbcd9dba5b785b9031374edecb066316b1138ea6",
          "md5": "d080e94fa25f327eeed5cd3bc5cf4611"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLAppUtil-2.4.4.aar",
          "url": "DLAppUtil-2.4.4.aar",
          "size": 104191,
          "sha512": "135165ede809c78edf4f4ca2b6d82456fff20dd926eb6ffd646752554455f817e524a9a76d19496d9d43e8e4476da0c22648e4e4eb3ff6bc41fb922677193da1",
          "sha256": "5ef9850a970701a4bf388bc273074cdc25db06126313d10e79c4db7c0d939ae6",
          "sha1": "bbcd9dba5b785b9031374edecb066316b1138ea6",
          "md5": "d080e94fa25f327eeed5cd3bc5cf4611"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLAppUtil-2.4.4-sources.jar",
          "url": "DLAppUtil-2.4.4-sources.jar",
          "size": 33163,
          "sha512": "a2cf1797a58f40ee49a86d242b8a2971e18570467fd2242761638b598dcb366d3dd565a0c13b6d8394c3b8ebb99cac6eaa582dfd17761447966c6075396be0af",
          "sha256": "8a3584b1bb04eda69b71550e176796ddd352d03a1fcb1db824173f7163bcb054",
          "sha1": "d3ca4051aa9a2de50d66c0d5dbb48deeaae1deb1",
          "md5": "971c5dddaf898523932cf17d6bd645d8"
        }
      ]
    }
  ]
}
