{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/1.8.0/DLDateUtil-1.8.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "1.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil.klib",
          "url": "DLDateUtil-iosx64-1.8.0.klib",
          "size": 56566,
          "sha512": "48ab8a284eaebd117f772a58afba7e83ef9af1c06e9e429fdcab0da3881c819cb35465a4e49e43dff6c41096c186ea7e45c1cf01723fd513f419e5fce8f2e8b4",
          "sha256": "be0a94ae0293348a8a05a53476a3bc499256ea0e8777fc64e34429d873ff6d91",
          "sha1": "dcc8d6982d65badf74e9225e2539abf7f8fb4107",
          "md5": "fd00a4973847de4984bc1d499de2bc7a"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-iosx64-1.8.0-metadata.jar",
          "url": "DLDateUtil-iosx64-1.8.0-metadata.jar",
          "size": 261,
          "sha512": "ffba9db58258b4495e2d81399fd4482f7d2d98238a89d88117223fbc2db904c179ce84563c9d0abf8942ee66ffb230fff8d75d29c11496a9cd70c45a781d772d",
          "sha256": "dc0e5f1925d8db3cdecd14c27faa3b6bd7a14a6306591a16190b024194e9f926",
          "sha1": "99e1064c0ec465a30d6fdcd41a47401643639528",
          "md5": "fb065e125f8bd3fb72d864e3a56841ce"
        }
      ]
    }
  ]
}
