{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLPcmResampleUtil/0.2.1/DLPcmResampleUtil-0.2.1.module",
    "group": "com.github.D10NGYANG",
    "module": "DLPcmResampleUtil",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLPcmResampleUtil-release.aar",
          "url": "DLPcmResampleUtil-android-0.2.1.aar",
          "size": 63507,
          "sha512": "f90e50d0f0ba53552b237f56d4fe31bba30467ddc896087d10d06ccf9dcf37c28b16888f5b08d15c47af0125d19e6d25f8c918019b9ddb0bd9829e423e1381c0",
          "sha256": "63bbcc8000ed14488bec496c5391f629f1c14d5babcfa7ba9adfe4bcc63617c0",
          "sha1": "f1f0df2a35e6fa7387242887fa16e0a28d88e674",
          "md5": "f9fd95737209dee08414651cb4506f00"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.4.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "DLPcmResampleUtil-release.aar",
          "url": "DLPcmResampleUtil-android-0.2.1.aar",
          "size": 63507,
          "sha512": "f90e50d0f0ba53552b237f56d4fe31bba30467ddc896087d10d06ccf9dcf37c28b16888f5b08d15c47af0125d19e6d25f8c918019b9ddb0bd9829e423e1381c0",
          "sha256": "63bbcc8000ed14488bec496c5391f629f1c14d5babcfa7ba9adfe4bcc63617c0",
          "sha1": "f1f0df2a35e6fa7387242887fa16e0a28d88e674",
          "md5": "f9fd95737209dee08414651cb4506f00"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "DLPcmResampleUtil-android-0.2.1-sources.jar",
          "url": "DLPcmResampleUtil-android-0.2.1-sources.jar",
          "size": 29498,
          "sha512": "4f096ce098d2c99292b316414eb3dd74a967d7436f9ab3cc27668c15b81514c25b71a0967616101694f7b024753e6a426b61d9af5e6c6dbf6d905f427c173b6b",
          "sha256": "1fc4ed72daa9d1a5d7dc8b8182b3aaeeceff08defb1317c0daf5735f82058ec4",
          "sha1": "93bc0627a4523f6fa6bab1c6acd5561a5cf5bc7a",
          "md5": "f573a7abe1cfa719011b671905188cef"
        }
      ]
    }
  ]
}
