{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLBluetoothUtil/0.6.3/DLBluetoothUtil-0.6.3.module",
    "group": "com.github.D10NGYANG",
    "module": "DLBluetoothUtil",
    "version": "0.6.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "DLBluetoothUtil-wasm-js-0.6.3.klib",
          "url": "DLBluetoothUtil-wasm-js-0.6.3.klib",
          "size": 60719,
          "sha512": "5a9cb9c6c09a815420a373ef8e9b4aabd4a3384fc3f46768d240302513513bb4d49806424ddc19e431831a5649926b1d25b4dd488a8d9a35106e663d1688b892",
          "sha256": "4a9ecaeefb9f999287ad325579534638d94bc5b3d11ab56dee5b9473718020e5",
          "sha1": "227b55f4319e73babbdb5c92d906e5689e62c89b",
          "md5": "df0d835a5db66adae8c2604d99c6fab3"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLLogUtil",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLBluetoothUtil-wasm-js-0.6.3.klib",
          "url": "DLBluetoothUtil-wasm-js-0.6.3.klib",
          "size": 60719,
          "sha512": "5a9cb9c6c09a815420a373ef8e9b4aabd4a3384fc3f46768d240302513513bb4d49806424ddc19e431831a5649926b1d25b4dd488a8d9a35106e663d1688b892",
          "sha256": "4a9ecaeefb9f999287ad325579534638d94bc5b3d11ab56dee5b9473718020e5",
          "sha1": "227b55f4319e73babbdb5c92d906e5689e62c89b",
          "md5": "df0d835a5db66adae8c2604d99c6fab3"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "DLBluetoothUtil-wasm-js-0.6.3-sources.jar",
          "url": "DLBluetoothUtil-wasm-js-0.6.3-sources.jar",
          "size": 14113,
          "sha512": "01e1ad98ce4f066ba19d65795cdf4637c5388f654b922873931434f761d6c1de386a50e620cd9f30187a536ea33044904b839ddcbe942abb46ecd4a72726d550",
          "sha256": "f208266edb1c74353817d18b73924535c6170b1869f8d135193c320793812577",
          "sha1": "17c164510f9a95a3bcef644270fd4ce76f5eb720",
          "md5": "145edee5a7f095f6ec00235a373c9a26"
        }
      ]
    }
  ]
}
