{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLAppUtil",
    "version": "2.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "DLAppUtil-2.5.0.aar",
          "url": "DLAppUtil-2.5.0.aar",
          "size": 192118,
          "sha512": "a1265654460357d0795d5c3615c7538718454761b3c766b44d0e30b351653a030b3b6d208d6a9e1069381a639739a46a560596136cbe62cafae9aa6cde67f0d7",
          "sha256": "20e9b1a0b15388e602f0ed98e8d3e9a9b3912e479899216567db5881a1a63f89",
          "sha1": "b77a91f069bb623a8b2d73d0f15d10986e1ea730",
          "md5": "1d42005f5e1d3bc5532b9476860994e8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "DLAppUtil-2.5.0.aar",
          "url": "DLAppUtil-2.5.0.aar",
          "size": 192118,
          "sha512": "a1265654460357d0795d5c3615c7538718454761b3c766b44d0e30b351653a030b3b6d208d6a9e1069381a639739a46a560596136cbe62cafae9aa6cde67f0d7",
          "sha256": "20e9b1a0b15388e602f0ed98e8d3e9a9b3912e479899216567db5881a1a63f89",
          "sha1": "b77a91f069bb623a8b2d73d0f15d10986e1ea730",
          "md5": "1d42005f5e1d3bc5532b9476860994e8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLAppUtil-2.5.0-sources.jar",
          "url": "DLAppUtil-2.5.0-sources.jar",
          "size": 38223,
          "sha512": "1c279e7dffa39b7eb293b5a6b6ca779556a62d8828d0aa2400c79b7cb2f50a4b946b86d958e05280b42ff2b6dd532bf1f603fca1b4e4739b05df0eedd543e74e",
          "sha256": "1a3d2999f4d59b68b17554bb8f1c62408cde4c44bd6a23b2172b0424f76a3050",
          "sha1": "111baa58c47a7ada9bc7682dc31016e15a3fb2ac",
          "md5": "9b80cab3a67752b6249772aa06fab198"
        }
      ]
    }
  ]
}
