{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLMapboxUtil",
    "version": "0.9.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mapbox.maps",
          "module": "android",
          "version": {
            "requires": "10.11.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLMapboxUtil-0.9.7.aar",
          "url": "DLMapboxUtil-0.9.7.aar",
          "size": 850043,
          "sha512": "eb4151aef5ba35a5f2f1e9e3b77abd0df7867b51dd749b38537cf1c11c590f70643a6f144c4e37badef05288f0ac655541de6468fca90d384af4e6613a68b3db",
          "sha256": "e1a2035fc74928e0ba186d53ffcfecaead529169dbafb037176c6453ebd95eae",
          "sha1": "7b7798c228c03eee36daec87b41db519853ea47b",
          "md5": "c4c42a7729aa2a9df34b6ada7cb06e51"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "io.github.raamcosta.compose-destinations",
          "module": "animations-core",
          "version": {
            "requires": "1.8.41-beta"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLJetpackComposeUtil",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLAppUtil",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLGpsUtil",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLLatLngUtil-jvm",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLTianDiTuApi-jvm",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLHttpUtil-jvm",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mapbox.maps",
          "module": "android",
          "version": {
            "requires": "10.11.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLMapboxUtil-0.9.7.aar",
          "url": "DLMapboxUtil-0.9.7.aar",
          "size": 850043,
          "sha512": "eb4151aef5ba35a5f2f1e9e3b77abd0df7867b51dd749b38537cf1c11c590f70643a6f144c4e37badef05288f0ac655541de6468fca90d384af4e6613a68b3db",
          "sha256": "e1a2035fc74928e0ba186d53ffcfecaead529169dbafb037176c6453ebd95eae",
          "sha1": "7b7798c228c03eee36daec87b41db519853ea47b",
          "md5": "c4c42a7729aa2a9df34b6ada7cb06e51"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLMapboxUtil-0.9.7-sources.jar",
          "url": "DLMapboxUtil-0.9.7-sources.jar",
          "size": 44427,
          "sha512": "0b50c64a054b4e83869df60f46f11c3e9b00629dabdf3d8a7c5ec5ea20f189edba801186683723a7fd7efc27569f95adb771a78187aef551af8c3124068d47ae",
          "sha256": "4f5738257706f3e25e26ab9beba524693852a873f03c6338a8d92274503b87ef",
          "sha1": "5f16280ef315218533a3c1576eb85c746ff40aa5",
          "md5": "bc08a85c93282d822d54bfac8efc9999"
        }
      ]
    }
  ]
}
