{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLLatLngUtil/1.6.1/DLLatLngUtil-1.6.1.module",
    "group": "com.github.D10NGYANG",
    "module": "DLLatLngUtil",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil-jvm-1.6.1.jar",
          "url": "DLLatLngUtil-jvm-1.6.1.jar",
          "size": 27885,
          "sha512": "90603ba5cf2a256087cda0059de60214249ef0a92bb10e2b2dbc034fe55b9e0627ad1b9c06944a17979609bdd934116f1a7f3ceb9125f9ca8761d0fd8fb1f463",
          "sha256": "9c1f566fa8df640e390d3d782ac1c630034706c2dc89f1c0d05766fd98aa2ecf",
          "sha1": "67f3e8728d900e8ca5174c84f1a02585a812819b",
          "md5": "bb2851c104ec9f556e31c4f36301b51a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil-jvm-1.6.1.jar",
          "url": "DLLatLngUtil-jvm-1.6.1.jar",
          "size": 27885,
          "sha512": "90603ba5cf2a256087cda0059de60214249ef0a92bb10e2b2dbc034fe55b9e0627ad1b9c06944a17979609bdd934116f1a7f3ceb9125f9ca8761d0fd8fb1f463",
          "sha256": "9c1f566fa8df640e390d3d782ac1c630034706c2dc89f1c0d05766fd98aa2ecf",
          "sha1": "67f3e8728d900e8ca5174c84f1a02585a812819b",
          "md5": "bb2851c104ec9f556e31c4f36301b51a"
        }
      ]
    }
  ]
}
