{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLDatastoreUtil",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLDatastoreUtil-0.0.4.aar",
          "url": "DLDatastoreUtil-0.0.4.aar",
          "size": 9445,
          "sha512": "41cf0b833d08614d8e73075768dd8b2315912c6b3f795ec9b4e0c1db99a9bb1dc1f746dad4b9f11b98582d30490487080bf08fb36c1d57099c4825f1157cd489",
          "sha256": "453bbb9d478fb84915c116b468c8be4fe165dbc4a386a958416d28e7c89094db",
          "sha1": "5b45e2c7b75ac8fd5da2f98d5b7e2af7f9a44d5b",
          "md5": "3c9d7a1506e66d8d6eacbd57ba1e08af"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLDatastoreUtil-0.0.4.aar",
          "url": "DLDatastoreUtil-0.0.4.aar",
          "size": 9445,
          "sha512": "41cf0b833d08614d8e73075768dd8b2315912c6b3f795ec9b4e0c1db99a9bb1dc1f746dad4b9f11b98582d30490487080bf08fb36c1d57099c4825f1157cd489",
          "sha256": "453bbb9d478fb84915c116b468c8be4fe165dbc4a386a958416d28e7c89094db",
          "sha1": "5b45e2c7b75ac8fd5da2f98d5b7e2af7f9a44d5b",
          "md5": "3c9d7a1506e66d8d6eacbd57ba1e08af"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLDatastoreUtil-0.0.4-sources.jar",
          "url": "DLDatastoreUtil-0.0.4-sources.jar",
          "size": 2715,
          "sha512": "17d97c80c83b760d70e4db1dedd0e678b35f5bf1affd57990bd23dcab9e71108e72be0079b60d1d7d3c57a954b307a0926a082a273cce52c07b6da603c43bc24",
          "sha256": "1b8b0a2dfd1dba63862c44dea4092706d8beab8cc570daa516155818d5784848",
          "sha1": "04f430f4ab7c621f74878e606eb89207103a5bc2",
          "md5": "5f01e0ee1cd32f0abcac57cf066635d4"
        }
      ]
    }
  ]
}
