{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLBluetoothUtil/0.9.0/DLBluetoothUtil-0.9.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLBluetoothUtil",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "DLBluetoothUtil-js-0.9.0.klib",
          "url": "DLBluetoothUtil-js-0.9.0.klib",
          "size": 64799,
          "sha512": "8e635647ebf9ff1f9cba54f3f94f05c6e4c3f6447bf3399a5bbc82f44c32cf67fa66fd5654b30b57eaca33489f8f0e95f6b3759ded0bae258b3f8aa5787fc708",
          "sha256": "65026d1b35c15ffdf3782cc81f0529338bf112edc8eec6d8ef8053fba40aa80a",
          "sha1": "fc0432d96b63b446320dc50ea361792b2a59efb8",
          "md5": "f47e8883d32f495da7024b09bf3c40d0"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLLogUtil",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLBluetoothUtil-js-0.9.0.klib",
          "url": "DLBluetoothUtil-js-0.9.0.klib",
          "size": 64799,
          "sha512": "8e635647ebf9ff1f9cba54f3f94f05c6e4c3f6447bf3399a5bbc82f44c32cf67fa66fd5654b30b57eaca33489f8f0e95f6b3759ded0bae258b3f8aa5787fc708",
          "sha256": "65026d1b35c15ffdf3782cc81f0529338bf112edc8eec6d8ef8053fba40aa80a",
          "sha1": "fc0432d96b63b446320dc50ea361792b2a59efb8",
          "md5": "f47e8883d32f495da7024b09bf3c40d0"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "DLBluetoothUtil-js-0.9.0-sources.jar",
          "url": "DLBluetoothUtil-js-0.9.0-sources.jar",
          "size": 20765,
          "sha512": "58648dd23a85c5a2f335d5677c43b9edb82be898b3ede10068ca5006696953148faafce541da84d56c3bf46d777f94afb4c8fed648916817d3bd72a880237616",
          "sha256": "40a22d8b680e5bfa6644c2cd7c66fc529866673bd58d4f6c50ab26c3da3980cc",
          "sha1": "2639f03fde11aa66a328e92aa688668e62f2818d",
          "md5": "8e33e197c18ee01ee446f46f7cca91bd"
        }
      ]
    }
  ]
}
