{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/2.1.0/DLDateUtil-2.1.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-iosArm64Main-2.1.0.klib",
          "url": "DLDateUtil-iosarm64-2.1.0.klib",
          "size": 76900,
          "sha512": "85c11531bb9eb383259276193c8f2e1af0aabb7c04d4a18af6beb2db543e043a2609b39a99633e92146132597d158d8cee1d3ac37a281a5e1ff050bbb89be20f",
          "sha256": "5cb23e434c4c82cc1cac40f7e3b8e2a4148ed4126ea7d7075a4c4912a5603fc9",
          "sha1": "07c3b98fe8b0e2322bc17685d97d966b222603ac",
          "md5": "052868d6be4d06443ef81cd97515bb29"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLDateUtil-iosarm64-2.1.0-sources.jar",
          "url": "DLDateUtil-iosarm64-2.1.0-sources.jar",
          "size": 17232,
          "sha512": "b8d79c6283ff88e837ddc3a09ba5bdf8699a2a4fe77e5fc8901d5cce63e8c9d4febfd42667699643513e15abe3162d38b6caa93b7e57235ef6af4b0b02099887",
          "sha256": "f7b7660b171231b2f4c2aff1359711b1694e753a21041add4b009f1d859055b8",
          "sha1": "29731f21fc212fa56c686b33b47c58e97a676243",
          "md5": "cfe31385e210ad62a83d8b501483b495"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-iosarm64-2.1.0-metadata.jar",
          "url": "DLDateUtil-iosarm64-2.1.0-metadata.jar",
          "size": 261,
          "sha512": "bf3a924328af2533c172fafbdf04a22d4abf5edad472d3f2b94eefb92da26750d2540eacb0ef16aab4d2f37be27ae419580658be2b0ea17750cdda39d039a00c",
          "sha256": "87461073ef042d86b567e2029ab9589c98823f4dc7459b9f62c8d9beac632c27",
          "sha1": "e30dd2ca2d6b79eea31f8bab9abb1587b39b7647",
          "md5": "1ae463f6eddc0567c9e111b13a6447e9"
        }
      ]
    }
  ]
}
