{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/1.6/DLDateUtil-1.6.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil.klib",
          "url": "DLDateUtil-iosarm64-1.6.klib",
          "size": 52120,
          "sha512": "82e93915946d7521521b613ae8cb67c917faae485197763f7fdf4f477b68a0600dddf2dc42e3044ffcbe5216ed1fd2a56d6fddf6ca58003d9cb31fe7a94f5cf7",
          "sha256": "78d5a0bc9856f44de9f6d898ce9c2f222b076571106d8f5b01b61c5e15654da9",
          "sha1": "845d35ee9ad8417f0eacb81ec90d1d0370cd7ee4",
          "md5": "afe06ca31daa5935801b56e9e892a848"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-iosarm64-1.6-metadata.jar",
          "url": "DLDateUtil-iosarm64-1.6-metadata.jar",
          "size": 261,
          "sha512": "bc14d3680eb01d4fda0dab6c98f596f1fe0fa284e0a994b95c6abaccccedb442df9a985117db7a1b5dbf6c7ca54a858b72897afab70703f257fb0960fc6d8619",
          "sha256": "69014ec95807fb838ecf552f7d79b7048df54caecf26baa95dad148a4a5c42ea",
          "sha1": "055b57f10cd05b26795025ef795e0387501b47c7",
          "md5": "6ff5ea00f67877d13d789f757d00caa2"
        }
      ]
    }
  ]
}
