{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLBluetoothUtil/0.6.0/DLBluetoothUtil-0.6.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLBluetoothUtil",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLBluetoothUtil-release.aar",
          "url": "DLBluetoothUtil-android-0.6.0.aar",
          "size": 143145,
          "sha512": "dd2e5d364e0b4293105f03ed1c7e533049b8621613a88ea82c8972749064a239bf2d685f3f3832ff2393624183e626adb954afb375fe9214c365715fb760ac16",
          "sha256": "29fac61f8a57a019148c8c9db928c24bf0efe3a9bfb2b03073bbc4362f18b7be",
          "sha1": "a88c2b32eba834fdcef1569378b2954ac1d6b5a2",
          "md5": "3e10aa68419f120bba9874508f3b35ec"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLAppUtil",
          "version": {
            "requires": "2.6.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLLogUtil",
          "version": {
            "requires": "0.1.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "DLBluetoothUtil-release.aar",
          "url": "DLBluetoothUtil-android-0.6.0.aar",
          "size": 143145,
          "sha512": "dd2e5d364e0b4293105f03ed1c7e533049b8621613a88ea82c8972749064a239bf2d685f3f3832ff2393624183e626adb954afb375fe9214c365715fb760ac16",
          "sha256": "29fac61f8a57a019148c8c9db928c24bf0efe3a9bfb2b03073bbc4362f18b7be",
          "sha1": "a88c2b32eba834fdcef1569378b2954ac1d6b5a2",
          "md5": "3e10aa68419f120bba9874508f3b35ec"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "DLBluetoothUtil-android-0.6.0-sources.jar",
          "url": "DLBluetoothUtil-android-0.6.0-sources.jar",
          "size": 18337,
          "sha512": "de3caf7f0af85f99291e4b7b7c00c8f4d9e23d8ae2feaf37fb00603dfbff18cf4f8552c420f8e75e25b4ca8082379bded32e6f0bd160d872fe928d665ae0a500",
          "sha256": "5dd7ac5aa552e0fef851303d66c8fa1095588d5cdc0a55e35d036f37408bb4b4",
          "sha1": "5fd2e2ff688ee8e291d414050f68d83bdc8c7039",
          "md5": "0b990205db864d348130535f731dd070"
        }
      ]
    }
  ]
}
