{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDatastoreUtil/0.2.1/DLDatastoreUtil-0.2.1.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDatastoreUtil",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLDatastoreUtil-iosArm64Main-0.2.1.klib",
          "url": "DLDatastoreUtil-iosarm64-0.2.1.klib",
          "size": 10974,
          "sha512": "0fddc7278e56ac0d9ce8be12ef8d84fd2bb5b53a3461911a472069dbff0665310fa551e35906b3e5e68f8c3191c059853e38fa9470c1ec58737ceece1739ceab",
          "sha256": "47a0b8e6667e57aae7a0dfe956d045656aa1d9c0fe963d012fa37b5126fc96ab",
          "sha1": "7323903ef7d3520da6ed3890e2c6a39b8b3b84cb",
          "md5": "52ed53d91761fa2f71278edf711533a7"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLDatastoreUtil-iosarm64-0.2.1-sources.jar",
          "url": "DLDatastoreUtil-iosarm64-0.2.1-sources.jar",
          "size": 3667,
          "sha512": "0264a2e5d1b158f3057c0f42cebe8ee78a758938ff7f28077d020153eb6895c96580d45f2591e011877a3ccea55f5d4867bcf795596d468eba731b8f6a807c4a",
          "sha256": "4c6cc84482f9755a4c3f5ee1ecb8c31d15c330d00a0635c6433ab150bf73eaf1",
          "sha1": "05c4dd26d0b8e2a1e4d7416e5bc4a22c3142f279",
          "md5": "25cc034df759644962644db3f1a62883"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLDatastoreUtil-iosarm64-0.2.1-metadata.jar",
          "url": "DLDatastoreUtil-iosarm64-0.2.1-metadata.jar",
          "size": 2576,
          "sha512": "8519244b01f0916077994db06b0112aad27f10f3a9e6e292dd6f86519da26032b6b2ea3a4558ab48d90be83ad81f0b714e6e381ab9caec9379164326d2761941",
          "sha256": "5bc0ffef39b9d031c6238c83a18ece72e66ccb9b7050788d5e9c43d216d14073",
          "sha1": "b2471b93866730942546dbe1e8c3cb7389fcb958",
          "md5": "6fe6709bf5cffa41e69df8223517f57d"
        }
      ]
    }
  ]
}
