{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLJetpackComposeUtil",
    "version": "3.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.6.0-shaded"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-metadata-3.1.1.jar",
          "url": "DLJetpackComposeUtil-3.1.1.jar",
          "size": 48945,
          "sha512": "5316e01e627143e7f0040f2551465d59782ddc2c0fda1cfa8a1ebec51abc58df149af6ca7e5162e2eee9d3a4bb4a93191bbcd77c259e89aee38ae6baa9aeb2aa",
          "sha256": "e78e80ef38d708fb74965c1ff42e049b801b9533cb245dd82139be0e609f3013",
          "sha1": "a4ef9eb3c0509149d9f10031b01417d4d42f9ea6",
          "md5": "ccb2736e7a545c759dc90e2d172165ea"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "DLJetpackComposeUtil-kotlin-3.1.1-sources.jar",
          "url": "DLJetpackComposeUtil-3.1.1-sources.jar",
          "size": 80370,
          "sha512": "111b1478b5492c7f7c188c76952078d2fc5f2c1841fb397885cd36182b0463aae505342033360f0dd011dfc6c78c8185d983d20fc500c087edb6033cdad01ea0",
          "sha256": "8794eb6e0093c1803e8ee23001d7cc3d1e532c59399b7599c4a33fd175338726",
          "sha1": "c352834bf140bb24ea296038f6621e2a1b8badc3",
          "md5": "306916fa2767fc400986afa35b2c38a0"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-android/3.1.1/DLJetpackComposeUtil-android-3.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-android",
        "version": "3.1.1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-android/3.1.1/DLJetpackComposeUtil-android-3.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-android",
        "version": "3.1.1"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-android/3.1.1/DLJetpackComposeUtil-android-3.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-android",
        "version": "3.1.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iosarm64/3.1.1/DLJetpackComposeUtil-iosarm64-3.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iosarm64",
        "version": "3.1.1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iosarm64/3.1.1/DLJetpackComposeUtil-iosarm64-3.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iosarm64",
        "version": "3.1.1"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iosarm64/3.1.1/DLJetpackComposeUtil-iosarm64-3.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iosarm64",
        "version": "3.1.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iosarm64/3.1.1/DLJetpackComposeUtil-iosarm64-3.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iosarm64",
        "version": "3.1.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iossimulatorarm64/3.1.1/DLJetpackComposeUtil-iossimulatorarm64-3.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iossimulatorarm64",
        "version": "3.1.1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iossimulatorarm64/3.1.1/DLJetpackComposeUtil-iossimulatorarm64-3.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iossimulatorarm64",
        "version": "3.1.1"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iossimulatorarm64/3.1.1/DLJetpackComposeUtil-iossimulatorarm64-3.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iossimulatorarm64",
        "version": "3.1.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iossimulatorarm64/3.1.1/DLJetpackComposeUtil-iossimulatorarm64-3.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iossimulatorarm64",
        "version": "3.1.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iosx64/3.1.1/DLJetpackComposeUtil-iosx64-3.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iosx64",
        "version": "3.1.1"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iosx64/3.1.1/DLJetpackComposeUtil-iosx64-3.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iosx64",
        "version": "3.1.1"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iosx64/3.1.1/DLJetpackComposeUtil-iosx64-3.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iosx64",
        "version": "3.1.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iosx64/3.1.1/DLJetpackComposeUtil-iosx64-3.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iosx64",
        "version": "3.1.1"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-wasm-js/3.1.1/DLJetpackComposeUtil-wasm-js-3.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-wasm-js",
        "version": "3.1.1"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-wasm-js/3.1.1/DLJetpackComposeUtil-wasm-js-3.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-wasm-js",
        "version": "3.1.1"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-wasm-js/3.1.1/DLJetpackComposeUtil-wasm-js-3.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-wasm-js",
        "version": "3.1.1"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-wasm-js/3.1.1/DLJetpackComposeUtil-wasm-js-3.1.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-wasm-js",
        "version": "3.1.1"
      }
    }
  ]
}
