{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "2.3.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-metadata-2.3.0-alpha01.jar",
          "url": "DLDateUtil-2.3.0-alpha01.jar",
          "size": 14336,
          "sha512": "b548da04213817ce18b1b2c8371eedafa6048567ee56a69016e96a7eaa843e61354c769c7a21e35856dedcaf0c7bed8243c667f0c03cce029aad62d77f91e8cc",
          "sha256": "e2fc921dbb4394131d16f700ae33191a4f103eccc4d4af8c32ab0f8fc1219742",
          "sha1": "8e1222ebf80f270916b3140511d71c0a60015b79",
          "md5": "279fed27a45d7a4c3a711305fecce324"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "DLDateUtil-kotlin-2.3.0-alpha01-sources.jar",
          "url": "DLDateUtil-2.3.0-alpha01-sources.jar",
          "size": 20711,
          "sha512": "1a7e2c8a7d2d19933ecf19c7c3b0f11c25e7608b4dedd5b086e4f5d789dd4aa4d9f9dd62c04193cda628ad50f2c9054fa2f3ce25a32231edb209722cc1f45861",
          "sha256": "3226355c59e086e941ccde3df5dc183c94fee93de7e471d1f0dc38165205d03e",
          "sha1": "6b6911ce395d0504143be31a704f369eb86dd172",
          "md5": "3373755ef4b3167533a70abb517304c3"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLDateUtil-android/2.3.0-alpha01/DLDateUtil-android-2.3.0-alpha01.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-android",
        "version": "2.3.0-alpha01"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLDateUtil-android/2.3.0-alpha01/DLDateUtil-android-2.3.0-alpha01.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-android",
        "version": "2.3.0-alpha01"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLDateUtil-android/2.3.0-alpha01/DLDateUtil-android-2.3.0-alpha01.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-android",
        "version": "2.3.0-alpha01"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iosarm64/2.3.0-alpha01/DLDateUtil-iosarm64-2.3.0-alpha01.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iosarm64",
        "version": "2.3.0-alpha01"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iosarm64/2.3.0-alpha01/DLDateUtil-iosarm64-2.3.0-alpha01.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iosarm64",
        "version": "2.3.0-alpha01"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iosarm64/2.3.0-alpha01/DLDateUtil-iosarm64-2.3.0-alpha01.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iosarm64",
        "version": "2.3.0-alpha01"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iossimulatorarm64/2.3.0-alpha01/DLDateUtil-iossimulatorarm64-2.3.0-alpha01.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iossimulatorarm64",
        "version": "2.3.0-alpha01"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iossimulatorarm64/2.3.0-alpha01/DLDateUtil-iossimulatorarm64-2.3.0-alpha01.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iossimulatorarm64",
        "version": "2.3.0-alpha01"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iossimulatorarm64/2.3.0-alpha01/DLDateUtil-iossimulatorarm64-2.3.0-alpha01.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iossimulatorarm64",
        "version": "2.3.0-alpha01"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iosx64/2.3.0-alpha01/DLDateUtil-iosx64-2.3.0-alpha01.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iosx64",
        "version": "2.3.0-alpha01"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iosx64/2.3.0-alpha01/DLDateUtil-iosx64-2.3.0-alpha01.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iosx64",
        "version": "2.3.0-alpha01"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-iosx64/2.3.0-alpha01/DLDateUtil-iosx64-2.3.0-alpha01.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-iosx64",
        "version": "2.3.0-alpha01"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLDateUtil-js/2.3.0-alpha01/DLDateUtil-js-2.3.0-alpha01.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-js",
        "version": "2.3.0-alpha01"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLDateUtil-js/2.3.0-alpha01/DLDateUtil-js-2.3.0-alpha01.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-js",
        "version": "2.3.0-alpha01"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLDateUtil-js/2.3.0-alpha01/DLDateUtil-js-2.3.0-alpha01.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-js",
        "version": "2.3.0-alpha01"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLDateUtil-jvm/2.3.0-alpha01/DLDateUtil-jvm-2.3.0-alpha01.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-jvm",
        "version": "2.3.0-alpha01"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLDateUtil-jvm/2.3.0-alpha01/DLDateUtil-jvm-2.3.0-alpha01.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-jvm",
        "version": "2.3.0-alpha01"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLDateUtil-jvm/2.3.0-alpha01/DLDateUtil-jvm-2.3.0-alpha01.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-jvm",
        "version": "2.3.0-alpha01"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-linuxarm64/2.3.0-alpha01/DLDateUtil-linuxarm64-2.3.0-alpha01.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-linuxarm64",
        "version": "2.3.0-alpha01"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-linuxarm64/2.3.0-alpha01/DLDateUtil-linuxarm64-2.3.0-alpha01.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-linuxarm64",
        "version": "2.3.0-alpha01"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-linuxx64/2.3.0-alpha01/DLDateUtil-linuxx64-2.3.0-alpha01.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-linuxx64",
        "version": "2.3.0-alpha01"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-linuxx64/2.3.0-alpha01/DLDateUtil-linuxx64-2.3.0-alpha01.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-linuxx64",
        "version": "2.3.0-alpha01"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-macosarm64/2.3.0-alpha01/DLDateUtil-macosarm64-2.3.0-alpha01.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-macosarm64",
        "version": "2.3.0-alpha01"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-macosarm64/2.3.0-alpha01/DLDateUtil-macosarm64-2.3.0-alpha01.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-macosarm64",
        "version": "2.3.0-alpha01"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-macosarm64/2.3.0-alpha01/DLDateUtil-macosarm64-2.3.0-alpha01.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-macosarm64",
        "version": "2.3.0-alpha01"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-macosx64/2.3.0-alpha01/DLDateUtil-macosx64-2.3.0-alpha01.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-macosx64",
        "version": "2.3.0-alpha01"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-macosx64/2.3.0-alpha01/DLDateUtil-macosx64-2.3.0-alpha01.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-macosx64",
        "version": "2.3.0-alpha01"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLDateUtil-macosx64/2.3.0-alpha01/DLDateUtil-macosx64-2.3.0-alpha01.module",
        "group": "com.github.D10NGYANG",
        "module": "DLDateUtil-macosx64",
        "version": "2.3.0-alpha01"
      }
    }
  ]
}
