{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLMapboxUtil",
    "version": "0.9.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mapbox.maps",
          "module": "android",
          "version": {
            "requires": "10.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "DLMapboxUtil-0.9.8.aar",
          "url": "DLMapboxUtil-0.9.8.aar",
          "size": 850034,
          "sha512": "465e4c4ebbda40c3620c1750c5a9a69e6609d976be845d99cb9833df370a9b072af9fa805681548ebd1022559143264a91b280467f6b0fe5c190be11245c2415",
          "sha256": "e16127811e607dd5537059e60b675bbc61992d5b5c50b1bc4623bc689c8147e1",
          "sha1": "ab75297d852e58640789638166b7c7fda75c043c",
          "md5": "419631b8edd723039ad9a271fb0bbe0f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "io.github.raamcosta.compose-destinations",
          "module": "animations-core",
          "version": {
            "requires": "1.8.42-beta"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLJetpackComposeUtil",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLAppUtil",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLGpsUtil",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLLatLngUtil-jvm",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLTianDiTuApi-jvm",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLHttpUtil-jvm",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "com.mapbox.maps",
          "module": "android",
          "version": {
            "requires": "10.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "DLMapboxUtil-0.9.8.aar",
          "url": "DLMapboxUtil-0.9.8.aar",
          "size": 850034,
          "sha512": "465e4c4ebbda40c3620c1750c5a9a69e6609d976be845d99cb9833df370a9b072af9fa805681548ebd1022559143264a91b280467f6b0fe5c190be11245c2415",
          "sha256": "e16127811e607dd5537059e60b675bbc61992d5b5c50b1bc4623bc689c8147e1",
          "sha1": "ab75297d852e58640789638166b7c7fda75c043c",
          "md5": "419631b8edd723039ad9a271fb0bbe0f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLMapboxUtil-0.9.8-sources.jar",
          "url": "DLMapboxUtil-0.9.8-sources.jar",
          "size": 44427,
          "sha512": "0b50c64a054b4e83869df60f46f11c3e9b00629dabdf3d8a7c5ec5ea20f189edba801186683723a7fd7efc27569f95adb771a78187aef551af8c3124068d47ae",
          "sha256": "4f5738257706f3e25e26ab9beba524693852a873f03c6338a8d92274503b87ef",
          "sha1": "5f16280ef315218533a3c1576eb85c746ff40aa5",
          "md5": "bc08a85c93282d822d54bfac8efc9999"
        }
      ]
    }
  ]
}
