{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLJetpackComposeUtil/3.1.1/DLJetpackComposeUtil-3.1.1.module",
    "group": "com.github.D10NGYANG",
    "module": "DLJetpackComposeUtil",
    "version": "3.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-wasm-js-3.1.1.klib",
          "url": "DLJetpackComposeUtil-wasm-js-3.1.1.klib",
          "size": 639022,
          "sha512": "9188fde5b2d371f5ff9919d0994d09f5de395d33cab9f7326ca424f961939d4392c40d5835ee7b531a95d18d82b1d98332b228f407ff5921ee6941d9f276fba4",
          "sha256": "b1c0115f6a116918f9492fbcba6337163f0b57374ef08a6877f42cc77d9b655b",
          "sha1": "e584b108b5191a7e23b7f033a06cec08232bd456",
          "md5": "688a07b9cdd6dcb5d0a378cee15886d1"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.6.0-shaded"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-wasm-js-3.1.1.klib",
          "url": "DLJetpackComposeUtil-wasm-js-3.1.1.klib",
          "size": 639022,
          "sha512": "9188fde5b2d371f5ff9919d0994d09f5de395d33cab9f7326ca424f961939d4392c40d5835ee7b531a95d18d82b1d98332b228f407ff5921ee6941d9f276fba4",
          "sha256": "b1c0115f6a116918f9492fbcba6337163f0b57374ef08a6877f42cc77d9b655b",
          "sha1": "e584b108b5191a7e23b7f033a06cec08232bd456",
          "md5": "688a07b9cdd6dcb5d0a378cee15886d1"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "DLJetpackComposeUtil-wasm-js-3.1.1-sources.jar",
          "url": "DLJetpackComposeUtil-wasm-js-3.1.1-sources.jar",
          "size": 81014,
          "sha512": "0109365447096840cb8478047ffe83332242723026cd334948ae844bf668d2352732993915639232f270a3a89112d88cf0ae691fd624195a322b46a3c5adc08d",
          "sha256": "70aa4bad1be4c48faa6d06ce657f534ef6b6ba6cc433fb92f79f8462af34b6a2",
          "sha1": "cd2e466b558c12c54ad77ebd55142689d4930296",
          "md5": "82bbdcfebb77321c7c5510ccaa72ccc8"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.6.0-shaded"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-3.1.1.kotlin_resources.zip",
          "url": "DLJetpackComposeUtil-wasm-js-3.1.1-kotlin_resources.kotlin_resources.zip",
          "size": 10276,
          "sha512": "28b5a60b413c713e65f960616461941bd71ec0651613f0017b3bd97fe03cb0af4ad9bdec67fb497a4309234deafb261411dcb06bcdc00c6b099b7dc9f03184ac",
          "sha256": "87e3e67daa60ebf5c5d05b0b4d0c28a6ba91453e72f538b5c9dd76d3dac22bf0",
          "sha1": "046e770bf1a9bf7d65ebaeef8ed9272485c8896e",
          "md5": "c021fe773696e9ba1ec90c56e01543df"
        }
      ]
    }
  ]
}
