{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ImageCompress/1.0.0/ImageCompress-1.0.0.module",
    "group": "com.hailiao.util",
    "module": "ImageCompress",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ImageCompress.klib",
          "url": "ImageCompress-iosarm64-1.0.0.klib",
          "size": 37906,
          "sha512": "3c180637647eeafa2d31bf4b935174713e19e1d426ef6f35cbe7a97e768237217ea402a41a2da8f33ad45387c87cc17ad5b4a3302ecc1b9c4dd5c40a9a99bbec",
          "sha256": "20eaf80b11c4f868e69ce95e6ed256ef067f8a9b8d5cf77f95fca0079fbd68c7",
          "sha1": "65259d282504546edca46a3241b6e3383aadf4d7",
          "md5": "814132291d3c3782e3ce45472ae90d57"
        },
        {
          "name": "ImageCompress-cinterop-ImageCompress.klib",
          "url": "ImageCompress-iosarm64-1.0.0-cinterop-ImageCompress.klib",
          "size": 267434,
          "sha512": "45e0313e50896b1d6cc65b67251159ace9b80249dbe27eb67d46d58a4cd228469d5f1bb4a3dce82f25250016cd51f24d74121ccc560f88f0067386344e046c89",
          "sha256": "fda78a1fb1f256fec0b8669605406c0a0fa7c1b9bcd9eaf55b32d8c144299d31",
          "sha1": "7c2d9a57ef891ec4dc993b76eba96e65623610b0",
          "md5": "2d23ddcc1d7b81bcab3d70f2bcddde7a"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ImageCompress-iosarm64-1.0.0-sources.jar",
          "url": "ImageCompress-iosarm64-1.0.0-sources.jar",
          "size": 11344,
          "sha512": "34869c1587adec2c6d5d8652614e521b5d2bc9c7c03db4d62618e9cce544d548ab5671c8baef79d0ad8fbdbc24a7d312a0aab99e4fa401f22edafd2c97294b12",
          "sha256": "6df849476786874314c390cf4898d18693cb0b21f437529d293cffa444735ebe",
          "sha1": "db5b52308c8818f51680672acdbffd4e34bb47bf",
          "md5": "0345c769e9e8374483e6f2df5e65486e"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ImageCompress-iosarm64-1.0.0-metadata.jar",
          "url": "ImageCompress-iosarm64-1.0.0-metadata.jar",
          "size": 261,
          "sha512": "a02e9c8aca7062f9b0a7cec55a01b6fc5eafdf0b0775b867f45a15307860c8acbb05ecaf6d2a9b27b21f802c23f4356374f5c4b2fd2c582adfccf0b3802e55cb",
          "sha256": "b654d391deec25c0d0d2ad7eab331d0061719ed948d8b65ebd8feaaa1baec2b3",
          "sha1": "9671046fbcd4b2ac25eac2ebede04cd086957dc8",
          "md5": "88ddc49462ab4c6ccd59cafbfc2663c9"
        }
      ]
    }
  ]
}
