{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/1.9.4/DLDateUtil-1.9.4.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "1.9.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil.klib",
          "url": "DLDateUtil-iossimulatorarm64-1.9.4.klib",
          "size": 60007,
          "sha512": "1ec7f3c09e9c237c6469529691e82817264dabd2cfe75c2afe76bcf3dc3aeb2a0f6069a4a7e90139efd4d962cbc46b837bc2be34cc26172ff6ec1e77051c6dd5",
          "sha256": "28de3b32ce01c42a3b71587f0d719bced69c78be091e32d328e37c1dcd59f750",
          "sha1": "c4b0011c8cd2ff2c1bafc62f1c41116be2779f2a",
          "md5": "6445c76eae72230b23479f2b063c65db"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLDateUtil-iossimulatorarm64-1.9.4-sources.jar",
          "url": "DLDateUtil-iossimulatorarm64-1.9.4-sources.jar",
          "size": 11809,
          "sha512": "ea24f10dc8a5188c1d85b6e5ef2923981267b1637d1ea93f0db5b16ced012a2492114cadbe499edd71d21f25a5d58a3dbff605f9c7633c75c4958cb35e9dd4cf",
          "sha256": "5e697495954e3d8372f25f09fc7e23e8d63052f7c68ec7bb4bcd3fd948e4e0a2",
          "sha1": "b32b254f6a56032ae2491674fce7f99506dbce91",
          "md5": "8da7f0d3f956d1700fa3513a283e2ffa"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-iossimulatorarm64-1.9.4-metadata.jar",
          "url": "DLDateUtil-iossimulatorarm64-1.9.4-metadata.jar",
          "size": 261,
          "sha512": "86b899d4e0125ce8d998d82bb3f9d327e8378a4639a3f8d2e98cf6a833068e38af73b1470f83033b8919f2a7195436369bae76ae4c6a6faad9f11715afbe9c3a",
          "sha256": "3aca364fe6ccbbc68dbd9b1ad3d05ec5384993a778a395925e841a5086ccfc7b",
          "sha1": "3a0e62a9501443393d132cc5e5fcbec63a301ee9",
          "md5": "52ea6810068ab564c1f1fbc1f0e19133"
        }
      ]
    }
  ]
}
