{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLDateUtil/1.6/DLDateUtil-1.6.module",
    "group": "com.github.D10NGYANG",
    "module": "DLDateUtil",
    "version": "1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil.klib",
          "url": "DLDateUtil-iosx64-1.6.klib",
          "size": 52104,
          "sha512": "df781aadae0ee68b540a591fcba7c61279d4477a38ff47a9b420b2e72fdb75df0cf35a0df9d69fd7b9888ed4f6867bd10917dc3e883be7964176ed4b058f353d",
          "sha256": "568fb7b73a045b8d10644a6a6ef1e08b0d43fd689c8f90f91e858478da2f89da",
          "sha1": "c7fb6ca00cd2935319ad4d91ca8ec86a10176f54",
          "md5": "28e70421dd6d64ff58ca54ab32ff2968"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLDateUtil-iosx64-1.6-metadata.jar",
          "url": "DLDateUtil-iosx64-1.6-metadata.jar",
          "size": 261,
          "sha512": "bc14d3680eb01d4fda0dab6c98f596f1fe0fa284e0a994b95c6abaccccedb442df9a985117db7a1b5dbf6c7ca54a858b72897afab70703f257fb0960fc6d8619",
          "sha256": "69014ec95807fb838ecf552f7d79b7048df54caecf26baa95dad148a4a5c42ea",
          "sha1": "055b57f10cd05b26795025ef795e0387501b47c7",
          "md5": "6ff5ea00f67877d13d789f757d00caa2"
        }
      ]
    }
  ]
}
