{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLJetpackComposeUtil/3.0.0-RC08/DLJetpackComposeUtil-3.0.0-RC08.module",
    "group": "com.github.D10NGYANG",
    "module": "DLJetpackComposeUtil",
    "version": "3.0.0-RC08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLDateUtil",
          "version": {
            "requires": "2.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-iosSimulatorArm64Main-3.0.0-RC08.klib",
          "url": "DLJetpackComposeUtil-iossimulatorarm64-3.0.0-RC08.klib",
          "size": 598950,
          "sha512": "983105f53b15b9e4dfc10b1ddea3069b97ff5735cb4ae5f5743b89834abebc6473e36c6d8db7c9e6dec70cc360b4d9ca57ac427f1427819e0a4b7a8bab0fe13e",
          "sha256": "15589269847b3f6cbfbb9c4fdb86523e8107909b64505966e6e85618541450e8",
          "sha1": "0ab32e92e70b6273dc6a6673255e83aa257b478c",
          "md5": "0e3e629c9a75d9d177cae32b396f2be8"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLJetpackComposeUtil-iossimulatorarm64-3.0.0-RC08-sources.jar",
          "url": "DLJetpackComposeUtil-iossimulatorarm64-3.0.0-RC08-sources.jar",
          "size": 81369,
          "sha512": "e030536ce5ee79344bce771df9c62f5775c068b48d81c6d2d15bb8f8c4ac9227463ecd146a878f0f84c3efa1b1209834b3e7428036798caafd265f2f9373406f",
          "sha256": "2e0c69be1c86fddb86bd00d7f97ed31f54cee35cac43b8ebbfea440175d43496",
          "sha1": "7104205b19ef5a598207b1bb529e0d434e5ca645",
          "md5": "3901d01acdf90434ccb73741155143cf"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLDateUtil",
          "version": {
            "requires": "2.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-3.0.0-RC08.kotlin_resources.zip",
          "url": "DLJetpackComposeUtil-iossimulatorarm64-3.0.0-RC08-kotlin_resources.kotlin_resources.zip",
          "size": 10276,
          "sha512": "146a8635d9c01c9ba7cd13c19243bc436832818d52ce9573ecb3c10205448d971cb28bc6274185c935d702f215ee33d9263ca93206f28d18df49692645872fbb",
          "sha256": "8a37d25c5416c365d4f83d4f2c77206b99c8a057eef465917ce204b2aa6bde63",
          "sha1": "5252acfdc6e9394b93f263292b9e88a5a2c69098",
          "md5": "ee4187957f5c1123334a4fac84dc2136"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLDateUtil",
          "version": {
            "requires": "2.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-iossimulatorarm64-3.0.0-RC08-metadata.jar",
          "url": "DLJetpackComposeUtil-iossimulatorarm64-3.0.0-RC08-metadata.jar",
          "size": 2618,
          "sha512": "e0f3603b0498e3c68e4f878a656c8d696191448f78e9b5442e7890bf91c512f7a669caf85b88f5bc5fc5d1275ac6f32ec5f924e3ea359cf7b751d3ded1162d32",
          "sha256": "9eb2e85c1d84a6f115fef2a210aec0e8244f228ea9a0013239b37a12e8102c40",
          "sha1": "b8032e6b6fd28145dd72e02ccbb4b09d88b5e71f",
          "md5": "efe401cb357b84a149d6bcdf84fde560"
        }
      ]
    }
  ]
}
