{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLJetpackComposeUtil",
    "version": "3.0.0-RC02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.5.4"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLDateUtil",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-metadata-3.0.0-RC02.jar",
          "url": "DLJetpackComposeUtil-3.0.0-RC02.jar",
          "size": 47924,
          "sha512": "a9ad2fe9dff5c31bc3d0df4abeedfb0b93f90211f08a0f226bc2d82a3397a08e8255177c6666f57e6d467eb45373e62f153d968ebdcf7299bb223c77168b817f",
          "sha256": "980bc80c03c1fb8d39d34e73a8cf8ceec6f3772983732fe4c24db2f7ae563551",
          "sha1": "d3572f341fe513eb0dc1e3b1096d1a0611e5ab54",
          "md5": "3cb8f0ad77310a56e52bd98e7e7a36b2"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "DLJetpackComposeUtil-kotlin-3.0.0-RC02-sources.jar",
          "url": "DLJetpackComposeUtil-3.0.0-RC02-sources.jar",
          "size": 78002,
          "sha512": "e7402337b1903726cd6d04f616f0f50049f701f9946b2218a277e2d64df0c0b6b184218e8a3979f7f5aa5aa849ac472cd78a2477bb142d965b3d4aed23389769",
          "sha256": "dbb2d17f459c736a3ea76f14817c64b4b560e064e725ae45be49129b2e6ea378",
          "sha1": "1afb4edcbee732470315cd679aec4c054ce04612",
          "md5": "63bad3e12d21ab09177e2af7c6fbf8be"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-android/3.0.0-RC02/DLJetpackComposeUtil-android-3.0.0-RC02.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-android",
        "version": "3.0.0-RC02"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-android/3.0.0-RC02/DLJetpackComposeUtil-android-3.0.0-RC02.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-android",
        "version": "3.0.0-RC02"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-android/3.0.0-RC02/DLJetpackComposeUtil-android-3.0.0-RC02.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-android",
        "version": "3.0.0-RC02"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iosarm64/3.0.0-RC02/DLJetpackComposeUtil-iosarm64-3.0.0-RC02.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iosarm64",
        "version": "3.0.0-RC02"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iosarm64/3.0.0-RC02/DLJetpackComposeUtil-iosarm64-3.0.0-RC02.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iosarm64",
        "version": "3.0.0-RC02"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iosarm64/3.0.0-RC02/DLJetpackComposeUtil-iosarm64-3.0.0-RC02.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iosarm64",
        "version": "3.0.0-RC02"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iosarm64/3.0.0-RC02/DLJetpackComposeUtil-iosarm64-3.0.0-RC02.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iosarm64",
        "version": "3.0.0-RC02"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iossimulatorarm64/3.0.0-RC02/DLJetpackComposeUtil-iossimulatorarm64-3.0.0-RC02.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iossimulatorarm64",
        "version": "3.0.0-RC02"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iossimulatorarm64/3.0.0-RC02/DLJetpackComposeUtil-iossimulatorarm64-3.0.0-RC02.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iossimulatorarm64",
        "version": "3.0.0-RC02"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iossimulatorarm64/3.0.0-RC02/DLJetpackComposeUtil-iossimulatorarm64-3.0.0-RC02.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iossimulatorarm64",
        "version": "3.0.0-RC02"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iossimulatorarm64/3.0.0-RC02/DLJetpackComposeUtil-iossimulatorarm64-3.0.0-RC02.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iossimulatorarm64",
        "version": "3.0.0-RC02"
      }
    }
  ]
}
