{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLPcmResampleUtil/0.2.5/DLPcmResampleUtil-0.2.5.module",
    "group": "com.github.D10NGYANG",
    "module": "DLPcmResampleUtil",
    "version": "0.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLPcmResampleUtil-iosArm64Main-0.2.5.klib",
          "url": "DLPcmResampleUtil-iosarm64-0.2.5.klib",
          "size": 222601,
          "sha512": "f8147343640a59030fb54c9e3fb7283d73d5c528102262c82aa47d90cc416dd6694df151b45cf49117ee7044772a213a4ea7a16ad8a6b758e6d287bd9edc1cd7",
          "sha256": "7a22f0e5ad047c87ba146b23396216de22e78b4901a9f7af9c232a17edb5cb5c",
          "sha1": "53a771cd7e771020dbbbd4f1e7d13b2e0d14a0b6",
          "md5": "3b6edbc7bb80abb89cbdcbdf23c04c0e"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLPcmResampleUtil-iosarm64-0.2.5-sources.jar",
          "url": "DLPcmResampleUtil-iosarm64-0.2.5-sources.jar",
          "size": 29527,
          "sha512": "1a194d4e2857f7193e66f10520343b3936df7d348c00f3bda215e19056c48944d24e2e5f729ca375935618e6184615c890426f7d23562f343c79ee8acc1c407c",
          "sha256": "a5c1d6a53b898b6678bd2f030f75dd7fce53899ecf8781f4487223aaca919e51",
          "sha1": "3f9636b6b03ac896e64cca4922a78ef7598e1877",
          "md5": "32d19eca613b0166d22c4fd22eb7f266"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLPcmResampleUtil-iosarm64-0.2.5-metadata.jar",
          "url": "DLPcmResampleUtil-iosarm64-0.2.5-metadata.jar",
          "size": 261,
          "sha512": "460ea69dc39f94953181dce45bd5b2651b3a083be6847d14fe60e29c04f27040ebbc59794a93d93f7febd8f3a76e5906ce765218640c54896dec176f2e780cec",
          "sha256": "e9181d64963ce0f751c45b460b5bd6a43ca4b19d03cc8457887a8c34a2ff4134",
          "sha1": "560231d2cab22bb321a9166ad01b64f1eadfdd2a",
          "md5": "943ec6a57a359b903656e2ad00f0bdde"
        }
      ]
    }
  ]
}
