{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLGpsUtil",
    "version": "2.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLGpsUtil-2.2.1.aar",
          "url": "DLGpsUtil-2.2.1.aar",
          "size": 23360,
          "sha512": "ac97d0094fb415252d1dcec7b97f1d3737280a48564405c57271893a983def1542f4ddf99156d785f5cc2da1a9edc9a188e224d56471b8bc6ea6fec13543eec8",
          "sha256": "2f6b6d150096b9f63da4195ec5e3ec75c3c53d35f232d28b23d910d316592e34",
          "sha1": "2bb0585ce526264375575fe1b848cf8dd442c700",
          "md5": "262ef1a29de82fcb0713146b94de3f86"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLLatLngUtil-jvm",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.amap.api",
          "module": "location",
          "version": {
            "requires": "latest.integration"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "DLGpsUtil-2.2.1.aar",
          "url": "DLGpsUtil-2.2.1.aar",
          "size": 23360,
          "sha512": "ac97d0094fb415252d1dcec7b97f1d3737280a48564405c57271893a983def1542f4ddf99156d785f5cc2da1a9edc9a188e224d56471b8bc6ea6fec13543eec8",
          "sha256": "2f6b6d150096b9f63da4195ec5e3ec75c3c53d35f232d28b23d910d316592e34",
          "sha1": "2bb0585ce526264375575fe1b848cf8dd442c700",
          "md5": "262ef1a29de82fcb0713146b94de3f86"
        }
      ]
    }
  ]
}
