{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLLogUtil/0.2.0/DLLogUtil-0.2.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLLogUtil",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLLogUtil-wasm-js-0.2.0.klib",
          "url": "DLLogUtil-wasm-js-0.2.0.klib",
          "size": 17082,
          "sha512": "77e13c93e8ccc882cc73ce8caf9fe79648a8596e6c715fdfe7df75173e3cb0cc1fc4d7365ac4cd9289e33b7fad59d49592eb72e398e7ce18f99d7ca4e9c60e85",
          "sha256": "f23ca2110966ed3f7bf1bd184a48aaf01f0ec578748639a7291e99fd83957f96",
          "sha1": "df674133be46445d49cabff5cc61b9a27ad47224",
          "md5": "3ad7e0edf85d739ed9d406963b70c66f"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "DLLogUtil-wasm-js-0.2.0.klib",
          "url": "DLLogUtil-wasm-js-0.2.0.klib",
          "size": 17082,
          "sha512": "77e13c93e8ccc882cc73ce8caf9fe79648a8596e6c715fdfe7df75173e3cb0cc1fc4d7365ac4cd9289e33b7fad59d49592eb72e398e7ce18f99d7ca4e9c60e85",
          "sha256": "f23ca2110966ed3f7bf1bd184a48aaf01f0ec578748639a7291e99fd83957f96",
          "sha1": "df674133be46445d49cabff5cc61b9a27ad47224",
          "md5": "3ad7e0edf85d739ed9d406963b70c66f"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "DLLogUtil-wasm-js-0.2.0-sources.jar",
          "url": "DLLogUtil-wasm-js-0.2.0-sources.jar",
          "size": 4574,
          "sha512": "ef161075d2a692f599c573a33f2b3fc9ceaa59320ea857368aa949d3f4a807e8ecc751d05499fececb101babe92fd5d1bfeb20e10c752e9173d8152691bf1be2",
          "sha256": "33811f6c14815bec7c9a1fbbbc80c9a2671f17c34c270e1972c0aeb21aa94268",
          "sha1": "75bfb4c8d50f470ba20b94e681cb89288f74423c",
          "md5": "23b46d30c5ccef2936e50bf06d326996"
        }
      ]
    }
  ]
}
