{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLJetpackComposeUtil",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-metadata-3.2.1.jar",
          "url": "DLJetpackComposeUtil-3.2.1.jar",
          "size": 50505,
          "sha512": "b0960ee857a1d2bbd195481870b601ba5bda362144de24165af2cfbb582f13bbda5172a6e4eff064e0cfa155a567024f72cb58e071e4965769e4183dedaa440f",
          "sha256": "ee2ea260c9f9eaadc3c0af04e6238c8e0a5bf97f46c8991c362eadd6bdb9df8c",
          "sha1": "457dd2176b55314b50d2b226aac38c4ed4ccb3b6",
          "md5": "e734360b7be5ae51c4f1cce2d3000f09"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "DLJetpackComposeUtil-kotlin-3.2.1-sources.jar",
          "url": "DLJetpackComposeUtil-3.2.1-sources.jar",
          "size": 100657,
          "sha512": "9b595eb3c06d467f4dff0abc9246068a40539b56033b491d27c0e2fd90636b3a63d9966559bd0f2d770dc67f9ec1f425809112c7723edb0301f648ac49efa143",
          "sha256": "dee364cf0d4fd2cba82a31ae7f448d3531d734da15cf68c831d63ad5cbd9339d",
          "sha1": "c00673e32de5203b48fadf50412b1148eb1f44f5",
          "md5": "c9f7124b7c6b3892e5c46901f9f03176"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-android/3.2.1/DLJetpackComposeUtil-android-3.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-android",
        "version": "3.2.1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-android/3.2.1/DLJetpackComposeUtil-android-3.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-android",
        "version": "3.2.1"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-android/3.2.1/DLJetpackComposeUtil-android-3.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-android",
        "version": "3.2.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iosarm64/3.2.1/DLJetpackComposeUtil-iosarm64-3.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iosarm64",
        "version": "3.2.1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iosarm64/3.2.1/DLJetpackComposeUtil-iosarm64-3.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iosarm64",
        "version": "3.2.1"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iosarm64/3.2.1/DLJetpackComposeUtil-iosarm64-3.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iosarm64",
        "version": "3.2.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iosarm64/3.2.1/DLJetpackComposeUtil-iosarm64-3.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iosarm64",
        "version": "3.2.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iossimulatorarm64/3.2.1/DLJetpackComposeUtil-iossimulatorarm64-3.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iossimulatorarm64",
        "version": "3.2.1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iossimulatorarm64/3.2.1/DLJetpackComposeUtil-iossimulatorarm64-3.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iossimulatorarm64",
        "version": "3.2.1"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iossimulatorarm64/3.2.1/DLJetpackComposeUtil-iossimulatorarm64-3.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iossimulatorarm64",
        "version": "3.2.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iossimulatorarm64/3.2.1/DLJetpackComposeUtil-iossimulatorarm64-3.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iossimulatorarm64",
        "version": "3.2.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iosx64/3.2.1/DLJetpackComposeUtil-iosx64-3.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iosx64",
        "version": "3.2.1"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iosx64/3.2.1/DLJetpackComposeUtil-iosx64-3.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iosx64",
        "version": "3.2.1"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iosx64/3.2.1/DLJetpackComposeUtil-iosx64-3.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iosx64",
        "version": "3.2.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-iosx64/3.2.1/DLJetpackComposeUtil-iosx64-3.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-iosx64",
        "version": "3.2.1"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-js/3.2.1/DLJetpackComposeUtil-js-3.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-js",
        "version": "3.2.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-js/3.2.1/DLJetpackComposeUtil-js-3.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-js",
        "version": "3.2.1"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-js/3.2.1/DLJetpackComposeUtil-js-3.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-js",
        "version": "3.2.1"
      }
    },
    {
      "name": "jsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-js/3.2.1/DLJetpackComposeUtil-js-3.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-js",
        "version": "3.2.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-jvm/3.2.1/DLJetpackComposeUtil-jvm-3.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-jvm",
        "version": "3.2.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-jvm/3.2.1/DLJetpackComposeUtil-jvm-3.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-jvm",
        "version": "3.2.1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-jvm/3.2.1/DLJetpackComposeUtil-jvm-3.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-jvm",
        "version": "3.2.1"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-wasm-js/3.2.1/DLJetpackComposeUtil-wasm-js-3.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-wasm-js",
        "version": "3.2.1"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-wasm-js/3.2.1/DLJetpackComposeUtil-wasm-js-3.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-wasm-js",
        "version": "3.2.1"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-wasm-js/3.2.1/DLJetpackComposeUtil-wasm-js-3.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-wasm-js",
        "version": "3.2.1"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../DLJetpackComposeUtil-wasm-js/3.2.1/DLJetpackComposeUtil-wasm-js-3.2.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLJetpackComposeUtil-wasm-js",
        "version": "3.2.1"
      }
    }
  ]
}
