{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLSerialPortUtil",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLLogUtil",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLSerialPortUtil-metadata-0.7.0.jar",
          "url": "DLSerialPortUtil-0.7.0.jar",
          "size": 14227,
          "sha512": "8b9bc45b279f1bb72275e31c0d7d18856bba84cacc447d2a2887ae1b8a9037ea08dc999a09c5e7aefe184b2daad4d931d7aabea5ac7d083decb0ed7e78cc3bd9",
          "sha256": "d7e4a7312b1bc62283dff4a1e8babfb8c7af6a23cacc59b784f370fcb6aa8440",
          "sha1": "903ede0c2c675508197218d261613793a940b6bf",
          "md5": "c10f57a741e80e4914dff47aac3f788d"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "DLSerialPortUtil-kotlin-0.7.0-sources.jar",
          "url": "DLSerialPortUtil-0.7.0-sources.jar",
          "size": 20176,
          "sha512": "fbd93d178bc53824a40bc17abff9e93bf529772bb01b63586c8782bb328a83615ada670a71f11b0495b730b5a7d3fff94c66b590c2f2e5aa0ab8ac8d446281f8",
          "sha256": "194f2d74cb74efbda34287d8b5f53bec1fa86bae8e7974914e07a315af22960a",
          "sha1": "7621815781a66a673ee7d01c8368f453b4e0af1b",
          "md5": "aab671cf05a4f01168fd44735e6f428e"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-android/0.7.0/DLSerialPortUtil-android-0.7.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-android",
        "version": "0.7.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-android/0.7.0/DLSerialPortUtil-android-0.7.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-android",
        "version": "0.7.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-android/0.7.0/DLSerialPortUtil-android-0.7.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-android",
        "version": "0.7.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-js/0.7.0/DLSerialPortUtil-js-0.7.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-js",
        "version": "0.7.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-js/0.7.0/DLSerialPortUtil-js-0.7.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-js",
        "version": "0.7.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-js/0.7.0/DLSerialPortUtil-js-0.7.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-js",
        "version": "0.7.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-jvm/0.7.0/DLSerialPortUtil-jvm-0.7.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-jvm",
        "version": "0.7.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-jvm/0.7.0/DLSerialPortUtil-jvm-0.7.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-jvm",
        "version": "0.7.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-jvm/0.7.0/DLSerialPortUtil-jvm-0.7.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-jvm",
        "version": "0.7.0"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-linuxarm64/0.7.0/DLSerialPortUtil-linuxarm64-0.7.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-linuxarm64",
        "version": "0.7.0"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-linuxarm64/0.7.0/DLSerialPortUtil-linuxarm64-0.7.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-linuxarm64",
        "version": "0.7.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-linuxx64/0.7.0/DLSerialPortUtil-linuxx64-0.7.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-linuxx64",
        "version": "0.7.0"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-linuxx64/0.7.0/DLSerialPortUtil-linuxx64-0.7.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-linuxx64",
        "version": "0.7.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-macosarm64/0.7.0/DLSerialPortUtil-macosarm64-0.7.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-macosarm64",
        "version": "0.7.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-macosarm64/0.7.0/DLSerialPortUtil-macosarm64-0.7.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-macosarm64",
        "version": "0.7.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-macosarm64/0.7.0/DLSerialPortUtil-macosarm64-0.7.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-macosarm64",
        "version": "0.7.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-macosx64/0.7.0/DLSerialPortUtil-macosx64-0.7.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-macosx64",
        "version": "0.7.0"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-macosx64/0.7.0/DLSerialPortUtil-macosx64-0.7.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-macosx64",
        "version": "0.7.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-macosx64/0.7.0/DLSerialPortUtil-macosx64-0.7.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-macosx64",
        "version": "0.7.0"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-wasm-js/0.7.0/DLSerialPortUtil-wasm-js-0.7.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-wasm-js",
        "version": "0.7.0"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-wasm-js/0.7.0/DLSerialPortUtil-wasm-js-0.7.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-wasm-js",
        "version": "0.7.0"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../DLSerialPortUtil-wasm-js/0.7.0/DLSerialPortUtil-wasm-js-0.7.0.module",
        "group": "com.github.D10NGYANG",
        "module": "DLSerialPortUtil-wasm-js",
        "version": "0.7.0"
      }
    }
  ]
}
