{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLCommonUtil/0.0.8/DLCommonUtil-0.0.8.module",
    "group": "com.github.D10NGYANG",
    "module": "DLCommonUtil",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.ditchoom",
          "module": "buffer",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil.klib",
          "url": "DLCommonUtil-iosarm64-0.0.8.klib",
          "size": 98398,
          "sha512": "22fdda5a6169aeb6b71e413bd7613362aba568218ce39ada937a2131d3a5bb2472a356935027d262a8c3acdbac8bb05693d67ac65c093931e2f0827c84d9d30d",
          "sha256": "83c981fec413b6b4f1fe9edee75befa8d53a6fecde3ffe17c962620feae29272",
          "sha1": "111a2fb7afe5fea3a18d410eca23bd2eaedaf087",
          "md5": "34c59041850eb13c341190bb51a57d3a"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLCommonUtil-iosarm64-0.0.8-sources.jar",
          "url": "DLCommonUtil-iosarm64-0.0.8-sources.jar",
          "size": 27103,
          "sha512": "d16564e2eb03edc63868c2ff2ea5bbb8586f5c725922a14d77a89bd37b7347c55453ec8eb3f5acc2709934aa75b66492e6097a951744e8a211ac61ac48796146",
          "sha256": "36014e20bf39bde0808d30e774f27bbb9ff19403cd78720faae522ebaa5035fe",
          "sha1": "c31d42272caa332071df6beb2e97c7927772f9c8",
          "md5": "9d77c9a36ace67d94160c52a93d76896"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.ditchoom",
          "module": "buffer",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-iosarm64-0.0.8-metadata.jar",
          "url": "DLCommonUtil-iosarm64-0.0.8-metadata.jar",
          "size": 4086,
          "sha512": "c7dcd144dce5ef620cc3ce6b0db81745f4ff86c6815bb82d903d59e9faeba3cc2224e3b21395236c11f342dbf11c5193c77e9d1dc83189fe71a8f77726a34621",
          "sha256": "78eb7ab341f00381c0ebb9c0fd06d51ea38c6014d93039288a84975edf97c5f3",
          "sha1": "52b5f59546111a29ac9ba248933faf545dd69f71",
          "md5": "82be0bd42b59196f063be2b68f746313"
        }
      ]
    }
  ]
}
