{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLPcmResampleUtil/0.2.5/DLPcmResampleUtil-0.2.5.module",
    "group": "com.github.D10NGYANG",
    "module": "DLPcmResampleUtil",
    "version": "0.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLPcmResampleUtil-js-0.2.5.klib",
          "url": "DLPcmResampleUtil-js-0.2.5.klib",
          "size": 222543,
          "sha512": "b3bd242ebb5b746aa4421b78972a62897cbbc06f550e457020a62d9bd3e965a3f4efae1cf18033e8400ac3c4bf01b846569c2828f2e0412dc82420841d0de09c",
          "sha256": "480307aa4265e15553be087a794a31f452061540b1c1f519baa83d5e0ecf0aed",
          "sha1": "7b0e56fd3e093fdbc0e3f226b3a2f6f5189ad1fe",
          "md5": "75b8e06892c197ae3da9031a5f019399"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLPcmResampleUtil-js-0.2.5.klib",
          "url": "DLPcmResampleUtil-js-0.2.5.klib",
          "size": 222543,
          "sha512": "b3bd242ebb5b746aa4421b78972a62897cbbc06f550e457020a62d9bd3e965a3f4efae1cf18033e8400ac3c4bf01b846569c2828f2e0412dc82420841d0de09c",
          "sha256": "480307aa4265e15553be087a794a31f452061540b1c1f519baa83d5e0ecf0aed",
          "sha1": "7b0e56fd3e093fdbc0e3f226b3a2f6f5189ad1fe",
          "md5": "75b8e06892c197ae3da9031a5f019399"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "DLPcmResampleUtil-js-0.2.5-sources.jar",
          "url": "DLPcmResampleUtil-js-0.2.5-sources.jar",
          "size": 29527,
          "sha512": "1a194d4e2857f7193e66f10520343b3936df7d348c00f3bda215e19056c48944d24e2e5f729ca375935618e6184615c890426f7d23562f343c79ee8acc1c407c",
          "sha256": "a5c1d6a53b898b6678bd2f030f75dd7fce53899ecf8781f4487223aaca919e51",
          "sha1": "3f9636b6b03ac896e64cca4922a78ef7598e1877",
          "md5": "32d19eca613b0166d22c4fd22eb7f266"
        }
      ]
    }
  ]
}
