{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLJetpackComposeUtil",
    "version": "2.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2023.10.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.0-alpha13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-2.0.6.aar",
          "url": "DLJetpackComposeUtil-2.0.6.aar",
          "size": 1058817,
          "sha512": "87a7294b774fd1c4a68f4861b559955b7f6e4ec54012099029b59b838d2400aa8113c1157d7c3976c8020629b17033d4cf190d9cf30063801c73b642f5f739b0",
          "sha256": "fccb4238cb961e5a7026aafb1bee2b82d10acef4c224f878f135ba92628e8ffa",
          "sha1": "49507c8003ef09ed5d86af7f6223a12fe5383689",
          "md5": "567a244064c2c50c64a13396395a1c82"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.github.raamcosta.compose-destinations",
          "module": "animations-core",
          "version": {
            "requires": "1.9.54"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLDateUtil",
          "version": {
            "requires": "1.8.7"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2023.10.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.0-alpha13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "DLJetpackComposeUtil-2.0.6.aar",
          "url": "DLJetpackComposeUtil-2.0.6.aar",
          "size": 1058817,
          "sha512": "87a7294b774fd1c4a68f4861b559955b7f6e4ec54012099029b59b838d2400aa8113c1157d7c3976c8020629b17033d4cf190d9cf30063801c73b642f5f739b0",
          "sha256": "fccb4238cb961e5a7026aafb1bee2b82d10acef4c224f878f135ba92628e8ffa",
          "sha1": "49507c8003ef09ed5d86af7f6223a12fe5383689",
          "md5": "567a244064c2c50c64a13396395a1c82"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLJetpackComposeUtil-2.0.6-sources.jar",
          "url": "DLJetpackComposeUtil-2.0.6-sources.jar",
          "size": 74272,
          "sha512": "b60d8962028fe914dcb3b77b6e08d30636e8c40242d8f625cf374a62c0edef96c202d1ee2ac8343a3b5c63d85965e00375a95a4dc31e764c6eba6343167d1402",
          "sha256": "7a73ea12bf3971ec9722ac2e5ba12bcba3267aab07409ad23c66ad6fa6d60046",
          "sha1": "9ecfb004341ca1881f17e77ee06d3c059991342d",
          "md5": "2790ba2f985e1b9e4893e4c404aa3e8e"
        }
      ]
    }
  ]
}
