{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLCommonUtil",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0-RC.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLCommonUtil-metadata-0.5.1.jar",
          "url": "DLCommonUtil-0.5.1.jar",
          "size": 18524,
          "sha512": "ff178a32dc239d7d85bcbe892473a62a8b4f1b21fb592f35499a54deda315613daf1934ce751501adac55fa1265e8039ab31692f2bb875b66eac80e0bb66f0f1",
          "sha256": "1ef8c667b9290fc7846f4eef584fe7ded08305731598a4de35a8db0020c06691",
          "sha1": "102aed0d6b765f7dfa178c06cfdc4594d99d8718",
          "md5": "e76d62ad41c5ccff1a52f8c399d7489d"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "DLCommonUtil-kotlin-0.5.1-sources.jar",
          "url": "DLCommonUtil-0.5.1-sources.jar",
          "size": 195443,
          "sha512": "47dce62021391029542359690b52bbc24cb9c0ba791e5f463d6fd5fb50e4bc54dbc399203e8be3ad5a6c2e9ea0a6467d565041096276b0b72e3c971eae3bb176",
          "sha256": "c49a02a4c20798877899d6cbd1d74a6129d8e8c929ff8c2243ec7222c71e00f9",
          "sha1": "1c6931396504afa11ead324055ccbb0ae375fdac",
          "md5": "30ec75fc81aee3ffb1915e95bef88234"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLCommonUtil-android/0.5.1/DLCommonUtil-android-0.5.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-android",
        "version": "0.5.1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLCommonUtil-android/0.5.1/DLCommonUtil-android-0.5.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-android",
        "version": "0.5.1"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../DLCommonUtil-android/0.5.1/DLCommonUtil-android-0.5.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-android",
        "version": "0.5.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCommonUtil-iosarm64/0.5.1/DLCommonUtil-iosarm64-0.5.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-iosarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCommonUtil-iosarm64/0.5.1/DLCommonUtil-iosarm64-0.5.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-iosarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCommonUtil-iosarm64/0.5.1/DLCommonUtil-iosarm64-0.5.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-iosarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCommonUtil-iossimulatorarm64/0.5.1/DLCommonUtil-iossimulatorarm64-0.5.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-iossimulatorarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCommonUtil-iossimulatorarm64/0.5.1/DLCommonUtil-iossimulatorarm64-0.5.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-iossimulatorarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCommonUtil-iossimulatorarm64/0.5.1/DLCommonUtil-iossimulatorarm64-0.5.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-iossimulatorarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLCommonUtil-js/0.5.1/DLCommonUtil-js-0.5.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-js",
        "version": "0.5.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLCommonUtil-js/0.5.1/DLCommonUtil-js-0.5.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-js",
        "version": "0.5.1"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../DLCommonUtil-js/0.5.1/DLCommonUtil-js-0.5.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-js",
        "version": "0.5.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLCommonUtil-jvm/0.5.1/DLCommonUtil-jvm-0.5.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-jvm",
        "version": "0.5.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLCommonUtil-jvm/0.5.1/DLCommonUtil-jvm-0.5.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-jvm",
        "version": "0.5.1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../DLCommonUtil-jvm/0.5.1/DLCommonUtil-jvm-0.5.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-jvm",
        "version": "0.5.1"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCommonUtil-linuxarm64/0.5.1/DLCommonUtil-linuxarm64-0.5.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-linuxarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCommonUtil-linuxarm64/0.5.1/DLCommonUtil-linuxarm64-0.5.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-linuxarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCommonUtil-linuxx64/0.5.1/DLCommonUtil-linuxx64-0.5.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-linuxx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCommonUtil-linuxx64/0.5.1/DLCommonUtil-linuxx64-0.5.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-linuxx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCommonUtil-macosarm64/0.5.1/DLCommonUtil-macosarm64-0.5.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-macosarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCommonUtil-macosarm64/0.5.1/DLCommonUtil-macosarm64-0.5.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-macosarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCommonUtil-macosarm64/0.5.1/DLCommonUtil-macosarm64-0.5.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-macosarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCommonUtil-macosx64/0.5.1/DLCommonUtil-macosx64-0.5.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-macosx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCommonUtil-macosx64/0.5.1/DLCommonUtil-macosx64-0.5.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-macosx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../DLCommonUtil-macosx64/0.5.1/DLCommonUtil-macosx64-0.5.1.module",
        "group": "com.github.D10NGYANG",
        "module": "DLCommonUtil-macosx64",
        "version": "0.5.1"
      }
    }
  ]
}
