{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLLatLngUtil/1.7.3/DLLatLngUtil-1.7.3.module",
    "group": "com.github.D10NGYANG",
    "module": "DLLatLngUtil",
    "version": "1.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil-js-1.7.3.klib",
          "url": "DLLatLngUtil-js-1.7.3.klib",
          "size": 62130,
          "sha512": "119de131595964473b8742dc50108a2e5f5b0b17f07a01405cdbf7fe0fe9a172b4353f0e2d135d8519947aa454685d18d31e0c0ca3d344cd39490eb977607314",
          "sha256": "cdcbaeea39a480012f1bdbec6d36a6008b74cb5b9344c6492ba86e02895c5d5d",
          "sha1": "36426b40e2cb616a44640b34e3493795ccc6bc41",
          "md5": "720573a6d1e2221a1033772846981ace"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "DLLatLngUtil-js-1.7.3.klib",
          "url": "DLLatLngUtil-js-1.7.3.klib",
          "size": 62130,
          "sha512": "119de131595964473b8742dc50108a2e5f5b0b17f07a01405cdbf7fe0fe9a172b4353f0e2d135d8519947aa454685d18d31e0c0ca3d344cd39490eb977607314",
          "sha256": "cdcbaeea39a480012f1bdbec6d36a6008b74cb5b9344c6492ba86e02895c5d5d",
          "sha1": "36426b40e2cb616a44640b34e3493795ccc6bc41",
          "md5": "720573a6d1e2221a1033772846981ace"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "DLLatLngUtil-js-1.7.3-sources.jar",
          "url": "DLLatLngUtil-js-1.7.3-sources.jar",
          "size": 14827,
          "sha512": "b26e7136df1894d888b2f12e2e74c34a37d297916f689f186db6e55052ac7f90b4f448850cb1ad2b2d6ccc4daa36f765d740fc773054e5ac2941d37d459653aa",
          "sha256": "6b813e321fe518f00312024523fb5b21d3a3d6100cebc9314e2aa8fb9214e3ed",
          "sha1": "b52b15eef847b1b4bcac396d514dd7ec5e2d0837",
          "md5": "f3e617b94fd0c111d3f8fcf895087f4f"
        }
      ]
    }
  ]
}
