{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLTianDiTuApi/1.2.0/DLTianDiTuApi-1.2.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLTianDiTuApi",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "DLTianDiTuApi-macosArm64Main-1.2.0.klib",
          "url": "DLTianDiTuApi-macosarm64-1.2.0.klib",
          "size": 112395,
          "sha512": "3b7c67bfa1f9b549880e04e5dad42c06e359945a5628c3f83568d338920649cc76841d93fb34410368e61daf665838259164b7c762f963cfff0129ad53e4b0cb",
          "sha256": "7a117dcd2a297745685bba2397c67268d66204bfb855ce30c706c090397042d8",
          "sha1": "52ed93d276644f6e8537d9e7ac2b9e74a91b4570",
          "md5": "9022c32ee21f46fdc74d7ed4001d1f1a"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLTianDiTuApi-macosarm64-1.2.0-sources.jar",
          "url": "DLTianDiTuApi-macosarm64-1.2.0-sources.jar",
          "size": 6741,
          "sha512": "e995fd07814e5a74a95204d799c654f7da718945c0da9e007b32c722f6f66af2530e821b6ae755d000b3f768b7ed5f5ba48599211dc0e8bed8834ec08ff7e6b0",
          "sha256": "0414baa275caeb80f95cda9aeef4ed8055384c749dae672dafeea476dc9d8b9c",
          "sha1": "0828114131dafc5114da91d86d312e29b9883d3e",
          "md5": "13050d4174ed636150e82130e94bd601"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "DLTianDiTuApi-macosarm64-1.2.0-metadata.jar",
          "url": "DLTianDiTuApi-macosarm64-1.2.0-metadata.jar",
          "size": 261,
          "sha512": "bfd17da75a58096c8a11f6fceb6f750ee615b708a2853e59088e2afb52cf34275b837010e5b418c598e784bcb581a66b1e2bdec2efd9c37acaf97ee3c54a878e",
          "sha256": "c086a2991d70ea3bb062ebc47009c0a1f9a93c65d38e83e3df17b515b5bc8f06",
          "sha1": "75dbbc5846e4b2fda96c285e6a535e19bcc0f904",
          "md5": "6758e78cbf6249ed23acbd50696aca3d"
        }
      ]
    }
  ]
}
