{
  "formatVersion": "1.1",
  "component": {
    "url": "../../DLSerialPortUtil/0.4.0/DLSerialPortUtil-0.4.0.module",
    "group": "com.github.D10NGYANG",
    "module": "DLSerialPortUtil",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLLogUtil",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLSerialPortUtil-macosX64Main-0.4.0.klib",
          "url": "DLSerialPortUtil-macosx64-0.4.0.klib",
          "size": 36153,
          "sha512": "28ac81d25eacacee8083b0be8e34c38cba270cee7218bd5d7e5b768ffa38e4e16d75cd62994e735e9874aed1c06b1ea528284babf7c255658622e5175f130a90",
          "sha256": "5e5a9088b5772901ddffd4fa6b5f6062805ae5fde479b5d2debb9d99bd8f79d7",
          "sha1": "3dd7e31a1dc90c0509a61326796d7a8b9ff37f66",
          "md5": "1c4fcda825d4240e5781c3f8d09a9fe1"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "DLSerialPortUtil-macosx64-0.4.0-sources.jar",
          "url": "DLSerialPortUtil-macosx64-0.4.0-sources.jar",
          "size": 9010,
          "sha512": "0c95f57efb4f2f9441504155d43f2e49fedf874354989cd16d6c33a5293747fe4f92a7e371c4985c66b95d93d25ce18e9a99c6098a36f367cb75cfce6cb20212",
          "sha256": "bbf012ce65c23e552e9bcbb6e7a7ddfba9aeb1f06fc3e81506c91f95461ac362",
          "sha1": "d19f738f354a5744921b98ade8d37c6e01d1e08d",
          "md5": "a5cb25f09bb0ffcc2cc850ef6daf0c4c"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLLogUtil",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "DLSerialPortUtil-macosx64-0.4.0-metadata.jar",
          "url": "DLSerialPortUtil-macosx64-0.4.0-metadata.jar",
          "size": 4349,
          "sha512": "a017976bda3870d3b2865578cf80b3568887c5a49784acfb947f767155be69a0066cb219c31b2b1b29813762ba16b874615e70723362fa32baedcb899f410238",
          "sha256": "6634eee0a14707b67609604ec99620d322218a9f4d1c838310b7202f5b5ae3b9",
          "sha1": "076195d389b9374ba7769553ff4161dfe222a8dc",
          "md5": "12e5c57c0d18c23d9c147fbfb15dc921"
        }
      ]
    }
  ]
}
