{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.D10NGYANG",
    "module": "DLAppUtil",
    "version": "2.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLAppUtil-2.7.0.aar",
          "url": "DLAppUtil-2.7.0.aar",
          "size": 194934,
          "sha512": "dfe919a47de956c2122ba06617c9ffc969db3c4b84dc864740d256eb3ec97a33ff0ff4282d4015a4d1acdfcbc93b03fc20de91c333e6ce624777102190653f42",
          "sha256": "e9e064052b77155cf6acdb055722389c3844dd27fbf1add1e20295a6f4078801",
          "sha1": "668cf69c507d45673584f19efd214f6dd98ddee7",
          "md5": "0b67aeea987d6d03ae4d593afd572f32"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.D10NGYANG",
          "module": "DLCommonUtil",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "DLAppUtil-2.7.0.aar",
          "url": "DLAppUtil-2.7.0.aar",
          "size": 194934,
          "sha512": "dfe919a47de956c2122ba06617c9ffc969db3c4b84dc864740d256eb3ec97a33ff0ff4282d4015a4d1acdfcbc93b03fc20de91c333e6ce624777102190653f42",
          "sha256": "e9e064052b77155cf6acdb055722389c3844dd27fbf1add1e20295a6f4078801",
          "sha1": "668cf69c507d45673584f19efd214f6dd98ddee7",
          "md5": "0b67aeea987d6d03ae4d593afd572f32"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DLAppUtil-2.7.0-sources.jar",
          "url": "DLAppUtil-2.7.0-sources.jar",
          "size": 41883,
          "sha512": "7189d1ca3dce2c4e3cb1e692ed3a32cd300bba1a3d06efa9cca0d3cf60114bda164f454d36aa1b9f17e3333a6bc5b761286e7fc32588fa0d8db9190e2025e9ec",
          "sha256": "c51130a9a51e128764a4d897df94a0289bfbce4d560d6669fe6175c5b02d638d",
          "sha1": "832adff64dffb1174019785c532c5e0809493839",
          "md5": "2e501885c3c770498c2cd331fc9ec07e"
        }
      ]
    }
  ]
}
